### ISSUE TITLE
timescale stutters when slowed down

### ISSUE THREAD

**Issue by Cotaks** [UPBGE/upbge#1001]
For slow motion i use the timescale, but when slowed down it starts to stutter, no smooth movement anymore.

Is this a bug, or related to the sleep that you guys have added?
blend on BA: https://blenderartists.org/t/slow-motion/1112323

as you can see the video is in BGE runs smooth when slowed down, if you use it in UPBGE it stutters when slowed down.

**Comment by UglinessInTheUI** [comment]
Hey Cotaks , where is the buggy blend file ? 
I want to run it and test it on my system.
Thanks.

**Comment by youle31** [comment]
The demo files in BA thread seem to work fine in 0.2.5a then I close this thread, nice file btw
