### ISSUE TITLE
Game Controller index 0,1: Could not be initialized

### ISSUE THREAD

**Issue by AnikiPepe** [UPBGE/upbge#1008]
My game controller is **detected but cannot be initialized** neither inside nor in the standalone player (It's a two slot hub)
    * Error: Game Controller index 0: Could not be initialized
    * Error: Game Controller index 1: Could not be initialized

Details
- Gamepad works fine in Blender  2.79
- Have read and proceed with [New Game controller system](https://github.com/UPBGE/blender/wiki/New-Game-controller-system)
- I have a custom SDL_GAMECONTROLLERCONFIG env var **working in every SDL2 program** so far
- Didn't messed with the bundled controller .txt file
- UPBGE reports controller hotplug connection while running the game and throws the same error above

Any idea?
Thank you guys, this is weird :confused:

**Comment by BluePrintRandom** [comment]
@AnikiPepe is this still an issue for you?

**Comment by Solone** [comment]
This is also an issue for me. I can't get any joystick logic bricks working?

Error: Game Controller index 0: Could not be initialized
Please, generate Xbox360 compatible mapping using Antimicro (https://github.com/AntiMicro/antimicro)
or SDL2 Gamepad Tool (http://www.generalarcade.com/gamepadtool) or Steam big mode applications
and after, set the SDL controller variable before you launch the executable, i.e:
export SDL_GAMECONTROLLERCONFIG="[the string you received from controllermap]"
Error: Game Controller index 1: Could not be initialized
Please, generate Xbox360 compatible mapping using Antimicro (https://github.com/AntiMicro/antimicro)
or SDL2 Gamepad Tool (http://www.generalarcade.com/gamepadtool) or Steam big mode applications
and after, set the SDL controller variable before you launch the executable, i.e:
export SDL_GAMECONTROLLERCONFIG="[the string you received from controllermap]"
Error: Game Controller index 2: Could not be initialized
Please, generate Xbox360 compatible mapping using Antimicro (https://github.com/AntiMicro/antimicro)
or SDL2 Gamepad Tool (http://www.generalarcade.com/gamepadtool) or Steam big mode applications
and after, set the SDL controller variable before you launch the executable, i.e:
export SDL_GAMECONTROLLERCONFIG="[the string you received from controllermap]"
Error: Game Controller index 3: Could not be initialized
Please, generate Xbox360 compatible mapping using Antimicro (https://github.com/AntiMicro/antimicro)
or SDL2 Gamepad Tool (http://www.generalarcade.com/gamepadtool) or Steam big mode applications
and after, set the SDL controller variable before you launch the executable, i.e:
export SDL_GAMECONTROLLERCONFIG="[the string you received from controllermap]"
Error: Game Controller index 4: Could not be initialized
Please, generate Xbox360 compatible mapping using Antimicro (https://github.com/AntiMicro/antimicro)
or SDL2 Gamepad Tool (http://www.generalarcade.com/gamepadtool) or Steam big mode applications
and after, set the SDL controller variable before you launch the executable, i.e:
export SDL_GAMECONTROLLERCONFIG="[the string you received from controllermap]"
Blender Game Engine Finished
Info: Total files 0 | Changed 0 | Failed 0

**Comment by lordloki** [comment]
These issues is that your controller is not mapped inside game controller database.
Which UPBGE version are you using?

**Comment by Solone** [comment]
I’m new to UPBGE and using 0.30 (the latest?)

**Comment by lordloki** [comment]
There is no official UPBGE 0.3 yet. We need the compilation date and the hash number as you can see in the imagen below.
![image](https://user-images.githubusercontent.com/1015605/77843791-cf02e180-71a0-11ea-9e74-8b7d64675002.png)
Thanks.

**Comment by Solone** [comment]
ah ok, thanks. Well, I'll be eagerly patiently waiting looking forward to 0.3 it looks very promising with EEVEE.

**Comment by lordloki** [comment]
HI,
Could you test the build UPBGE-EEVEE-Win64-2020-04-03 Rev A.7z from MEGA share folder (https://mega.nz/folder/t9EEFSaS#JPiOPSInCZyU-SW_-rhEOQ)?

This build includes a fix to use a game controller database more updated.

Thanks.

**Comment by Solone** [comment]
Thanks I'm on it. Will try it right now.

**Comment by Solone** [comment]
I got the wired ps3 joystick working, it responds in analog mode only it seems.

**Comment by lordloki** [comment]
Thanks for testing and reporting. Closing the issue.
