### ISSUE TITLE
Document import sheningans happing with in-editor Python files

### ISSUE THREAD

**Issue by marechal-p** [UPBGE/upbge#1012]
Blender/UPBGE overrides the import function in Python to first look into the datablocks to find some Python module file.

As it can be confusing, an entry in the documentation should make it clear.

See: https://github.com/UPBGE/blender/issues/1011#issuecomment-461093314

**Comment by youle31** [comment]
Hello, I think you can commit if you want. @panzergame : are you ok?

**Comment by lordloki** [comment]
Thanks for reporting. I moved the issue to the document repo: https://github.com/UPBGE/UPBGE-Docs/issues/2

Closing here.
