### ISSUE TITLE
Null attributes in bgl module when running blenderplayer

### ISSUE THREAD

**Issue by lopas85** [UPBGE/upbge#1022]
as indicated, simply by printing on console any function of the bgl module, in the embedded player it is recognized, differently in the standalone it is None (in upbge 2.3 render attachements and 2.4)
[test bgl.zip](https://github.com/UPBGE/blender/files/2907357/test.bgl.zip)

**Comment by BluePrintRandom** [comment]
I noticed attachment was failing if the screen size was full

**Comment by marechal-p** [comment]
Using:

```py
for name in dir(bgl):
    print(name, getattr(bgl, name))
```

## Blender Editor

    __doc__ None
    glFramebufferTexture None
    glGetBufferParameteri64v None
    glGetInteger64i_v None

## Blender Player

    __doc__ None
    glActiveTexture None
    glAttachShader None
    glBeginQuery None
    glBindAttribLocation None
    glBindBuffer None
    glBindBufferBase None
    glBindBufferRange None
    glBindFramebuffer None
    glBindRenderbuffer None
    glBindVertexArray None
    glBlendColor None
    glBlendEquation None
    glBlendEquationSeparate None
    glBufferData None
    glBufferSubData None
    glCheckFramebufferStatus None
    glClientActiveTexture None
    glColorP3ui None
    glColorP3uiv None
    glColorP4ui None
    glColorP4uiv None
    glCompileShader None
    glCompressedTexImage1D None
    glCompressedTexImage2D None
    glCompressedTexImage3D None
    glCompressedTexSubImage1D None
    glCompressedTexSubImage2D None
    glCompressedTexSubImage3D None
    glCopyTexSubImage3D None
    glCreateProgram None
    glCreateShader None
    glDeleteBuffers None
    glDeleteFramebuffers None
    glDeleteProgram None
    glDeleteQueries None
    glDeleteRenderbuffers None
    glDeleteShader None
    glDeleteVertexArrays None
    glDetachShader None
    glDisableVertexAttribArray None
    glDrawBuffers None
    glDrawRangeElements None
    glEnableVertexAttribArray None
    glEndQuery None
    glFramebufferRenderbuffer None
    glFramebufferTexture None
    glFramebufferTexture1D None
    glFramebufferTexture2D None
    glFramebufferTexture3D None
    glGenBuffers None
    glGenFramebuffers None
    glGenQueries None
    glGenRenderbuffers None
    glGenVertexArrays None
    glGetActiveAttrib None
    glGetActiveUniform None
    glGetActiveUniformBlockName None
    glGetActiveUniformBlockiv None
    glGetActiveUniformName None
    glGetActiveUniformsiv None
    glGetAttachedShaders None
    glGetAttribLocation None
    glGetBufferParameteri64v None
    glGetBufferParameteriv None
    glGetBufferPointerv None
    glGetBufferSubData None
    glGetCompressedTexImage None
    glGetInteger64i_v None
    glGetIntegeri_v None
    glGetMultisamplefv None
    glGetProgramInfoLog None
    glGetProgramiv None
    glGetQueryObjectiv None
    glGetQueryObjectuiv None
    glGetQueryiv None
    glGetShaderInfoLog None
    glGetShaderSource None
    glGetShaderiv None
    glGetUniformBlockIndex None
    glGetUniformIndices None
    glGetUniformLocation None
    glGetUniformfv None
    glGetUniformiv None
    glGetVertexAttribPointerv None
    glGetVertexAttribdv None
    glGetVertexAttribfv None
    glGetVertexAttribiv None
    glIsBuffer None
    glIsFramebuffer None
    glIsProgram None
    glIsQuery None
    glIsRenderbuffer None
    glIsShader None
    glIsVertexArray None
    glLinkProgram None
    glLoadTransposeMatrixd None
    glLoadTransposeMatrixf None
    glMapBuffer None
    glMultTransposeMatrixd None
    glMultTransposeMatrixf None
    glMultiTexCoord1d None
    glMultiTexCoord1dv None
    glMultiTexCoord1f None
    glMultiTexCoord1fv None
    glMultiTexCoord1i None
    glMultiTexCoord1iv None
    glMultiTexCoord1s None
    glMultiTexCoord1sv None
    glMultiTexCoord2d None
    glMultiTexCoord2dv None
    glMultiTexCoord2f None
    glMultiTexCoord2fv None
    glMultiTexCoord2i None
    glMultiTexCoord2iv None
    glMultiTexCoord2s None
    glMultiTexCoord2sv None
    glMultiTexCoord3d None
    glMultiTexCoord3dv None
    glMultiTexCoord3f None
    glMultiTexCoord3fv None
    glMultiTexCoord3i None
    glMultiTexCoord3iv None
    glMultiTexCoord3s None
    glMultiTexCoord3sv None
    glMultiTexCoord4d None
    glMultiTexCoord4dv None
    glMultiTexCoord4f None
    glMultiTexCoord4fv None
    glMultiTexCoord4i None
    glMultiTexCoord4iv None
    glMultiTexCoord4s None
    glMultiTexCoord4sv None
    glMultiTexCoordP1ui None
    glMultiTexCoordP1uiv None
    glMultiTexCoordP2ui None
    glMultiTexCoordP2uiv None
    glMultiTexCoordP3ui None
    glMultiTexCoordP3uiv None
    glMultiTexCoordP4ui None
    glMultiTexCoordP4uiv None
    glNormalP3ui None
    glNormalP3uiv None
    glRenderbufferStorage None
    glSampleCoverage None
    glSampleMaski None
    glSecondaryColorP3ui None
    glSecondaryColorP3uiv None
    glShaderSource None
    glStencilFuncSeparate None
    glStencilMaskSeparate None
    glStencilOpSeparate None
    glTexCoordP1ui None
    glTexCoordP1uiv None
    glTexCoordP2ui None
    glTexCoordP2uiv None
    glTexCoordP3ui None
    glTexCoordP3uiv None
    glTexCoordP4ui None
    glTexCoordP4uiv None
    glTexImage2DMultisample None
    glTexImage3D None
    glTexImage3DMultisample None
    glTexSubImage3D None
    glUniform1f None
    glUniform1fv None
    glUniform1i None
    glUniform1iv None
    glUniform2f None
    glUniform2fv None
    glUniform2i None
    glUniform2iv None
    glUniform3f None
    glUniform3fv None
    glUniform3i None
    glUniform3iv None
    glUniform4f None
    glUniform4fv None
    glUniform4i None
    glUniform4iv None
    glUniformBlockBinding None
    glUniformMatrix2fv None
    glUniformMatrix2x3fv None
    glUniformMatrix2x4fv None
    glUniformMatrix3fv None
    glUniformMatrix3x2fv None
    glUniformMatrix3x4fv None
    glUniformMatrix4fv None
    glUniformMatrix4x2fv None
    glUniformMatrix4x3fv None
    glUnmapBuffer None
    glUseProgram None
    glValidateProgram None
    glVertexAttrib1d None
    glVertexAttrib1dv None
    glVertexAttrib1f None
    glVertexAttrib1fv None
    glVertexAttrib1s None
    glVertexAttrib1sv None
    glVertexAttrib2d None
    glVertexAttrib2dv None
    glVertexAttrib2f None
    glVertexAttrib2fv None
    glVertexAttrib2s None
    glVertexAttrib2sv None
    glVertexAttrib3d None
    glVertexAttrib3dv None
    glVertexAttrib3f None
    glVertexAttrib3fv None
    glVertexAttrib3s None
    glVertexAttrib3sv None
    glVertexAttrib4Nbv None
    glVertexAttrib4Niv None
    glVertexAttrib4Nsv None
    glVertexAttrib4Nub None
    glVertexAttrib4Nubv None
    glVertexAttrib4Nuiv None
    glVertexAttrib4Nusv None
    glVertexAttrib4bv None
    glVertexAttrib4d None
    glVertexAttrib4dv None
    glVertexAttrib4f None
    glVertexAttrib4fv None
    glVertexAttrib4iv None
    glVertexAttrib4s None
    glVertexAttrib4sv None
    glVertexAttrib4ubv None
    glVertexAttrib4uiv None
    glVertexAttrib4usv None
    glVertexAttribPointer None
    glVertexP2ui None
    glVertexP2uiv None
    glVertexP3ui None
    glVertexP3uiv None
    glVertexP4ui None
    glVertexP4uiv None

**Comment by UglinessInTheUI** [comment]
Blender Game Engine Started
Error: Python(Plane), Python script error
Traceback (most recent call last):
  File "Text", line 3, in <module>
NameError: name 'bgl' is not defined
Blender Game Engine Finished

**Comment by UglinessInTheUI** [comment]
Maybe your result explains why the bloom shader works in 2.79 but it fails in UPBGE.

**Comment by BluePrintRandom** [comment]
I can close this eh @marechal-p ?

**Comment by lordloki** [comment]
Hi,
this is working in UPBGE 0.3 in embedding and player now
![image](https://user-images.githubusercontent.com/1015605/102579022-e5204b80-40fb-11eb-9c3b-c851d50c8b87.png)

Closing the report. Thanks for reporting.
