### ISSUE TITLE
Building Portable Version on Linux

### ISSUE THREAD

**Issue by wwderw** [UPBGE/upbge#1033]
I tend to only use one computer from building programs from source and then try to get portable versions from there (typically binary archive versions) to actually go to my production computers and I was wondering what are the instructions for doing so for this project?

Only thing that I noticed in the issues was one from 2016 #50 and it said that it had been resolved with the 0.0.5 release.  I checked the wiki and couldn't find any instructions specific to that type of build for Linux.  

Any help on the steps needed to build a portable version would be great.

Thanks!

**Comment by marechal-p** [comment]
Did you try simply building the application? Using `ldd` it seems like most dynamically linked libraries are really core ones (nothing too much BGE specific), but am no expert.

My guess is that you should be able to fairly easily move your build around.

If not the case, simply report back on this issue :)

**Comment by wwderw** [comment]
Hmmm, I actually wasn't able to do a working build even on my build computer.

I got a bunch of RNA String Set errors (not founds etc) and it all ended with a "Aborted (Core Dump)".

I'm sure that it is something to do with the person at the keyboard (me), but not really having a step by step guide, it's hard for me to ascertain where I went wrong, did or didn't do etc.

>like most dynamically linked libraries are really core ones (nothing too much BGE specific), but am no expert.

For me, even if they are just core libraries, I would still have them within the build itself and that way it won't matter so much system to system in case something was different with one and that meant I had to rebuild the entire program.  The storage space concern (for me) is trumped by having to not worry about if a new LTS will kill a working build for me.

**Comment by marechal-p** [comment]
So in a perfect world you want a fully static build.

I unfortunately cannot help here, someone with more experience on linking and on Blender's build system will need to take a look here.

But I wonder if the current dynamic libraries will actually cause issues using newer Linux distributions...
So far so good :p

**Comment by wwderw** [comment]
> But I wonder if the current dynamic libraries will actually cause issues using newer Linux distributions...
So far so good :p

I've only had a couple of programs that had a problem, they were both built on a 14.04 system and were just recently broken on an 18.04 (current) system.

One was exceptionally easy to build, so that wasn't a huge concern/problem.  

I couldn't get BGE to have a workable build, so I couldn't test it's portability out of the box with dynamically linked libs.  I'm 99% certain that it was something that I did, but without a step by step, I'm sure I missed something, either did or didn't do something or combination thereof.

**Comment by marechal-p** [comment]
https://github.com/UPBGE/blender/wiki/Build-UPBGE-on-Linux?

**Comment by wwderw** [comment]
That's what I followed.

The part about getting all those git submodules all turned up errors on my end.  Not a module etc.

This part

>In Cmake, advanced options, check with CXX11. Once you have configured and generate your cmake files,

I lack the knowledge itself to know exactly what I'm supposed to do.  What's save to do etc.

It's usually CD into this folder, do this command etc.

I don't know which cmake.txt (or if those are even the files that are being called upon etc) files to configure and then generate or do it for all of them etc.

**Comment by marechal-p** [comment]
I may try to build UPBGE on a Linux later today, I'll see if I can add anything to the wiki.

**Comment by wwderw** [comment]
I appreciate the help.

**Comment by marechal-p** [comment]
https://github.com/UPBGE/blender/wiki/Build-UPBGE-on-Linux

Updated a bit the wiki, hopefully that helps.

**Comment by wwderw** [comment]
I really appreciate the help.  There was a lot that I didn't do when I saw the updated wiki.  Thanks again.

Attached is a screenshot of BASH with some of the errors that I was getting running ./Blender in the bin folder of the resulting build.
[UPBGE Run Errors.zip](https://github.com/UPBGE/blender/files/3065447/UPBGE.Run.Errors.zip)

**Comment by marechal-p** [comment]
I would go for an issue with the submodules, maybe not initialized.

**Comment by marechal-p** [comment]
Ok my bad, `make install` is not optional at all.

Was afraid it would install it somewhere in `/bin` or something, but no, it adds everything missing to the `/build-dir/bin` folder!

Updating the wiki :)

**Comment by wwderw** [comment]
> Ok my bad, make install is not optional at all.

Hmmm, I haven't tried that yet, but let me ask this, if I invoke `make install` that would make the resultant build not portable correct?

**Comment by marechal-p** [comment]
@wwderw from what I understand, it just appends Blender's flesh to the `/build-dir/bin` folder (addons and scripts and whatnot).

The errors you saw might have been because the `./blender` executable tried to look around itself to find these, but wasn't able to.

The point where things would make UPBGE portable or not is already passed when you have compiled binaries in your build folder. The program is already built to dynamically link or not.

**Comment by wwderw** [comment]
Ok, I'll give that a shoot after a bit (have to get some work done after all) and report back.

Thanks again for all the help!

**Comment by marechal-p** [comment]
You are welcome, that also helped me a bit :)

**Comment by wwderw** [comment]
I snuck it in there.  

Build was successful.  Unfortunately, it isn't portable.  It was only giving me one missing library issue on my actual production computer, but given past experiences, once one is usually reconciled, another one pops up. 

Bummer.

**Comment by marechal-p** [comment]
You can run `ldd` on the executable and see every library that it requires.

**Comment by wwderw** [comment]
It was somewhere between 30-40 libraries that were missing.  

I appreciate the help, but I just don't think that this is going to accomplish what I'm needing.  

I'm going to close out this issue.  Again, I really do appreciate all the help.

**Comment by vlad1777d** [comment]
@wwderw , I made a portable version for myself some time ago.
(don't remember which UPBGE I used)

I placed all libraries into ./libs directory, pre-loaded them using environment variable and python script.

If you need it - write me, I'll send you .zip.

**Comment by marechal-p** [comment]
@vlad1777d can you post the script here?

**Comment by wwderw** [comment]
That would be awesome!

**Comment by lordloki** [comment]
For example, you include shared library (i.e libtbb.so) in a new "lib" directory at the same level that upbgeplayer.
The script should have:
LD_LIBRARY_PATH="$(pwd)/lib"
export LD_LIBRARY_PATH
./upbgeplayer

**Comment by marechal-p** [comment]
Thanks @lordloki !

But how to select what to include in the libs? Everything listed by `ldd ./blenderplayer` ?

**Comment by lordloki** [comment]
you could include all libraries but generally you should include the most problematics (tbb, exr, openal-soft, etc)

**Comment by vlad1777d** [comment]
@marechal-p , just place this to your upbge directory of same version, launch everything via that script.
It also passes all arguments to blender executable.

[upbge-0.2.4.zip](https://github.com/UPBGE/blender/files/3124653/upbge-0.2.4.zip)

**Comment by wwderw** [comment]
Attached is what I get when I try to run the script with a UPBGE 2.4 version.

![UPBGE Error](https://user-images.githubusercontent.com/24878362/57180737-4aed9000-6e51-11e9-9a19-a95b9f17c148.png)

I did notice that on the web page, in the experimental folder of the download section there is a tarball labeled "static-lib", would that be able to get a portable version?  If so, what would be the way to go about that?

**Comment by wwderw** [comment]
I also starting wondering something else.  I know with Armory, you can either use their standalone install of Blender or you can extract the Armory bits and use it within the regular Blender.  

Is that method possible with UPBGE as well or not?  Trying to figure out portability options.

**Comment by marechal-p** [comment]
@wwderw Armory is a standalone engine with tight integrations to Blender using addons IIUC.

UPBGE on the other hand is built alongside Blender, like you have seen. They share things at the runtime level (ABI and stuff), unlike Armory where the addons make the interface between Blender and the Armory engine (if I still understand things correctly).

Yes you can isolate the standalone player, but I don't really know what you would want to do with it?

**Comment by wwderw** [comment]
No big issue there if I cant separate the BGE and use it in a portable version of Blender.

Really, it's more about getting this portable.  It looks like it should be possible given what I saw in the experimental folder, but I'm not seeing any instructions on how, so maybe it is possible.

But portability is my main goal.  I like to have apps and their dependencies isolated to their respective programs.  It makes for a far better production machine in my experience.

**Comment by marechal-p** [comment]
From the error screenshot you posted, it seems that `ld` had troubles with `libtbb`, just like Loki mentionned. Did you copy the library in your portable build like he recommended?

**Comment by marechal-p** [comment]
I just looked in the archive, and apparently the libs are included. If you did copy the libs over too, I would recommend altering the script to print the paths and ensure that everything is pointing to the right place.

**Comment by wwderw** [comment]
Yes, everything was moved over and I made sure everything was executable as well.

As far as altering scripts, I can do simple bash scripts, but altering something like the supplied script is beyond my knowledge base.

**Comment by marechal-p** [comment]
The script is not really complicated:
- Creates path variables (`os.path.join`)
- Fetches the arguments back from how the script itself is started (to propagate them back to the actual Blender process that will be spawned).
- Adds a new environment variable `LD_PRELOAD` to point to the folder with the libs (this variable is looked up by `ld`, which is the launcher used to actually run the Blender executable, since it is dynamically linked).
- Runs Blender in this new environment, and passes the args.

Anyway, the troubleshooting you would have to do here is to ensure that `LD_PRELOAD` points to the right path on your system.

**Comment by wwderw** [comment]
Well, managed to get it past that error (without adding the static libraries, just seeing if I could get it out of that error message).  Did that, but then it came up with another library not found.

While it is included in the static library tarball (right now it's coming up with a libjemalloc.so.1 error), it isn't in the ".so.1" naming format.

I would imagine that I would need to edit this portion of the script for all the libraries in the static tarball:

![Lib Part of Script](https://user-images.githubusercontent.com/24878362/57182235-72008d80-6e62-11e9-92bd-b143946e785e.png)

I'm just not finding the such and such library.so.1 format to add into the script or could use another file or am I just totally off my rocker here?

**Comment by marechal-p** [comment]
I'm not really sure how the naming conventions works here, but it sounds like some kind of versioning system, `.so.1` and `.so.2` could be two different version?

The stupid approach would be to rename the included libraries to match what the Blender executable wants, and stuff more libraries inside the `LD_PRELOAD` variable.

According to [this](http://man7.org/linux/man-pages/man8/ld.so.8.html):

```
       LD_PRELOAD
              A list of additional, user-specified, ELF shared objects to be
              loaded before all others.  This feature can be used to selec‐
              tively override functions in other shared objects.

              The items of the list can be separated by spaces or colons,
              and there is no support for escaping either separator.  The
              objects are searched for using the rules given under DESCRIP‐
              TION.  Objects are searched for and added to the link map in
              the left-to-right order specified in the list.

              In secure-execution mode, preload pathnames containing slashes
              are ignored.  Furthermore, shared objects are preloaded only
              from the standard search directories and only if they have
              set-user-ID mode bit enabled (which is not typical).

              Within the names specified in the LD_PRELOAD list, the dynamic
              linker understands the tokens $ORIGIN, $LIB, and $PLATFORM (or
              the versions using curly braces around the names) as described
              above in Rpath token expansion.  (See also the discussion of
              quoting under the description of LD_LIBRARY_PATH.)

              There are various methods of specifying libraries to be pre‐
              loaded, and these are handled in the following order:

              (1) The LD_PRELOAD environment variable.

              (2) The --preload command-line option when invoking the
                  dynamic linker directly.

              (3) The /etc/ld.so.preload file (described below).
```

**Comment by marechal-p** [comment]
If the renaming doesn't work, then maybe you could try to run `ldd` on your own clean install of UPBGE, look at the loaded libraries for such names and copy them over to your portable lib folder?

Sounds sketchy but I think it is nice to first aim at having _something_ working :)

**Comment by wwderw** [comment]
I used this command:

`cp $(ldd /path/to/executable | cut -d \( -f1 | cut -d \> -f2) path/to/destination`

I now have a total of 58 library files (including and in the same folder as the 3 that were already given in this thread here).

Now, I knew the libjemalloc was the first one that it was asking for, so to test to make sure I was doing it right, I was just going to see if I could get that error to change to another library.  If it did, I would have done the same thing that I did for libjemalloc.

I added this to the script:

`libjemalloc_path        = os.path.join(libs_path, 'libjemalloc.so.1')`

Error is still there.

Either what I did is totally wrong, or there was something else that I needed to do.

Thoughts?

**Comment by marechal-p** [comment]
Did you change the part where it create the value for `LD_PRELOAD` ?

It should look something like `... = f'{tbb_path} {jemalloc_path}'.

**Comment by wwderw** [comment]
adding `{libjemalloc_path}` get's this error:

![UPBGE New Error](https://user-images.githubusercontent.com/24878362/57183889-a121f980-6e78-11e9-816a-cb78a251eb2a.png)

And I checked the permissions of the blender binary and nothing would limit my permissions, at least what is showing up in the binaries properties.

**Comment by wwderw** [comment]
Never mind, I know what I did and it fixed it.  Got a new library issue.

I'll see about getting all the others on there (it'll take awhile I'm sure, I've gotten slower with my typing) and see if that works.

Let y'all know.

**Comment by wwderw** [comment]
Well, after all 58 were scripted in there, final error was this, since it's not the typical shared object library, I don't know it:

![UPBGE Final Script Requirement](https://user-images.githubusercontent.com/24878362/57185186-717cec80-6e8c-11e9-94f4-946313b40bb6.png)

**Comment by marechal-p** [comment]
Googled it real quick, I don't really know either...

**Comment by wwderw** [comment]
Bummer, I guess there really is no way of getting this portable.

**Comment by wwderw** [comment]
Ok, I tried a hail mary, I swapped out the libtbb file that I got from this thread here to the one that was on the computer that I built UPBGE on and this is what I got:

![OK](https://user-images.githubusercontent.com/24878362/57185854-5b295d80-6e99-11e9-9af8-59c56aeb0800.png)

Not to sure where I'm supposed to go from here.

**Comment by lordloki** [comment]
Another solution is to compile UPBGE with TBB static

**Comment by wwderw** [comment]
If I knew how to, ideally I would have all the libraries static.

Size is less of a concern for me compared to portability, it's just knowing what to do and how to do it during the build process.

**Comment by marechal-p** [comment]
https://stackoverflow.com/a/2152157/7983255

I think these statements must be defined in some `CMakeLists.txt` file, but which ¯\\\_(ツ)\_/¯

Hopefully (and not so at the same time), in the [main one](https://github.com/UPBGE/blender/blob/master/CMakeLists.txt)?

**Comment by marechal-p** [comment]
After a quick search, there's quite a lot of big files involving `tbb`, but I don't know how CMake works enough to help with this :(

**Comment by wwderw** [comment]
This is all above me.  I know nothing about how CMake works.  If only it was as simple as what's listed in OBS build instructions for a portable build.

**Comment by marechal-p** [comment]
> Another solution is to compile UPBGE with TBB static

@lordloki do you have any pointers for @wwderw ?

**Comment by lordloki** [comment]
Check https://github.com/UPBGE/blender/blob/master/build_files/cmake/platform/platform_win32.cmake
Line 534. We should do the same for linux.

Before to this, you should exec install_deps.sh to build tbb libraries in /opt/lib

In 2 weeks i will have enough free time to make a linux static build

**Comment by lordloki** [comment]
There is another method, I tested that in ubuntu 18.04. You have to install libtool, autoconf, tcl, nasm and build-essentials.
You have to do:
- Create a new directory: Dev
- Clone blender repository and upbge at same level
- Enter in blender directory and execute 'make deps'
- Enter in upbge directory and execute 'make'
and voila

**Comment by wwderw** [comment]
Are there other instructions that have to be done and if so, what would be the recommended order?

I'm getting "no rule to make target 'deps'"

**Comment by lordloki** [comment]
it is `make deps` without quote marks
![image](https://user-images.githubusercontent.com/1015605/57349587-03ba1480-715b-11e9-88f7-6eaa04f234ca.png)

**Comment by lordloki** [comment]
The binary build this way is totally portable
![image](https://user-images.githubusercontent.com/1015605/57349658-44199280-715b-11e9-80b2-7a9a8ddbec42.png)

**Comment by wwderw** [comment]
I didn't use quotes:

![make deps](https://user-images.githubusercontent.com/24878362/57350863-5082f880-7125-11e9-9331-b0dffe16aba7.png)

**Comment by wwderw** [comment]
I did notice 2 directors in the Dev folder that I don't have, don't know where you got them and that is build_linux and lib along with blender and upbge.  All I have is the source for blender 2.79 and the source for upbge.

I don't know if that would make a difference with make deps issue or not, but it is something different from what I have versus what you are showing.

**Comment by lordloki** [comment]
blender and upbge directories are cloned from blender and upbge git repositories.
build_linux and lib are directories generated from 'make deps' and 'make'

**Comment by wwderw** [comment]
I started thinking that was the case early this morning since I posted that, but I wasn't sure.

I'm at a lost, I downloads the 5 programs that you mentioned and did the other steps, but I couldn't get make deps to work.

**Comment by lordloki** [comment]
Could you do 'ls' inside blender directory and post a capture of the result?

**Comment by wwderw** [comment]
![ls](https://user-images.githubusercontent.com/24878362/57393868-ad17ff00-7189-11e9-80ee-4ab06a6a50a3.png)

**Comment by wwderw** [comment]
Ok, I was thinking that maybe KDE NEON was missing some other dependency to get this to work, so I loaded up default Ubuntu install in a VM using regular install, not minimum install.

Did all the updates, installed the dependencies listed in the post above and it still says no rule to make target 'deps'.

Something else has got to be missing.  Some other package or something else that needs to be done that I'm just missing.

**Comment by wwderw** [comment]
It must be something with the Blender 2.79 source that I used for `make deps`.  

I used `make deps` in the upbge folder (I know it wasn't apart of the instructions, but since it was in a VM, if something did screw it up, it's relatively easy to fix up a new VM) using the source in this repo and it did start doing the `make deps`, it however, did fail to complete (I think it failed on spnav), but it did start the process.

To me, since it did start the process in the other folder, I should have everything working.  At least in theory, thoughts?

**Comment by marechal-p** [comment]
What do you mean by "it did start the process"? From experience when making a target, if it failed before completion, my build would be broken :(

Did you clone Blender from here? https://git.blender.org/gitweb/gitweb.cgi/blender.git

Also did you correctly clone UPBGE repository inside a different folder? (it uses `blender` by default, not `upbge`, you have to change it when cloning).

Just tried to clone both upbge and blender, and run `make deps` in the latter, it works. (Ubuntu 16.04)

**Comment by wwderw** [comment]
> What do you mean by "it did start the process"? From experience when making a target, if it failed before completion, my build would be broken :(

Just for giggles, I went into the UPBGE directory and did 'make deps', and it did start building the deps from within that directory, but it did not from the blender directory.

>Did you clone Blender from here? https://git.blender.org/gitweb/gitweb.cgi/blender.git

No, I downloaded the source code from blender.org.

>Also did you correctly clone UPBGE repository inside a different folder? (it uses blender by default, not upbge, you have to change it when cloning).

I downloaded the zip from this repo and then extracted it into a upbge folder within the Dev folder.  I had both the blender and upbge folders with the newly created Dev folder.

I CD into blender and issued 'make deps' from which I got that error that's on the screenshot.

**Comment by wwderw** [comment]
I git cloned both repos this time.

Blender did start doing the make dep process, but this is what I get with spnav:

![Error](https://user-images.githubusercontent.com/24878362/57558884-26a81c80-7345-11e9-947c-bdd8e96d727e.png)

Is there anything in this process that might be considered too trivial that it wasn't mentioned, but is a step that I should be doing?

**Comment by marechal-p** [comment]
Look at the error, missing a header file: `Xlib.h`. It looks like an Ubuntu terminal, so I search on https://packages.ubuntu.com for packages containing that file:

> https://packages.ubuntu.com/search?searchon=contents&keywords=Xlib.h&mode=exactfilename&suite=xenial&arch=any

Maybe just a matter of installing the `libx11-dev` package?

**Comment by wwderw** [comment]
Well, that did work and it went through a long process, but still failed and no handy dandy item in red this time.

![Error2](https://user-images.githubusercontent.com/24878362/57560009-10e92600-734a-11e9-86a4-3e967e11c722.png)

I see the references to log file, but I can't make head or tails of it.

**Comment by marechal-p** [comment]
I would say that we don't have enough information from your screenshot alone :/

**Comment by wwderw** [comment]
Is there a option when initiating the 'make deps' command to output whatever happens in the terminal to a text file or something like that?  Or do you think the log file would be sufficient from the CMakeOutput.log?

**Comment by lordloki** [comment]
I have created a VMware virtual machine with all the UPBGE environment configured. With this Virtual machine you can build portable builds for linux.

Check this: https://github.com/UPBGE/upbge/wiki/Build-UPBGE-on-Linux-VMWare
