### ISSUE TITLE
UPBGE downloads

### ISSUE THREAD

**Issue by youle31** [UPBGE/upbge#1041]
I paste here some links we have where we stored some builds/infos:

## > https://upbge.org/

Hosted from GitHub pages at https://github.com/UPBGE/UPBGE-Web/tree/gh-pages

## > https://github.com/bge-community/upbge/releases

Fork where builds are triggered on commit and release

## > https://github.com/UPBGE/upbge/releases

---

**Some old Windows builds:**
https://drive.google.com/drive/folders/0B8EITuogwZr6Mi1EQW5FbERqTHc

**Last builds from youle based on final 2.7 master:**
https://drive.google.com/drive/folders/1Kzj-4MN7EddvXXG5icDgdD7jUpDQsvIx?usp=sharing
(I think they are a bit more stable than the last master)

ge_23a_attachment for Linux64: https://drive.google.com/file/d/1WfW812Gmwb2WNvp08reC7FcQlWl0oTb5/view?usp=sharing

**Comment by youle31** [comment]
Feel free to add resources.

@lordloki : How much do you pay for upbge.org? Can I send you a donation with paypal on your mail?

**Comment by marechal-p** [comment]
I reformatted the message a bit, since it is going to be pinned.

Thanks for the links, nice idea :)

**Comment by youle31** [comment]
Updated first post with the last builds I did based on last 2.7 master

**Comment by joelgomes1994** [comment]
Hey, why not hosting the older releases from the [Drive folder](https://drive.google.com/drive/folders/0B8EITuogwZr6Mi1EQW5FbERqTHc) to [Github's releases](https://github.com/UPBGE/blender/releases) page?

**Comment by lordloki** [comment]
I tryed but i cant edit the releases to include the build

**Comment by lordloki** [comment]
I updated upbge's github release pages to add upbge releases.
Additionally we have this Mega folder with all the former releases and new upbge-eevee releases.
https://mega.nz/#F!k9MW1KiZ!UOKzjh3IQ0GEgjQ6GUc7ug

**Comment by youle31** [comment]
upbge releases page is this one? https://github.com/UPBGE/upbge/releases

**Comment by lordloki** [comment]
Closing as the other pinned issue. It will be showed in the top part only

**Comment by ShayBox** [comment]
What about a Steam release similar to Blender & Godot?  
Game creators usually have and release on Steam, maybe even a beta channel if it's possible with CI
