### ISSUE TITLE
UPBGE 0.2.4b issues and games crashs report

### ISSUE THREAD

**Issue by RedstarBelg** [UPBGE/upbge#1044]
Good day everyone,

I try to create a video game with Blender Game Engine and I was recently to the 2.70 (from Blender 2.70). I have try the UpBGE 0.2.4 but it seems I have some problems.

This is a big project, so I think it will be interresting to see what's wrong if there are bugs.

So, first thing: I have create a "main menu" game. To customise my character, I must append it to the currect blend dynamicaly. When I use libload, the game crash after load a external blend file with it (the window close without error messages).

Should I use an other trick ?

If you need anything to test that, ask me. I can provide my entire project.

Second thing: i've receive a message warning from the python console: it said "mesh 'something' has no primitives for 'mat' material....". What does it mean ?

**Comment by marechal-p** [comment]
Where did you get UPBGE 0.2.4? The official release was already known to be somewhat unstable, but later builds following master's tip got more and more bugged regarding libloading.

Two options:
- If you have too much trouble with 0.2.4, maybe try to use an older version, fallback to 2.70 if you keep having troubles and that works with you.
- If you have the means of contributing to the sources and fixing some of your issues, do :)

**Comment by RedstarBelg** [comment]
From the officiel [UPBGE site](https://upbge.org/).

In the 0.2.3 version, if I quit the game with "esc" key, the game crachs like the 0.2.4.

I absolutely need to use the "mouselook logic brick" for optimisation purpose, Blender 2.70 hasn't it and the 2.72 version has the same problem about libload (but it had the mouselook brick).

I've tried 2.73, 2.74, 2.75 and 2.79 but the problem is the same...

[Here, this files should be useful. google drive link](https://drive.google.com/file/d/1SMBxq8oAu2Ht8eUKiR_w817jZhwr-bcF/view?usp=sharing)

If something missing, tell me.

**Comment by BluePrintRandom** [comment]
try appending the whole game into a new .blend in the upbge version you want to use

**Comment by RedstarBelg** [comment]
Hello there,

After one year, i come back and i have finally found the problem about "bge.logic.LibLoad". This module is very broken.

I say broken because the "link blend" tool, with groups instance, work perfectly. I just want to warn you about that.

**Comment by lordloki** [comment]
This issue should fix now in 0.2.5. Closing. Thanks for reporting
