### ISSUE TITLE
UPBGE bug In Logic Bricks float value less than one

### ISSUE THREAD

**Issue by mmuhomorik** [UPBGE/upbge#1047]
UPBGE bug In Logic Bricks when you choose the keyboard and Character motion or Simple Motion and set the value to 0.10 or 0.20 or 0.30 or -0.10 or -0.20 or -0.30 character does not move anywhere, but if you put an integer 1 or 2 or -1 or -2 it moves but very fast.

Create cube -> open Logic Editor → add sensor keyboard → add controller and → add actuator Motion → Character motion or Simple Motion and set the value to 0.10 or 0.20 or 0.30 or -0.10 or -0.20 or -0.30 character does not move anywhere, but if you put a whole The number 1 or 2 or -1 or -2 moves but very quickly. The error is that the values with a dot less than 1 do not work.

Operating system: Linux Debian 9 x64
UPBGE 0.2.4 Date: 2018-11-08 19:50 Hash: b387a7f

**Comment by BluePrintRandom** [comment]
can you try this branch for me?
https://drive.google.com/open?id=1lW81SLyVcOymYvvCfCTS_O_vfDe3qZSK

ge23_oldBullet ?

**Comment by Cygn** [comment]
Hello,

Same issue here on Linux 64, v2.4b2.79. 

Something ele to try ? (the link to the test branch is offline)

**Comment by lordloki** [comment]
It works in current 0.2.5 and 0.3.
Closing the issue. Thanks for reporting.
