### ISSUE TITLE
Feature Request: Support for Raspberry Pi (since 2.79 has an ARM package working already)

### ISSUE THREAD

**Issue by skyfpv** [UPBGE/upbge#1057]
I'd like some help getting UPBGE working on the Raspberry Pi. I just picked up a Pi4, and it runs Vanilla Blender 2.79 impressively well. A simple scene yields upwards of 60fps at lower resolutions (480p). I installed 2.79 via "sudo apt install blender", and it seems as though this is the arch linux package where the port lives. 

https://archlinuxarm.org/packages/armv7h/blender/files/PKGBUILD

I'd like to see if it would be possible to perform this same port for UPBGE so that I can get back joystick support (since the original port didn't seem to pick up joystick inputs).

![blender on pi](https://user-images.githubusercontent.com/45609851/65558751-3770bd80-def5-11e9-95e9-ed301142c09f.png)

**Comment by lordloki** [comment]
Sorry but we don't have any Raspberry Pi to make/test the build. If you want I can guide you through the compilation.

Anyway, following the nuew issue tracker rules I close the report but I add the tags to can check  the feature request later.

Thanks for your proposal.

**Comment by skyfpv** [comment]
@lordloki I'd be more than happy to ship a raspberry pi to ya if it's something you'd be interested in playing with. Otherwise I'd love to take a crack at compiling for the ARM architecture.

**Comment by BluePrintRandom** [comment]
also look at the jetson Nano - and xavier modules*

**Comment by BluePrintRandom** [comment]
I would pay for you to have a devkit loki

this is what the tablet I want to make uses*

https://developer.nvidia.com/embedded/jetson-xavier-nx

**Comment by lordloki** [comment]
@skyfpv @BluePrintRandom thanks for both offers but i will try with QEMU+raspbian for raspberry or linux + jetson containers for jetson nano first.
