### ISSUE TITLE
UPBGE on FreeBSD

### ISSUE THREAD

**Issue by cederom** [UPBGE/upbge#1081]
Hello world!

Thank you for creating UPBGE. The 2.80+ decission to simply wipe out Game Engine out of Blender is a __disaster__. That was the main reason I was using Blender at all. Now the reason is lost for some UX folks "that know better and destroy something that was there for decades"^TM :-(

On FreeBSD that is my OS of choice there is Blender 2.80 already. How can I create UPBGE package for FreeBSD and how to use is with system provided Blender 2.80?

Any hints welcome :-)
Tomek

**Comment by youle31** [comment]
upbge0.3 branch (based on blender 2.8) is a complete fork of blender.
Last time i tested compilation on Linux Mint, i was not abled to build blenderplayer but you can maybe build blender with gameengine disabling blenderplayer following these instructions:

https://github.com/UPBGE/blender/issues/1053

Instead of git checkout eevee_merge8, do git checkout upbge0.3

This is experimental.

**Comment by cederom** [comment]
Thank you @youle31 :-) Please reopen the issue until we have working solution on FreeBSD and we could ask all related questions here in one place instead opening new tickets :-) I will ask more general questions in https://github.com/UPBGE/blender/issues/1082 :-)

**Comment by cederom** [comment]
Thank you for reopening :-) Current status:
* I am working on `upbge0.3` branch.
* I have created `make.sh` script just to have build automated :-)
* `cmake` works.
* `make` build fails at one point where physics meet python.
* I have problems running `build_files/build_environment/install_deps.sh` it does not respect any of the commandline parameters (specifically `-s` and `-i` and `--no-sudo` directories not to touch the build OS that I am working on). Any hints welcome :-)
* I have 24 CPU 128GB RAM machine for build, `make -j24` works much faster than on a laptop, still crashes in the same place where physics meets python, probably a dependency issue, so I have to fix the `install_deps.sh` script :-)

**Comment by lordloki** [comment]
There are 2 methods to build dependencies. One of them is install_deps.sh, the another one is exec 'make deps' placed in upbge0.3 sources directory

**Comment by cederom** [comment]
Today's update: @sambler turned out to be maintainer of the Blender project on FreeBSD (and many more impressive 3D engines and visual utilities suite), he has provided a working solution to have Blender-2.79 automatically compiled and installed right next to Blender-2.80 on FreeBSD and was so kind to share the solution.. so I will use this 2.79 as priority for me is to finish the ongoing project.. but I will still try to build UPBGE on FreeBSD.. in the best situation we would prefer to have a static release package for a port :-)

https://github.com/sambler/sambler-redports/tree/master/graphics/blender279

**Comment by BluePrintRandom** [comment]
you do know there is a upbge port of blender 2.8 eh?

upbge branch upbge0.3 :D

**Comment by cederom** [comment]
sure I am working to build `upbge0.3` in the first place :-)

**Comment by youle31** [comment]
if you manage to install dependancies, you can try to compile upbge_linking_hell branch doing:

make update
make -j12 (if you want debug build, make -j12 debug)

**Comment by cederom** [comment]
Thank you @youle31 :-) In perfect situation build on Linux and build on FreeBSD should look exactly the same because both are POSIX systems :-)

Looking at how Blender is organized, there is a dynamically linked binary built in `/usr/local/bin/blender` and some dependencies are installed as separate system packages.

For various portability reasons I more often consider building statically linked binaries especially on Linux because FreeBSD can also emulate Linux ELF the only problem are the Linux dependencies ;-) On FreeBSD when something works on one machine it works on another, while when it works on one Linux there is a big change it will not on another Linux. This is why I stick to FreeBSD :-) 

If you have a static binary of `upbge` I could try to run in directly on FreeBSD (there is Centos7 core available) :-)

**Comment by youle31** [comment]
(i just wanted to warn that last upbge_linking_hell update has new issues because BF did changes with cmake and make which need to be fixed, then what i said in previous post is not working anymore, for now)

**Comment by sambler** [comment]
I have got the upbge0.3 branch built and running on FreeBSD, I have used the ports tree and plan to add it as an official port. Right now, I'm not sure if I will get it added now or wait for an official 0.3 tag. I renamed the binaries to upbge and upbgeplayer to allow it to be installed at the same time as blender.

When is it planned to tag the 0.3 release?

For anyone interested the initial port can be found [here](https://github.com/sambler/sambler-redports/tree/master/graphics/upbge).

**Comment by youle31** [comment]
💯 ! (else, idk about tagging and official things)

**Comment by lordloki** [comment]
0.3 release it is not ready yet. It will need a year more or less.

**Comment by cederom** [comment]
WHOH @sambler YOU ROX! THANK YOU!! :-) :-)

I did build package on one machine and it works on another machine (`FreeBSD 12.1-RELEASE`) :-) 

There seems to be a problem with `embree` dependency - it depends on something that is not there even if current embree package is installed. Build works with embree disabled :-)

Maybe you can create `graphics/upbge-devel` based on `0.3` branch and  `graphics/upbge` based on `0.2.4` release? :-)

Is `0.2.4` worth the effort @youle31 @lordloki @BluePrintRandom ? :-)

Is it possible to create `BGE` Add-On so it can be included easily dynamically into upstream Blender or it has to be compiled-into-the-core?

**Comment by sambler** [comment]
@cederom, I overlooked the fact that the embree port has not [been updated](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=239314), the old version was meant to have been moved to [graphics/embree2](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=240117).

To build 0.2.4, it is like blender 2.79, mostly a need for the older 1.8.x version of openimageio.

Not to belittle the upbge development, but I don't see a big demand for upbge on FreeBSD, even blender use isn't large. So I don't see the need to keep multiple versions in the official ports, which makes it more a choice of which version is more deserving of support right now?

The UPBGE/blender-addons have changes that are intended for use with upbge. I wouldn't expect any of the upbge addon changes to get accepted upstream. They are python modules (all as text scripts) and could be swapped for blenders addons, but you may find some changes that rely on upbge features that don't exist in blender.

**Comment by cederom** [comment]
Allright @sambler you are right, probably only us will use it ;-) However, to stay BSD, when its non-release we should mark it with -devel suffix :-)

What I meant with Add-On is to make whole BGE an add-on so it can be compiled separately and loaded into upstream Blender.. but that is probably for a dedicated thread/issue :-)

**Comment by sambler** [comment]
@cederom, I'm really sure that turning the game engine into an addon would not work, there is too much code sharing with the rest of blender. If it was possible this project wouldn't be using the complete blender source tree.

**Comment by cederom** [comment]
BGE has its problems. It may be replaced with something more elegant. But I was really shocked to see it simply removed with no alternative.. while I am still using it in my projects :-(

I hope some sort of Game Mode will be implemented soon in the upstream so we can use it in VR applications even if physics is not there :-)

This is why I am really happy to have it back in a form of UPBGE on my FreeBSD :-)

THANK YOU!!!
