### ISSUE TITLE
Rename `UPBGE/blender` to `UPBGE/upbge`

### ISSUE THREAD

**Issue by marechal-p** [UPBGE/upbge#1083]
I can actually rename the repository, but I was wondering if everyone were ok with this.

This is not really important, but I do think it would make more sense to have the actual repository named after UPBGE.

After the rename, GitHub will keep redirecting the olds links to the new one, for all protocols (http/s + git), which means people won't even notice something has changed.

@lordloki @youle31 @BluePrintRandom

**Comment by youle31** [comment]
I don't mind.

**Comment by BluePrintRandom** [comment]
as long as it does not break anything it's ok with me

**Comment by marechal-p** [comment]
Done!
