### ISSUE TITLE
setting mesh vertex color also appears to 'lock' translation 

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/upbge#1084]
setting mesh vertex color also appears to 'lock' translation 
(like setting object color does)
https://www.youtube.com/watch?v=sHV6KTuI6hs

**Comment by youle31** [comment]
Is this bug still in last master?

**Comment by BluePrintRandom** [comment]
No, it appears to be fixed (I tested in ipo_controllers branch)
