### ISSUE TITLE
roadmap to release - upbge 0.30

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/upbge#1087]
what is left to do before the first release?

I find the branch quite stable and usable,

some missing things still exist but could these be earmarked for 0.3.1 etc?

**Comment by lordloki** [comment]
Before the 0.3 release we have to be at 0.2.4 level and recover old lost features.

**Comment by BluePrintRandom** [comment]
Do you have some sort of list you are working off of ?

maybe some onlookers would start trying to pick off a few for you if we had a list?
great work so far and thank you!

**Comment by lordloki** [comment]
There is no a list. I am taking every commit from upbge 0.1.9, reviewing and applying if it is acceptable.
