### ISSUE TITLE
something strange with current master / setPosition

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/upbge#1090]
https://www.youtube.com/watch?v=Kob0P2nATis

something is behaving strangely with current master

**Comment by youle31** [comment]
I guess it comes from a line added in KX_GameObject::TagForUpdate

BKE_object_apply_mat4(ob, ob->obmat, ob->parent...)

This line was added when working on blenderobject color. It would need a VERY simple file to reproduce the thing to see if it is really a bug, if we can workaround, what behaviour is the best (with or without this line: BKE_object_apply_mat4)

**Comment by BluePrintRandom** [comment]
👍

**Comment by youle31** [comment]
I reverted the change I did for now in TagForUpdate, I only use BKE_object_apply_mat4 when we use object color API because i noticed this was causing issues with some of my test files too

**Comment by BluePrintRandom** [comment]
Thank you !
