### ISSUE TITLE
Windows Ink Support

### ISSUE THREAD

**Issue by riceart** [UPBGE/upbge#1094]
Hello, since release of windows 10 revision 1511 dropped support for wintab api and force devices to use Windows Ink, tabletpc users have a lot of problems with their pen devices. Blender 2.8 get that support and works fine. Unfortunately anything pre2.8 will never get it. So i was wondering if there is any chance to add Windows Ink api support for newer devices that use Windows 10.

Few topics on this issue
https://developer.blender.org/T57538
https://developer.blender.org/T55589

Solution for 2.80
https://developer.blender.org/D4314

Best Regards, Paul.

**Comment by youle31** [comment]
I don't have tabletpc, then I couldn't test if i wanted to work on this, but we have a 2.8 branch named upbge0.3 if you want to test.
lordloki did builds here: https://mega.nz/#F!t9EEFSaS!JPiOPSInCZyU-SW_-rhEOQ

**Comment by riceart** [comment]
Thank you for your kind attention. Ive downloaded this version and it works cause its 2.8. Sorry for my english if i was missunderstood but Im looking for pre 2.8 version of blender with windows ink like 2.79.

Best Regards, Paul.

**Comment by youle31** [comment]
If you know how to compile blender and edit sources, you can try to manually apply the patch (download raw diff here: https://developer.blender.org/D4314), else, as we're not tabletpc users, we can't test, then we can't help. The file names are indicated in the diff file. The "+" are for the lines added and the "-" are for the lines removed. Sorry, I think we can't do more.

Unless someone who has this device read this and wants to help, we can't do anything.

Then I close this report. Sorry that we can't help more.

**Comment by riceart** [comment]
OK, thank you very much for giving direction. Ive no idea what are you talking about but will try my best.

Best Regards, Paul.
