### ISSUE TITLE
added.groupMembers not populated on spawn in master

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/upbge#1097]
adding a group of objects using

added = own.scene.addObject('groupInstance',own,0)
print(added.groupMembers)

prints none at the moment even with a group full of objects.

**Comment by BluePrintRandom** [comment]
do you have any suggestion to how I may edit KX_Scene?



I tried editing it like before to get my ragdolls working using

    if (!BKE_collection_has_object(group, blenderobj)) 
    
and it now produces a crash however I am terrible at C++

**Comment by lordloki** [comment]
Can we close this issue BPR?

**Comment by BluePrintRandom** [comment]
💯 
thank you loki !
