### ISSUE TITLE
Feature request: Please return old tool shelf too and I will never use official blender builds.

### ISSUE THREAD

**Issue by thima2017** [UPBGE/upbge#1099]
I saw the UPBGE Eevee experimental build and you get the blender game logic editor back. It's wow! Thank you! I think the last one thing to fix is the useless blender 2.8 tool shelf. Or maybe it's possible just add old tool shelf to new one, like there https://devtalk.blender.org/t/blender-2-8-user-interface-design/505/1423

**Comment by youle31** [comment]
hi, this would be very difficult to do technically, and you can find most of the options in the context menus now. If you use 2.7 keymap, this is with W key, else this is right click
