### ISSUE TITLE
world settings

### ISSUE THREAD

**Issue by RomStef** [UPBGE/upbge#1101]
hi guys  ,
I'm trying to reproduce the world setup and lights configurations of the last upbge 0.2.9b in upbge 0.3.0 alpha.
I have made a little playground.

this is the world sahder
![Immagine_2](https://user-images.githubusercontent.com/20901566/73032404-4c2b7680-3e3f-11ea-957e-56c2571f2d75.jpg)

this is the final resoult
![Immagine_1](https://user-images.githubusercontent.com/20901566/73032427-5baabf80-3e3f-11ea-9838-28c40e4c3016.jpg)

this is the demo for the community if anyone want to try it, hope you like it.
[upbge030_suzanne_playground.zip](https://github.com/UPBGE/upbge/files/4106041/upbge030_suzanne_playground.zip)

**Comment by youle31** [comment]
Cool! Thanks for sharing. It should be easy to animate with a small python script. I'll give a try now

**Comment by RomStef** [comment]
I'm not an expert in environment lights, if you want to improve the setup, we can use it as default in the next release of upbge

**Comment by youle31** [comment]
![Sans titre](https://user-images.githubusercontent.com/10052509/73033698-1daf9a80-3e43-11ea-87ef-1e3234469fee.png)

**Comment by youle31** [comment]
a gif recorded at 15fps
![voiture](https://user-images.githubusercontent.com/10052509/73033932-cfe76200-3e43-11ea-8235-a3e84935087d.gif)

**Comment by RomStef** [comment]
With a little bit of work , we can integrate a basic day night cycle and some cool effect. I can't figure out how to reproduce a decent mist effect. Maybe with the volume shader, i don't know

**Comment by youle31** [comment]
maybe with input camera node you can get the distance to camera

**Comment by RomStef** [comment]
Omg, you are right.

**Comment by RomStef** [comment]
I'ts not a real upgrade but i have added a sun
![Immagine_3](https://user-images.githubusercontent.com/20901566/73144275-6a45e080-40a4-11ea-999e-b1576b503a0f.jpg)

A little bit of mist visible at 100m to the camera
![Immagine_4](https://user-images.githubusercontent.com/20901566/73144276-6a45e080-40a4-11ea-8b16-abbad9d05a54.jpg)

And setting the camera lens to 20mm for  remove the fisheye effect.

The Third step must be the sun animation and change sky color dynamically

**Comment by RomStef** [comment]
Upgrade
 - Added a sky dome with clouds
 - Script for animate the clouds (Thanks to @youle31 ) 
 - script to animate the sun (and the sun lamp) according to the hours spent in the game

[upbge030_suzanne_playground.zip](https://github.com/UPBGE/upbge/files/4120380/upbge030_suzanne_playground.zip)

https://youtu.be/UUBEwuJWO6E

**Comment by AFWSI** [comment]
> 
> 
> a gif recorded at 15fps
> ![voiture](https://user-images.githubusercontent.com/10052509/73033932-cfe76200-3e43-11ea-8235-a3e84935087d.gif)

How did you get it to animate? What logic(If any) did you use?

**Comment by RomStef** [comment]
the file is free to download. You can find it in my previous comment. The logic to animate the clouds is under the world object (the world is an empty object)

**Comment by lordloki** [comment]
Hi,
I move this to https://github.com/UPBGE/upbge/discussions under Resources to better organization. Thanks.
