### ISSUE TITLE
UPBGE KX_INPUT__JUST_ACTIVATED not working?

### ISSUE THREAD

**Issue by rECRUTAsantos** [UPBGE/upbge#1102]
I'm not able to use 'tap' via python

example:

from bge import logic as g, events

tap = g.KX_INPUT_JUST_ACTIVATED
ms = g.mouse.inputs
LMB = ms[events.LEFTMOUSE].values "or .queue/.status"

if LMB == tap:
         print('hello')

(does not work)

**Comment by youle31** [comment]
This is working like in this .blend:

http://pasteall.org/blend/index.php?id=52818

1 = just activated mouse/keyboard.inputs[...].queue
3 = just released mouse/keyboard.inputs[...].queue
2 = active mouse/keyboard.inputs[...].values

**Comment by rECRUTAsantos** [comment]
> Isso está funcionando como neste .blend:
> 
> http://pasteall.org/blend/index.php?id=52818
> 
> 1 = acabou de ativar mouse / teclado.inputs [...]. Fila
> 3 = acabou de liberar mouse / keyboard.inputs [...]. Fila
> 2 = ativo mouse / keyboard.inputs [...].

thank you very much friend. It worked here, I had tried everything. it helped a lot

**Comment by rECRUTAsantos** [comment]
thank you very much friend. It worked here, I had tried everything. it
helped a lot. tanks

Em sáb., 25 de jan. de 2020 às 14:07, youle31 <notifications@github.com>
escreveu:
