### ISSUE TITLE
Can't animate character using Action Animations from logic bricks.

### ISSUE THREAD

**Issue by adorno-dev** [UPBGE/upbge#1103]
When I try to animate my character using logic bricks (Keyboard -> Action (Play Loop End).
Is there some alternative solution for that??

**Comment by youle31** [comment]
Can you provide a file please? (Actions in some files doesn't work and this is not fixed for now, but a test file could help)

**Comment by youle31** [comment]
This should be fixed in last master since https://github.com/UPBGE/upbge/commit/ca696040c372e2791c495441867cb2df2be56cd1
