### ISSUE TITLE
Navmesh causes crash on Game Exit

### ISSUE THREAD

**Issue by IzaZed** [UPBGE/upbge#1104]
When setting any object to Navmesh in the physics Tab, the game will run, even perform the Navmesh calculation correctly, but then crashes on exit.

**Comment by lordloki** [comment]
The issue comes when we do undo to restore the scene original then we have to do BKE_id_free but Navmesh has no ID set.

**Comment by lordloki** [comment]
Fixed in current master. Thanks for report. Closing now
