### ISSUE TITLE
Numpy can't be used in embedded player 2x in row without restarting

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/upbge#1105]
https://www.youtube.com/watch?v=aNqfsnGQKRQ

if we import numpy, close engine -> start again -> import numpy we get some error messages

[nummpy.zip](https://github.com/UPBGE/upbge/files/4123740/nummpy.zip)

**Comment by marechal-p** [comment]
Does using module mode help, rather than script mode?

**Comment by BluePrintRandom** [comment]
![image](https://user-images.githubusercontent.com/7190873/73324711-c3c32200-4200-11ea-9b8c-fc795a146a05.png)

**Comment by marechal-p** [comment]
Seems to be a bug with numpy itself.

The BGE makes a backup of the modules before running the embedded player, and restores it at the end. This ensures that modules are not cached for eternity (until you restart Blender itself), and allows your game to always load modules from disk, else it would always hit the cache and never update modules.

The embedded player does not have this issue since no backup and restore is required.

The approximate call chain leading to the backup of the modules:

```
file: /source/gameengine/Ketsji/KX_PythonInit.cpp

- initGamePlayerPythonScripting
  - initPySysObjects
    - initPySysObjects
      - backupPySysObjects
```

I guess you can wrap numpy's importation somehow, since the ` sys`  object is not entirely backup'ed:

```py
# file: numpy_wrapper.py
import sys
if hasattr(sys, '__numpy__'):
    # restore module cache with backup ref
    numpy = sys.modules['numpy'] = sys.__numpy__
else:
    import numpy
    # store a backup ref
    sys.__numpy__ = numpy
```

And then to use it:

```py
from numpy_wrapper import numpy
```

**Comment by youle31** [comment]
I can't reproduce a bug with numpy in last master with this test file:

https://pasteall.org/blend/c18e144cf3194a829ccdc7cce2851f56

(neither in embedded, neither in standalone)

**Comment by BluePrintRandom** [comment]
Nice!

**Comment by BluePrintRandom** [comment]
![image](https://user-images.githubusercontent.com/7190873/80751095-0cc79280-8ade-11ea-8d8c-fdd61e586a9b.png)
this is from this build hash
![image](https://user-images.githubusercontent.com/7190873/80751121-1bae4500-8ade-11ea-84d2-a2adb4325366.png)


it fails the second time I run your test file @youle31

**Comment by BluePrintRandom** [comment]
(the first time it made kinda  a rainbow on the cube?)

**Comment by youle31** [comment]
I can't reproduce this bug (even if I restart 50 times, I have no error message). Yes, it is an example from gpu module doc

**Comment by lordloki** [comment]
I can confirm it.
![image](https://user-images.githubusercontent.com/1015605/80762446-dc631100-8b3c-11ea-805f-eed3a7bb8ea8.png)
It seems that is an issue of numpy itself (https://github.com/numpy/numpy/issues/14384)
A mitigation as pointer by an user in the numpy github tracker is to downgrading numpy to numpy==1.15.4
I'm going to see if it is possible this solution

**Comment by lordloki** [comment]
It works!! but the issue it with the version 1.15.4 we have the following error
![image](https://user-images.githubusercontent.com/1015605/80764174-6660a900-8b40-11ea-8e3d-975b7933deba.png)
and then we don't have audio. We can not solve this because _multiarray_umath needs numpy 1.16 and the numpy reload needs version 1.15.4

We will have to live with this issue.

**Comment by BluePrintRandom** [comment]
Ok - since we can use it in standalone it's not that big of a deal,

maybe we can think of a fix long term and come back to this?

I will close for now,

**Comment by marechal-p** [comment]
The issue comes from the fact that numpy does monkey patching on module initialization, and the BGE re-initialize numpy in a global Python context where the monkey patch cannot be applied twice. You can find the workaround code here:

```py
# file: numpy_wrapper.py

import sys

if 'numpy' not in sys.modules and hasattr(sys, '__numpy__'):
    # restore module cache with backup ref
    numpy = sys.modules['numpy'] = sys.__numpy__

else:
    import numpy
    # store a backup ref
    sys.__numpy__ = numpy
```

And then to use it:

```py
from numpy_wrapper import numpy
```

**Comment by lordloki** [comment]
Thanks. I will include in the release notes.

**Comment by marechal-p** [comment]
Just tried to import numpy on 0.2.5 and I don't get the crash... But when it fails with the `... has already a docstring` my workaround should apply.

**Comment by BluePrintRandom** [comment]
no crash for me either -

when I say "without restarting" I mean shutting down blender and opening it
again - the file works again =

**Comment by BluePrintRandom** [comment]
Is there a way to use your workaround if in embedded automatically
?

**Comment by youle31** [comment]
it's weird that you have this error and not me, maybe it is because of the way we build blender...

**Comment by lordloki** [comment]
I also have WITH_PYTHON_INSTALL_NUMPY enabled and my cmake is 3.15.3.
Very weird
