### ISSUE TITLE
Playing Actions(Animations) in RunTime causes crash

### ISSUE THREAD

**Issue by mohammedzero43** [UPBGE/upbge#1110]
The following project has an example of an animation that crashes when played:
https://drive.google.com/open?id=1QSbXKk4CNdP865ujdjGRMuXZAN4jZ9Pw

I passed --debug and got the crash followed by this error :
Memoryblock bPoseChannel_Runtime::bbone_rest_mats: double free

**Comment by youle31** [comment]
What are the steps to reproduce the bug?

Does it only occur at exit?

What if you uncheck "undo at exit" option?

**Comment by BluePrintRandom** [comment]
I think he said you have to hit a button two times in discord,

**Comment by youle31** [comment]
I have a crash related to undo at exit, but that's beyond my competence...

**Comment by mohammedzero43** [comment]
The the problem is everytime I try to play animation by pressing E (twice) it breaks i i disabled the animation and it worked properly

**Comment by youle31** [comment]
The url of the test file is not available anymore

**Comment by mohammedzero43** [comment]
@youle31  Forgive me , I mistakenly deleted it yesterday .. here's another copy :
https://drive.google.com/open?id=1U2a4I8gZMdDHsrPPBM9MCvG4fI3_TpJC

Triggering the animation twice causes the crash (Hold E to trigger the animation)

**Comment by youle31** [comment]
Ok, thanks, i'll take a look when i'll have time

**Comment by youle31** [comment]
I tried a fix here: https://github.com/UPBGE/upbge/commit/fd924be13d5dc35bfdbf73b4d84572478c7d916f ,  it will need time to review and test

**Comment by youle31** [comment]
Fixed in https://github.com/UPBGE/upbge/commit/6a7400ddc1590c557e03130fbde4fdf9c3cce482
