### ISSUE TITLE
Scene Exposure

### ISSUE THREAD

**Issue by RomStef** [UPBGE/upbge#1112]
At the moment , i'ts not possible to change the exposure on the fly.
If i want to change the light in the scene, i must to put to gray and black all the color (RGB and RAMP node) in all of my shaders nodes

**Comment by youle31** [comment]
I don't think we can do something about that because it is more eevee's code, but what I can say is that some changes in bge are not visibled if you don't use:
bge.logic.getCurrentScene().resetTaaSamples = True #to call each frame if you do a change each frame

**Comment by RomStef** [comment]
It works, thank you. Where can i find the documentation for all of this things ?

**Comment by youle31** [comment]
There is no documentation currently, it's very experimental. Sorry. You can only find some infos in the github commit log for now.

Glad my solution worked. I close the issue

**Comment by RomStef** [comment]
Don't worry about that , maybe we can group all of this tips with a tag
