### ISSUE TITLE
Change Light Color/Energy in game

### ISSUE THREAD

**Issue by IzaZed** [UPBGE/upbge#1124]
I don't know if the attribute is simply accessed differently since 2.8, but changing light attributes doesn't seem to affect the scene anymore

File:
[set_light_color.zip](https://github.com/UPBGE/upbge/files/4186391/set_light_color.zip)

goes for both color and energy

**Comment by BluePrintRandom** [comment]
I think you have to adjust the bpy object attributes*

lamp.blenderObject *

**Comment by IzaZed** [comment]
well, it should be the same via bpy as via bge, as both **bpy.types.Light** and **bge.types.KX_LightObject** have the attributes energy and color

**Comment by BluePrintRandom** [comment]
I don't think they are linked up yet*

**Comment by RomStef** [comment]
at the moment , changing properties of the bge objects module does not affect the scene itself. you must change the propreties from the bpy module , then refresh the scene. updating properties from bpy module it's a little bit heavy for the engine.

https://github.com/UPBGE/upbge/issues/1112

**Comment by RomStef** [comment]
before to open an issue take your time for reading the latest closed issue. maybe another asked the same ;)

**Comment by youle31** [comment]
Actually, I strongly recommend to use Python Tooltips in User Preferences > Interface:

![Sans titre](https://user-images.githubusercontent.com/10052509/74312824-b8303900-4d72-11ea-81e8-cdc40ce042ea.jpg)

If you do changes only with bpy, but that nothing is moving in the scene, you need to validate the changes with:

#IMPORTANT  
bge.logic.getCurrentScene().resetTaaSamples = True #to call each time you do something with bpy only

#IMPORTANT TOO  
In 2.8 bge, KX_GameObject is just a "container for a Blender Object.
you can access this Object like that:

kxob = bge.logic.getCurrentController().owner
ob = kxob.blenderObject

From there you can extrapolate:
kxLight = bge.logic.getCurrentScene().objects["Point"]
obLight = kxLight.blenderObject
def increaseLightPower():
    obLight.energy += 0.1

**Comment by IzaZed** [comment]
Alright, seems I didn't draw the line from #1112 to light attributes, whoopsi!
I'll get the code updated, then, thanks a lot :)

**Comment by lordloki** [comment]
I'm adding all these new tips under Release notes page (to be formatted later). 
If anyone is interested in helping with documentation, please let me know and I will give you rights.

**Comment by lordloki** [comment]
https://github.com/UPBGE/upbge/wiki/Release-notes-version-0.3.0

**Comment by youle31** [comment]
haha, yes, sorry, because it is bpy.data.lights and not bpy.data.objects

It should work if you use the code from the python tooltip @IzaZed  : )

**Comment by youle31** [comment]
light is maybe blenderObject.data ? I'd need to test

**Comment by youle31** [comment]
yes, light is blenderObject.data

Then you can do:

light = kxob.blenderObject.data
light.energy += 100 #test with light.color[2] -= 0.01 too
bge.logic.getCurrentScene().resetTaaSamples = True

**Comment by IzaZed** [comment]
You're incredible youle!
I do work with python tooltips all the time, to be honest I'm currently writing the docs for the logic nodes and just noticed that the light nodes didn't do anything.
Guess now they will

Closing this
