### ISSUE TITLE
hair dynamics ??

### ISSUE THREAD

**Issue by rt974** [UPBGE/upbge#1128]
does hair anim work ingame ? how do i use it ? it is written in the python api
{
bpy.types.ParticleSystem.use_hair_dynamics
Enable hair dynamics using cloth simulation
}
i see the hair renders just as in eevee wich is insane !!!
such a great job guys.

**Comment by youle31** [comment]
You can but it doesn't work well for realtime.
You can try maybe with a very small amount of hairs on a plane and moving it slowly.
You need to run blender simulation with bpy in the same time. For this you need to increase the timeline frame each frame with bpy.data.scenes["Scene"].frame_set((bpy.data.scenes["Scene"].frame_current + 1) % TotalSimulationFrames)
I'll do a quick try but imo it won't work well

**Comment by youle31** [comment]
Actually it has ther same behaviour than in the viewport when you press play in the timeline and when you grab the cube with G. The hairs don't follow the cube in realtime. When the cube stops to move, the hair simulation is updated

**Comment by youle31** [comment]
playing baked actions works a bit better: https://drive.google.com/file/d/1kmwBwbMrF2nE_UnCMnTczcVg09HmfKMt/view?usp=sharing

**Comment by BluePrintRandom** [comment]
Yeah, hair Sim and particle Sim both need re-done to be true real time.

I think Lukas was working on particles at least.

**Comment by rt974** [comment]
cool, thanks for the fast answer.
going to take a look.

**Comment by youle31** [comment]
I close this to have the bug tracker a bit cleaner
