### ISSUE TITLE
Standalone player doesn't work ?

### ISSUE THREAD

**Issue by RomStef** [UPBGE/upbge#1129]
When i launch StandAlone player it crash and i don't know why.
I have noticed that if i disable all logic briks it start. when i reconnect the logic nodes ,the blenderplayer crash

UPBGE lastest release

[crash.zip](https://github.com/UPBGE/upbge/files/4221776/crash.zip)

Win32 Error# (0): Operazione completata.
found bundled python: C:\myprograms\UPBGE_030\Release\2.83\python
Exception in module register(): C:\myprograms\UPBGE_030\Release\2.83\scripts\addons\cycles\__init__.py
Traceback (most recent call last):
  File "C:\myprograms\UPBGE_030\Release\2.83\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\myprograms\UPBGE_030\Release\2.83\scripts\addons\cycles\__init__.py", line 124, in register
    from . import properties
  File "C:\myprograms\UPBGE_030\Release\2.83\scripts\addons\cycles\properties.py", line 34, in <module>
    import _cycles
ModuleNotFoundError: No module named '_cycles'
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: GeForce GTX 1050 Ti/PCIe/SSE2
GL_VERSION: 4.5.0 NVIDIA 436.02
GL_SHADING_LANGUAGE_VERSION: 4.50 NVIDIA
Supported Extensions...
 GL_ARB_shader_objects supported?       yes.
 GL_ARB_geometry_shader4 supported?     yes.
 GL_ARB_vertex_shader supported?        yes.
 ----------Details----------
  Max uniform components.4096
  Max varying floats.124
  Max vertex texture units.32
  Max vertex attribs.16
  Max combined texture units.192

 GL_ARB_fragment_shader supported?      yes.
 ----------Details----------
  Max uniform components.4096

 GL_ARB_texture_cube_map supported?     yes.
 ----------Details----------
  Max cubemap size.32768

 GL_ARB_multitexture supported?         yes.
 ----------Details----------
  Max texture units available.  4

 GL_ARB_texture_env_combine supported?  yes.
 GL_ARB_draw_instanced supported?  yes.

**Comment by youle31** [comment]
Fixed in https://github.com/UPBGE/upbge/commit/9ddc646de06030067cf0291f8488a3da79fdc586

**Comment by youle31** [comment]
thanks for report

**Comment by RomStef** [comment]
Glad to help , thanks to you ;)
