### ISSUE TITLE
animated textures

### ISSUE THREAD

**Issue by Frankjore** [UPBGE/upbge#1130]
I have continued to explore the use in UPBGE of animated textures and I have encountered the following problem. In a project where I use the texture shift to place the appropriate frame, and in program mode it works but once exported to .exe the texture disappears.

![program-exe](https://user-images.githubusercontent.com/40981362/75100531-0f35d980-55cf-11ea-9369-97c56cf25ea9.jpg)
![runtime-exe](https://user-images.githubusercontent.com/40981362/75100532-0fce7000-55cf-11ea-8c82-b1dee28910ad.jpg)

[untitledexpl.zip](https://github.com/UPBGE/upbge/files/4240311/untitledexpl.zip)
Export to runtime and execute, the result is not as expected.

**Comment by youle31** [comment]
It seems the textures are not correctly packed into the .blend file.
You can try:
File > External Data > automatically pack into .blend.
Then save your file.
Then export again as runtime

**Comment by Frankjore** [comment]
[untitledexpl.zip](https://github.com/UPBGE/upbge/files/4240680/untitledexpl.zip)
