### ISSUE TITLE
Scripting game using c++ instead of python

### ISSUE THREAD

**Issue by PROGRAMMINGBOI** [UPBGE/upbge#1142]
I like UPBGE and its a revamp of BGE and the best part is that it is integrated into blender. But it is better to use c++ rather than python because c++ is way faster than python.

**Comment by BluePrintRandom** [comment]
check the logic node addon - maybe you can make something that does similar and writes C++ ?

**Comment by youle31** [comment]
We can't use c++ with upbge then i'd recommend you to try another engine which supports c++.
(bge is written is c++, but the scripting is just in python)

**Comment by BluePrintRandom** [comment]
we can compile libs and then use them - I saw SDFGEOFF did this for a BGMC.

**Comment by WisdomTheWizard** [comment]
is it possible to write the gamelogic in c++ in an IDE and then use the code via the python C-API (Python.h)?
