### ISSUE TITLE
Game actuator's restart game function  dosen't work as expect. (1. and 2. (ledi.zip file))

### ISSUE THREAD

**Issue by eleven-monkey** [UPBGE/upbge#1143]
- 1.I added the blend file,below.I have setup a text entry in second scene.you can swith to it and switch back with space key .after you swith to second scene ,you can input text there.but in upbge,after you restart game with Game actuator,you can't input the text entry any more.And the same setup in blender 2.79 works flawlessly.
[blend file setup with ubge 3.0 alpha](https://github.com/UPBGE/upbge/files/4322115/text_input.zip)
[blend file with same setup using blender 2.79](https://github.com/UPBGE/upbge/files/4322106/text_input2.7.zip)

- 2 I put a character in the scene .you can rotate it with left and right arrow key,and restart the game with R key.After restart the game ,the texture coordinate seems to freeze ,didn't move along the character .
![](https://s1.ax1x.com/2020/03/12/8ZF4ld.png)
normal character 
![](https://s1.ax1x.com/2020/03/12/8ZkikT.png)
after restart game with Game actuator ,texture didn't rotate with character .
The texture is procedure texture made with node tree.
the blend file of this character:
[ledi.zip](https://github.com/UPBGE/upbge/files/4322159/ledi.zip)

- 3 by the way ,In blender 2.7 I can cut the link between logic blocks with ctrl+LMB.but I can't do this in upbge 0.3 alpha ,hope this convenient method can be restored in future versions.

**Comment by youle31** [comment]
About 1., ALL the scenes, .blend files have to be saved while we are in camera view in upbge 0.3 alpha, because now, we are using blender camera and this has a different behaviour if you are in camera view (for developers: if rv3d == CAM_OB) or not. (The second scene has to have a camera)

I didn't look at the others for now.

**Comment by youle31** [comment]
The 2. is a valid Bug related to restart scene pipeline I guess. There is also a freeze in blenderplayer, then restart scenes, load .blends would need work and tests both in embedded and blenderplayer.

About the .3 the shortcut has been restored recently (in lasts upbge versions). It is ctrl + right click.

**Comment by eleven-monkey** [comment]
> About 1., ALL the scenes, .blend files have to be saved while we are in camera view in upbge 0.3 alpha, because now, we are using blender camera and this has a different behaviour if you are in camera view (for developers: if rv3d->persp == CAM_OB) or not. (The second scene has to have a camera)
> 
> I didn't look at the others for now.

thanks for reply，for 1st issue ,I add a camera in second scene .but the issue remains.
[text_input.zip](https://github.com/UPBGE/upbge/files/4322229/text_input.zip)

**Comment by youle31** [comment]
The .blends have to be saved in camera view

**Comment by youle31** [comment]
ok the 1. has also an issue

**Comment by eleven-monkey** [comment]
> The 2. is a valid Bug related to restart scene pipeline I guess. There is also a freeze in blenderplayer, then restart scenes, load .blends would need work and tests both in embedded and blenderplayer.
> 
> About the .3 the shortcut has been restored recently (in lasts upbge versions). It is ctrl + right click.

just tried ctrl+RMB to cut links,feel great .It's a good idea to unify this operation with node editor .

**Comment by youle31** [comment]
Note: If we call WM_redraw_windows(C) in InitBlenderContextVariables() for example, this is fixing the bugs in embedded.
If we really don't care to understand why, we can do like that...

**Comment by youle31** [comment]
The test files are great, thanks for the report. I'm working on it. I think it's fixed in restart_hacks branch but we'd need a bit time to test/see if there are better solutions...
About the shortcuts, maybe we can add a second keymap to imitate node editor, we'll see that.

**Comment by youle31** [comment]
Ah ok, i misread your last comment: "it's a good idea to unify links cut op with node editor". Actually, idk why but it was already these shortcuts I think in logic ops. Maybe they modified the shortcuts before removing the bge from 2.8... idk.
Then as it is not a request, I think 1, 2, 3 are ok after this commit: https://github.com/UPBGE/upbge/commit/08ec25eb955093998eaa90591fa8ea3d070e73a5
which is a temporary solution to try to fix your files both in embedded and in blenderplayer.

There's a remaining issue when we restart a scene when we try to use bpy, but I close this report as the mentionned issue seems solved.

Thanks for report and simple test files.
