### ISSUE TITLE
Need Help with overlay collection

### ISSUE THREAD

**Issue by RomStef** [UPBGE/upbge#1144]
Hi guys , 

I'm trying to create a player controller for rts game type.
I want to create an interface with custom cursor in an ortographic view but the game camera must be in perspective view.
I have made this kind of stuff in vanilla bge with overlay scene. I'm try to reproduce it with the overlay collection but it doesn't work.

How can i achieve the same resoult with th overlay collection ?

this is an example file :
[rts_controller.zip](https://github.com/UPBGE/upbge/files/4329672/rts_controller.zip)

thanks

**Comment by RomStef** [comment]
i have found a workaround.
This is the resoult. it's the old method with the mouse over sensors on an invisible plane.

https://youtu.be/4JVr4crGLXI

**Comment by youle31** [comment]
Cool, then if you found a workaround, i close this. (Now, really, for rendering, everything is done with blender code, we even use blender code to set the camera settings...)

About resources/workarounds/help wanted/requests, it could be better to find another place than issues section in this github.

Users could organize that and try to centralize all resources as your world nodetree setup somewhere.

I'd prefer personally to try to keep the tracker only for bug reports only
