### ISSUE TITLE
Logic Tree Editor - Add Object Node

### ISSUE THREAD

**Issue by ArkadiuszWernicki2000** [UPBGE/upbge#1145]
I was trying to add an object with this node, but despite the attempts, I couldn't do that.

**Comment by lordloki** [comment]
Fo the logic node addon bugs, please report them in its own repository.
https://github.com/IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes

**Comment by ArkadiuszWernicki2000** [comment]
Thanks! 😃

**Comment by BluePrintRandom** [comment]
Is the object hidden?
