### ISSUE TITLE
in the latest version alpha 3.0 when i delete something it crash

### ISSUE THREAD

**Issue by devilspringtrap** [UPBGE/upbge#1146]

**Comment by youle31** [comment]
I can't reproduce the bug in several of my test files. Without more infos provided, the report will be closed in 1 day. Thanks for comprehension, we want to keep the tracker clean

**Comment by devilspringtrap** [comment]
> I can't reproduce the bug in several of my test files. Without more infos provided, the report will be closed in 1 day. Thanks for comprehension, we want to keep the tracker clean

WHAT I AM NOT FREAKING TRACKER LOL

**Comment by youle31** [comment]
The bug tracker. I'll close that right now.
If you want to report a bug, please follow this guide: https://github.com/UPBGE/upbge/wiki/Report-a-bug-guide

**Comment by LP-ita** [comment]
I had the same problem, in my case caused by an incompatibility with the "logic nodes" add-on...
