### ISSUE TITLE
Restart physics values to default,

### ISSUE THREAD

**Issue by Hichlon** [UPBGE/upbge#1148]
After quit game, physics variables are restarted in soft body physics type.

**Comment by youle31** [comment]
please follow this guide to report an issue: https://github.com/UPBGE/upbge/wiki/Report-a-bug-guide

if it concerns upbge based on blender 2.7, the development is stopped, but you can still make your report in the case someone wants to work on it.

**Comment by BluePrintRandom** [comment]
I think it's 'undo at exit'

something is not marking the values to stay when undo happens,

I noted saving it works

**Comment by youle31** [comment]
I need a test file, precise steps to reproduce the issue, images to show exactly what is the issue. Then no need to comment until the bug report is correctly filled following the guide. Else i'll close that in 24 hours.

**Comment by Hichlon** [comment]
Winwows7, 8GB, GeForce GTX 1060 6GB.

UPBGE 0.3 Alpha Date: 2020-03-13 00:17 Hash: 07f5da191f0c
Test file: default cube with soft body physics with changed general
attributes.

When you quit played game on Embedded Start those attributes are restarted
to default.
It`s work fine on "Standalone Start"

pon., 16 mar 2020 o 06:01 youle31 <notifications@github.com> napisał(a):

**Comment by youle31** [comment]
But... Soft bodies are not supported with upbge 0.3. Only the interface remains, the the meshes can't be deformed. You can do softbody simulations with bpy. Else, I don't know if you can play baked blender softbody/clothes physics simulations in the current blender code.

You can deform meshes using modifiers and bpy API (I guess for example that a wave modifier can fake a moving flag...)

I'll add to my todo list to remove/comment the softbodies UI here: https://github.com/UPBGE/upbge/issues/1136

I close this report as there's not any work planned to restore deformers code (incompatible with blender code).
