### ISSUE TITLE
0.3 Alpha Component args not working

### ISSUE THREAD

**Issue by xphlawlessx** [UPBGE/upbge#1153]
I have an enemy component, with a moveSpeed arg.
If i update the value in the script speed changes , but no change if updated in the "logic editor" "component tab"

**Comment by nestanqueiro** [comment]
can you show some code... maybe a typo? is that the only argument you are using? do others work?

**Comment by youle31** [comment]
I close this as there is no answer. The bug reports have to follow this guide: https://github.com/UPBGE/upbge/wiki/Report-a-bug-guide
