### ISSUE TITLE
game actuator restart game function seems still have some problems.

### ISSUE THREAD

**Issue by eleven-monkey** [UPBGE/upbge#1154]
1.In the blend file below,I use edit object actuator 's add object to make bullet,you can shoot down the wall.then press F1 to restart.but after restart,the bullet became invisible ,but it is there,you still can shoot down the wall although the bullet didn't show up.after restart the game then exit to blender,if you select an object ,it has a high probability blender will crash.this is the situation in embedded player.The standalone player seems works well on this file.I include the test file below :
[fps-test.zip](https://github.com/UPBGE/upbge/files/4362338/fps-test.zip)

2.I made a catapultor game for my kid.you can press space key to  throw a ball into a wall and smash it.In order to encourage my kid to do some math.I made a second scene ,press esc key can enter it .it shows some simple math question ,if the kid give the right answers and press numpad enter key ,then activate the game actuator to restart game.In embedded player,the file works well sometimes,but crashed when restart in most time,and leave a meesage  says:
Blender Game Engine Finished
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x000007FEF4DE7D99
Module  : C:\upbge\Release\tbbmalloc.dll
start this file with standalone player, it crashed every time when restart.
I don't know is that something I did in wrong way or there are bugs,maybe you can helpme figure out.Thanks,I include the blend file below . 
[catapultor-wall.zip](https://github.com/UPBGE/upbge/files/4362343/catapultor-wall.zip)

**Comment by youle31** [comment]
yes... we need real coders to fix that.

**Comment by youle31** [comment]
I have maybe an API which can be used: WM_window_set_active_scene(blenderdata, C, CTX_wm_window(C), scene); (It causes issues with undo at exit system for now but this is a clue.
Note: It could maybe used for blenderplayer to avoid to spawn a new window

**Comment by eleven-monkey** [comment]
well，I'm not a real coder,hope this get fixed soon.

**Comment by youle31** [comment]
For blenderplayer, it's ok for me, but i'd need to work on embedded, no idea how long this will take, neither if i'll find a solution.

**Comment by eleven-monkey** [comment]
I test my blend file on build of 3.27.The texture coordinate freezing issue after restart come back.
In embedded I can't input text after game restart again.

**Comment by BluePrintRandom** [comment]
@eleven-monkey it make take a while but youle understands your issues and is likely thinking about them now - try not to put too much pressure on him,
he does this for free when he feels like it.

**Comment by youle31** [comment]
I know, this is because of 2 lines I added in BL_KetsjiEmbedStart.
For now, you can use only blenderplayer.

**Comment by eleven-monkey** [comment]
> @eleven-monkey it make take a while but youle understands your issues and is likely thinking about them now - try not to put too much pressure on him,
> he does this for free when he feels like it.

I didn't mean to put pressure on developers,they did amazing work so far.since I am not a real coder, I just offer some help for testing here.
 by the way ,on the web site,It says ,a experiment export to Android is on the way.when will we see that ?

**Comment by youle31** [comment]
I guess it refers to an old work of Dalai Felinto in blender 2.63.
Lordloki said he might give a new try to that, but this is not for now (it would need blender to support Vulkan first and it's not going to happen soon). Furthermore, I guess there are very few android devices which could run eevee because blender 2.8 requires a good computer, especially if you want to do realtime stuffs.

**Comment by undearstand** [comment]
@eleven-monkey
hi, after checking your files
I was wondering if double byte characters were a reason to make UPBGE player crash
so I removed all Chinese content in text objects of your catapult game
and then this file worked well in the standalone player on my PC (UPBGE version march 30)
but in the embeded player, it couldn't show the math question after the first time restarting
and crashed sometimes while quitting game

hope my experiment can help :)

**Comment by youle31** [comment]
In blenderplayer, all is ok in the 4 files eleven-monkey submitted.
Embedded player is not fixed yet. There are some functions in the code which makes embedded player work better, but there are still weird things which are happening.
This might take a long time to be fixed. Use blenderplayer if you want to use game actuator.

**Comment by eleven-monkey** [comment]
> @eleven-monkey
> hi, after checking your files
> I was wondering if double byte characters were a reason to make UPBGE player crash
> so I removed all Chinese content in text objects of your catapult game
> and then this file worked well in the standalone player on my PC (UPBGE version March 30)
> but in the embedded player, it couldn't show the math question after the first time restarting
> and crashed sometimes while quitting game
> 
> hope my experiment can help :)
yes ,after,convert text object to mesh,my file works fine in standalone player too.
thank you for your suggestion.
better doublebyte support will appreciated.but I know this is not so important at present .

**Comment by youle31** [comment]
Ortiz says: Hello Dear UPBGE folks!

Looks like that the Scene Restart actuator is not working in UPBGE Eeevee. I tested the file bellow in:

UPBGE-EEVEE-Linux64-2020-04-06
And
UPBGE-EEVEE-Linux64-2020-04-14

And it's not restarting the scene.

Download .blend file for test here:
https://drive.google.com/file/d/12x5hNWBPcjmE2d-g2R-pzfpuvdxVIv0s/view?usp=sharing

I wish you all the best,

Greetings,

Ortiz

**Comment by youle31** [comment]
Game restart actuator bugs in embedded should be fixed now: https://github.com/UPBGE/upbge/commit/3264dc7633b880827ecbfb26d879c964507672e5 (I forgot to thanks lordloki for tests and code review)

For Double bytes characters issues, I don't really know, but I don't think it is a bge specific issue. Maybe there are topics on the net which could help to solve python + double bytes characters issues if double bytes characters are correctly displayed in the viewport.

I close this report for now with the hope restart actuator will work better for you in the next builds
