### ISSUE TITLE
can't show double byte characters with text objects correctly

### ISSUE THREAD

**Issue by undearstand** [UPBGE/upbge#1156]
https://imgur.com/iUBnyWr
↑ I created a text object to show an imported Chinese string
but Upbge 0.3 alpha couldn't show it correctly while running
and became easy to crash.
I tried again with some Japanese characters, and got similar result
so I guess this issue is due to double byte characters

https://imgur.com/9rQtk4S
↑ btw, I also turned some options on like what I do in BGE 2.7x
it still didn't work well

**Comment by BluePrintRandom** [comment]
do these characters work in blender 2.83 ?

**Comment by undearstand** [comment]
thanks for answering :)
I tried the latest Blender 2.83 alpha (March 23)
and couldn't even input any Chinese in the edit mode of text objects 
(2.79b neither)

in my opinion, as a modeling tool
text objects don't support double byte characters is not actually a serious issue
because we can use other softwares to help our work
but as a game engine 
it might be an obstacle to develop something in certain languages

**Comment by eleven-monkey** [comment]
you should set a font that support Chinese first.
if you can't input Chinese directly ,you could type it in text editor ,then copy and paste into blender.
![Image 211](https://user-images.githubusercontent.com/62041627/77866962-c75a4000-7267-11ea-93be-59b89d1e888d.jpg)

**Comment by undearstand** [comment]
wow, thanks for answering :)
I tried your way and it worked
but when I want to show Chinese with python strings 
there are still some problems like this ↓

![addoil](https://user-images.githubusercontent.com/52462452/77873571-f202c380-727c-11ea-9a97-ecdac23f8e29.png)

sorry if I look picky
I just think about how to show dialogue with script :'(

**Comment by lordloki** [comment]
I think font objects are not well prepared to work with double byte characters ( and I don't know when Blender will put more work on this).

Another solution is to use blf library. I just tested it and it works:
![image](https://user-images.githubusercontent.com/1015605/79507620-5624d600-8038-11ea-95c2-da8ef94de8dc.png)

I attach a example file. 
[post_draw-2.8.zip](https://github.com/UPBGE/upbge/files/4489776/post_draw-2.8.zip)

**Comment by undearstand** [comment]
thanks for answering
this solution is really useful to me :)

**Comment by lordloki** [comment]
Thanks for your feedback. I close the bug as the solution depends from BF-Blender. I will check it in 6 months again. Thanks
