### ISSUE TITLE
Collection Instance behavior

### ISSUE THREAD

**Issue by IzaZed** [UPBGE/upbge#1158]
This is probably more of a feature request, because it is after all doable by different means

But I wanted to ask if it was an option to recover the old Group Instance behavior, which has the advantage that Instances can act independently from one another.

I believe @BluePrintRandom  mentioned that is was one line in source to switch (current behavior of mirroring all data from the instanced collection) to the old one where all objects are spawned in at game start

Would maybe be kind of a future feature, but it might be useful to have the behavior selectable when an object instances a collection in the instancing menu, but that's luxury then

**Comment by lordloki** [comment]
I will check it

**Comment by lordloki** [comment]
Could you attach a little example or video with the old behaviour?
I didn't see differences and i don't know if i'm doing correctly

**Comment by BluePrintRandom** [comment]
Current behavior in 2.8 is a a standing empty with A composite mesh of all
group members alll stuck together, no logic.,no physics per item.


Old behavior spawned in all group members + logic etc.

**Comment by lordloki** [comment]
I just uploaded a Test_spawn.7z build in MEGA folder. Could you check if it is the behaviour expected?
There is a check under collection panel in object tab (for original object).
![image](https://user-images.githubusercontent.com/1015605/78507113-73c38700-777e-11ea-919e-44c4af84329b.png)

**Comment by BluePrintRandom** [comment]
Nice work Loki !

**Comment by IzaZed** [comment]
It should be the right behavior, I'll play around with it today

It seems that copy is added too. though, so that the instanced object is spawned once as a copy and once as an actual group of entities

Test:

[InstanceTest.zip](https://github.com/UPBGE/upbge/files/4438091/InstanceTest.zip)

**Comment by lordloki** [comment]
It is already pushed in master and there is new build available

**Comment by IzaZed** [comment]
I know, the file is made with most recent build
I'm having the mentioned issue, though

**Comment by BluePrintRandom** [comment]
add

delay 1------and--------end object - in the instance

**Comment by lordloki** [comment]
I commit a fix. Could you check the new build? I'm not totally sure about it.
[InstanceTest2.zip](https://github.com/UPBGE/upbge/files/4444576/InstanceTest2.zip)

**Comment by IzaZed** [comment]
Yup, I think it's working now :) All the objects are spawned when the box is checked, and as far as I can tell they are addressable individually, I'll test my stuff further, but so far everything's good!

Guess this can be closed now :) kudos!
