### ISSUE TITLE
Logic Editor UI Polishing

### ISSUE THREAD

**Issue by Shohrukh1999** [UPBGE/upbge#1160]
Hello! I would like to share some ideas about Logic Editor UI.
![Logic Bricks UI Polishing](https://user-images.githubusercontent.com/46423713/77923971-91937680-72bc-11ea-98ef-fde4c0de6f1c.png)

1. Make Add Sensor and its components, Add Controller and its components, Add Actuator and its components always on top, like top bar. This will make it easier to add new Logic Brick, when there will be a lot of them. You no longer need to move up to add new Logic Brick (white line).
2. I never understood the meaning of the empty spaces in these Logic Bricks (pink arrows).
3. Make the window automatically scale to the size of the window (as in the picture).

I hope these ideas make using Logic Bricks more convenient.

**Comment by lordloki** [comment]
Thanks for the request. Closing the report but keep the feature request open to check later.
