### ISSUE TITLE
Crash of blenderplayer: start with python script, crashed when exit engine

### ISSUE THREAD

**Issue by Innericy** [UPBGE/upbge#1165]
The python script is:
`    scene = bpy.data.scenes[0] `
`    scene.frame_start = 1`
`    scene.frame_end = 10`
`    bpy.ops.render.render(animation=True, write_still = False)`

I run my test like `blenderplayer.exe -p mypython.py test.blend`.
I can get the render images.
It will crash at 
![image](https://user-images.githubusercontent.com/17307275/78123359-a1d45e80-7440-11ea-9e59-1c820b8ab96c.png)
![image](https://user-images.githubusercontent.com/17307275/78123458-c3cde100-7440-11ea-9911-23f4da9c1769.png)

**Comment by youle31** [comment]
lol, interesting usage of blenderplayer... Well, I guess the same can be done with blender.exe.
I don't really know the blenderplayer -p script pipeline but if one day i'm motivated, i'll try to have a look.

**Comment by youle31** [comment]
Fixed here: https://github.com/UPBGE/upbge/commit/7760fbb9f0b35a2519e49f2731c27b5db67eb03e
