### ISSUE TITLE
bge.logic.addScene doesn't exist...

### ISSUE THREAD

**Issue by kgeogeo** [UPBGE/upbge#1167]
Hi,
sorry maybe it's not the right place to ask this but when I try to add a Scene with bge.logic.addScene
I've this error 
AttributeError: module 'GameLogic' has no attribute 'addScene'
It was deleted?
How do we do now to add a scene?
Upbge 3.0
Thanks and great great job done by the way.

**Comment by BluePrintRandom** [comment]
now we use the start game actuator and the collection actuator @kgeogeo

**Comment by BluePrintRandom** [comment]
also - we can now use collections in the collection branch to spawn a whole collection of objects

they are spawned as a group instance.
in the instance menu you check  'instance spawn' 
![image](https://user-images.githubusercontent.com/7190873/78511970-9ee5b080-7755-11ea-9abf-46966cdc0037.png)

**Comment by BluePrintRandom** [comment]
https://mega.nz/#F!t9EEFSaS!JPiOPSInCZyU-SW_-rhEOQ
build available here 

[collection_example.zip](https://github.com/UPBGE/upbge/files/4435222/collection_example.zip)
here is a example of spawning some objects using collection instance

**Comment by kgeogeo** [comment]
thanks a lot I we take a look at this solution.

**Comment by kgeogeo** [comment]
Hi, sorry to insist with this but I don't manage to do it.
I would like to append a scene in underlay to make render to texture.
Pretty easy to do with old BGE but I can't find the way to do it with UPBGE.
Thanks in advance.
ps: If you have a blend file to do it, I take ;)))
Thanks

**Comment by lordloki** [comment]
Here you have an example: 
[RenderToTexture.zip](https://github.com/UPBGE/upbge/files/4452817/ImageRender.zip)

**Comment by kgeogeo** [comment]
Thanks for that, it's really helpful, but in my case I look for render from a camera from another scene... 
I've done a full program that use it and now I would like to try with the Eevee power but I do not manage to load another scene...
Sorry to contact you this way, Can I contact you on another channel?

**Comment by BluePrintRandom** [comment]
the concept of scenes is gone now - instead we have collections.

I am not sure if 'background' collection is a option yet,
I think you can render to texture on a plane and slap it in the background
of the camera though

**Comment by lordloki** [comment]
Sorry, it is not possible to use overlay scenes now. 
Instead of it you have to use overlay collections.

**Comment by kgeogeo** [comment]
Ok thanks, I will try to change the project to do this.
Thanks, keep the good jod ;))
