### ISSUE TITLE
UPBGE eevee doesnt revert rigid body location

### ISSUE THREAD

**Issue by mushroomeo** [UPBGE/upbge#1180]
if i run BGE the rigid body doesnt revert location where they start in latest UPBGE eevee branch.

**Comment by lordloki** [comment]
Could you attach a little blend showing the bug? Thanks

**Comment by mushroomeo** [comment]
yes sure, i not sure how i could show that except video but here it is. just run bge and then see that the rigid objects stays on ground after pressing ESC to close BGE. its like happened apply visual transform.

[rigid body problem.zip](https://github.com/UPBGE/upbge/files/4482331/rigid.body.problem.zip)

**Comment by BluePrintRandom** [comment]
are you using upbge physics or blender rigid body si?

**Comment by lordloki** [comment]
surely, you have "undo at exit" unchecked.
You have to activate it.
![image](https://user-images.githubusercontent.com/1015605/79365074-71191c80-7f4a-11ea-865e-f4939b823cdb.png)

**Comment by mushroomeo** [comment]
yes i using UPBGE rigid body settings and not blenders.

oh wow. i had it checked but now i unchecked and then checked again and now it workds fine.  looks like the. looks like there is still some issue with the preferences / startup settings saved...
but thanks very much that fixed it.

**Comment by mushroomeo** [comment]
oh no its not working correctly, sometimes it does revert it and sometimes not very strange. the objects then stays on ground and the next time i run BGE and close again then its reverted...

**Comment by mushroomeo** [comment]
okay it looks like after i did in FIle > load factory settings then it doesnt revert it anymore , not 1 time did . so looks liek this time i need do complete reseting of blender options again after load factory settings T_T

but so it fixed it .thanks much guys

**Comment by youle31** [comment]
Alright, I close that then, thanks lordloki
