### ISSUE TITLE
Collection Instances spawn original Colliders

### ISSUE THREAD

**Issue by IzaZed** [UPBGE/upbge#1182]
There seems to be an issue with spawned instances, they are spawning the colliders at the original positions as well as relative to the instance spawner

![colliderissue](https://user-images.githubusercontent.com/32898133/79462991-8cdafc00-7ff8-11ea-965b-4fa1c08f33bf.PNG)

**Comment by lordloki** [comment]
I only have in the original position if I don't hide original object:
Ex: Cube at center original and both side instance
![image](https://user-images.githubusercontent.com/1015605/79481394-b8b5ac00-800f-11ea-84ba-7d1c6f27548f.png)
Original cube without hide:
![image](https://user-images.githubusercontent.com/1015605/79481451-d08d3000-800f-11ea-9bd3-32c273a526cc.png)
Original cube hide:
![image](https://user-images.githubusercontent.com/1015605/79481508-e3a00000-800f-11ea-9961-069b38be9eeb.png)

**Comment by IzaZed** [comment]
Confirmed, my bad :)
