### ISSUE TITLE
Collision sensor not working Upbge 0.3

### ISSUE THREAD

**Issue by corryVanr** [UPBGE/upbge#1184]
Hi guys
I'm currently having issues with the collision sensor on upbge-eevee-17-04-20
If i load a .blend file where I've recently made collision sensors on a previous build all is working 100% 
But when making a new one from scratch in the engine nothing happens regardles if set to material or property

Any advice will be greatly appreciated

**Comment by lordloki** [comment]
For me it is working
![image](https://user-images.githubusercontent.com/1015605/79590816-e6febe80-80d7-11ea-9203-e3f9cd1c5a00.png)
I attach the example created from scratch in upbge-eevee-17-04-20 [collision.zip](https://github.com/UPBGE/upbge/files/4494023/collision.zip)

**Comment by corryVanr** [comment]
Ok thanks I'll try again as i sat the collectable obj physics to static with collision bounds
And the player to chareter with collision bounds

**Comment by corryVanr** [comment]
Thank You for the file and quick respoce
Will do it this way

**Comment by lordloki** [comment]
Thanks for reporting. Closing now
