### ISSUE TITLE
Set Camera only applies target camera attributes

### ISSUE THREAD

**Issue by IzaZed** [UPBGE/upbge#1185]
It seems that when setting an active camera, the current camera simply has the attributes (FOV etc) of the target camera applied, but not the position

Happens via both logic bricks and python

**Comment by IzaZed** [comment]
Apparently this only happens when not in a camera view when starting the game, so switching from one camera to another is not a problem, just switching from free view

**Comment by youle31** [comment]
Yes, this is a difference compared to bge 2.7. We are using blender camera and the view matrix can't be correctly set by blender code if we are not in camera view (rv3d != RV3D_CAMOB). Then it is a limitation but not a bug. We have to start .blends in camera view, else SetCamera actuator won't work properly.
