### ISSUE TITLE
Instanced Lights use the same light data

### ISSUE THREAD

**Issue by IzaZed** [UPBGE/upbge#1186]
It appears that lights added by spawning instances cannot be given color or energy individually, but instead lights in multiple spawned collections use the same data.

Example File:
[LightInstanceTest.zip](https://github.com/UPBGE/upbge/files/4514333/LightInstanceTest.zip)

The Lights in the file should be colored according to the parent position

**Comment by youle31** [comment]
All objects types are using the same method to make instances (In the bge code, ReplicateBlenderObject).
If you want to add a new light with new data, you can add a light with bpy then convert it as gameobject using bge.logic.getCurrentScene().convertBlenderObject(bpy.data.objects["LightAdded"]).

This is not an issue. It's a choice, You can workaround using bpy.

**Comment by IzaZed** [comment]
Alright, can you tell me how I can access the added light too? Because when I add lights with bpy, they are not listed in getCurrentScene().objects, so I can't access them

**Comment by IzaZed** [comment]
Nevermind, I think I got it
