### ISSUE TITLE
Double Click issue

### ISSUE THREAD

**Issue by Shohrukh1999** [UPBGE/upbge#1187]
Hello, UPBGE Developers! 
When I click on the left key above the ***Settings***, but automatically enter the ***Video*** settings. 
Or when you are in the ***Video*** settings, click on ***Back***, it is automatically pressed twice and resets you to the ***Main Menu***.
[Main Menu.zip](https://github.com/UPBGE/upbge/files/4516563/Main.Menu.zip)
How to fix it?

**Comment by lordloki** [comment]
The sensors send 2 pulses always (when pass the negative to positive and positive to negative) -> Check this http://mikepan.com/GameEngineBook/text/03-LogicBricks.html#Header

To only make one pulse, for example you have to active tap + invert
