### ISSUE TITLE
Volumetrics Toggle

### ISSUE THREAD

**Issue by IzaZed** [UPBGE/upbge#1188]
Feature Request
The recently implemented Volumetric frame-to-frame interpolation by @lordloki is incredibly great, to have that said
But in certain cases it causes some artifacts, especially then using a higher anisotropy value on the volumetric shader.

It would be nice to have a Toggle for the interpolation feature under the render settings

**Comment by youle31** [comment]
lordloki pushed a new commit about volumes to fix an artifacts, could you test again in the next builds in the next days? Thanks!

**Comment by lordloki** [comment]
A build with the fix was uploaded

**Comment by IzaZed** [comment]
The fix for flickering seems to work 👍  
The artifact that makes using anisotropy problematic (as far as my layman brain suggensts) comes from mixing in the previous calculations though

Here's a setup showing the effect, it should be noticable as soon as you move the camera around in the viewport:
[vol_anisotropy.zip](https://github.com/UPBGE/upbge/files/4533008/vol_anisotropy.zip)

**Comment by lordloki** [comment]
Great!. Thanks for reporting.
Closing now.

**Comment by IzaZed** [comment]
Did you have time to check the file? The Issue with anisotropy is still there :/

**Comment by lordloki** [comment]
Oh, i checked rotating the cube but not moving the camera. I see the trail now.
Surely we will have to do a check to change between both behaviours

**Comment by BluePrintRandom** [comment]
http://twvideo01.ubm-us.net/o1/vault/gdc2016/Presentations/Pedersen_LasseJonFuglsang_TemporalReprojectionAntiAliasing.pdf


here is a really good paper on the subject

**Comment by youle31** [comment]
Fixed in https://github.com/UPBGE/upbge/commit/008aa804be52e90d9fdd9883ee374674074a4c23

A note has been added in release notes:
https://github.com/UPBGE/upbge/wiki/Release-notes-version-0.3.0

Thanks to lordloki for original patch for volumes, and for review of this patch!
