### ISSUE TITLE
How to start the game in v0.3-alpha?

### ISSUE THREAD

**Issue by sunwin123** [UPBGE/upbge#1192]
Could anyone tell me ?

**Comment by BluePrintRandom** [comment]
in the fork UPBGE you startup blender and press P or click on standalone start in the render dialog of the property panel>

builds are available here -
https://upbge.org/

in blender.org blender the game engine is removed so Pressing p does not invoke the engine.

**Comment by sunwin123** [comment]
Got it, Thanks! @BluePrintRandom
