### ISSUE TITLE
Collection Instances has no collision (UPBGE 0.3)

### ISSUE THREAD

**Issue by edderkopen** [UPBGE/upbge#1197]
when i have instances of a collection the objects in that instance has no collision.

**Comment by youle31** [comment]
I close this task as it doesn't respect this guide: https://github.com/UPBGE/upbge/wiki/Report-a-bug-guide

**Comment by lordloki** [comment]
![image](https://user-images.githubusercontent.com/1015605/80537353-32e91780-89a4-11ea-93ef-1e14c876d550.png)
Check Instance spawn

**Comment by edderkopen** [comment]
thanks lordloki, that was very help full (i had to download the latest linux build to get it tho)
