### ISSUE TITLE
UPBGE 0.2.5 Stopping the actuator at low fps 

### ISSUE THREAD

**Issue by ValakD** [UPBGE/upbge#1201]
When the fps is low (30 - 25), the actuator mouse stops working

**Comment by lordloki** [comment]
I confirm it. I'm investigating it

**Comment by lordloki** [comment]
It seems that when there is low fps only one of two mouse actuator receives events

**Comment by lordloki** [comment]
I commited a fix for next 0.2.5a. Thanks for reporting
