### ISSUE TITLE
UPBGE 0.3 Custom shaders

### ISSUE THREAD

**Issue by voland62** [UPBGE/upbge#1205]
Hi. I tryed code from [docs](https://upbge-docs.readthedocs.io/en/latest/api/bge.types.KX_BlenderMaterial.html#kx-blendermaterial-exp-pyobjectplus)(seems like it is for older version of UPBGE), and this simple one, based on [some examples](https://github.com/UPBGE/upbge/blob/upbge0.3/doc/python_api/examples/bge.texture.2.py):
``` python
from bge import logic

vs = """
uniform mat4 ModelViewProjectionMatrix;
in vec3 pos;

void main(void)
{
   gl_Position =  ModelViewProjectionMatrix * vec4(pos, 1.0);
}
"""

fs ="""
void main(void)
{
   gl_FragColor = vec4(0.0, 0.0, 1.0, 1.0);// blue
}
"""

object = logic.getCurrentController().owner

for mesh in object.meshes:
    for material in mesh.materials:
        shader = material.getShader()
        if shader is not None:
            if not shader.isValid():
                # print("appShader")
                shader.setSource(vs, fs, True)
```

both with no success...
So what is the correct way of doing this in UPBGE 0.3?

Thaks.

**Comment by youle31** [comment]
This code has not been adapted to have it working in 0.3 (would be complex and would need to modify eevee's code).
The gpu module has some examples to do few things:
https://docs.blender.org/api/master/gpu.html?highlight=gpu#module-gpu

Some of these examples won't work directly in bge, you can sometimes adapt it to have it working like here:

https://pasteall.org/blend/c18e144cf3194a829ccdc7cce2851f56
