### ISSUE TITLE
Crash after exit if using logic nodes

### ISSUE THREAD

**Issue by mushroomeo** [UPBGE/upbge#1207]
recently i started getting crash after i press ESC to close BGE but only happens if i use logic nodes .
this does not happen if using logic bricks.

here the BGE file
[TEST BGE CRASH.zip](https://github.com/UPBGE/upbge/files/4605526/TEST.BGE.CRASH.zip)

**Comment by youle31** [comment]
You might need to use undo legacy.

In user preferences > interface, check developers extra
In "Experimental", check undo legacy

If it works, you can close this report

**Comment by IzaZed** [comment]
That occurs when using a node that has an object socket, something in the new undo system messed that up
I'm trying to fix it but I don't really know where to look

**Comment by youle31** [comment]
Many other issues (not only with logic nodes addon) occur with new undo and bge undo at exit option. For now (and maybe forever, we'll see), I just recommend to use the legacy undo.

**Comment by mushroomeo** [comment]
oh well. i enabled legacy undo and saved and restarted and its still crashing. loading factory settings does nothing too.

**Comment by mushroomeo** [comment]
just downloiaded latest version and no more crash if exit !! SO SUPER COOL thanks guys : ) : )
