### ISSUE TITLE
Impossible to build UPBGE due to Joystick source file errors

### ISSUE THREAD

**Issue by Polirecyliente** [UPBGE/upbge#1212]
Bug frequency: Always

Good day, I'm building UPBGE on an Ubuntu/Linux system, I've tried 3 times and started fresh again when it fails. The guide I'm following is this: https://github.com/UPBGE/upbge/wiki/Build-UPBGE-on-Linux

The consistent error is produced at the step of executing make -j4
I read the error log and it always fails when compiling the Joystick files, in particular DEV_Joystick.cpp, a header also gives errors, it's DEV_JoystickPrivate.h

Since I'm not interested in joysticks, I'm searching for a solution like executing ./install_deps.sh --skip-joystick, or something of that nature (I already searched in the install_deps.sh file and there is no way I can tell to disable joysticks in the build), I'm ok building UPBGE without joystick support, is there a way to achieve this?

Steps to reproduce the error
Following the guide at: https://github.com/UPBGE/upbge/wiki/Build-UPBGE-on-Linux
Execute the following:
1. git clone https://github.com/UPBGE/upbge.git
2. cd upbge
3. git submodule sync
4. git submodule update --init --recursive --remote
5. git submodule foreach git checkout master
6. git submodule foreach git pull --rebase origin master
7. git pull --rebase
8. git submodule update --recursive --remote  // I know this looks redundant but it's just to update the local repository
9. git submodule foreach git pull --rebase origin master
10. (
    cd build_files/build_environment
    ./install_deps.sh --skip-osl # skips open shading language error that I get
)
11. cd ..
12. mkdir build_linux
13. cd build_linux
14. cmake -DCMAKE_CXX_STANDARD=11 ~/dirs/UPBGE/upbge 
15. make -j4

NOTE: the folder ~/dirs/UPBGE/upbge is the folder where I have cloned the UPBGE repository.

The command make -j4 gets to around 75% completion and then a myriad of joystick related errors appear, the errors are of the kind "error: 'type1' does not name a type", and I'm no C++ expert but that sounds like there where missing headers or something similar, the Joystick types are not found. Just in case here I'm uploading the error log.
[Joystick_errors_building_UPBGE.txt](https://github.com/UPBGE/upbge/files/4672664/Joystick_errors_building_UPBGE.txt)

**Comment by lordloki** [comment]
you need libsdl2-dev

**Comment by Polirecyliente** [comment]
@lordloki issue solved! you were right, I installed libsdl2-dev and the make -j4 command completed to 100% .. can the issue be closed? I would only advice that a mention of this be made in the guide, or that the file ./install_deps.sh ensures that libsdl2-dev is installed

**Comment by youle31** [comment]
Hello,

The new blender wiki to build blender on ubuntu should normally work with upbge:

https://wiki.blender.org/wiki/Building_Blender/Linux/Ubuntu

instead of install_deps, you need to download directly precompiled libraries in a folder named lib using this:

svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/linux_centos7_x86_64

**Comment by lordloki** [comment]
I modified our docs to be more updated. Thanks for reporting

**Comment by Polirecyliente** [comment]
Thank you so much gentlemen, this was the first time I built UPBGE so smoothly, if I may, here I'm pasting the plain text I wrote with the steps that lead to the successful build, in case it helps anyone (I don't really suggest putting it in the docs because I can only guarantee that these steps work for a person who has built Blender in another dir, before building UPBGE)

"Main instructions at: https://github.com/UPBGE/upbge/wiki/Build-UPBGE-on-Linux

From the dir you want UPBGE execute:
git clone https://github.com/UPBGE/upbge.git
cd upbge
git submodule sync
git submodule update --init --recursive --remote
git submodule foreach git checkout master
git submodule foreach git pull --rebase origin master
cd ..

Next instructions at: https://wiki.blender.org/wiki/Building_Blender/Linux/Ubuntu

mkdir lib
cd lib
svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/linux_centos7_x86_64
cd ..

cd upbge
make update
make

the UPBGE executable will be build_linux/bin/blender"
