### ISSUE TITLE
UPBGE 0.3.0 - mesh material animation do not work with action actuator

### ISSUE THREAD

**Issue by RomStef** [UPBGE/upbge#1218]
Hi , 
I have made two simple animation to emulate a day night cycle , a world's material animation and a skydome's material animation both controlled with a frame property.

The world's material animation work well. the skyDome's material animation do not work.

here is the example.
[skydome.zip](https://github.com/UPBGE/upbge/files/4736028/skydome.zip)

**Comment by youle31** [comment]
I think the skydome action must be called from an action actuator on the skydome.

**Comment by youle31** [comment]
(It is the skydome object which has the skydome material, then the action can only be played from logic on the skydome)

**Comment by RomStef** [comment]
oh , it works! 
Thanks a lot.
