### ISSUE TITLE
UPBGE 0.3.0 - strange artifact with the build of 05/06/2020

### ISSUE THREAD

**Issue by RomStef** [UPBGE/upbge#1219]
sometimes appears when i start the blenderplayer

![image](https://user-images.githubusercontent.com/20901566/83947734-2d8bb200-a819-11ea-920f-01bd867fda44.png)

**Comment by youle31** [comment]
Just after 2.83 release, there was a complete eevee's materials refactor.

As we can't do something with more informations provided, I close this report. Maybe you can find a more stable version for you near the may 15th before eevee's materials refactor (the render code is done by blender developers)

**Comment by RomStef** [comment]
thanks
