### ISSUE TITLE
Animated textures (Spreadsheets) didn't work in recent build.

### ISSUE THREAD

**Issue by eleven-monkey** [UPBGE/upbge#1221]
I used upbge eevee 06-08build .The animated texture feature didn't work in this build.even the the file from release note will freeze on first frame.
[fire_sprite.zip](https://github.com/UPBGE/upbge/files/4200519/fire_sprite.zip)

**Comment by youle31** [comment]
Fixed in https://github.com/UPBGE/upbge/commit/e50e52b40de6b790fdd5f54411eda208fc2f83e4
