### ISSUE TITLE
Array object some time didn't show up in blenderplayer.

### ISSUE THREAD

**Issue by eleven-monkey** [UPBGE/upbge#1222]
In the file below I made some stairs with array modifier.you can use w,a,s,d key to navigate the character ,and space key to jump up.In blenderplayer,when you climb up some where the stairs disappear .It seems that when the origin object out of sight ,the whole array will disappear.I don't know weather this is a bug.simply apply the modifier can solve it .but in embedded mode ,this didn't happen ,you needn't to apply the array and everything works just perfectly .

[array-bug.zip](https://github.com/UPBGE/upbge/files/4756712/array-bug.zip)

**Comment by youle31** [comment]
Fixed here: https://github.com/UPBGE/upbge/commit/3a5fd64176a19e9cb03a2203ef552d304497e0c8

Thanks for report
