### ISSUE TITLE
Add dispose callback for components and game objects

### ISSUE THREAD

**Issue by mysticfall** [UPBGE/upbge#1225]
Currently, we can either use the constructor or `start()` callback to initialize a `KX_PythonComponent`, but it does not provide a method to be notified when the component is destroyed (e.g. a character dies, or loses a trait which is implemented as a component, and so on).

In certain cases, it may be required to perform clean up tasks before the game object to which such a component is attached gets disposed, like when it was monitoring outside events.

Other game engines like Godot or Unity provides a callback like `GameObject.dispose()` or `MonoBehaviour.OnDestroy()` to support such a use case.

So, it would be useful if UPBGE can also provide a similar callback in `KX_PythonComponent` and `KX_GameObject`.

**Comment by youle31** [comment]
@marechal-p  implemented callbacks at scene exit here: f62dca6f3c8028dc69fff5be439fcc5d90a87124
(Comment:
Would it be possible to call RunOnRemoveCallbacks from KX_Scene destructor?)

As upbge0.3 is based on an old version of upbge, these callbacks have not been restored yet.

We could restore these callbacks for KX_Scene and add callbacks for KX_PythonComponents in the destructor.

@marechal-p  @lordloki : Do you have comments or thoughts about that?

**Comment by lordloki** [comment]
Yes, i will go over all python components commits to recover them

**Comment by youle31** [comment]
I think python components callbacks did not exist, but we can implement it easily taking example on KX_Scene

**Comment by marechal-p** [comment]
@youle31 how would such a PythonComponent callback look like?

IMO it should be an optional method people should implement in their component, like `start` and `update`. Maybe call it `dispose` like in godot?

**Comment by mysticfall** [comment]
I think `dispose()` could be a reasonable choice for consistency, but I'm a bit concerned if it would cause confusion for new users like myself, since it appears to be a method one can invoke to destory the object in question.

For reference, Unity provides the same methods as UPBGE for `start()` and `update()`, however, it prefixes all other callbacks with `on`, while Godot adopts a similar approach with `_` as a prefix.

**Comment by youle31** [comment]
With the above code, it would give something like that:

![Capture](https://user-images.githubusercontent.com/10052509/85055184-776f8300-b19d-11ea-8072-18e916cc6037.PNG)

It's not good @marechal-p  ?

**Comment by youle31** [comment]
Ok after discussion with @marechal-p , i'll do differently and then i'll send a pull request when i'll be motivated

**Comment by youle31** [comment]
Requests doone here: 

https://github.com/UPBGE/upbge/commit/807857f3e0fa7c18c599587cbbba0681b894cc85

and there:

https://github.com/UPBGE/upbge/commit/dd3bd6e2a93bc5b5e6b287da099b9d619714a4d2

Thanks for comments and help about the design for KX_PythonComponent callback

**Comment by mysticfall** [comment]
That was fast! I really needed this feature. Thanks much. :)
