### ISSUE TITLE
Operators provided by addons don't appear in the operator search popup

### ISSUE THREAD

**Issue by mysticfall** [UPBGE/upbge#1231]
Some addons provide various operators(`bpy.types.Operator`) to extend Blender's functionalities, which can be often searched for and invoked from the operator search popup (`F3` or `spacebar`, depending on the keymap settings).

However, it seems that such operators don't show up in the popup window in UPBGE, while regular Blender doesn't exhibit such an issue.

It happens with several addons that I tested so far, and they seem to be working correctly under UPBGE, except for the above mentioned problem. For instance, if I change the script to add a button to the header which invokes the addon's function, it works as intended.

**Comment by youle31** [comment]
Is it an upbge specific issue? Did you test with last blender nightly build?

**Comment by mysticfall** [comment]
Sorry I only tried with regular Blender 2.83. I'll soon test it with 2.9 snapshot and update the issue.

**Comment by youle31** [comment]
I close this report waiting for more infos (but i don't think it can be a bug specific to upbge).
