### ISSUE TITLE
Attaching a remote debugger crashes UPBGE

### ISSUE THREAD

**Issue by mysticfall** [UPBGE/upbge#1232]
I tried to attach a remote debugger to my UPBGE project, but it seems that it always crashes after components are initialized.

For debugging, I used PyCharm (Professional edition, but PyDev provides a similar feature) and a slightly modified version of this addon:
https://github.com/sybrenstuvel/random-blender-addons/blob/master/remote_debugger.py

(I had to modify it to accomodate a change in PyCharm and to circumvent #1231. I will attach the modified script below.)

[remote_debugger.tar.gz](https://github.com/UPBGE/upbge/files/4808814/remote_debugger.tar.gz)

It seems that setting a breakpoint in the constructor(`_init_`) of a component works as expected:
![image](https://user-images.githubusercontent.com/2367032/85214908-80826f00-b3ac-11ea-8ebd-d49a54900cdb.png)

However, when I resume the process, it immediately crashes UPBGE. And if I don't add any breakpoint, it also crashes the platform.

It looks like the debugger makes UPBGE crash as soon as the game loop starts (a threading issue?).

For a complex project, it'd be nice to have an ability to use a debugger to inspect the running project instance. Most other game engines support a similar feature in one way or another, so I think it'd be worthwhile if we could make this work as well.

**Comment by youle31** [comment]
About this request, this would suppose we install pycharm, and an addon which was not originally made for bge.

I think the python debugging console is fine enough to track python errors. If it is not enough, we have the possibility to display game properties in realtime (Game Debug UI > debug properties). Else, we can also use realtime game python console to stop runtime and type some commands to debug something.

I'm not personally really interested to work on this as there are already existing ways to debug, and that i don't really want to have to install pycharm and another addon.

But i leave the request opened for a week in case someone reacts to this and says he is interested to work on it.

**Comment by mysticfall** [comment]
I understand how this feature may not interest many of our users, especially when considering the fact that not many of them are using UPBGE for creating large and complex projects just yet.

However, this feature is not specific to PyCharm as `pydevd_pycharm` module is just an improved version of `pydevd`, which is a standard debugging module used by other popular IDEs like PyDev, or VSCode. (The addon mentioned in the issue also supports PyDev, for instance.)

And even though Blender's Python dev environment provides many useful tools to debug a problem, I think the ability to stop the execution at any specific point (e.g. only when certain condition is met) and investigate values in that particular scope could be very useful for more complex projects.

I understand that if not many people have such a requirement, it would be unreasonable to urge them to work on this issue.

I just wish that it someone may turn up to investigate the issue and find that it's something easily fixable. As breakpoint work in constructors, it'd probably be fully functional if we manage to find the way to avoid the crash.

**Comment by youle31** [comment]
To find the way to avoid the crash, it would need to have a blender compilation environment installed. This is a bit complex to setup the first time...
The doc to compile blender is here: https://wiki.blender.org/wiki/Building_Blender
There are other documentations to setup development environment for some IDEs (qtcreator...)

**Comment by mysticfall** [comment]
I'm not sure if it is related, but when I built UPBGE against Python 3.8 with a few changes suggested in #1239, I found that engaging a breakpoint in `def start()` no longer crashes Blender.

It still crashes when the execution is paused due to an error, but in this case, I can at least have a chance to investigate the cause in the IDE, so now I'm happy with how UPBGE works in this regard.

**Comment by mysticfall** [comment]
Maybe we could close this too, since #1239 is merged now?

I'd like to see someone else's confirmation before that, but I suppose not too many of us would be interested in testing it.

**Comment by youle31** [comment]
@marechal-p : are you interested to test?

**Comment by youle31** [comment]
I close this issue since it seems fixed by @mysticfall  commit #1239
