### ISSUE TITLE
0.3.0 - Remove keyboard.events deprecation warning

### ISSUE THREAD

**Issue by IzaZed** [UPBGE/upbge#1234]
I don't know if this is supposed to be there, but I can't seem to find any documentation on a **keyboard.inputs** module, which leaves me using the events module and getting this warning.

I think it's the same in 0.2.5 though, I just work with 0.3+

**Comment by lordloki** [comment]
You can see it here: https://github.com/UPBGE/upbge/blob/master/doc/python_api/rst/bge.events.rst

Also you can see this old issue: https://github.com/UPBGE/upbge/issues/515

**Comment by IzaZed** [comment]
So the deprecation warning is intentional and not old bge legacy? Then I'll update the code

**Comment by lordloki** [comment]
Teorically, we set deprecation warning to warn that we will remove after 2 release. But in this case we are kept for more.
I think we should remove it for 0.3

**Comment by youle31** [comment]
As you recovered .activated, .active.... which are handy, feel free to remove the old events code if you want. As you want

**Comment by IzaZed** [comment]
Ah, that's really useful
Each event has .active, .activated and .released, that actually shrinks the code 👍

**Comment by IzaZed** [comment]
Updated the node addon to use keyboard.inputs
