### ISSUE TITLE
UpBge 0.2.5 sensor mouse [Motion] - bug

### ISSUE THREAD

**Issue by Collapse640** [UPBGE/upbge#1236]
UpBGE 0.2.5 - bug

mouse sensor (motion) turns off when low FPS

**Comment by lordloki** [comment]
The issue is in 0.2.5 or 0.2.5a?
There was a commit trying to solve this issue in 0.2.5a

**Comment by Collapse640** [comment]
> There was a commit trying to solve this issue in 0.2.5a

yes sorry version 0.2.5a

**Comment by lordloki** [comment]
I just tested in 0.2.5a and it worked well. Do you have any test blend file showing the issue??

**Comment by Collapse640** [comment]
> I just tested in 0.2.5a and it worked well. Do you have any test blend file showing the issue??


[test_mouse_0.2.5a_upbge.blend.zip](https://github.com/UPBGE/upbge/files/4846778/test_mouse_0.2.5a_upbge.blend.zip)

**Comment by lordloki** [comment]
Please, check this build: https://mega.nz/file/J1UVmS4R#YAoQsBPR0voN8Sl0Hwl6fV2rvDSlAX6rqNn4hIiEUQE

**Comment by lordloki** [comment]
It seems (as it was exposed in duplicated report #1243 ) this bug was fixed. If you think that is not fixed yet, please reopen this same issue again.

Thanks for reporting.
