### ISSUE TITLE
Build error due to missing submodule (blender-addons) commit reference

### ISSUE THREAD

**Issue by mysticfall** [UPBGE/upbge#1237]
I'm trying to build UPBGE from the source but the current master seems to be failing with the following message:
```
* release/scripts/addons bc1262f4...66a41e79:
  Warn: release/scripts/addons doesn't contain commit bc1262f4d61feeba235bb75046e65e0e8411241f
```
Apparently, it's trying to reference that commit in the submodule of the forked repo https://github.com/UPBGE/blender-addons but fails to find it.

**Comment by lordloki** [comment]
The way to check out the sources is:
cd C:\blender-git
git clone https://github.com/UPBGE/upbge.git
cd upbge
git submodule sync
git submodule update --init --recursive --remote
git submodule foreach git checkout master
git submodule foreach git pull --rebase 

After for update:
git pull --rebase
git submodule update --recursive --remote
git submodule foreach git pull --rebase

Could you check again with these commands?

**Comment by mysticfall** [comment]
I was using a modified version of `PKGBUILD` which included all the required commands, but without `--remote` flag.

When I added it, it fixed the issue indeed.

Thanks much for the help! :)
