### ISSUE TITLE
Camera Transforms are corrupted following code change to Matrix Transforms

### ISSUE THREAD

**Issue by Feral3d** [UPBGE/upbge#1238]
The previous bug corrected by @lordloki shown here: [https://github.com/UPBGE/upbge/issues/1228 ](url)
Appears to have created a second minor, unforeseen issue that corrupts the scaling of the camera Transforms. From what I can tell, it appears to be inverting the scale of the camera when you apply any math to it's transform Matrix.

Here is a test gif where camera Transforms are working correctly in version 0.2.5a:
![Samples_Cam_Warp_Bug](https://user-images.githubusercontent.com/67176876/85627845-2d731b00-b63d-11ea-8e6e-28a282967ced.gif)

Here is that same gif with camera Transforms are working incorrectly in the recent update with Matrix Transforms fix:
![Samples_Cam_Warp_Bug_Broken](https://user-images.githubusercontent.com/67176876/85628441-27316e80-b63e-11ea-96c1-99178edb639c.gif)

The Problem:
Upon launch of the new build, the camera is immediately inverted and looks "backwards" and "upside down". This is not expected behavior for the Camera, and is not compatible with previous versions.

In this Blender File you can test the issue and see the problem:
[https://www.dropbox.com/s/147n8lvvgnnn7ee/Cam_bug_Transforms.blend?dl=0](url)

**Comment by lordloki** [comment]
Ok, second attemp: https://mega.nz/file/1sNkEQxR#SkEH-ry66BnW7vei7exruaclCtiPKezxyfAkXxwSljk

I changed row-major by column major. Works ok with both test files.

**Comment by Feral3d** [comment]
Holey heck that was fast!

**Comment by lordloki** [comment]
Great. Closing now. Thanks for reporting.
