### ISSUE TITLE
Mist dont update in Real time 0.2.5 #0.2.5

### ISSUE THREAD

**Issue by NatGazer** [UPBGE/upbge#1242]
If I create an animation with **horizon color**, or any value related to the mist, it wont update **in game or even in viewport**

**Comment by lordloki** [comment]
Hi, 

Has you uncheck World and Mist constants?
![image](https://user-images.githubusercontent.com/1015605/86045045-4ddf1300-ba4b-11ea-8213-a788407889db.png)

**Comment by NatGazer** [comment]
No! Sorry, I dindn't noticed that. And I really thank you for that! Now I can make a proper day/night cycle!
