### ISSUE TITLE
Mouse Movement Sensor not working properly with low FPS (0.2.5 and 0.2.5a)

### ISSUE THREAD

**Issue by NatGazer** [UPBGE/upbge#1243]
Basicaly, this sensor **don't return a True value** when my FPS goes down to **30 FPS or less**.

My GPU kinda of controls my FPS in a way that it is limited to 60 FPS and if it can't handle it, it goes down to 30 FPS. I have a NVIDIA GeForce GT  630M 2GB. 

The problem is that if I replace **this sensor** with an **always** sensor (camera look logic), my camera sometimes starts to rotate by itself.

Heres a .blend to help (maybe you need to increase the amount of rigid body objects depending on your hardware)

[Low FPS mouse_mov sensor.zip](https://github.com/UPBGE/upbge/files/4847641/Low.FPS.mouse_mov.sensor.zip)

**Comment by lordloki** [comment]
Please, check this build: https://mega.nz/file/J1UVmS4R#YAoQsBPR0voN8Sl0Hwl6fV2rvDSlAX6rqNn4hIiEUQE

**Comment by NatGazer** [comment]
Now it works! Thank you for your feedback!
