### ISSUE TITLE
A World animation (horizon and zenith color) don't play when new scene is added

### ISSUE THREAD

**Issue by NatGazer** [UPBGE/upbge#1244]
**Heres blend file:**

[World animation with overlay scene.zip](https://github.com/UPBGE/upbge/files/4854160/World.animation.with.overlay.scene.zip)

**Comment by youle31** [comment]
When we comment UpdateAnimations(scene) in RenderShadowBuffers, it works, then I guess something is wrong with animations update...

**Comment by youle31** [comment]
https://github.com/UPBGE/upbge/pull/1246

**Comment by youle31** [comment]
Fixed here: https://github.com/UPBGE/upbge/commit/5ff4725ebfd2e3140fd906f275e614e5eba08d85

Thanks for report

**Comment by NatGazer** [comment]
> Fixed here: [5ff4725](https://github.com/UPBGE/upbge/commit/5ff4725ebfd2e3140fd906f275e614e5eba08d85)
> 
> Thanks for report

Ok, good, but will you put a recompiled version in MEGA? I don't know, I don't understand this very well

**Comment by lordloki** [comment]
Her you have the build: https://mega.nz/file/1xUVVaQa#-2J0I6L0s585QcbSQCSSgNd6aN6jetMmBFbHReOjtI4

Thanks for reporting

**Comment by youle31** [comment]
Thanks very much lordloki!

**Comment by NatGazer** [comment]
Thanks!
