### ISSUE TITLE
Realtime Environment Lighting 0.2.5 (Good first issue: Implement world ipo envlight actions)

### ISSUE THREAD

**Issue by NatGazer** [UPBGE/upbge#1245]
Is it possible to be done with python or animations? It's not working here

**Comment by BluePrintRandom** [comment]
this seen is lit only by it's HDRI 
![image](https://user-images.githubusercontent.com/7190873/86268197-a9f58480-bb7c-11ea-9bb3-154c6c429883.png)

**Comment by NatGazer** [comment]
Ok but I'm working with 0.2.5

**Comment by BluePrintRandom** [comment]
Oh yeah, you may be able to update a probe on the overlay scene  and use it
to texture a cubemap on main

**Comment by NatGazer** [comment]
Yes but my point here is to change the "Environment Lighting" value located in world settings in realtime with an animation or python

**Comment by youle31** [comment]
It's working with python for me (not with world ipo controller though):

https://pasteall.org/blend/67baaac283614d6c87f3a692a41d2923

http://shuvit.org/python_api/bge.types.KX_WorldInfo.html?highlight=energy#KX_WorldInfo.envLightEnergy

(Warning about constants to uncheck in Material tab)

**Comment by NatGazer** [comment]
Thank you! That works
