### ISSUE TITLE
yeah. but what about encription?

### ISSUE THREAD

**Issue by feticcio** [UPBGE/upbge#1248]
i love the engine i really do.

its the most good game engine ive played with. until now.
just being able to do stuff with python is epic. and with one of the latest releases you can also import other libraries.
i would love to use if for an actual game. but theres still a problem. i cant encrypt game files. as so people would just be able to steal all the models. thats not the problem whatever.    the actual problem is for example if i wanted a "multiplayer game"
i wouldent want cheaters to just modifiy a file in the folder and then do all they want. basically anyone with a grasp of python can do it.

isent there any way of obfuscating heavily?   or an anti cheat wich would prevent game files modification?

**Comment by youle31** [comment]
There's Bpplayer to encrypt your .blends and protect your assets. Lordloki shared a version in his mega folder: https://mega.nz/folder/k9MW1KiZ#UOKzjh3IQ0GEgjQ6GUc7ug/folder/QsVFVIRb (BPPlayer 1.07b). (You need to select the right upbge blenderplayer version).

Else, as far I understood from GPL license, you just need to share a copy of your scripts if someone asks for it. But I won't start a debate around GPL here.

**Comment by feticcio** [comment]
> There's Bpplayer to encrypt your .blends and protect your assets. Lordloki shared a version in his mega folder: https://mega.nz/folder/k9MW1KiZ#UOKzjh3IQ0GEgjQ6GUc7ug/folder/QsVFVIRb (BPPlayer 1.07b). (You need to select the right upbge blenderplayer version).
> 
> Else, as far I understood from GPL license, you just need to share a copy of your scripts if someone asks for it. But I won't start a debate around GPL here.

well.  thats really useful! im gonna try it right away

**Comment by feticcio** [comment]
it works as needed. well this is a good feature UwU
