### ISSUE TITLE
problems with object moving speed and polygons

### ISSUE THREAD

**Issue by feticcio** [UPBGE/upbge#1250]
basically i have an armature. but when the armature moves really fast in the game engine. the polygons of the mesh start to flicker/move. also depends on the scale of the object. like with a high scale dosent almost happen but with a smaller one is really hard.  
i tried different resizes. the  problem always appear either ways

at really small sizes the mesh starts to flicker even  if its not moving.

anything im missing?

**Comment by lordloki** [comment]
Hi, I need a test file to check the issue. Thanks

**Comment by AC-Panda** [comment]
Have you applied scale to the mesh/armature before parenting them to each other.

**Comment by rpaladin** [comment]
@feticcio no test file was provided so I close this issue. Feel free to comment if you still experience these issues.
