### ISSUE TITLE
Crash when drawing message actuator 0.3

### ISSUE THREAD

**Issue by youle31** [UPBGE/upbge#1251]
test file: https://drive.google.com/file/d/1a7h7FPQacPlAJ9M9sKI7SHOTqlBI8TwP/view?usp=sharing

steps: Unroll one of the message actuators in the file

Note: In debug mode with visual studio, when you create a new file with a message actuator, then save it, then reopen, an error is raised at open.

**Comment by youle31** [comment]
I reference a branch i commited earlier: https://github.com/UPBGE/upbge/tree/message_actuator

idk what's the mess with toObject and toPropName for message actuator

**Comment by lordloki** [comment]
Fixed in master. Thanks mate.
Closing.
