### ISSUE TITLE
Crash when calling "reinstancePhysicsMesh()" in version 0.3 

### ISSUE THREAD

**Issue by GenericGitGuy** [UPBGE/upbge#1254]
Calling the "reinstancePhysicsMesh()" function from the bge api in a python script results in an access violation exception and therefore an instant crash. This problem seems to only occur in version 0.3, in a similar test carried out in version 0.2.5, everything worked. Find attached a detailed crash report and a test file.

[physicsmesh.crash.txt](https://github.com/UPBGE/upbge/files/4928390/physicsmesh.crash.txt)

[physicsmesh.zip](https://github.com/UPBGE/upbge/files/4928392/physicsmesh.zip)

And when i am on it, thank you everyone for your amazing work on this project.

**Comment by youle31** [comment]
ReinstancePhysicsMesh is not supported in 0.3. Instead there is a new API: kxob.updatePhysicsShape(True)

There are still few issues with it but we are aware of that and it is on the task list.

test file: https://pasteall.org/blend/468f2f7ecb174e1d9149ed2c190582eb

**Comment by youle31** [comment]
I added a note in release notes (at the bottom):

https://github.com/UPBGE/upbge/wiki/Release-notes-version-0.3.0
