### ISSUE TITLE
Fix the camera fov problem in reflection map

### ISSUE THREAD

**Issue by MarllonxD3** [UPBGE/upbge#1255]
When i change the camera fov/lens in game, this causes a strange problem in the reflection material...
it's like the reflection does not identify the change in camera fov. 
It's possible to fix it? I'm using UPBGE v2.5
.blend file:
https://www.mediafire.com/file/qcrbgsb71v15q3d/FovProblem.blend/file

**Comment by youle31** [comment]
Fixed here: https://github.com/UPBGE/upbge/commit/26b5c05d0932f6e993b80f92d9f9cf225abd6372

Thanks for report
