### ISSUE TITLE
UPBGE 3.0 EEVEE CANT SELECT FACE, EDGE AND VERTEX PROPERLY

### ISSUE THREAD

**Issue by Loniyke** [UPBGE/upbge#1257]
Please I need help. I'm using the UPBGE 3.0 EEVEE and each time I try to edit my mesh in edit mode it starts Messing up. Like I can't select faces, vertices or edges. If I try selecting it, it selects a different face or edges etc. Is this a bug? Should I use UPBGE 2.5? 
I'm using it for ArchViz. Eevee version stable enough for ArchViz?

**Comment by youle31** [comment]
For small Archviz it should be good enough...

Each day, upbge import last blender code. As blender is in 2.90 alpha, there might be some bugs I guess. It depends on the day.

Lordloki (an upbge developer) regularly does new builds (I saw that he did a build 12 hours ago). You can try with the last build. Else you can download older builds and you will surely find a build which has not this issue in edit mode.

(I didn't noticed issues in edit mode, but I don't test every day...)

The builds are in the Mega folder: https://mega.nz/folder/k9MW1KiZ#UOKzjh3IQ0GEgjQ6GUc7ug/folder/ZtcDzYYA

You can try the last, else, olders builds in "old builds" folder
