### ISSUE TITLE
Wiki release notes 0.3.0, broken image

### ISSUE THREAD

**Issue by duianto** [UPBGE/upbge#1258]
The first image on the following page is broken:
https://github.com/UPBGE/upbge/wiki/Release-notes-version-0.3.0

Inspecting the image shows that it's pointing to:
https://github.com/UPBGE/upbge/raw/master/release/datafiles/splash_2x.png

But there is no image with that name in the datafiles directory:
https://github.com/UPBGE/upbge/tree/master/release/datafiles

There is however an image there with a similar name:
https://github.com/UPBGE/upbge/blob/master/release/datafiles/splash.png

![splash](https://github.com/UPBGE/upbge/blob/master/release/datafiles/splash.png?raw=true)

It seems like it might be the correct image.

But on the previous release wiki page:
https://github.com/UPBGE/upbge/wiki/Release-notes-version-0.2.5

It's first image has the url:
https://github.com/UPBGE/Images/raw/master/0.2.5/release_a.png

Therefore maybe the splash.png image should be moved or copied to the 
https://github.com/UPBGE/Images repository, since it's description says:
>Images for Wiki

**Comment by youle31** [comment]
I just removed the "_2x" . Thanks for report
