### ISSUE TITLE
Bus error when built on Raspberry Pi 4

### ISSUE THREAD

**Issue by DonFlymoor** [UPBGE/upbge#1260]
I built UPBGE from the 0.2.5 archive on the release page, disabling `Cycles` and `OpenColorIO`. Compilation was successful with no errors, but running results in a grey screen, then `Bus error`. Interestingly, when I ran it with `valgrind ./blender`, it worked as expected, other then the 0.2 FPS. I'm not sure exactly what went wrong, and would appropriate any help!

### System information:
- Armv8 64 bit Proccessor
- Arm linux, Raspbian OS
- 32 bit Userland
- 64 bit Kernal
- Clang compiler

**Comment by lordloki** [comment]
It is difficult to debug this as we don't have a raspberry pi 4 to test.
Anyway, could you start from command line with "./blender --debug-all"?

**Comment by DonFlymoor** [comment]
Here is the log:
```sh
./blender --debug-all
Switching to fully guarded memory allocator.
Color management: using fallback mode for management
read file 
  Version 279 sub 7 date 2020-04-22 16:05 hash acc0a8441f8e

ordered
 OBLamp.002
 OBLamp.001
 OBPlane
 OBCube
 OBLamp
 OBCamera
ED_screen_refresh: set screen
found bundled python: /home/pi/Software/Source/Github/blender/upbge-0.2.5/build/bin/2.79/python
time bl_operators 0.0906
time bl_ui 0.2413
time keyingsets_builtins 0.0058
time nodeitems_builtins 0.0288
	addon_utils.enable io_scene_3ds
	addon_utils.enable io_scene_fbx
	addon_utils.enable io_anim_bvh
	addon_utils.enable io_mesh_ply
	addon_utils.enable io_scene_obj
	addon_utils.enable io_scene_x3d
	addon_utils.enable io_mesh_stl
	addon_utils.enable io_mesh_uv_layout
	addon_utils.enable io_curve_svg
Python Script Load Time 0.4879
FRS_set_context: context 0x0xe94baa00 scene 0x0xe8ce6020
libpng warning: iCCP: known incorrect sRGB profile
UI_menutype_draw: opening menu "USERPREF_MT_splash"
UI_menutype_draw: opening menu "USERPREF_MT_splash_footer"
Thread 0: update object OBCube
recalcob Cube
recalcdata Cube
Thread 2: update object OBCamera
Thread 1: update object OBLamp
recalcob Lamp
Thread 3: update object OBPlane
recalcob Camera
Thread 1: update object OBLamp.001
recalcob Lamp.001
Thread 1: update object OBLamp.002
recalcob Lamp.002
recalcob Plane
recalcdata Plane
Thread 0: total 1 objects in 0.002472 sec.
  Cube in 0.002472 sec
Thread 1: total 3 objects in 0.000228 sec.
  Lamp in 0.000162 sec
  Lamp.001 in 0.000037 sec
  Lamp.002 in 0.000029 sec
Thread 2: total 1 objects in 0.000352 sec.
  Camera in 0.000352 sec
Thread 3: total 1 objects in 0.001943 sec.
  Plane in 0.001943 sec
Scene updated 6 objects in 0.002678 sec
ghost_event_proc: window 1 state = normal
ghost_event_proc: ghost redraw 1
ED_screen_refresh: set screen
Bus error
```

**Comment by youle31** [comment]
I don't have a rasperry pi neither.

**Comment by DonFlymoor** [comment]
Perhaps use an emulator?

**Comment by TriVoxel** [comment]
I have a Raspberry Pi 4 B. @DonFlymoor try using Ubuntu. Raspberry Pi OS (formerly Raspbian) is super outdated and doesn't have up-to-date libraries and it doesn't even have half the dependencies required to build Blender properly it seems. I think it is running a Debian OS from 2017?? I would suggest installing Ubuntu server 64-bit and installing a desktop. At any rate, it's much faster and more performant that Raspbian. I get probably twice the performance. It has all up-to-date packages and unlike RPi OS, it has ALL x86 software compiled for it in the repositories. I will attempt to build the master branch of UPBGE and I'll get back to you.

**Comment by DonFlymoor** [comment]
Last time I compared Raspbian and Ubuntu on the Pi, Raspbian was far more responsive then Ubuntu, although perhaps Ubuntu has been optimized for the Pi at some point. I will try to get Ubuntu and see how well it performs now, then try to get UPBGE working on it. Thanks for the Info!

**Comment by TriVoxel** [comment]
@DonFlymoor I should mention you need a desktop without compositing. Gnome is very slow for instance. I prefer KDE Plasma. Just disable desktop compositing and animations and it actually runs really well. In fact it ended up outperforming my 5-year-old Intel laptop with 3x the RAM. Again, don’t use a composited desktop. Use KDE Plasma without desktop effects or LXDE/LXQT. Also anything with blue is a big no-no!

**Comment by DonFlymoor** [comment]
I had thought that Gnome would be faster, because that's what Raspbian uses, so I suppose that's why I thought it was slow. As soon as I can get the Ubuntu image, I'll try it!

**Comment by DonFlymoor** [comment]
I'm giving Ubuntu mate a try, it looks much better than Raspbian and responds very quickly. I'll try building UPBGE and see how it goes.

**Comment by DonFlymoor** [comment]
Indeed, after editing the install-dependencies.sh scrip to use my arm cpu and disabling sse and cycles, it built! Unfortunately, It's also very slow. As opposed to the ~40 FPS I got in Raspbian's bundled 2.79 blender with a cube and real-time shadows, I get ~20 fps with the default scene (~25 when the sun is deleted)(70% time is spent on the GPU). Any hints on how to improve performance?

**Comment by lordloki** [comment]
For low end devices the performance of blender 2.79 is higher as it uses vertex arrays. UPBGE uses VBO that gives a little less performance but high flexibility than Vertex array.  I think that can't be avoided

**Comment by DonFlymoor** [comment]
Are you saying that UPBGE replaced blender's VAO's with VBO's? Why did they do that?

**Comment by DonFlymoor** [comment]
I see. I'm currently using UPBGE 0.2.5, because blender 2.8 doesn't work well (at all, all GL calls have to be translated from 4 to 3)

**Comment by lordloki** [comment]
Hi, I'm going to close this issue report as we can do  nothing about last issue that you comment (less performance than blender 2.79). At this moment, the development of upbge 0.2.5 (with old render) is stopped although I will publish a new 0.2.5b before year ends but it will have fixes only. After that, all the efforts will be dedicated to master branch (upbge0.3) to release the 0.3 version asap.
Thanks for reporting
