### ISSUE TITLE
Please add an option to export a game to andriod.

### ISSUE THREAD

**Issue by INDIANUPBGEGAMERENDERER** [UPBGE/upbge#1261]
Hello UPBGE  devs, I have a small reauest to you, can you please add an option to export to andriod in UPBGE 2.5 as quick as possible? Thanks

**Comment by lordloki** [comment]
Hehehehhe, this is not a small request. We will see if we can get an android build but it will take time and we don't know if it is possible yet.

Closing the issue by the moment.
