### ISSUE TITLE
UPBGE 3.0 Action actuator PingPong playing animation in loop

### ISSUE THREAD

**Issue by rollalt** [UPBGE/upbge#1262]
ping pong is repeating the animation to infinity with out stoping so is opening and then closing and then again. Even if my animation is just the door opening.

**Comment by youle31** [comment]
Fixed in https://github.com/UPBGE/upbge/commit/060a558648c8479c514d87195c60b01530b73f4c

The next builds will include this fix, with the hope it's the behaviour you were expecting.
