### ISSUE TITLE
Lower fps with upbge-eevee than upbge 025

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/upbge#1264]
This issue looks bad too me.
video: https://www.youtube.com/watch?v=V9uNUNEhALY
files: https://drive.google.com/drive/folders/1ywE8FWoV9yGbance9b-zxXYvvTLfxH5s?usp=sharing

OS WIN 10, AMD video. 16gb ram

**Comment by youle31** [comment]
In upbge 0.3, we use directly blender code to play animations and it is very slow compared to bge. Blender Foundation coders identified several bottlenecks and are trying to improve it: https://developer.blender.org/T68908
But this requires big refactors and it could take several years. We know these issues but the blender code is far too complex for me to improve that. I close this task as it mainly relies on Blender coders animations improvement tasks.

**Comment by Akira1San** [comment]
Thx, its good to know.
