### ISSUE TITLE
UPBGE 3.0 will crash after 'Esc' when using navmesh!

### ISSUE THREAD

**Issue by rollalt** [UPBGE/upbge#1265]
UPBGE 3.0 will crash after 'Esc' when using navmesh on windows 10.

**Comment by youle31** [comment]
The navmeshes code is old and we need hacks to have it working in 2.8.
So I added a hack to the previous hack to avoid the crash here: https://github.com/UPBGE/upbge/commit/b7d3e34ee35600289e037b301106226def9dcf38

**Comment by rollalt** [comment]
> The navmeshes code is old and we need hacks to have it working in 2.8.
> So I added a hack to the previous hack to avoid the crash here: [b7d3e34](https://github.com/UPBGE/upbge/commit/b7d3e34ee35600289e037b301106226def9dcf38)

Thanks @youle31!
So what do I need to do to stop crashing?
A workaround is to generate navmesh save it in a new blend file and then append the navmesh from the new saved file, this way it will not crash any more.

**Comment by youle31** [comment]
Lordloki regularly new builds. The fix will be available in the next builds downloadable from upbge.org

**Comment by rollalt** [comment]
> Lordloki regularly new builds. The fix will be available in the next builds downloadable from upbge.org

Thanks.

**Comment by rollalt** [comment]
Hi @youle31,

With Lordloki update from a day ago this has not been sorted. It is still crashing after each on win 10. Can we reopen this, please?

**Comment by youle31** [comment]
I can't reproduce the bug. Can you follow this guide for bug report: https://github.com/UPBGE/upbge/wiki/Report-a-bug-guide and join a test file? Thanks.
