### ISSUE TITLE
Water shader setup with animated normal map and realtime SSR

### ISSUE THREAD

**Issue by RomStef** [UPBGE/upbge#1267]
I want to share my experimental setup of water using the IzaZed's upBGE logic nodes for moving the normal maps.
Here is the result

https://youtu.be/jjUvCZQe4zg

And here  is the file blend.

[POOL.zip](https://github.com/UPBGE/upbge/files/5024505/POOL.zip)

Feel free download and improve it.
Thanks to IzaZed.

**Comment by Feral3d** [comment]
Thanks for this!

**Comment by lordloki** [comment]
Hi, 
I move this to https://github.com/UPBGE/upbge/discussions under Resources to better organization. Thanks.
