### ISSUE TITLE
Standalone - Rotate view in viewport Option

### ISSUE THREAD

**Issue by pixelinkmedia** [UPBGE/upbge#1268]
I would like to be able to just use the UPBGE to create a standalone exe that allows me to view and rotate a scene in the view-port using my mouse, but I don't see an option to turn this on.

When I create an exe, I can't rotate my view using the mouse like I can when in the 3d Editor.

FYI, I am not using any game logic at all, just want to be able to create the scene as an EXE so a user can just rotate and view the object from any angle.

To be able to print the current view within the EXE would also be nice.

**Comment by BluePrintRandom** [comment]
you must use the scene camera, and attach it to a empty with parenting

add the logic

middle mouse
button------------------------------and--------------------Mouse actuator
(mouse look mode)

to the empty

**Comment by pixelinkmedia** [comment]
okay, i will give it a try later today or tomorrow
thanks

**Comment by pixelinkmedia** [comment]
Alright, I was able to get that to work.

So, do you know of a website where I can learn more about using the logic panel and such like.

I am also wanting to zoom in/out globally. But, it can't seem to get that to work.
I have tried using...
WheelpUp/Down......... And.......... Simple Motion.

But, the options are only x, y z, but that doesn't work globally on the scene like it does with the editor.

I must be missing something.

New to BGE

**Comment by youle31** [comment]
you can check Thatimster youtube chain: https://www.youtube.com/c/ThaTimst3r/videos
else there are many tutos on the net: You can google bge tutorial beginner, blender game engine tutorial...
It will be old tutos (2.7 or earlier) but the fundamentals are the same.

You can ask questions on discord: https://discord.gg/blender in bge channel or help-upbge channel.

I close this issue as it is normally for bug reports only. Thanks for your comprehension.

**Comment by youle31** [comment]
To zoom you can animate Camera lens and activate zoom in/out with 2 mouse wheel sensors (mouse sensor)

GIF: https://gifyu.com/image/WXSV
