### ISSUE TITLE
UPBGE 0.3 - bug - Added objects are displaced.

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/upbge#1270]
bug - Added objects are displaced.
OS: Win 10 Video AMD.
video: https://www.youtube.com/watch?v=ZTUt-ShgKt8
link: https://drive.google.com/drive/folders/1ywE8FWoV9yGbance9b-zxXYvvTLfxH5s?usp=sharing
file; Davostage01-E.blend - from the game Onikiri

**Comment by Akira1San** [comment]
theirs an error in the console added the error image in the folder - Clipboard012

**Comment by voland62** [comment]
Yeah.
scene.addObject("myObj") - doesn't work.
Have to rollback to Linux64-2020-07-31...

**Comment by youle31** [comment]
Maybe the issue can be solved applying the modifiers on all the objects + childrens added.
With integration with depsgraph, some behaviours might not be the same than for bge 2.7

**Comment by Akira1San** [comment]
I apply the modifier and the mesh is now displayed, but with no modifier, theres no animation plying.

**Comment by voland62** [comment]
The latest one: UPBGE-EEVEE-Linux64-2020-09-03
works good for me...

**Comment by Akira1San** [comment]
Its the same bug.

**Comment by youle31** [comment]
There's not backward compatibility for games made with bge versions based on 2.7. Some things have to be fixed manually (applying scale, on objects, applying modifiers, checking how animations are in the viewport and fixing manually...)
