### ISSUE TITLE
Ramdom actuator not working

### ISSUE THREAD

**Issue by Iks0rtso** [UPBGE/upbge#1272]
The logic brick ramdom actuator does not present any random value - Upbge 0.2.5a

**Comment by youle31** [comment]
It works fine for me
![Capture](https://user-images.githubusercontent.com/10052509/91059030-7fc6bd00-e629-11ea-8267-59624ba4cfed.PNG)

**Comment by Iks0rtso** [comment]
very strange, for me it generates the same value every time I start the engine! It is not drawing the numbers

**Comment by lordloki** [comment]
If you use a "seed" other than zero you will get a reproducible pattern. If you use a "seed" equal to zero you will use the system time as a generator initial point and the pattern will not be reproducible.

**Comment by youle31** [comment]
I close this report as it seems more a problem with random actuator usage than a bug.

I put a link to mikepan book: https://github.com/mikepan/GameEngineBook/blob/master/text/03-LogicBricks.md

but there might also be youtube tutos which can explain what you are trying to do.
