### ISSUE TITLE
BUG-UPBGE 0.3: Engine closes when trying to change scene

### ISSUE THREAD

**Issue by SwanTheHunt** [UPBGE/upbge#1276]
Since the last updates in August, upbge 0.3 is simply closing when trying to change the scene if your project / file is versions before August.

**Comment by youle31** [comment]
hi, did you try the build from yesterday?

**Comment by SwanTheHunt** [comment]
> Oi, você tentou a construção de ontem?

I tried, since build 17/08

**Comment by youle31** [comment]
I can't reproduce the bug in last master

**Comment by SwanTheHunt** [comment]
> Eu não posso reproduzir o inseto no último mestre

I opened the file in an old build and deleted the contents of the other scenes and opened that same file in this new build. I managed to change, apparently this is conflicting with the file size

**Comment by youle31** [comment]
Ok, then I closed this task as resolved
