### ISSUE TITLE
2D Sprite game property bug

### ISSUE THREAD

**Issue by RedstarBelg** [UPBGE/upbge#1282]
Hello everyone,

I report a bug about the 2D sprite texture execution: something seems to be "deactivated" because the sprite doesn't change.

I have compared between blender 2.70 and 2.79b (from blend fundation) and the same version upBGE 2.79b. If i create and configure the sprite from 2.70, save it and load it with 2.79b or upBGE version, the sprite system works.

But if i do the same with 2.79, the sprite system doesn't works...

Here what i'm talking about:
![Capture](https://user-images.githubusercontent.com/50919180/92900626-22e84680-f420-11ea-932f-dcc043ecf12e.JPG)

**Comment by BluePrintRandom** [comment]
a workaround is to use a node texture instead - add object color to UV and animate object color

this actually makes it so each sprite instance has it's own time value / is unique so you can run 100's of actors with 1 material etc.

**Comment by BluePrintRandom** [comment]
as the workaround is actually more flexible / functional  than fixing this - should we close it? @youle31

**Comment by youle31** [comment]
idk, if a volounteer wants to try to recover it in 0.2.5, there's still the code available... I don't know if it would be easy to do.

**Comment by RedstarBelg** [comment]
Hello @BluePrintRandom,

I'm not sure to see what you talking about. Can you make me an exemple blend, please ?

**Comment by BluePrintRandom** [comment]
[UV_Sprite_animation_fixed_bge.zip](https://github.com/UPBGE/upbge/files/5514018/UV_Sprite_animation_fixed_bge.zip)

**Comment by RedstarBelg** [comment]
Ok, thank you.

I am thinking about something: if i want to recover this tool in the 0.2.5, what knowledge i need ? Python or C/C++ ?
And about the source code of Blender, how can i take it or read it, how it's work ?

**Comment by lordloki** [comment]
This is working in current UPBGE 0.2.5. Closing now. Thanks for reporting
