### ISSUE TITLE
UPBGE-0.2.5 Character sliding

### ISSUE THREAD

**Issue by jhankiitus** [UPBGE/upbge#1285]
Objects with physical character are sliding, unless you have sphere collision bounds

translated by google translator

**Comment by youle31** [comment]
Please follow this guide: https://github.com/UPBGE/upbge/wiki/Report-a-bug-guide to report the bug,
and join a test file

**Comment by RomStef** [comment]
If the Character move and slide on a slope , you must increase the friction of the terrain in the physics tab. The character object have physics then it is affected by gravity. 
If this is the case , it's not a bug but you must learn how the physics in bge work

**Comment by Feral3d** [comment]
@RomStef in this instance, the Character Physics still does suffer from this "sliding bug". If I understand the problem correctly, there is no way to stop sliding for character physics with friction settings.  
Friction can stop objects with Dynamic physics, but not Character physics.

**Comment by youle31** [comment]
Bullet physics library doesn't handle friction for characters.

https://developer.blender.org/T34557

https://gamedev.stackexchange.com/questions/67375/bullet-character-controller-sliding-down-any-slope-gradient

There are several posts related to that on the net (this is not bge only) typing bullet physics character friction.

You can maybe find worarounds, or change of physics type to another type which supports friction
