### ISSUE TITLE
Always node didn't work with delay node 

### ISSUE THREAD

**Issue by mhreez** [UPBGE/upbge#1286]
Hay 
When i try always node with delay node the delay node didn't work i don't know why but when i used it with key pressed node it worked

**Comment by youle31** [comment]
Hi, are you talking about logic nodes addon?

If yes, the issue has to be reported here: https://github.com/IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes/issues

If it concerns logic bricks, please follow this guide: https://github.com/UPBGE/upbge/wiki/Report-a-bug-guide
 
and join a test file 

and tell us what version you are using

to report the bug
