### ISSUE TITLE
Character / Character bug sliding on sloping surfaces

### ISSUE THREAD

**Issue by firefoxjco** [UPBGE/upbge#1287]
I found a bug in **Character type physics** in UPBGE 0.2.5 / 0.2.5a. The only type of collision bounds that does not let the character slide on inclined surfaces is the sphere type bounds; in the other options the character / object slides. It seems to have something to do with friction but there is no option to regulate this in this type of physics, as it has in the Dynamic option.
Attached is a file made in UPBGE 0.2.5a.
[Character_type_physics_bug_test.zip](https://github.com/UPBGE/upbge/files/5267904/Character_type_physics_bug_test.zip)

**Comment by youle31** [comment]
There's no setting related to friction in btKinematicCharacterController. This is the standard behaviour for characters which don't support friction. As answered in other thread, this behaviour is mentionned in several threads on the net, not only for bge, but for other engines too such as iirlicht...
As it depends on Bullet library but not on bge code, we can't fix that, then I close this report.
