### ISSUE TITLE
0.3 Alpha Missing Scene Options

### ISSUE THREAD

**Issue by SunriseCreationsStudio** [UPBGE/upbge#1289]
Missing OverlayScene and another options, only 3 options in 0.3 Alpha.

Thanks for working on this project. Best regards

![Captura de pantalla 2020-09-29 234241](https://user-images.githubusercontent.com/71786138/94620579-28161400-02af-11eb-9c69-89e06831f473.jpg)

**Comment by BluePrintRandom** [comment]
Overlay is now done using collection actuator and a ui collection

**Comment by SunriseCreationsStudio** [comment]
Thanks, now are working!

**Comment by youle31** [comment]
Ok, I close this report since @BluePrintRandom  answered. Thanks!
