### ISSUE TITLE
Transformations for scaled and parented objects 

### ISSUE THREAD

**Issue by MechatronixX** [UPBGE/upbge#1291]
Try this to reproduce the issue. Add two cubes and parent them. Use a motion actuator in UPBGE game logics to rotate the parent around the x-axis. Everything seems fine. Now re-scale the parent around the x-axis and re-run. The child now makes an elliptical, or at least non-circular, motion around the parent cube. 

As this is something that doesn't happen in Blender when rotating the parent, I guess it is either a bug or should at least something to be considered undesirable. 

I have observed this for UPGE 0.3, both in Windows and Linux.

**Comment by youle31** [comment]
Could you follow this guide: https://github.com/UPBGE/upbge/wiki/Report-a-bug-guide to report an issue.

- In your case, could you join an upbge 0.2.5 test file and an upbge 0.3 test file to compare?
- Could you describe the exact steps to reproduce the issue? (you can do a gif with screenToGif for example and give us a link to it here).

Thanks.

**Comment by MechatronixX** [comment]
So this is an example of what I mean. See how the motion is skewed when re-scaling the objects. Even if this for some reason is an intended behavior, at least IMO it shouldn't be. It seems that the object scale factors are involved in some way they shouldn't, re-scaling the relative position vector between the objects. If you can give some pointers about where to start looking in the code,  I can see if I can do anything about it, would be fun :) 

I am using Ubuntu 20.04 with UPGE 0.3 alpha from 2020-10-07. 

Here is a file you could use to reproduce the issue. I guess the gif is of more interest though as it outlines all the steps I took. 
[transform_issue_alpha_03.zip](https://github.com/UPBGE/upbge/files/5366852/transform_issue_alpha_03.zip)

![transform_issue](https://user-images.githubusercontent.com/37342798/95777872-504a3d80-0cc7-11eb-9c57-ec95393a0bb1.gif)

My current workaround to this is to manually recalculate the positions and orientations in a script.

**Comment by lordloki** [comment]
To fix the rotation after scale, you have to apply rotation & scale on central object
![image](https://user-images.githubusercontent.com/1015605/95782625-77593d00-0cd0-11eb-88f1-aecd07d49c89.png)

**Comment by MechatronixX** [comment]
Awsome that a pull request is up already! :)
