### ISSUE TITLE
Windows terminal and script editing 

### ISSUE THREAD

**Issue by MechatronixX** [UPBGE/upbge#1292]
When opening the terminal emulator in Windows 10 64 bit during script editing it seemed like system crashes were always imminent. Often it seemed to happen when saving the .blend file. Sometimes it happened in connection to running the game. I observed this in both 0.25 and 0.3 alpha version.

**Comment by lordloki** [comment]
I tested opening the windows terminal while running the game or editing the script, in both upbge versions, and I can't make it crash (indeed this a very common procedure for us as we use to get feedback in the console during the debugging sesions).

Youle, do you have this crash??

**Comment by youle31** [comment]
no, i have no crash

**Comment by lordloki** [comment]
I tested this with 5 different computer and i didn't suffer any crash or malfunction in any of them.
I close the report as it seems something specific fo your configuration.
If later i detect this issue I will open again this report.

Thanks for reporting
