### ISSUE TITLE
0.30.0α | groupMembers = None. 

### ISSUE THREAD

**Issue by voland62** [UPBGE/upbge#1293]
myCollInctance.groupMembers = None in 0.30.0α-b.79 for myCollInstance full of objects...
In 0.2.5 - all works good...

**Comment by lordloki** [comment]
Confirmed. We are investigating.

**Comment by youle31** [comment]
It works now (in last upbge 0.3) for active instance collections (with the eye checked) and for spawned collections. Then I close this report. Thanks for report.
