### ISSUE TITLE
0.30.0α | Library Override for Game Properties

### ISSUE THREAD

**Issue by voland62** [UPBGE/upbge#1294]
We usually can override many data-blocks for linked objects. But it seems we can't do this for game related stuff(game props, attached components)... Am I wrong? If no, is it hard to implement?

**Comment by lordloki** [comment]
We know it. It is hard to implement as we would have to add data-block id  for game props, etc and this is not easy and we would need to modify A LOT blender code (more difficult merges, etc).

I will put under feature request label to check later in future releases. Closing until then.
