### ISSUE TITLE
0.3 I 2.90 I Baking cubemap or indirect lighting freezes the entire UI

### ISSUE THREAD

**Issue by SenhorPatolino** [UPBGE/upbge#1296]
Freezes the UI but im still able to save

**Comment by lordloki** [comment]
I baked an irradiance volumen for indirect lighting and it worked like a charm.
Do you have a blend to test?

**Comment by youle31** [comment]
I can't reproduce this issue, and even if I could, it doesn't depend of the part of the code we are maintaining (we only treat bugs related to gameengine). It might be solved in a future build of Blender. If you can reproduce this issue on official Blender, you could eventually report an issue following the guide to report a bug in their tracker (join a test file, indicate your OS, your hardware specifications, the exact steps to reproduce the issue...)

**Comment by SenhorPatolino** [comment]
My bad, it seems to be a problem with my specs, i guess the project is getting so heavy that cubemaps are not baking correctly, tested on Blender and the same happens
