### ISSUE TITLE
Cannot set font object text attribute directly 

### ISSUE THREAD

**Issue by MechatronixX** [UPBGE/upbge#1297]
For UPGE 0.3. This example doesn't seem to work: 
https://upbge-docs.readthedocs.io/en/latest/api/bge.types.KX_FontObject.html#KX_FontObject

This is the code I tried: 

`import bge `

` font_object = (bge.logic.getCurrentController()).owner `

` #font_object["Text"] = "foo"     # Works`

 `font_object.text ="bar"            # Does't work if the line above is commented out like now `

This code doesn't show "bar" as text. However, if  I uncomment ` #font_object["Text"] = "foo" ` then it will. Using ` #font_object["Text"] = "foo" ` always seems to work. 

I am running on Ubuntu 20.04.

**Comment by youle31** [comment]
indeed you need you use obj["Text"]

**Comment by lordloki** [comment]
Yes that doc should be rewrite as now we use also bpy and it has no sense to duplicate the api, then you could do:

```
import bge, bpy

font_object = (bge.logic.getCurrentController()).owner
font_object.worldPosition.y = 2

text = bpy.data.curves["Text"]
text.body = "Hi"
text.size = 4
text.resolution_u = 1
text.align_x = LEFT
```

**Comment by MechatronixX** [comment]
Neat that we can use bpy for this! Does this also apply for collections?

**Comment by sevi78** [comment]
I just found out, that whenever one adds a KX_FontObject with python or Actuator, the text assigned is always on all instances of the KX_FontObject---makes it impossible to assign text in realtime to spawned Texts. ... or i might be dumb as a donkey :) 

```
import bge
G = bge.logic
sce = G.getCurrentScene()

t = sce.addObject("Text",own,0.0)
t.worldPosition = (-2,0,0)
t["Text"] = "text"
## so far so good, t["Text"] shows "text"

## now after adding another Text, t["Text"] shows "text2"
t1 = sce.addObject("Text",own,0.0)
t1.worldPosition = (0,0,0)
t1["Text"] = "text2"

```
i have also tried with instantAddObject and Actuators with the same result
