### ISSUE TITLE
after starting bge the pbjects are displaced

### ISSUE THREAD

**Issue by mushroomeo** [UPBGE/upbge#1300]
in upbge eevee when i start bge then objects are displaced . and i applyed scale and rotation and still didnt fixes it.

[123.zip](https://github.com/UPBGE/upbge/files/5348457/123.zip)

**Comment by BluePrintRandom** [comment]
these objects are all joined as 1 object set to soft body

splitting them and resetting their origin behaves as expected
![ezgif com-gif-maker (9)](https://user-images.githubusercontent.com/7190873/95494243-792ea380-0952-11eb-95dd-6cf2ba017d80.gif)

**Comment by BluePrintRandom** [comment]
there does appear a issue with if a mesh is all triangles 
https://www.youtube.com/watch?v=oxdcDziWcMk

it very slight but it does exist

**Comment by youle31** [comment]
I close this because maybe it comes from that center of mass of a triangle is not the same than for a quad. Idk if we should use center of mass (intead of origin position), but if I used it, it is because i saw it was used in bullet. Then it might be a normal behaviour.

**Comment by youle31** [comment]
Fixed here: https://github.com/UPBGE/upbge/commit/ce6bb17c2e413d247d82be452cf793c183cf8c36
