### ISSUE TITLE
Interfacing with multiple scene collections [0.3 alpha]

### ISSUE THREAD

**Issue by MechatronixX** [UPBGE/upbge#1302]
A little background to this issue. I have a HUD that I am overlaying as a collection and it works fine. It is basically a camera that is directed at some text objects. Now I did move this collection to another scene collection with the following result: 

1. The collection actuator GUI block still shows all my HUD objects in the autocomplete so I guess these features are partly implemented 

2. However, in the console I get the following error when running the game: "Collection Actuator: Inexistant Camera or Camera already used by main render or ImageRender". I set the "Fake user" for all objects in the other scene so they wouldn't be deleted. 

3. The objects for the HUD scene collection don't show up in bge.logic.getCurrentScene()).objects when I am in the world scene, which is expected. However, is there yet some API function that allows me to access other scenes collections? 

Btw, If anybody knows a way to circumvent the problems with accessing objects in other scenes I would be very thankful. What I do currently is to put the HUD inside the same scene collection as the world environment, and put it beneath the floor where I cannot see it in game.

**Comment by youle31** [comment]
With depsgraph integration in upbge0.3, we can only manage 1 scene at a time. Then you can't have overlay scenes, background scenes, you can't use addScene... We added the overlay collections as a "solution" to add a HUD collection in the main scene.
The HUD needs its own camera and all HUD objects can be hidden at game start.
We added option to suspend/resume overlay collection (visibility/physics/logic) to imitate what was done in blender 2.7.
There's another option in HUD camera tab if you want mouse events to be computed in overlay camera space.

In upbge0.3, only 1 scene can be handled.
