### ISSUE TITLE
Force Field Not working ... Issue or changed how to use?

### ISSUE THREAD

**Issue by SunriseCreationsStudio** [UPBGE/upbge#1303]
Hi Team

I testing upbge 0.3.0 alpha,  and tried to make a simply plane force field for elevate a cube mesh, but not working, missing "buttons", worked fine on upbge 0.2.5.

Its changed the way to do the force field?

**Comment by BluePrintRandom** [comment]
![ezgif com-gif-maker (10)](https://user-images.githubusercontent.com/7190873/95496094-302c1e80-0955-11eb-949c-149d890e5969.gif)

appears to be working for me

ensure you check 'use forcefield' in your dynamic / rigid body objects.

**Comment by SunriseCreationsStudio** [comment]
The check in my version are missing

Working fine on 0.2.5

![UPBGEAlpha](https://user-images.githubusercontent.com/71786138/95511800-3d2e2980-09b8-11eb-8773-57e99fcf2a42.jpg)

**Comment by SunriseCreationsStudio** [comment]
capture from 0.2.5

In this version appears the check box and working, but in 0.3.0 alpha .... these check button are missing ... what are doing wrong?

![Captura de pantalla 2020-10-08 224953](https://user-images.githubusercontent.com/71786138/95512105-a1e98400-09b8-11eb-9006-9514fed2287e.jpg)

**Comment by lordloki** [comment]
At least in the last build the check is there:
![image](https://user-images.githubusercontent.com/1015605/95543539-16dcae00-09f9-11eb-8c6f-d2b98e19a59e.png)

**Comment by SunriseCreationsStudio** [comment]
Found the issue!

Force Field

UPBGE-EEVEE-Win64 2020-10-05 --> Working
UPBGE-EEVEE-Win64-2020-10-07 -->Not Working

Missing the check box force field on "dynamic"

![Captura de pantalla 2020-10-09 091351](https://user-images.githubusercontent.com/71786138/95554133-f1a76a00-0a0f-11eb-9af2-130b6e41d736.jpg)

**Comment by lordloki** [comment]
I will check later if there is an issue with the build compilation. Thanks for reporting.

**Comment by SunriseCreationsStudio** [comment]
Hi!

Downloaded again ... and now working on ultimate build.

Maybe an addon cause the issue, in my another build i have addons installed ....
