### ISSUE TITLE
UPGE versioning and download section.

### ISSUE THREAD

**Issue by chicortiz** [UPBGE/upbge#1309]
Hello Dear UPBGE Devs.

I'm writing to ask if there is a way to let the download section of UPBGE more intuitive ( https://upbge.org/ ). It would be a good thing to know in which Blender version the UPBGE versions are based on for example.

Thank you very much for your attention and patience.

Greetings,

Ortiz

**Comment by lordloki** [comment]
Yes, I'm currently updating the web. I will update the download section too doing it more intuitive.

Just for info, UPBGE 0.2.5 is based in blender 2.79 and UPBGE 0.3.0 Alpha (or UPBGE-EEVEE) is based in current Blender master (2.91)

**Comment by lordloki** [comment]
I close this as the update is in progress (I think before year ends the update will be  active)

**Comment by chicortiz** [comment]
> I close this as the update is in progress (I think before year ends the update will be active)

Thank you very much lordloki!
