### ISSUE TITLE
Bug report: Keyboard Sensor > First Modifier, Second Modifier

### ISSUE THREAD

**Issue by denicolas** [UPBGE/upbge#1313]
UPBGE 0.30.0 Alpha (based on Blender 2.91.0 Alpha)
Doesn't work as expected:
- If you use only "First Modifier", it is ignored.
- If you use the same modifier key in "First Modifier" AND "Second Modifier", then it works...
- If you use one modifier key in "First Modifier" and another in "Second Modifier", "Second Modifier" is ignored.

**Comment by youle31** [comment]
Could you follow this guide: https://github.com/UPBGE/upbge/wiki/Report-a-bug-guide to report a bug and join a test file. Thanks

**Comment by lordloki** [comment]
For this issue, there was a fix for upbge 0.2.5 branch but it has not been ported yet to current master branch. The solution will be ported but not inmeddiately

**Comment by lordloki** [comment]
Fixed in master. It will be available in the next build. Thanks for reporting. Closing

**Comment by denicolas** [comment]
That was quick, great, thanks!
