### ISSUE TITLE
some finds of text objects

### ISSUE THREAD

**Issue by undearstand** [UPBGE/upbge#1314]
hi all:

I reported a double byte character text issue before => https://github.com/UPBGE/upbge/issues/1156
and tested the latest UPBGE (Win64-2020-10-27) these days
there seems not to be too much improvement
but after seeing this post => https://github.com/UPBGE/upbge/issues/1297
I tried to use bpy to do what I wanted bge API to do before
then both players worked correctly ↓
![bpytest](https://user-images.githubusercontent.com/52462452/97719566-2fc11680-1b02-11eb-8d12-d83df47fda80.png)
if anyone else has need to use text objects with double byte characters in game
this might be a possible workaround to avoid the bge error

I also found a new issue during my testing process
it's when I change the content of text objects with Python at game runtime
↓ the older content will become translucent and stay on the screen (no matter using bpy or bge)
![gghost](https://user-images.githubusercontent.com/52462452/97719930-9f370600-1b02-11eb-9b70-0bde4cb01dc0.png)

thanks for your time :)

**Comment by lordloki** [comment]
If you do changes in game with bpy then you need to put this at the end of script:
`bge.logic.getCurrentScene().resetTaaSamples = True`

**Comment by undearstand** [comment]
oh, thanks for answering :D

btw, this code also worked in the bge sample I posted
are these two situations due to the same reason?
