### ISSUE TITLE
Bug report: Property Sensor > Value

### ISSUE THREAD

**Issue by denicolas** [UPBGE/upbge#1315]
In the Property Sensor, using the name of another property in the "Value" field doesn't work as expected. According to the manual (https://upbge-docs.readthedocs.io/en/latest/manual/logic/sensors/types/property.html), "The names of other properties can also be entered to compare properties."

Cf issue "Property Sensor run crazy in 0.2.4 #1045" (Closed).
Maybe it's the manual that needs to be fixed...

Version: UPBGE 0.30.0 Alpha (based on Blender 2.91.0 Alpha)
Hash: c1aa337362dc
Downloaded file: UPBGE-EEVEE-Linux64-2020-10-07.tar.xz
Test file: [test.zip](https://github.com/UPBGE/upbge/files/5467450/test.zip)

In the test file, "Suzanne" owns two Integer properties set to 0, "prop1" and "prop2".
The Property Sensor tests prop1 for equality with the value of prop2.
Launch the game with [P]: Suzanne doesn't move forward as she should...
Now in the "Value" field of the Property Sensor, replace "prop2" with its value (0).
Launch the game with [P]: Suzanne moves forward!

**Comment by youle31** [comment]
I guess that if someone wants to work on this he can check the SCA_PropertyActuator code which works with property names

**Comment by youle31** [comment]
Actually, I propose to remove that from the documentation to avoid work as we already have expression controllers

**Comment by lordloki** [comment]
Yes, better to modify documentation doing explicit use of expresion controllers for this thing

**Comment by lordloki** [comment]
Done.
![image](https://user-images.githubusercontent.com/1015605/97781480-00ef8280-1b8c-11eb-89a9-e01285ee390d.png)

**Comment by youle31** [comment]
Great! Thanks!

**Comment by denicolas** [comment]
Thanks!
