### ISSUE TITLE
0.3.0: Crash when exiting game with linked Collection

### ISSUE THREAD

**Issue by IzaZed** [UPBGE/upbge#1318]
Title says it all, I don't think it's necessary to provide a test file because you can just try to link any collection of any blend file into a new file and test it.

It happened with Instance Spawn active as well as inactive. The linked collections may be active or inactive as well, same result.
Does not happen with appended collections or instanced collections from the same file.

**Comment by youle31** [comment]
"Fixed" here: https://github.com/UPBGE/upbge/commit/1654417a53c52db7d9363c17f0e020e13b5773b0

**Comment by IzaZed** [comment]
Aw cool! That was fast! Why the quotation marks?

**Comment by youle31** [comment]
Because i don't know/understand all what can happen using linked collections... But the crash is fixed
