### ISSUE TITLE
Possible Broken Lamp Functions

### ISSUE THREAD

**Issue by AC-Panda** [UPBGE/upbge#1319]
Hi,
I was just going through all the ways to copy a lamp's 'energy-color' of a object's 'object-color'.
From the 4 ways that I state below, only the last 2 ways work.
Am I missing something crucial?
http://www.mediafire.com/file/rjuyjs2pmth04ax/Test_Zone.zip/file
```
import bge

def script(self):
        
#Function method
        self.owner.scene.objects["Lamp"].color.r = self.owner.color[0]
        self.owner.scene.objects["Lamp"].color.g = self.owner.color[1]
        self.owner.scene.objects["Lamp"].color.b = self.owner.color[2]
        
#Index method
        #self.owner.scene.objects["Lamp"].color[0] = self.owner.color[0]
        #self.owner.scene.objects["Lamp"].color[1] = self.owner.color[1]
        #self.owner.scene.objects["Lamp"].color[2] = self.owner.color[2]
        
#Absolute method (1)
        #self.owner.scene.objects["Lamp"].color = [1,0,0]
        
#Absolute method (2)
        #self.owner.scene.objects["Lamp"].color = [self.owner.color[0],self.owner.color[1],self.owner.color[2]]
```

**Comment by IzaZed** [comment]
In 0.3.0 you need to access the internal blender object of the lights

lamp = self.owner.scene.objects['Lamp']
light = lamp.blenderObject.data
light.energy = 10
bge.logic.getCurrentScene().resetTaaSamples = True

the resetTaaSamples should be done everytime something from the bpy module is used

**Comment by youle31** [comment]
Solved by @IzaZed . Thanks!

**Comment by AC-Panda** [comment]
Ah yes. But I was referring to legacy 0.2x 🙂

**Comment by BluePrintRandom** [comment]
You have to send a whole vector
It's a uniform

When you get a copy of it, it's not a pointer but a copy

**Comment by AC-Panda** [comment]
So your saying arg3 can't be assigned to arg4 correct?
Would list append()s be better you think.

**Comment by BluePrintRandom** [comment]
lamp.color is a vect3
Object.color is a vec4
