### ISSUE TITLE
UPBGE 2.5 ❗ occluder it is not working if it is invisible ❗

### ISSUE THREAD

**Issue by SyncOfHeroes** [UPBGE/upbge#1327]
.blend ⬎ 

https://pasteall.org/blend/0786ed6cae6c487288253ac7d3c7b751

-  version : upbge 2.5

**Comment by AC-Panda** [comment]
> UPBGE 2.5 ❗ occluder it is not working if it is invisible ❗

I noticed this bug too while recently using occluders.
The workaround I use is to have alpha/transparency for the occluder mesh set to 0, because it's technically still visible, just not in the normal way you'd expect.

**Comment by lordloki** [comment]
Fixed in 0.2.5 branch. A build will be available in next weeks when i release UPBGE 0.2.5b 

Thanks for reporting. Closing now.
