### ISSUE TITLE
Replace mesh actuator does not work. 0.3

### ISSUE THREAD

**Issue by srhighwizard** [UPBGE/upbge#1331]
The replace mesh actuator does not replace the mesh if the mesh owner object is not visible, and if it is not in the same spatial location as the target.

**Comment by youle31** [comment]
Can you provide a test file please?

**Comment by srhighwizard** [comment]
After I created an empty file, mesh replacement works,
it must be because my main project was migrated from 0.2.5,
however, unlike the old upbge, if the object has animation or materials, the new mesh does not replace that.
I intended to use it for something like changing skin for animated characters.
is attached

[replace.zip](https://github.com/UPBGE/upbge/files/5585845/replace.zip)

**Comment by BluePrintRandom** [comment]
many times appending your project 1 object at a time and porting it is a
good idea,

not everything works the same - many features have shifted locations etc,
as you do this you also learned what has changed.
