### ISSUE TITLE
Override hard limits on sliders

### ISSUE THREAD

**Issue by dirkse** [UPBGE/upbge#1333]
For games or simulations that use physics, I would like to set rigidbody elasticity to larger than 1. This would create a surface that accelerate a bouncing ball without additional logic. 
Using it to simulate increase in gas particle speed/temperature.

**Comment by youle31** [comment]
I found this about elasticity/restitution on the net:
![Capture](https://user-images.githubusercontent.com/10052509/100132992-7d713a80-2e86-11eb-9c2f-2e166af8fa7e.PNG)
here: https://www.raywenderlich.com/2606-bullet-physics-tutorial-getting-started

Why not... in blender, this is a variable named "reflect" in DNA_object_types/RNA_object.

I'm ok to change that for upbge 0.3. Are you using upbge0.3 or upbge0.2.5?

**Comment by dirkse** [comment]
I've just started using 0.2.5 but am happy to switch to 0.3.
Thanks, in the new Blender this can go above 1 if you type the value, but they do not have the bge...;(

**Comment by dirkse** [comment]
Found it on MEGA thanks...

**Comment by youle31** [comment]
Ok, I pushed this commit: https://github.com/UPBGE/upbge/commit/326ac57bb54aa013761e5a31a1bf8ed23d15f703 to allow to set elasticity to a value > 1.0.

This property "elasticity" seems the same thing as blender "Bounciness".

In the next upbge0.3 builds, it will be possible to set bge physics elasticity manually to a value > 1.0 as for blender physics bouciness...

**Comment by dirkse** [comment]
Thanks! much appreciated.

**Comment by dirkse** [comment]
If youv'e pushed it; does that mean the linux version on MEGA will be updated? or must I compile from the source here on Github?
Thanks again!

**Comment by youle31** [comment]
Lordloki (another developer) does builds regularly and uploads on his MEGA folder. I guess it will be available in nexts days.
