### ISSUE TITLE
Bug (upbge 0.3): standard HDRI does not work when emulated in standalone

### ISSUE THREAD

**Issue by SwanTheHunt** [UPBGE/upbge#1334]
since the last builds I noticed that the "standalone start" did not work with the hdri enabled. I thought it could be a bug, or just some function that has been disabled.

How it should work
![github](https://user-images.githubusercontent.com/70351880/100297187-e206c500-2f6c-11eb-9606-e866e45fcea2.jpeg)

Standalone:
![8594bdb4-5550-4a29-ac6e-ca6b56567459](https://user-images.githubusercontent.com/70351880/100297237-f9de4900-2f6c-11eb-932c-876081642086.jpg)

another problem, the standalone will only work if the Properties or Framerate debug is activated. Or else there will only be a black screen.

**Comment by youle31** [comment]
I can't reproduce the issue in this test file: 
https://pasteall.org/blend/ae842c1c12e2462e9b930ba924c2f819

It works for me both in embedded and standalone.

Could you join a test file please?

**Comment by SwanTheHunt** [comment]
Yes, the customized world works. What doesn't work is that. I believe that it must be implemented in the properties of the world making it accessible

![test](https://user-images.githubusercontent.com/70351880/100360189-5ece8900-2fd7-11eb-9d9b-97f1f072e551.jpeg)

**Comment by youle31** [comment]
It seems the shading is not correctly initialized when disabling this option (I'll try to find why later):

Waiting for that, you can use the script in this .blend to set the option manually:


https://pasteall.org/blend/b3936bed0cc545d291d68606306fc747

**Comment by youle31** [comment]
I  pushed this commit to solve shading issue in blenderplayer: https://github.com/UPBGE/upbge/commit/551ba94126b2a3f4daa71c988612734bbb136057

I hope this won't cause unexpected issues...

I can't reproduce the issue related to framerate enabled or not.
