### ISSUE TITLE
the execution of the cutscene video does not work in the upbge version 0.3 alpha

### ISSUE THREAD

**Issue by prometheus-systems** [UPBGE/upbge#1338]
the execution of the cutscene video does not work in the upbge version 0.3 alpha.

The code below exchanges the texture for the mp4 video, this works perfectly in version 0.25. But at 0.3 it doesn't happen.
######################################################
#
#    Movie.py        Blender 2.6
#
#    Tutorial for using Video.py can be found at
#
#    www.tutorialsforblender3d.com
#
#    Released under the Creative Commons Attribution 3.0 Unported License.	
#
#    If you use this code, please include this information header.
#
######################################################

#import bge
import bge

# get the current controller
controller = bge.logic.getCurrentController()

# get object script is attached to
obj = controller.owner

# check to see variable Video has been created
if "Video" in obj:
    
    # get video 
    video = obj["Video"]
    
    # update the video 
    video.refresh(True)
                        
# if variable Video hasn't been created
else:

    # get current scene
    scene = bge.logic.getCurrentScene()
    # get matID for the movie screen	
    matID = bge.texture.materialID(obj, 'MA'+obj['material'])
    #matID = 1
    
    
    

    # get the texture
    video = bge.texture.Texture(obj, matID)
    
    # get the name of the movie
    movieName = obj['movie']
    
    # get movie path
    movie = bge.logic.expandPath('//' + movieName)
    
    # get movie
    video.source = bge.texture.VideoFFmpeg(movie)
    obj['ID'] = video
    
    # set scaling
    video.source.scale = True	
    
    # save mirror as an object variable
    obj["Video"] = video
    
    # check for optional loop property
    if "loop" in obj:
        
        # loop it forever
        if obj['loop'] == True:
            video.source.repeat = -1
    
        # no looping
        else:
            video.source.repeat = 0

    # start the video
    video.source.play()

**Comment by youle31** [comment]
we need to call video.source.play() each frame
