### ISSUE TITLE
bge.logic.getCurrentScene().world.zenithColor needs 4 args, not 3. Propose world tab update.

### ISSUE THREAD

**Issue by AC-Panda** [UPBGE/upbge#1345]
Not sure if this is the right github area for this or I should use pull requests?
I propose updating the world tab 'zenith' setting to allow 4 args (R,G,B,A - A is sky-blend.) & not just 3 args (R,G,B)
Unless there's something I'm not getting ...

**Comment by lordloki** [comment]
Hi @AC-Panda 
In the next days - few weeks i will release the UPBGE 0.2.5b. This release will have several additional bugfixes and one or two tested features that I can use them for UPBGE 0.3 too.

After the UPBGE 0.2.5b I will work exclusively in UPBGE 0.3. Then i'm going to close this issue but i will put a "open" and "feature request" tags in case someone wants to develop them in the future.

Thanks for the feedback.
