### ISSUE TITLE
MouseLook acting weird UPBGE_0.2.5a_Rev5_Depth-Test3.7

### ISSUE THREAD

**Issue by NatGazer** [UPBGE/upbge#1352]
Basically when there are **two Mouse Look in two different objects**, and if both are triggered by the **same sensor**, when the the sensor returns False, only **one random Mouse Look gets deactivated**, and it is random, because sometimes one gets deactivated and then gets the other.

Here it is a file that shows that:

- One Mouse Look for the camera and the cube, both triggered by a keboard sendor (letter G):
[MouseLook_bug.zip](https://github.com/UPBGE/upbge/files/5702032/MouseLook_bug.zip)

**Comment by lordloki** [comment]
Fixed in 0.2.5 branch. Closing
