### ISSUE TITLE
having problems with standalone player

### ISSUE THREAD

**Issue by peticcio** [UPBGE/upbge#1356]
i have a project wich connects to a server.

i have tested it to 2 machines. (of my friends)
the first one is in italy (im also in italy)
the other one is in germany. 
when running the game in a packaged standalone.exe with all the files. theres a problem on the first machine. it works like a charm.
the second one it has really bad hiccups. (is sure its not a hardware issue because the first machine is worse than the second one)
by worse i mean worse specs.
also the internet connection of the second machine's location is way better than the first one.
so my question is. whats causing this? maybe a bad python env?
i cant find stuff by googling the problem sadly.
any kind of hint would be really helpful!
thanks. -peticcio

**Comment by lordloki** [comment]
Hi,
We need a blend to test where is the error (if any). Additionally, we dont have in current UPBGE an official method to do multiplayer and maybe the issue is not in upbge itself but it is difficult to say with the info supplied.

**Comment by peticcio** [comment]
> Hi,
> We need a blend to test where is the error (if any). Additionally, we dont have in current UPBGE an official method to do multiplayer and maybe the issue is not in upbge itself but it is difficult to say with the info supplied.

ill give the .blend right away

**Comment by peticcio** [comment]
> Hi,
> We need a blend to test where is the error (if any). Additionally, we dont have in current UPBGE an official method to do multiplayer and maybe the issue is not in upbge itself but it is difficult to say with the info supplied.

https://we.tl/t-L5vWrf8grj (.blend link)

**Comment by lordloki** [comment]
I played but i didn't see any issue. Both players (id = 1 or id = 2) can move. 
The only minor issue I saw is that when you finish the game the threading is executing and it calls to getCurrentScene() when the module doesn't already have access to this function as the game is stopped.

**Comment by peticcio** [comment]
> I played but i didn't see any issue. Both players (id = 1 or id = 2) can move.
> The only minor issue I saw is that when you finish the game the threading is executing and it calls to getCurrentScene() when the module doesn't already have access to this function as the game is stopped.
> 
> Maybe, iIt is possible that it is a issue with threading use.

i have 2 questions. is there a way to make code wich is unbinded from the frame render? and second is there a way to enable occluder in the 0.3 version of upbge?

**Comment by lordloki** [comment]
You can control your own game loop using python as in this tutorial: https://pymove3d.readthedocs.io/en/latest/stations/blender-game-engine/c_mainloop.html
This way you can execute the render phase only when you want.

Occluder doesn't work for 0.3.

I close the report. Thanks for reporting
