### ISSUE TITLE
0.3: Speaker Objects (this has no priority)

### ISSUE THREAD

**Issue by IzaZed** [UPBGE/upbge#1357]
I wanted to ask if it was possible to initialize Speaker-type objects in the game engine, simply because it would allow for clean scene setups - not talking about special behavior at all, basically initialize them as empty maybe?
I don't know enough about the game engine transition.

This really has no priority in my opinion, I just tought I'd leave it here

**Comment by youle31** [comment]
Hi, yeah, i guess we could "convert" speakers as empties. But I have no idea about how it is used and what would be the interest compared to any other object with a sound actuator. Could you tell us a/some usecase(s) where it would be useful?

**Comment by IzaZed** [comment]
Actually it's simply for having an object type **inteded** to be used as a speaker, there's absolutely no urgent need for it though.

If you have a lot of 3D Sounds in a scene, you may want to be able to identify your speakers visually, that's my thought, since now I often use the "Cone"-empty, as it looks a bit like a speaker

**Comment by youle31** [comment]
Ok, it is for visually purpose only then if I understand.

I mark this thread as feature request and move it into dicussions (with lordloki we agree to keep only real bugs into issues section)
