### ISSUE TITLE
Action Blending wrong behavior when using logic blocks

### ISSUE THREAD

**Issue by ChengduLittleA** [UPBGE/upbge#1359]
I'm using UpBGE 0.3.

The action blending does not work as expected. Demo file provided. I've set up 2 keys for activating two actions, one is scale, one is move, by pressing the keys sequentially, you should be able to view the animation blend together.

- Expected: Animation appears sequentially.
- Got: Animation appears but the frame appears to be starting with the earlier animation rather than starting on its own time, resulting a jump.

To test:

- press space bar alone, the brick moves upwards.
- press w key along, the brick scales up.
- press space bar, while the brick is moving, press w key, you can see it jumps back. To me it looks like a timing issue.

In UpBGE 0.25 it works as expected as two animations blends together without any hitches.

[Here's the test blend file](https://pasteall.org/blend/1978bc137d02441099cf6cfdc16c699e)

**Comment by youle31** [comment]
Hi, could you provide the 0.2.5 file, like that we'll be abled to see the difference when opened in 0.3

**Comment by lordloki** [comment]
Here is the blend for 0.2.5: 
[action_blending_bug_0.2.5.blend.zip](https://github.com/UPBGE/upbge/files/5741695/action_blending_bug_0.2.5.blend.zip)

**Comment by youle31** [comment]
The upbge 0.3 behaviour is the same than the behaviour we had in upbge 0.2.3.

I can't be 100% sure, but I think the behaviour changed with a commits serie by panzergame near 27/28/29 december 2017 (after 0.2.3 release)

![Capture](https://user-images.githubusercontent.com/10052509/103140166-b7329c80-46e3-11eb-89e0-200fd18eddcb.PNG)

I think the commits to cherry-pick should be:

95774a19cbef9ad4f98219d4bbf18f832a6a9d9a
a972f04fbf66590c922346491b813f074acf4d9b
ad70ea45a0ec80b283cd8b5e1bf0d1a87b2fb5fc
7dfc5e21e7382ff50442f0563c3df6e4915b6a20
a8d9f4069bf14b7225f9eafce4b884a44e5aec3c
0ba4f915b1b5abdbac66cef5c40bf2c4c540ea40
6d876f11f507638111e64ef3021dd5b1df852fdc
3c8e4c45b93935a25949382cc9ad24c0ebe905b3
bfebcec9bb0900ceae513f47016da4e7e1f96cbf
6141fa37a9c031c16269e19c4aeaaa47a987a8e6
ab74372ecc8618169ad4f33154a62664fe33a83e
cf4845819140ea00e64ee71e88f73ca0546410d6
863d1ce9e6e3dbd6fca09e74f33f2efa3b6251aa
c0d24cff49fe3db82f4ef297e22ae87a6608978b
986e236810468738525a81f7905f28563216e096
06e8f2ab57690adcddcb65fd56d9bcc67860a891
96567f26f82cb64e240857d3070d5a015904d9d2
096e566ef25f36369f26a448ca4d54601bd60b19

But i'm not even sure it will fix the bug and it will require patience and time to recover all of that (considering that mathfu was used and other potential conflicts)

On a side note, i don't remember what i wanted to say... I'll edit when i'll remember

**Comment by youle31** [comment]
I'll do a bisect tomorrow (it seems it isn't these commits which fix the issue)

**Comment by youle31** [comment]
The first commit with the 0.2.5 behaviour with this file is: 8df1a7249d9441190c2cd822b7bac6d7d4a98f11

**Comment by lordloki** [comment]
Ok, then I will move all the commit that you pointed in a branch and after the last one to check if we can adapt all those commits.

**Comment by youle31** [comment]
@lordloki : As you want but I tried and it's a big pain +  I pushed a potential simple fix but I need to test
