### ISSUE TITLE
bge.render.setGLSLMaterialSetting() doesn't revert settings when game-player is ended.

### ISSUE THREAD

**Issue by AC-Panda** [UPBGE/upbge#1360]
Hi,
```
bge.render.setGLSLMaterialSetting()
```
Whenever you turn-on/turn-off a graphics setting with the function Blender doesn't revert the option to what value it was on init of run-time.

**Comment by youle31** [comment]
Fixed here: https://github.com/UPBGE/upbge/commit/fdae06d12db255c6664ac705596192d7f5c13576

**Comment by BluePrintRandom** [comment]
Wow that was fast!!

**Comment by AC-Panda** [comment]
Uh. The reverting fix works for all settings except <kbd>Environment Lighting</kbd>. Sorry, didn't catch that earlier.

Bug happens whether environment lighting is turned on/off.

_Tested with startup blend / empty scene._
