### ISSUE TITLE
upbge0.3 does not have any ability to support external special effects

### ISSUE THREAD

**Issue by 2655251820** [UPBGE/upbge#1362]
There is no particle effect, no picture playback ability. From some aspects, I think that upbge does not have any ability to support game special effects, but it is too limited to use material nodes to create special effects. It is extremely unfriendly to external game special effects.

https://user-images.githubusercontent.com/38093850/103189689-d4948000-4908-11eb-82a9-ed0ab1100129.mp4

**Comment by 2655251820** [comment]
I just want a game that can support playing video files such as MP4 in the game, so as to support the playing of external special effect files, making the game special effect production easier.

**Comment by 2655251820** [comment]
I just suggest, because the special effects of the game need such a node, but it can not support video animation?
I just want this effect, but I tried various settings for two days, but there is no way. There is no particle effect and no picture playback ability. From some aspects, I think that upbge does not have the ability to support game special effects.

**Comment by youle31** [comment]
- About video playing, you can do that with a script: https://pasteall.org/blend/8b8cf4831e2040eca0baeb9824d3cf6f (needs a video named a.avi in the same folder than the .blend)
- About "special effects", i guess you are talking about material actions. These actions can be played with an action actuator (logic bricks)
