### ISSUE TITLE
addObject function not working with Collection neither with Instanced collection

### ISSUE THREAD

**Issue by begbarros** [UPBGE/upbge#1364]
Hi,
is there a way to spawn a collection or an instanced collection via logic bricks (Edit Object->Add Object actuator) or via python (scene.addObject()) in upbge 0.3 ?

**Comment by BluePrintRandom** [comment]
add a group instance to the scene before starting the game and hide it.

added = own.scene.addObject('Instance_name',object, life)

**Comment by youle31** [comment]
Spawn entire collections could be an option to add to collection actuator, but it is not implemented yet.

**Comment by youle31** [comment]
I move this to discussions as it is more apparented to a feature request.
