### ISSUE TITLE
scene.addObject() not working with collection instances

### ISSUE THREAD

**Issue by begbarros** [UPBGE/upbge#1366]
I created an object inside a collection, instanciated it in the scene and put it inside another collection, hid it, and tried to add via python using scene.addObject(obj,ref,time). The error message is:  "KX_Scene (first argument): object must be in an inactive layer"
[InstanceAdder.zip](https://github.com/UPBGE/upbge/files/5749384/InstanceAdder.zip)

**Comment by youle31** [comment]
It's not like that we add an object in upbge0.3, it's like blueprintrandom explained in the other thread
