### ISSUE TITLE
Normals are not updated with shape key animations

### ISSUE THREAD

**Issue by Luckykov** [UPBGE/upbge#1368]
Hello, I'm not the best with English, but I will try to be as readable as possible. Well, I love the engine and I hope you are still supporting it. I found an error recently, which I'm not sure if it is in fact a program error, or I'm skipping some step. I tried to use a technique I was testing, to use the ocean modifier, write it in .MDD and then import it again. to have a mesh with wave simulation. .MDD records animations in shapekeys. but in UPBGE when I put an animation of shapekeys to work, the system does not update the normal coordinates of the object. leaving strange lighting. if possible I will leave a photo of the simplified event happening.
Note: The tests were performed on UPBGEv0.2.5a-b2.79 and UPBGEv0.2.4-b2.79. both x64
![image](https://user-images.githubusercontent.com/76780938/103356106-c6706c00-4a8e-11eb-98b9-241c0780ca49.png)
![image](https://user-images.githubusercontent.com/76780938/103356116-cec8a700-4a8e-11eb-8651-749a1190bcb5.png)

**Comment by youle31** [comment]
I confirm there's a bug.

This patch: 

[p.zip](https://github.com/UPBGE/upbge/files/5756467/p.zip)

works with this file:

[shapekeyAction.zip](https://github.com/UPBGE/upbge/files/5756469/shapekeyAction.zip)

to update normals during shapekeys action. But idk if RecalcNormals should be called every time at this place or not

**Comment by lordloki** [comment]
Yes, the patch is way that the code was before. I think we can use the patch because i didn't see any crash or issue related to this

**Comment by lordloki** [comment]
Fixed in 0.2.5 branch. Closing
