### ISSUE TITLE
mouse look issue ?

### ISSUE THREAD

**Issue by mhreez** [UPBGE/upbge#1372]
mouse look in v 2020-12-16 it is working good but in v 2021-01-02 didnt work the direction ( wrong )
I opend the file in 2 version 

https://user-images.githubusercontent.com/55386433/103490681-2e73d900-4e26-11eb-85b0-ff0f4dc9d72c.mp4

**Comment by lordloki** [comment]
Closing this report here. I just open the issue in the UPBGE Logic Nodes github (https://github.com/IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes/issues/39). Thanks for reporting
