### ISSUE TITLE
Will upbge have a GPU particle system?

### ISSUE THREAD

**Issue by 2655251820** [UPBGE/upbge#1375]
Under the game engine made by Sabge, there are many supplementary functions that are currently insufficient in Upbge, especially the GPU particle system. Of course, some people have successfully made particle systems https://hamisertcan.com/2020/06/03/upbge-icin-parcacik-sistemi/
Maybe it will help. I like upbge to solve game problems with simple logic. I also learned the code for two days to solve the key frame setting of the picture animation for me. But I have to say that it is really painful for people whose native language is not English.
Can we see the particle system in the official version 0.3?
And sprite animation system

**Comment by lordloki** [comment]
Hi,

For this feature we will use the scheduled new particle nodes for Blender. It seems faster than previously system (even was said that it is going accelerated by gpu). Then there is no need to duplicate efforts here. I think it will be released in this year.

Thanks for the feedback. Closing the issue.

**Comment by BluePrintRandom** [comment]
so basically we have 'use vertex to create instances' in a object menu tab
- we are missing 'billboard' facing then the this could be considered a
particle system.

'marching' these particles involves a raycast per particle to have physics
interaction,
I could outline the script in py for you loki.

**Comment by lordloki** [comment]
Yes, if you have a basic script we can orient the users in the documentation
