### ISSUE TITLE
0.3.0 parent losing/strange beahviour on scene restart

### ISSUE THREAD

**Issue by ExcaliburGO** [UPBGE/upbge#1377]
I noticed that in UPBGE 3.0, something strange is happening if you restart the scene and some objects have already moved. Especially the parented ones are affected, they get some strange rotation and location. Adding a parent actuator on start sometimes solves it, but not always. Here is the demo file to show you what's happening:
[bug.zip](https://github.com/UPBGE/upbge/files/5780270/bug.zip)
There is an object with 2 children, controlled by mouse and keyboard (WASD), you can restart the scene by pressing X.

**Comment by youle31** [comment]
Fixed in  69d4c24 . Thanks for report

**Comment by youle31** [comment]
My commit doesn't handle the case where original kxobjects are removed during runtime then I reopen the issue.

test file: 
[bug.zip](https://github.com/UPBGE/upbge/files/5784198/bug.zip)

**Comment by ExcaliburGO** [comment]
I just tested the restore_obmat branch and it is solved, thanks, I will be using it until it's done properly and merged into master.

**Comment by youle31** [comment]
Merged, Thanks again for report, i hope this will fix all potential parent issues at scene exit...
