### ISSUE TITLE
I need a Property Sensor and Actuator that can compare 2 variables

### ISSUE THREAD

**Issue by UglinessInTheUI** [UPBGE/upbge#1395]
Right now the Property Sensor is only allowing me to compare a Variable with a hard coded fixed value.
It's not allowing me to compare one variable with another variable.
Can you guys fix it ?

**Comment by lordloki** [comment]
The expresion controller can compare variables. https://upbge.org/manual/manual/logic/controllers/types/expression.html

https://blenderartists.org/t/comparing-properties/646470/3
![image](https://user-images.githubusercontent.com/1015605/106959017-69756f00-673a-11eb-951c-009d261cd40f.png)
![image](https://user-images.githubusercontent.com/1015605/106958988-624e6100-673a-11eb-8cc2-882abe188409.png)

Closing the issue as it can be done with current controller. Thanks for reporting

**Comment by UglinessInTheUI** [comment]
Thanks. That seem to work but it would be nice to have a modified Property Sensor that can do all that without so many complications. Can it be done in the source code ? Let's say I want to clone the Property Sensor and name it something else and to add that function to the new cloned version.

**Comment by lordloki** [comment]
> Thanks. That seem to work but it would be nice to have a modified Property Sensor that can do all that without so many complications. Can it be done in the source code ?

The problem with that solution is it would be so specific to your case because what happen if another user wants to compare between 3 properties or 4 or 5...
The expression controller was created to do those simple comparisons and another things more complicated.

**Comment by UglinessInTheUI** [comment]
Actually I need a Property Sensor that can check if the current number in a specific variable equals 1 or 5 or 9 or 13. That would be the first beat in every Bar. And I just noticed that the timer property is all broken. Should I open a new thread for that timer bug ?

**Comment by UglinessInTheUI** [comment]
Here is a timer bug. I changed the refresh rate and FPS and it broke. The timer is now counting something else but not seconds.



     On Friday, February 5, 2021, 01:26:25 AM MST, lordloki <notifications@github.com> wrote:  
 
 



Thanks. That seem to work but it would be nice to have a modified Property Sensor that can do all that without so many complications. Can it be done in the source code ?


The problem with that solution is it would be so specific to your case because what happen if another user wants to compare between 3 properties or 4 or 5...
The expression controller was created to do those simple comparisons and another things more complicated.
