### ISSUE TITLE
MacOS builds outdated?

### ISSUE THREAD

**Issue by ExcaliburGO** [UPBGE/upbge#1401]
Yesterday I downloaded the "UPBGE-EEVEE-MacOS-2021-02-07.dmg" file from the MEGA share and I was so surprised that it was based on Blender 2.83. Also, I noticed that the issue with not restoring the parent on scene restart (I opened an issue and it got fixed 2 months ago) still persists, so it seems like the MacOS builds are somehow outdated. Today I managed to build the latest UPBGE (with some errors though on make update, but it passed and works) so why don't you put the current builds instead of the old ones?

**Comment by lordloki** [comment]
Yeah, I did the build from another machine and I didn't test. I have just uploaded a new up to date build.

Thanks for reporting. Closing the issue
