### ISSUE TITLE
Game displayed on quarter view on MacOS

### ISSUE THREAD

**Issue by ExcaliburGO** [UPBGE/upbge#1402]
Whenever I press "Standalone start" or open my game in Blenderplayer on Mac, this happens:
<img width="1440" alt="Zrzut ekranu 2021-02-10 o 12 55 31" src="https://user-images.githubusercontent.com/26136688/107507177-7ad9d380-6b9f-11eb-92d0-6c820c1f7f59.png">
It happens in both fulscreen and windowed view, in any resolution. Image is displayed only at the lower left corner of the display, whereas the mouse is captured on the whole window - I had to navigate my mouse to the black background on the right in order to click the button.
It is not a problem with my game file, as the same happens on the default file:
<img width="1440" alt="Zrzut ekranu 2021-02-10 o 13 02 42" src="https://user-images.githubusercontent.com/26136688/107507736-4b779680-6ba0-11eb-8cbf-e5ece91a4034.png">

It is the same for both UPBGE-EEVEE-MacOS-2021-02-07.dmg (2.83) and the current master, built today by me.

I heard that it's a problem with Mac's hidpi on Retina displays and that Adobe Flash also had this kind of problem (I've personally never experienced it myself).

EDIT: On the same Mac, both official blender-2.79b and latest UPBGE 0.2.5 release work well.

**Comment by youle31** [comment]
Hi, i've no macos machine to test but I pushed a branch which could possibly fix the display issue:

https://github.com/UPBGE/upbge/commit/a0683c3c3408a70c3b62a89b624874e4baffb0a9

the branch is named macos_scale_issue.

Could you test it to see if it solves your issue?

parenthesis: you need to checkout the branch, then build it:

git checkout macos_scale_issue

then build.

to go back to master you need to do:

git checkout master

**Comment by ExcaliburGO** [comment]
Alright, I'm downloading the repo right now.

**Comment by ExcaliburGO** [comment]
Unfortunately, nothing has really changed.

**Comment by youle31** [comment]
Ok, Thanks for testing. For now, neither lordloki, neither me can reproduce the issue, then we can't solve it.
Idk if the solution is in wm_window.c, it's possible...

**Comment by ExcaliburGO** [comment]
If it helps, I can give you all the mem dumps, debug info and stuff like that... just tell me how to do it.

**Comment by lordloki** [comment]
Maybe we can use this patch as guide. https://developer.blender.org/D9837

**Comment by youle31** [comment]
Ah, yes, nice catch, it sounds similar issue

**Comment by lordloki** [comment]
@ExcaliburGO could you update the branch and compile again?
I just committed a possible fix. Thanks in advance

**Comment by ExcaliburGO** [comment]
Ok, I will do it tomorrow, do I have to git checkout anything or just make update && make?

**Comment by BluePrintRandom** [comment]
Make update also does git pull I think

**Comment by youle31** [comment]
if you are on master you need to do:

git checkout macos_scale_issue
git pull

then build.

Then to go back on master:

git checkout master

**Comment by ExcaliburGO** [comment]
Still nothing...
<img width="192" alt="obraz" src="https://user-images.githubusercontent.com/26136688/107612060-add6a280-6c45-11eb-8d26-d7bb190fd9f8.png">
<img width="1440" alt="obraz" src="https://user-images.githubusercontent.com/26136688/107612104-cba40780-6c45-11eb-8d1a-a288486dac11.png">

**Comment by lordloki** [comment]
Could you update & build again?

I just commit another try. NOTE: This can not be the final solution. We are only trying to find something that works to focuse in that direction.

**Comment by ExcaliburGO** [comment]
I'm having a build error right now, probably connected to python, as I saw svn downloading python 3.9.
```
Configuring Blender in "/Users/asystenta/blender-git/build_darwin" ...
-- Detected OS X 11.1 and Xcode 12.4 at /Applications/Xcode.app
-- OSX_SYSROOT_PREFIX: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
-- Detected OSX_SYSROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk
CMake Error at build_files/cmake/platform/platform_apple.cmake:164 (message):
  Python executable missing:
  /Users/asystenta/blender-git/upbge/../lib/darwin/python/bin/python3.7m
Call Stack (most recent call first):
  CMakeLists.txt:1023 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/asystenta/blender-git/build_darwin/CMakeFiles/CMakeOutput.log".
See also "/Users/asystenta/blender-git/build_darwin/CMakeFiles/CMakeError.log".
make: *** [all] Error 1
```

**Comment by lordloki** [comment]
Meanwhile, the python3.9 transition is done I have uploaded a build with the last fix: https://mega.nz/file/llslkS5A#UJirR0DAvQ-gM4Y-pn_nPCrBO3Hsid1rj1Q44TmZY-o

Could you test it? Thanks in advance

**Comment by ExcaliburGO** [comment]
Still nothing has changed. Here is the console log from running blenderplayer:
```
asystenta@MacBook-Pro-Krzysztof MacOS % ./Blenderplayer ~/Desktop/game2.blend 
BLT_lang_init: 'locale' data path for translations not found, continuing
2021-02-11 23:00:07.518 Blenderplayer[9370:332003] not in fullscreen state
GL_VENDOR: Intel Inc.
GL_RENDERER: Intel Iris Pro OpenGL Engine
GL_VERSION: 4.1 INTEL-16.1.7
GL_SHADING_LANGUAGE_VERSION: 4.10
Supported Extensions...
 GL_ARB_shader_objects supported?       no.
 GL_ARB_geometry_shader4 supported?     no.
 GL_ARB_vertex_shader supported?        no.
 GL_ARB_fragment_shader supported?      no.
 GL_ARB_texture_cube_map supported?     no.
 GL_ARB_multitexture supported?         no.
 GL_ARB_texture_env_combine supported?  no.
 GL_ARB_draw_instanced supported?  no.
Error: totblock: 1
```

**Comment by youle31** [comment]
Actually, i was thinking... From what we can see in the pictures, the window size sounds ok but there's an issue with what is inside the window.

Does it work when you check "use viewport render" in render options, then press standalone start?

**Comment by lordloki** [comment]
I think that the window size is the double what it should be. Searching it seems the common resolution for retina hidpi display is 2880*1800. The player initial resolution is 1280*720. 
Then viewing the screenshot it seems that the inner imagen is at 1280*720 but the window size is at double.

I just pushed a new branch inline with master and python3.9. Also I uploaded a build in MEGA (form today)

Could you downlaod and test. We are interested in the values showed in the imagen below. Also a screenshot of the desktop + the blenderplayer.

![image](https://user-images.githubusercontent.com/1015605/107735079-28afc400-6cff-11eb-97c9-6d28339a8bdb.png)

Thanks for your help.

**Comment by ExcaliburGO** [comment]
Viewport render doesn't really change anything. I noticed that the window size changed now, but the content is still in only one quarter:
<img width="1440" alt="Zrzut ekranu 2021-02-12 o 08 45 20" src="https://user-images.githubusercontent.com/26136688/107742186-dd051680-6d0e-11eb-9c2f-6f7b56492892.png">

**Comment by lordloki** [comment]
Ah, ok. Thanks.
Then the size of the window is fixed now. We need to find where to multiply by 2 the size (width & height) of the inner content.

**Comment by ExcaliburGO** [comment]
Well, that's the main problem - I don't actually care about the window being twice the size it should be (mainly because I want to launch the game in fullscreen) but the player in only one quarter of the window is indeed a problem.

**Comment by youle31** [comment]
As you said that upbge 0.2.5 was working for you but not upbge 0.3, i was wondering if doing this:

![Capture](https://user-images.githubusercontent.com/10052509/107763562-1cdbf600-6d2f-11eb-9547-c95b3daa541e.PNG)

in GHOST_ContextWGL.cpp in master would fix the issue for you in master?

**Comment by ExcaliburGO** [comment]
Alright, so I have to checkout the master branch and make changes to reflect your screenshot, right?

**Comment by youle31** [comment]
yes

git checkout master

Then in the sources, find this file and edit it. Save. Then build. See if it changed something.

To reset the changes in master you can do:

git reset --hard

Then build.

**Comment by ExcaliburGO** [comment]
I did it, unfortunately still no luck - the window is twice the size it should be with its contents 2 times smaller than it should be.
<img width="1440" alt="Zrzut ekranu 2021-02-12 o 16 32 43" src="https://user-images.githubusercontent.com/26136688/107787854-f2e6fb80-6d4f-11eb-9024-c241a49e925a.png">

**Comment by lordloki** [comment]
Ok, I simulated :-)  https://pasteall.org/QeP7
![image](https://user-images.githubusercontent.com/1015605/107794950-5ecd6200-6d58-11eb-8210-462cf08bb81a.png)

**Comment by ExcaliburGO** [comment]
Nice. But did you simulate it completely? You should check how the mouse works.

**Comment by lordloki** [comment]
I just uploaded a new build (rev2) to MEGA. Surely the mouse doesn't work correctly.

**Comment by ExcaliburGO** [comment]
It works!
<img width="1440" alt="obraz" src="https://user-images.githubusercontent.com/26136688/107825720-e9778680-6d83-11eb-8d47-7347c77fdbf1.png">
Mouse seems to be scaled 2 times (my mouse was where I placed the black mark) and when I move the window, it shifts.

**Comment by lordloki** [comment]
Hi, I pushed a solution for mouse in the branch macos_scale_issue3 (i think it will work) but, at this moment, due to current update to python 3.9 I can not compile a build with my current environment.
I have in both compilation computer installed mac os high sierra but with python 3.9 it needs, at least, mac os mojave (10.14.4)
I will investigate how can update my environments.

**Comment by ExcaliburGO** [comment]
I built it, it works, however the camera seems to shake a lot in menus. I'll provide you with a video and a demo file in a moment.

**Comment by ExcaliburGO** [comment]
This is how the camera shakes:
https://user-images.githubusercontent.com/26136688/107891749-ebc31780-6f20-11eb-93ec-3f0c823817b7.mp4
On master branch, no issue at all.
Demo file:
[shaky.blend.zip](https://github.com/UPBGE/upbge/files/5978687/shaky.blend.zip)
(don't worry about it crashing when you click play)

**Comment by youle31** [comment]
This shaking is due to recent blender render code changes (eevee changes by blender coders) but not to lordloki patch. Lordloki patch itself seems to work fine. For the shaking issue, i guess blender coders will fix that in next weeks (they just commited big changes which makes the drawing (at least in realtime) unstable/shaky)

**Comment by youle31** [comment]
I pushed a temp fix for shaky camera because it's an annoying issue: https://github.com/UPBGE/upbge/commit/e74f476c3ed50c7203f6e29cb8720d2f7155b704

knowing that it might cause troubles about the bug mentionned just below about EEVEE_screen_raytrace_init

**Comment by ExcaliburGO** [comment]
Ok, if so, then I'd consider this fixed. Thank you so much!
