### ISSUE TITLE
LibFree not working

### ISSUE THREAD

**Issue by zacksamzacksam** [UPBGE/upbge#1412]
Writing a dynamic scene loader and for whatever reason libfree is not working at all, it works in other sections of the code just not the section I need it to work in. This is in 2.5a upbge and this is just a script attached to a camera always controller with 12 blend files in the same directory. Each blend file has a mesh and that mesh is parented to an empty object. The empty object has the same name as the blend file.

from bge import logic, events

co = logic.getCurrentController()
cameraObj = co.owner
scene = logic.getCurrentScene()
xNeighbors = [-1,0,1,-1,0,1,-1,0,1]
yNeighbors = [-1,-1,-1,0,0,0,1,1,1]
    
def keyHit(key_code): 
    
    status = logic.keyboard.events[key_code]
    
    return status == logic.KX_INPUT_ACTIVE
    
    
def loadChunks(curr):
    chunksToLoad = []
    chunkNeighborsX = []
    chunkNeighborsY = []
    chunksToRemove = []
    currX = curr % 3
    currY = int(curr/3)
    loopIndex = -1
    
    for x in xNeighbors:
        loopIndex += 1
        index = (currX + xNeighbors[loopIndex]) + 3 * (yNeighbors[loopIndex] + currY)+1
        checkX = currX + xNeighbors[loopIndex]
        checkY = currY + yNeighbors[loopIndex]
        if (checkX > 3):
            continue
        if (checkX < 0):
            continue
        if (checkY > 4):
            continue
        if (checkY < 0):
            continue
        chunksToLoad.append(index)
        chunkNeighborsX.append(xNeighbors[loopIndex])
        chunkNeighborsY.append(yNeighbors[loopIndex])
        
    # check scene for the empty object associated with that blend file, if it
    # exists, then there is no need to load the blend file and it can be skipped 
    # when loading the blend files
    

    
    for object in scene.objects:
        libToFree = 0
        loopIndex = 0
        for x in chunksToLoad:
            if (object.name == 'chunk0' + str(x)):
                #blend file that needs to be opened has already been opened
                chunksToLoad.remove(x)
                chunkNeighborsX.pop(loopIndex)
                chunkNeighborsY.pop(loopIndex)
                libToFree = 1
            loopIndex += 1
        if (libToFree == 0):
            if ('chunk0' in object.name):
               logic.LibFree('//' + object.name + '.blend')
                
    loopIndex = 0
    print(chunksToLoad)
    print(chunkNeighborsX)
    print(chunkNeighborsY)
    for x in chunksToLoad:
        try:
            logic.LibLoad('//chunk0' + str(x) + '.blend','Scene')
        except:
            continue
        
        chunkContents=scene.objects['chunk0'+str(x)]
        chunkContents.localPosition[0] += chunkNeighborsX[loopIndex]*16
        chunkContents.localPosition[1] += chunkNeighborsY[loopIndex]*16
        loopIndex += 1
    
def main():
    
    chunkSize = 16
    chunkChange = 0
    
    if (cameraObj['initState'] == 0):
        loadChunks(0)
        cameraObj['initState'] = 1
    
    if (keyHit(events.AKEY)):
        cameraObj['y'] = cameraObj['y'] + 0.1
        for object in scene.objects:
            if (object.name != 'Camera'):
                object.localPosition[1] = object.localPosition[1] - 0.1
    
    y = cameraObj['y']
    x = cameraObj['x']
    currChunk = cameraObj['currChunk']
    checkChunk = int((y)/16) * 3 + int((x)/16) + 1
    
    if (currChunk != checkChunk):
        cameraObj['currChunk'] = checkChunk
        loadChunks(checkChunk - 1)

        
main()

**Comment by zacksamzacksam** [comment]
Nevermind I got LibFree to work by putting expandpath before the filename, have no clue why it worked

**Comment by youle31** [comment]
Alright, if it is working, i close the report.
It's always goos to normalize pathes with bge.logic.expandPath, it can solve problems lik working in embedded but not in blenderplayer, working on windows but not on linux...
