### ISSUE TITLE
UPBGE0.3 Jagged edges appear when rigid bodies move

### ISSUE THREAD

**Issue by FengQuanLi** [UPBGE/upbge#1414]
UPBGE0.3

Jagged edges appear when the rigid body is moving, but they become normal when the rigid body is stationary for a period of time.
As shown in the figure below:
![Serrated_edges](https://user-images.githubusercontent.com/57764986/108675876-56c4ad80-7522-11eb-80df-3f54690a2f28.jpg)

At the same time, I also uploaded the blend file with this problem
[untitled3.zip](https://github.com/UPBGE/upbge/files/6020155/untitled3.zip)
Thank you very much for your work.

**Comment by youle31** [comment]
We are almost not working on render, we are just usig eevee render as it is. The antialiasing doesn't work well when objects are moving, in some cases.

It can sometimes be mitigated when you enable SMAA (smart antialiasing) or adapting the scene to have a better result.

We're aware of these aliasing issues and maybe one day we'll find the solution, but for now, i close the report as it is something we're aware about and as it is not our priority for now.
