### ISSUE TITLE
Problem in Relations Extras > Slow Parent - UPBGE 0.2.5

### ISSUE THREAD

**Issue by sam-mahonri** [UPBGE/upbge#1415]
Problem in (Properties > Object > Relations Extras > Slow Parent)
When using Slow Parent and starting the game, the object always starts at the center of the scene until the original position, and does not start at its original position, this bug does not exist in the Official BGE.

FILE: [problem.zip](https://github.com/UPBGE/upbge/files/6023818/problem.zip)
VIDEO: https://user-images.githubusercontent.com/64850697/108743989-2e37b600-7518-11eb-980c-7a01831210ae.mp4

**Comment by youle31** [comment]
I confirm the bug.
This solves the issue:
[p.zip](https://github.com/UPBGE/upbge/files/6027029/p.zip)

However, I think there are no more upbge 0.2.5 developers.

**Comment by sam-mahonri** [comment]
Thanks!

**Comment by youle31** [comment]
I leave the issue opened if there are guys who want to rework on upbge 0.2.5 development

**Comment by sam-mahonri** [comment]
Okay, to review the problems in UPBGE 0.2.5.

**Comment by lordloki** [comment]
It is committed in the 0.2.5 branch. There is a new build available with the fix included https://mega.nz/file/s40m0YCL#c86lAFlymScZJg99HCZZEqWq6j3u5Xv12QKRIBfZu_M

Thank @youle31 for the fix. Closing the report.
