### ISSUE TITLE
Actuators > Visibility > "Visible" checkbox: tooltip correction

### ISSUE THREAD

**Issue by denicolas** [UPBGE/upbge#1416]
UPBGE 0.30.0 Alpha

Tooltip:
"Set the objects visible (initialized from the object render restriction toggle in physics button)."
should be something like:
"Set the object visible (initialized from the Renders checkbox, in Object Properties > Visibility panel)."

**Comment by youle31** [comment]
Fixed here: https://github.com/UPBGE/upbge/commit/12cfa2e81abed9dfa38785e959ae46c98904948d

Thanks for the report. And for the many other reports on upbge documentation gihub.
