### ISSUE TITLE
why in upbge youtube channel there are no new video

### ISSUE THREAD

**Issue by Shahed002** [UPBGE/upbge#1421]
we are new. in YouTube hasn't any good or new video about upbge. then how we learn upbge. because we are beginner. Please continue upbge youtube channel. 
thank you.

**Comment by lordloki** [comment]
At this moment we are reworking the UPBGE Manual (updating from blender 2.79 or upbge0.2.5) to put it inline with upbge 0.3.
When it is finished we evaluate if we can complete it with several videos from youtube channels.

Thanks for the feedback. Closing the issue
