### ISSUE TITLE
Blender Crashes when switching scene 

### ISSUE THREAD

**Issue by Rocketgmpt** [UPBGE/upbge#1423]
First time experience an issue so ill try my best to to provide  files required to obtain help on the situation.

 look at the logic brick 
![image](https://user-images.githubusercontent.com/41500319/110191525-d42bd000-7df6-11eb-9cf9-463b3f18e85a.png)

Basically what I'm doing here is trying to make the scene change  When The  Yes button is moussed over and clicked
I've noticed while playing around that while inside a camera  a crash occurs but if I click the button while not in a cameras the scene loads fine.

If my problem isn't fixable is there a way I can exit the cameras with logic bricks .

happy to be here all help is welcomed 
Thanks !

~Rocket

**Comment by youle31** [comment]
I can reproduce with this:


[untitled.zip](https://github.com/UPBGE/upbge/files/6094602/untitled.zip)

**Comment by youle31** [comment]
Fixed here: https://github.com/UPBGE/upbge/commit/53e9b293017a4bfa5961c81981fda2578e1f63d1

Thanks for report (you can join a test file if you open another bug report)

**Comment by youle31** [comment]
Actually, i tried another fix here: https://github.com/UPBGE/upbge/commit/d356c34b581de25df27538cd65d9ed2c711d6127

I hope it will solve the issue.

**Comment by youle31** [comment]
again, i tried to improve the previous fix here: https://github.com/UPBGE/upbge/commit/64b662d905f8e70497914dca4932ee9cabb6642c
