### ISSUE TITLE
UPBGE 0.2 - Crash with "Cycles Environment" node

### ISSUE THREAD

**Issue by rpaladin** [UPBGE/upbge#1424]
Blender Cycles keeps crashing with any attempt to select a image for environment node when linked to world output.
Problem seems slightly related to these issue(s) below. A merge would be cool. Cheers.
https://developer.blender.org/T74803

**Test File**
[Issue_Blender_0.25a_Cycles_Environment_Node.zip](https://github.com/UPBGE/upbge/files/6094550/Issue_Blender_0.25a_Cycles_Environment_Node.zip)

**Comment by lordloki** [comment]
I just test with upbge 0.2.5a-Rev7: https://mega.nz/file/Y01mUIYR#bvs63kvV-BDxjTcLv_4OCwizH9zGKAZc5o1uSGz-kS4

and it is not crashing:
![image](https://user-images.githubusercontent.com/1015605/110218675-4d8cf680-7ebb-11eb-9151-41c8e9886e24.png)

Have you test with last version? or maybe I'm not doing the necessary steps for make it crash (I only selected the image in the image-texture node)

**Comment by AC-Panda** [comment]
Problem still persists. I don't know why I didn't think of this before, but here are the logs.
Exception Violation: **0x00007FF739B862EC**

**Link**
[debug_logs.zip](https://github.com/UPBGE/upbge/files/6098296/debug_logs.zip)

**Comment by AC-Panda** [comment]
**Related:** #1480

**Comment by rpaladin** [comment]
Fixed in UPBGE 0.2.6: https://github.com/UPBGE/upbge/issues/1480#issuecomment-974185034
