### ISSUE TITLE
[0.30.0 Alpha] Collections doubling in game when linked 

### ISSUE THREAD

**Issue by levelpixellevel** [UPBGE/upbge#1430]
I'm working in UPBGE-EEVEE-Win64-2021-03-02. 
I've created an asset with a simple logic node attached to it (asset_scene.blend) 
![image](https://user-images.githubusercontent.com/62971280/110794618-ed43df00-8243-11eb-9c61-b03f09f9671c.png)
When I try to link this asset into another session of the blender (linked_in_test.blend) using file-link-collection, the asset will double once it begins to move in the embedded start and standalone start. 
![image](https://user-images.githubusercontent.com/62971280/110794807-21b79b00-8244-11eb-8488-52f6266e4958.png)
I've attached my demo files to this report. 
[link_test.zip](https://github.com/UPBGE/upbge/files/6123269/link_test.zip)
The same problem exists when I try to link collections within the same file. 

This same setup works fine in UPBGEv0.2.5a-b2.79Windows64

Let me know if you need any more information.

**Comment by lordloki** [comment]
It seems that the flag IS_SPAWNED is not included when we call a instance_collection from link. I will investigate it.

**Comment by youle31** [comment]
Hello, I did 0.2.5 test files:

[link_test2.7.zip](https://github.com/UPBGE/upbge/files/6129452/link_test2.7.zip)

and DupliGroupRecurse was not even called. And when you print scene.objects, it prints Suzanne. I don't really know what we should do but my first thought was that we should maybe replace SetLooper flag in BlenderDataConversion with FOREACH_COLLECTION_OBJECT_RECURSIVE_BEGIN and maybe also change IsDupliGroup definition... But i'm not sure...

**Comment by youle31** [comment]
I closed my pull request because I had not the same setup than yours @levelpixellevel in my 2.7 test files. Could you join 2.7 test files for the same case and tell us what exactly you linked please?

**Comment by levelpixellevel** [comment]
Hey here is the 2.7 example (UPBGEv0.2.5a-b2.79Windows64). 

I have a file called: asset. In that file, I have the Suzanne head with a simple logic node for motion when the left mouse button is clicked. 
I've places that mesh into a group called: my_asset. 
![image](https://user-images.githubusercontent.com/62971280/111036040-38e4bd00-83eb-11eb-8ada-9809bf517a54.png)

In a new file, I'm going - file - link. 
![image](https://user-images.githubusercontent.com/62971280/111036083-6d587900-83eb-11eb-9837-5d83112aecbf.png)

Then I navigate to the asset, to the data blocks, choose group and select the my_asset group to link in. 

![image](https://user-images.githubusercontent.com/62971280/111036114-90832880-83eb-11eb-888f-0b73a57e5b2c.png)

![image](https://user-images.githubusercontent.com/62971280/111036106-87925700-83eb-11eb-990a-dd3660d63188.png)

Once this is linked in I'm able to enter play mode and click with the left mouse button. I've attached the example files for this:
[2_79_test_files.zip](https://github.com/UPBGE/upbge/files/6135084/2_79_test_files.zip)

I guess the main difference is that in 2.8/2.9 build I'm doing this with a collection, not a group. 

I also notice that the 2.8/2.9 build will 'double' the linked in the collection even within the same file. Here is a simple example.

I have two scenes:
![image](https://user-images.githubusercontent.com/62971280/111036198-13a47e80-83ec-11eb-8a9f-76c8b4447773.png)

One has the cube in a collection with a simple logic node for mouse input. 
![image](https://user-images.githubusercontent.com/62971280/111036242-4189c300-83ec-11eb-9a68-c125e25ad98f.png)

If I link that collection into another scene it will double on playtest: 

![image](https://user-images.githubusercontent.com/62971280/111036260-5cf4ce00-83ec-11eb-978f-e7e97f2d9d94.png)

[2_9_single_file_example.zip](https://github.com/UPBGE/upbge/files/6135089/2_9_single_file_example.zip)

I link in this cube by switching to the 
Blender File option in the outliner: 
![image](https://user-images.githubusercontent.com/62971280/111036299-92012080-83ec-11eb-82cf-056d554a9a50.png)

And dragging the collection into my scene: 
![image](https://user-images.githubusercontent.com/62971280/111036316-a7764a80-83ec-11eb-916a-20c970c788f5.png)


Let me know if this is what you were looking for.

**Comment by youle31** [comment]
Lordloki previously saw this issue I think because he pushed something to remove duplicates but it was causing issues in other files... Then we reverted the commit to remove duplicates... We'd need to find how all of that should behave.

**Comment by youle31** [comment]
Normally fixed in the mentionned commit. Thanks for report.

**Comment by youle31** [comment]
I reopen because the fix is causing physics issues in other files (can be related to blenderscene->lay)

**Comment by youle31** [comment]
The fix was generating few other issues, but i think it is fixed now. Then I close again
