### ISSUE TITLE
Embedded player crashing

### ISSUE THREAD

**Issue by Rocketgmpt** [UPBGE/upbge#1431]
Recently I had to switch to my old pc for game development but now I have an issue where the embedded player wont start it just crashes blender completely I did do some research and I found how to run blender in debug mode I think here's the crash file it lead me to. I have a feeling it may just be missing software
[.crash.txt](https://github.com/UPBGE/upbge/files/6129746/default.crash.txt)
Just Lmk if  there's anything  I can do to  solve the issue thanks.  ~ Rocket

P.s I have A Amd Radeon 5 Graphics card and an Amd A6-74000Radeon 5 Cpu

**Comment by lordloki** [comment]
It seems something related to audio (PyInit_aud) but we would need a file to reproduce/investigate.

**Comment by Rocketgmpt** [comment]
> It seems something related to audio (PyInit_aud) but we would need a file to reproduce/investigate.

Well i haven't actually began making my game yet and the file that is causing this to happen is the default cube that spawns when you open blender would you like some type of screen recording instead ??

**Comment by Rocketgmpt** [comment]
UPDATE i actually did some more research and it seem blender MUST have an audio playback in order to work. Being that my computer was built with out speakers pluggin in some headphones fixed the issue 😅 sorry for taking you time up like that
