### ISSUE TITLE
upbge 0.3 (program crashes and then quits when running game with navigation mesh

### ISSUE THREAD

**Issue by dennispetsinis** [UPBGE/upbge#1437]
System Information
Operating system: windows 10 (version 19042
Graphics card: Amd Ryzen 3200U

Blender Version 2.92 (originally tried as well 2.93)
Can not be sure it has to with blender, adding logic in upbge 0.3
Attached file.
I get the same results on my desktop as well.

I started upbge.

scene name: Main

added a cube as my landscape. (added material)
selected: added build navigation mesh

added a cone as enemy. (added material - sea blue)
Selected: added logic (Always - And - Steering (path following) - target (player) - navigation (navmesh)

added cube for player. (edited the cube, added material)
Selected: added logic (Collision / material- sea blue) - And - (Edit object / end object)
                                                                                                 (scene / set scene / main)
Press "P"

targeting and collision occur.

there is no scene change, program crashes and terminates.

[firing cube_1.zip](https://github.com/UPBGE/upbge/files/6152079/firing.cube_1.zip)

**Comment by youle31** [comment]
Thanks for report! It should be fixed in last master
