### ISSUE TITLE
hide.viewport = True before starting the game doesn't import the object

### ISSUE THREAD

**Issue by e2002e** [UPBGE/upbge#1439]
As the title says, when setting objects to be invisible before starting the game makes it impossible to make them visible once in the game engine.
Why do I need to hide objects in the viewport then make them appear in game ? For performance reason, I can't work on a file with thousands of models.
Why do I not use the build in LOD ? Because it doesn't remove the object, only replaces the mesh, and the objects are patches of ground which have particule systems; instead I'm making theses patches visible / invisible according to their distance from the player thanks to near sensors.
If you think this is not a bug then please tell me what should I do to make the objects invisible in the viewport before starting the game.
Regards.

**Comment by BluePrintRandom** [comment]
perhaps you should keep a list of locations and the objects in them
[tile1][tile2][tile3][fortress][tile4] etc
and create a kdtree of the locations,
and use kdtree.find_range() to free / fill tiles / locations with objects

**Comment by BluePrintRandom** [comment]
example - build a list of points
[KD_Tree_example.zip](https://github.com/UPBGE/upbge/files/6167740/KD_Tree_example.zip)

example - load a object from a blend and convert it
[lib_load_example.zip](https://github.com/UPBGE/upbge/files/6167741/lib_load_example.zip)

**Comment by e2002e** [comment]
This seems to be what I'm looking for, I'm going to study these files and implement 'kdtree', I'm using brackets since I don't know what that stands for.... THANKS

**Comment by e2002e** [comment]
Nevertheless there is an issue with the connection between console and UI, when you hit hide viewport it'll hide it but the console lets you only unhide it when you have hidden it from the console. And same the other way, i.e when you hide the object from the console, it cannot be unhidden from the UI. Weird but I don't think this is specific to upbge.
Thanks again.

**Comment by BluePrintRandom** [comment]
hidden objects are available to be added using own.scene.addObject() or the
add object actuator or the add object logic node.

**Comment by e2002e** [comment]
I'm looking into that now

**Comment by e2002e** [comment]
One think for sure is that a hidden object before starting bge is like dead and can't be the owner of the script

**Comment by e2002e** [comment]
Yes this is what I tumbled on the first place, now that I'm assigning the add object to dispatched empties it is working. Infinite HD forest... I just need a gameplay now.
