### ISSUE TITLE
Logic Brick Editor 0.3.0 object not combinable

### ISSUE THREAD

**Issue by BerglerAndi** [UPBGE/upbge#1441]
Hey there,

i have a complex logic brick network. There are two object which i can not see together in logic brick editor. From one i want to get a property and a key, to start a animation in the other object. Are there any requirement to see both make the network or any known issuses?

Thx
Best
Andi

**Comment by BluePrintRandom** [comment]
select one object, hold shift, select the other

**Comment by BerglerAndi** [comment]
Yes I know. If a do that the first selected disappears.

**Comment by BerglerAndi** [comment]
Here are some screen shots
![grafik](https://user-images.githubusercontent.com/58920393/112128477-c338d800-8bc6-11eb-91a5-e9fe5cb9faeb.png)
![grafik](https://user-images.githubusercontent.com/58920393/112128719-fed3a200-8bc6-11eb-8cef-d2e130b7274e.png)
KameraPosSchalter is one object, Icosphere the other. Separate selected you can see them in the logic brick editor

![grafik](https://user-images.githubusercontent.com/58920393/112128856-1d399d80-8bc7-11eb-87c6-e56018d15671.png)
Are both selected just the last selected is in logic brick editor.

**Comment by lordloki** [comment]
For me is working in last build
![image](https://user-images.githubusercontent.com/1015605/112200062-23ec0300-8c0f-11eb-8f28-cb0b33fabddf.png)
Could you upload a basic test file where is not working?

**Comment by BerglerAndi** [comment]
I cannot upload the whole file, because of sensible data. I made a minimal-file and left just that two objects in the file. What should i say the problem is gone.

I proceed step by step..

**Comment by BerglerAndi** [comment]
Is there probably a limitation in the number sensors or actuators which can be display in the logic brick editor.. I have one sensor, which has a lot of elements linked. May this is the reason. I see 24 actuators, more isn't possible.

**Comment by lordloki** [comment]
I did the test with around 30 logic bricks and it worked.
![image](https://user-images.githubusercontent.com/1015605/112226106-08dcbb80-8c2e-11eb-8f16-2e22f3a079dc.png)

**Comment by BerglerAndi** [comment]
Not really what i did..
![grafik](https://user-images.githubusercontent.com/58920393/112228178-29f2db80-8c31-11eb-98b4-a1aa51131eec.png)
The icosphere act as switches with states.
You cannot see all three icospheres in the sensor coloum. If you try to get some propertyies from icosphere and icosphere.001 to do something in icosphere.002 it is not possible..
[github_testfile_logicbrick.zip](https://github.com/UPBGE/upbge/files/6193155/github_testfile_logicbrick.zip)


Here is a minimal file.

**Comment by lordloki** [comment]
Ok. I confirm the bug.

**Comment by youle31** [comment]
I counted the number of actuators and it was 24. Then i searched for 24 in logic_window.c and it seems the count is limited to 24 in the code here:

![Capture](https://user-images.githubusercontent.com/10052509/112396705-f2536480-8d00-11eb-8692-dbd32df34df1.PNG)

We could increase the max count eventually, and spawn an UI error message if count > maxcount...
We could also investigate on why there was a max count...

**Comment by lordloki** [comment]
Yeah, I was investigating and is a thing that comes from the original release to limit memory consumption (in 2000 was not as cheaper than now). Maybe we can put a #define MAX_NUMBER_THE_LOGIC_BRICKS_SHOWED 256 or 512 and after as you say print a warning if we pass that limit.

**Comment by youle31** [comment]
Ok, it is as you want, we can either remove the limit, or increase the limit and send a warning.
I guess the simpler would be to remove the limit. We can comment the old code just in case we find something unexpected.

**Comment by youle31** [comment]
I just tested this patch: 
[p.zip](https://github.com/UPBGE/upbge/files/6203120/p.zip)
and it works:
![Capture](https://user-images.githubusercontent.com/10052509/112442680-68c98400-8d4c-11eb-9072-53fb641a7d23.PNG)

Who knows, maybe someone will try to generate logic bricks setups via bpy with more than 1000 linked objects :p

**Comment by BerglerAndi** [comment]
Thx, guys. This let me continue my project. For me 100 is more then enough.. Do you make a new release?

**Comment by youle31** [comment]
The limit is removed, it can be changed if we notice something wrong or if the other solution to increase the limit is better.

**Comment by BerglerAndi** [comment]
Where can i get the new version?

**Comment by lordloki** [comment]
I uploaded a new version just now. You can download from that directory.
