### ISSUE TITLE
UPBGE 0.3 on Raspberry pi 4 arm64

### ISSUE THREAD

**Issue by Anducalliew** [UPBGE/upbge#1443]
Hi, I developed an application with UPBGE 0.3 on my pc.
Is it possible to run it on a Raspberry pi 4 with arm64 architecture?
Thnaks

**Comment by lordloki** [comment]
Currently is not possible as Raspberry pi 4 doesn't support OpenGL 3.3. Maybe when UPBGE support vulkan and raspberry complete its vulkan support will be possible. Closing the report
