### ISSUE TITLE
UPBGE Shadow and performance problem

### ISSUE THREAD

**Issue by NODARman** [UPBGE/upbge#1447]
Hi, I need help. I have a shadow problem in UPBGE. Light source is a “point light” and it isn’t calculating fast.

https://user-images.githubusercontent.com/81517067/112752786-c3314180-8fe5-11eb-9f50-eeaec588dc87.mp4

**Comment by youle31** [comment]
What you show in the video seems soft shadows. Soft shadows are only computed when nothing is moving (neither the camera, neither any object in the scene). It isn't supported in realtime. We use eevee (blender code as it is). But it's not a bug. It's just that eevee's is not totally meant to be realtime. You can disable soft shadows in render tab > shadows
