### ISSUE TITLE
UPBGE BUG TEXTURES

### ISSUE THREAD

**Issue by WooDOd** [UPBGE/upbge#1448]
When I am in the upbge and I want to test my game, I press "P" and it starts but the textures are buggy and the block is white, when I enter the editmod in the block the block is totally yellow! This happened in version 0.2.3 I tested 0.2.2, 0.2.1 0.1.8! And they all happen, that is, making it impossible for me to create a game! However, in 0.2.4 onwards it does not happen, but when I press "P" it closes! Someone help?/

**Comment by WooDOd** [comment]
O mesmo acontece na 0.2.5

**Comment by lordloki** [comment]
we need a test file to check the bug. Thanks

**Comment by WooDOd** [comment]
> precisamos de um arquivo de teste para verificar o bug. Obrigado

![Sem título](https://user-images.githubusercontent.com/81538690/112876487-f504df80-909b-11eb-9de5-3486a01447f0.png)
[Uploading cube.blend…]()
[Uploading cube.rar…]()
[Uploading cube.zip.rar…]()
[cube.zip](https://github.com/UPBGE/upbge/files/6223478/cube.zip)

Here is the blend file

**Comment by lordloki** [comment]
I tested but I didn't see anything strange. The blend is a normal cube and I can edit and play normally. You can check the video

https://user-images.githubusercontent.com/1015605/113031353-e3503480-918e-11eb-996c-48ccd3d77e59.mp4

**Comment by WooDOd** [comment]
It was just outdated drives and DirectX Thanks
