### ISSUE TITLE
Something wrong logic-brick nearsensor after 0.3.0 build 26.03.2021

### ISSUE THREAD

**Issue by BerglerAndi** [UPBGE/upbge#1449]
Hey there,
something happend after build 0.3.0 of 26.03.2021 with the near-sensor in logicbricks. I started my game, which i made with 26.03.2021 in the version 29.03.2021 and the sensor doesnt work anymore.
Andi

**Comment by youle31** [comment]
Can you provide a test file please?

**Comment by youle31** [comment]
I close this report waiting to have a feedback/test file
