### ISSUE TITLE
UPBGE 0.3 - Feature request: allow collision logic bricks to detect if a property is True or False

### ISSUE THREAD

**Issue by arch-sketch** [UPBGE/upbge#1450]
First, I would like to thank you guys for all the work, upbge is amazing and you guys are awesome. 
As the title says, I would like to ask you to consider adding a way for collision logic bricks to differentiate between a True or False boolean property, so it will only activate if the property is True, and not if its False. Currently, the collision sensor will be activated if the property is detected, regardless of its value. 
This would allow for a colliding object to hold several properties at the same time, and have each activate different collision sensors depending on which of the properties is currently set to True.

**Comment by youle31** [comment]
I move this thread to discussions as it is a feature requerst and not a bug report.
