### ISSUE TITLE
bug about lod，Do not refresh the physical state

### ISSUE THREAD

**Issue by 2655251820** [UPBGE/upbge#1455]
When using lod to create a large area of terrain, I divided it into 4*4 squares. When running, the lod grid works normally, but the physical grid state is not refreshed.
That is, the state of the physical grid at the beginning of the game. There is no problem running on 0.25, but this problem will occur when you switch to 0.3

**Comment by 2655251820** [comment]
![Uploading 2.JPG…]()

**Comment by 2655251820** [comment]
In order to prevent machine translation from causing problems in understanding.
The rendering grid can be refreshed, but only the physical grid calculated from the camera distance when entering the game is read.

**Comment by youle31** [comment]
Current Level of detail implementation concerns only render, not physics. I'll compare with 0.2.5 behaviour and if physics is refreshed automatically in 0.2.5, I'll see if i can do something to refresh physics.
Waiting for that, there's a python API to refresh physics (kxob.reinstancePhysicsMesh(evaluated = True) )

**Comment by youle31** [comment]
0.2.5 doesn't refresh physics:

![Sans titre](https://user-images.githubusercontent.com/10052509/113862588-e196fa00-97a8-11eb-8f81-6ede2c2a4cf3.jpg)

I move this topic to discussions.
