### ISSUE TITLE
support for blender Physics and and animation, geometry nodes

### ISSUE THREAD

**Issue by Reaper10** [UPBGE/upbge#1457]
i dont know fi this is helpful or not  but, i think it'd will help to add support for blender's upgraded  Physics and  animation geometry nodes tool

Physics 
https://www.youtube.com/watch?v=i29tccdq3Cs

geometry nodes
https://www.youtube.com/results?search_query=blender+2.9+geometry+nodes

**Comment by lordloki** [comment]
Blender and UPBGE use same physics library (and version) but different implementations. At this moment, we don't have in our schedule to use blender physics implementation. Perhaps in a future.

Regarding to Geometry nodes animation is currently supported in UPBGE 0.3 alpha. An example:

https://user-images.githubusercontent.com/1015605/114282927-42436280-9a47-11eb-8973-bbfb6e62085c.mp4

Closing the report. Thanks for the feedback.

**Comment by Reaper10** [comment]
is it the same for animation rigging and  geometry nodes editor for Procedurally generating stuff
