### ISSUE TITLE
more game platforms

### ISSUE THREAD

**Issue by Reaper10** [UPBGE/upbge#1458]
you may want to look at kha after all you could add support for

Supported platforms
HTML5 (WebGL 2, WebGL and canvas)
Windows (Direct3D 12, Direct3D 11, Direct3D 9, Vulkan or OpenGL)
Universal Windows Platform (Direct3D 12 or Direct3D 11)
macOS (Metal or OpenGL)
Linux (Vulkan or OpenGL)
Android (via C++ or via Java)
iOS (Metal or OpenGL)
tvOS
Raspberry Pi
PlayStation 4
Xbox One
Nintendo Switch
Tizen
Flash
Unity 3D
Node.js (for automatically created server versions)
Java and AWT
C# and Windows Presentation Foundation
https://github.com/Kode/Kha

**Comment by youle31** [comment]
Thanks
