### ISSUE TITLE
[UPBGE 0.3x] Can't change active camera while in default view

### ISSUE THREAD

**Issue by AC-Panda** [UPBGE/upbge#1464]
Active camera view can not be changed at run-time if in default-view in embedded/standalone players.
Tested both mechanics with scene actuator, type: **"Set Camera"** and **KX_Scene.active_camera**

Noticed by **Planetary#7243**
[UPBGE_0.3x_Active_Camera_Bug.zip](https://github.com/UPBGE/upbge/files/6388958/UPBGE_0.3x_Active_Camera_Bug.zip)

**Comment by youle31** [comment]
It is not supported. We are using blender code to set camera view and changing active cam can only work if we are in camera view at bge start. (Also answered on discord)
