### ISSUE TITLE
suggestion add more rendering engines

### ISSUE THREAD

**Issue by Reaper10** [UPBGE/upbge#1469]
This is a thought to add more rendering engines to upbge like Appleseed as built in option.

> appleseed is an open source, physically-based global illumination rendering engine primarily designed for animation and visual effects.

> appleseed is actively developed by a small, international team of talented volunteers from the animation and VFX industry. Its core mission is to provide individuals and small studios with a complete, reliable, fully open rendering package.
via https://appleseedhq.net/

**Comment by lordloki** [comment]
Hi,
The purpose of the UPBGE is the development of the former blender game engine only . Adding additional renders is more focused to Blender itself. Maybe it is better to ask to Blender BF directly.
Thanks for the feedback. Closing.
