### ISSUE TITLE
Transfom issues: Parent relation / Armatures / Frame delay / Standalone and embedded

### ISSUE THREAD

**Issue by youle31** [UPBGE/upbge#1470]
Please post the maximum of buggy files. Thanks!

**Comment by mysticfall** [comment]
Attached a minimal test case which shows a mesh lagging behind the bone to which it is parented. If you play it, you can observe that the relative distance between the two meshes changes across the animation cycle.

The included patch from youle seems to fix the problem.

[transform-test.tar.gz](https://github.com/UPBGE/upbge/files/6447680/transform-test.tar.gz)

**Comment by youle31** [comment]
[armatureIssue.zip](https://github.com/UPBGE/upbge/files/6447785/armatureIssue.zip)

**Comment by youle31** [comment]
[ParentRelation-2.8.zip](https://github.com/UPBGE/upbge/files/6447788/ParentRelation-2.8.zip)

Files from @lordloki  in another pull request

**Comment by youle31** [comment]
Note: Don't trust physics debug lines in viewport render mode because it is drawn 1 frame too late.

**Comment by lordloki** [comment]
There is this commit https://github.com/UPBGE/upbge/commit/a536bbde11602b649c665ac61f64fc04e7d80aed that i have to check if it solves something
