### ISSUE TITLE
Alpha hashed transparency looks grainy and unstable

### ISSUE THREAD

**Issue by mysticfall** [UPBGE/upbge#1471]
(It's a known issue but I realised that it hasn't been reported before despite being the biggest problem I've so far had with UPBGE. So I decided to create a report to track the issue.)

Currently, EEVEE supports 3 different alpha transparency handling modes, namely alpha clipped, alpha blended, alpha hashed which can be used for different purposes.

However, the alpha hashed mode looks very jagged and unstable (especially when animating) to an extent to be unusable:
![image](https://user-images.githubusercontent.com/2367032/117556500-a25c1180-b0a4-11eb-94ed-4dfd4984eaac.png)

This issue makes it impossible to create any semi-realistic hair in UPBGE, since it requires this particular alpha handling mode to do so.

I found it to be quite unfortunate since UPBGE has a superb visual quality otherwise. It could be a definite advantage over its peers like Godot, but this issue (and another limitation with soft shadows) prevents it from being used to create realistic graphics.

**Comment by BluePrintRandom** [comment]
hypersomniac had this in response to this [video](https://www.youtube.com/watch?v=PSG5ttd8dTE):

JacobMerrill I used world position because for our case, we randomize samples for a still frame. Object space random was giving issues if the objects had really large scale etc... so to avoid more problems I decided to go for worldPosition. For UPBGE you can patch to use object position if you like 
objPosition = transform_point(ModelMatrixInverse,  worldPosition);

**Comment by BluePrintRandom** [comment]
so this is 1/2 the fix, we need to find where the samples are randomized, and add a checkbox to not do that

**Comment by mysticfall** [comment]
I'd like to comment that now the situation with the limitation has been alleviated greatly with #1474, which I consider to be the most significant visual improvement I've seen so far.

Particle hair might be still too expensive to use in UPBGE, but at least they look good after the change. Also, both alpha hashed material and soft-shadows look far better than they used to:

![image](https://user-images.githubusercontent.com/2367032/117588170-bb27fe00-b15c-11eb-9157-3fb3bbe23b0d.png)

Alpha hashed transparency probably needs a few more tweaks (e.g. still looks a bit grainy and unstable), but I think it has entered a usable territory with the aforementioned change now.

**Comment by youle31** [comment]
If he has a solid fix and does a pull request, it will be integrated to upbge....
I already tried and already told him where Noise texture which is used for alpha hash was updated.

**Comment by BluePrintRandom** [comment]
Actually, I found where to set the noise in object space, but I never
understood where the sample is randomozed

**Comment by BluePrintRandom** [comment]
"I already tried and already told him where Noise texture which is used for alpha hash was updated."

there is some edits that need to happen in prepass_frag - but there is also something that randomizes the samples somewhere (for TAA and for soft shadows and for alpha hash) we need to not randomize alpha hash only.

I will try and talk to hypersomniac or atmind today

**Comment by lordloki** [comment]
A test file: 
[2.8 MonkeyHairTest.blend.zip](https://github.com/UPBGE/upbge/files/6488300/2.8.MonkeyHairTest.blend.zip)

**Comment by mysticfall** [comment]
Reported an upstream issue, as discussed on Discord today:
 * https://developer.blender.org/T88331
