### ISSUE TITLE
Soft shadow stopped working, possibly after the recent introduction of per-light override

### ISSUE THREAD

**Issue by mysticfall** [UPBGE/upbge#1473]
I found that I can no longer make soft shadow working with the current master(cf591bb) build I'm using.

When I toggle the global soft shadow option, it doesn't have any effect when I switch viewport shading mode to `Rendered`.

If I toggle the soft shadow override option of individual lights, I can see soft shadows in the viewport. However, if I run the game the shadows still look blocky as if the option is disabled.

**Comment by youle31** [comment]
Soft shadow never worked for non static scenes. I needs several render passes with different taa samples to do an accumulation in eevee. I close this report and the other because it comes more from the eevee's normal behaviour which is not good at realtime for some things.
