### ISSUE TITLE
game does not start EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by BerglerAndi** [UPBGE/upbge#1476]
Dear community,

i'm not able to start gamemode (p key). There is a EXCEPTION_ACCESS_VIOLATION.

Can anyboby help?

(btw: I go back to Version 2021-03-12. In this Version the error doesn't occure.)

This is the content of .crash.txt

Blender 3.0.0, Commit date: 2021-05-10 03:40, Hash ea744e7e0b02

backtrace
Exception Record:

ExceptionCode         : EXCEPTION_ACCESS_VIOLATION
Exception Address     : 0x00007FF7766232C4
Exception Module      : blender.exe
Exception Flags       : 0x00000000
Exception Parameters  : 0x2
	Parameters[0] : 0x0000000000000000
	Parameters[1] : 0x0000000000000000

Stack trace:
blender.exe         :0x00007FF776618650  PyInit_aud
blender.exe         :0x00007FF776618650  PyInit_aud
blender.exe         :0x00007FF776618650  PyInit_aud
blender.exe         :0x00007FF7729869F0  Symbols not available

Loaded Modules :
0x00007FF771C00000 3.0.0.0              blender.exe  
0x00007FFAE7940000 10.0.18362.1500      ntdll.dll  
0x00007FFAE64D0000 10.0.18362.1500      KERNEL32.DLL  
0x00007FFAE5520000 10.0.18362.1474      KERNELBASE.dll  
0x00007FFAE67D0000 10.0.18362.1316      USER32.dll  
0x00007FFAE4A60000 10.0.18362.1474      win32u.dll  
0x00007FFADBA00000 2020.2.0.0           tbb.dll  
0x00007FFAE64A0000 10.0.18362.1316      GDI32.dll  
0x00007FFAE5290000 10.0.18362.1500      gdi32full.dll  
0x00007FFAE5480000 10.0.18362.1110      msvcp_win.dll  
0x00007FFAE4960000 10.0.18362.1110      ucrtbase.dll  
0x00007FFAE69F0000 10.0.18362.1474      SHELL32.dll  
0x00007FFAE5430000 10.0.18362.387       cfgmgr32.dll  
0x00007FFAE73C0000 10.0.18362.1316      shcore.dll  
0x00007FFADCD10000 14.28.29913.0        VCRUNTIME140.dll  
0x00007FFADB920000 14.28.29913.0        MSVCP140.dll  
0x00007FFAE6730000 7.0.18362.1          msvcrt.dll  
0x00007FFAE71B0000 10.0.18362.1500      RPCRT4.dll  
0x00007FFAE75C0000 10.0.18362.1500      combase.dll  
0x00007FFAE0540000 14.28.29913.0        VCRUNTIME140_1.dll  
0x00007FFAE5960000 10.0.18362.1237      bcryptPrimitives.dll  
0x00007FFAE4B10000 10.0.18362.1474      windows.storage.dll  
0x00007FFAE5AC0000 10.0.18362.1474      sechost.dll  
0x00007FFAE59F0000 10.0.18362.752       advapi32.dll  
0x00007FFAE4820000 10.0.18362.1411      profapi.dll  
0x00007FFAE4840000 10.0.18362.1         powrprof.dll  
0x00007FFAE47F0000                      UMPDC.dll  
0x00007FFAE6170000 10.0.18362.1316      shlwapi.dll  
0x00007FFAE4890000 10.0.18362.1171      kernel.appcore.dll  
0x00007FFAE4AF0000 10.0.18362.1         cryptsp.dll  
0x00007FFAE70E0000 10.0.18362.387       WS2_32.dll  
0x00007FFAACD20000 10.0.18362.1500      OPENGL32.dll  
0x00007FFAE6590000 10.0.18362.1316      ole32.dll  
0x00007FFA9D5B0000 3.9.2150.1013        python39.dll  
0x00007FFAD5730000 8.0.1.0              openvdb.dll  
0x00007FFAE72E0000 10.0.18362.1         PSAPI.DLL  
0x00007FFAE6700000 10.0.18362.387       IMM32.dll  
0x00007FFABBF70000 56.31.100.0          avutil-56.dll  
0x00007FFA9B310000 58.29.100.0          avformat-58.dll  
0x00007FFA9B650000 58.54.100.0          avcodec-58.dll  
0x00007FFAE57D0000 10.0.18362.1237      bcrypt.dll  
0x00007FFAD5660000 58.8.100.0           avdevice-58.dll  
0x00007FFAD5690000 5.5.100.0            swscale-5.dll  
0x00007FFABBE20000 1.20.1.0             OpenAL32.dll  
0x0000000070440000 1.0.28.0             libsndfile-1.dll  
0x00007FFAE72F0000 10.0.18362.1377      OLEAUT32.dll  
0x00007FFADD8C0000 2020.2.0.0           tbbmalloc_proxy.dll  
0x00007FFAB83E0000 2.0.12.0             SDL2.dll  
0x00007FFAD5640000 10.0.18362.1         AVIFIL32.dll  
0x00007FFAE5D00000 10.0.18362.1         SETUPAPI.dll  
0x00007FFAD8650000 6.10.18362.1500      COMCTL32.dll  
0x00007FFADA810000 10.0.18362.1         VERSION.dll  
0x00007FFAACF20000 10.0.18362.387       GLU32.dll  
0x00007FFAE2F10000 10.0.18362.1440      dbghelp.dll  
0x0000000070680000                      libfftw3-3.dll  
0x000000006ACC0000                      libgmp-10.dll  
0x00007FFADB060000 10.0.18362.1         Secur32.dll  
0x00007FFAD5610000 3.5.100.0            swresample-3.dll  
0x00007FFAC9130000 10.0.18362.1         AVICAP32.dll  
0x00007FFAC5620000 2020.2.0.0           tbbmalloc.dll  
0x00007FFAC55F0000 10.0.18362.1         MSVFW32.dll  
0x00007FFAC55D0000 10.0.18362.1         MSACM32.dll  
0x00007FFAD7EA0000 10.0.18362.1         WINMM.dll  
0x00007FFAD7E70000 10.0.18362.1         winmmbase.dll  
0x00007FFAE46E0000 10.0.18362.1474      SSPICLI.DLL  
0x00007FFAE3460000 10.0.18362.1316      dxcore.dll  
0x000000005FEE0000 20.12.0.173          mfehcinj.dll  
0x00007FFAE4A90000 10.0.18362.1377      WINTRUST.dll  
0x00007FFAE4800000 10.0.18362.1         MSASN1.dll  
0x00007FFAE5800000 10.0.18362.1411      CRYPT32.dll  
0x000000005FED0000 20.12.0.173          mfehcthe.dll  
0x00007FFADBA40000 20.12.0.58           mfedeeprem64.dll  
0x00007FFAE1A10000 10.0.18362.1316      uxtheme.dll  
0x00007FFAE61D0000 2001.12.10941.16384  clbcatq.dll  
0x00007FFADF060000 10.0.18362.1316      MMDevApi.dll  
0x00007FFAE45E0000 10.0.18362.387       DEVOBJ.dll  
0x00007FFADF510000 10.0.18362.1350      AUDIOSES.DLL  
0x00007FFADF930000 10.0.18362.1500      wintypes.dll  
0x00007FFAE5B60000 10.0.18362.1350      MSCTF.dll  
0x00007FFAA7290000 10.0.18362.1316      dataexchange.dll  
0x00007FFAE0C50000 10.0.18362.1474      dcomp.dll  
0x00007FFAE3110000 10.0.18362.1411      d3d11.dll  
0x00007FFAE3480000 10.0.18362.1500      dxgi.dll  
0x00007FFAE1BD0000 10.0.18362.1316      twinapi.appcore.dll  
0x00007FFAE2030000 10.0.18362.1316      RMCLIENT.dll  
0x00007FFA71010000 27.20.100.8853       ig9icd64.dll  
0x00007FFAE1F20000 10.0.18362.1316      dwmapi.dll  
0x00007FFAD46F0000 27.20.100.8853       igdgmm64.dll  
0x00007FFACE930000 27.20.100.8853       igc64.dll  
0x00007FFA9AF00000 27.20.100.8853       igdml64.dll  
0x00007FFAC5340000 10.0.18362.1474      TextInputFramework.dll  
0x00007FFAE0E30000 10.0.18362.1316      CoreMessaging.dll  
0x00007FFAD7640000 10.0.18362.1110      CoreUIComponents.dll  
0x00007FFAE37C0000 10.0.18362.1         ntmarta.dll  
0x00007FFAD95E0000 11.0.18362.1474      iertutil.dll  
0x00007FFABF2C0000 7.2.18362.1316       Oleacc.dll  
0x00007FFAA3E90000 1.0.5.10             Wintab32.dll  
0x00007FFADEAF0000 10.0.18362.1         WTSAPI32.dll  
0x00007FFACD360000 10.0.18362.1         MPR.dll  
0x00007FFAA3C00000 7.6.1.28             ISD_Tablet.dll  
0x00007FFAA6E80000 10.0.18362.1350      explorerframe.dll  
0x00007FFAE2270000 7.0.18362.1474       propsys.dll  
0x00007FFAB4F80000 10.0.18362.1         drprov.dll  
0x00007FFAE3860000 10.0.18362.836       WINSTA.dll  
0x00007FFAB4F60000 10.0.18362.1379      ntlanman.dll  
0x00007FFAB4F40000 10.0.18362.1         davclnt.dll  
0x00007FFAB4F30000 10.0.18362.1         DAVHLPR.dll  
0x00007FFADD660000 10.0.18362.1         wkscli.dll  
0x00007FFAC92A0000 10.0.18362.1         cscapi.dll  
0x00007FFAE3E10000 10.0.18362.1         netutils.dll  
0x00007FFAE3B70000 10.0.18362.1         rsaenh.dll  
0x00007FFAE4220000 10.0.18362.1         CRYPTBASE.dll  
0x00007FFABEA30000 10.0.18362.1         dinput8.dll  
0x00007FFAC5220000 10.0.18362.1474      inputhost.dll  
0x00007FFAE2E50000 10.0.18362.1         HID.DLL  
0x00007FFAC55B0000 10.0.18362.329       XInput1_4.dll  
0x00007FFADB910000 3.9.2150.1013        python3.DLL  
0x00007FFAB1EB0000                      _multiarray_umath.cp39-win_amd64.pyd  
0x00007FFABEC30000                      _multiarray_tests.cp39-win_amd64.pyd  
0x00007FFABD390000 3.9.2150.1013        _ctypes.pyd  
0x00007FFAC9370000                      libffi-7.dll  
0x00007FFAB7880000                      lapack_lite.cp39-win_amd64.pyd  
0x00007FFA9F1C0000                      _umath_linalg.cp39-win_amd64.pyd  
0x00007FFABE9D0000 3.9.2150.1013        _bz2.pyd  
0x00007FFABBDA0000 3.9.2150.1013        _lzma.pyd  
0x00007FFABA3E0000 3.9.2150.1013        _decimal.pyd  
0x00007FFABA0C0000                      _pocketfft_internal.cp39-win_amd64.pyd  
0x00007FFAB5200000                      mtrand.cp39-win_amd64.pyd  
0x00007FFAB93B0000                      bit_generator.cp39-win_amd64.pyd  
0x00007FFAB8890000                      _common.cp39-win_amd64.pyd  
0x00007FFAB9390000 3.9.2150.1013        _hashlib.pyd  
0x00007FFA97E30000 1.1.1.9              libcrypto-1_1.dll  
0x00007FFAB7230000                      _bounded_integers.cp39-win_amd64.pyd  
0x00007FFAB8930000                      _mt19937.cp39-win_amd64.pyd  
0x00007FFAB8560000                      _philox.cp39-win_amd64.pyd  
0x00007FFAB8350000                      _pcg64.cp39-win_amd64.pyd  
0x00007FFAB8220000                      _sfc64.cp39-win_amd64.pyd  
0x00007FFAB5150000                      _generator.cp39-win_amd64.pyd  

# Python backtrace

**Comment by lordloki** [comment]
Have you got selected OpenAl-Soft under Preferences->System->Sound??

**Comment by BerglerAndi** [comment]
No, WASAPI is selected.

I deleted the config files in \AppData\Roaming\UPBGE\Blender. Now it works. But i have absolutly no idea, wether this was the error..

**Comment by lordloki** [comment]
Closing then. Thanks for the feedback.
