### ISSUE TITLE
UPBGE 0.3.0 Crashes when saving

### ISSUE THREAD

**Issue by wario-sys** [UPBGE/upbge#1479]
I have been experiencing crashes when saving. It doesn't happen all the time, but often enough to be a hindrance to my work. I posted about the issue on blenderartists.org as well. https://blenderartists.org/t/upbge-0-3-0-crashes-when-saving/1304446
Any help is greatly appreciated.

**Comment by youle31** [comment]
I saw on BA that finally, the issue didn't happen anymore. I didn't notice save issues on my side. I close this report for now. If the issue happens again and that you have a reliable way to reproduce it with a test file, you could open a new report. Thanks.
