### ISSUE TITLE
added objects material are linked

### ISSUE THREAD

**Issue by mushroomeo** [UPBGE/upbge#1485]
hi if i add object in game then the materials are linked and so cant make damage effect because if one objects is effected then all added objects materials are animated same time...

**Comment by BluePrintRandom** [comment]
Use object color r g or b to drive this or use a custom object attribute in
the blender object and get it using attribute node

**Comment by youle31** [comment]
BluePrintRandom is right (It can be discussed on discord for more explainations/examples.)

As said in softbody issue, I close this one because it is basically the same problem.
