### ISSUE TITLE
mixing eev and cycle 

### ISSUE THREAD

**Issue by Reaper10** [UPBGE/upbge#1487]
I just found this found it very intriguing for a game engine.
https://www.youtube.com/watch?v=6-hkc2xzzg0
https://gumroad.com/l/PgyXc

**Comment by AC-Panda** [comment]
UPBGE 0.3x already has full EEVEE integration.

**Comment by lordloki** [comment]
I follow that addon and I am waiting to see if the addon is incorporated in blender's code directly or if it evolves as addon only.

Thanks for the feedback. Closing the report.

**Comment by BluePrintRandom** [comment]
the only thing I would say - is we could support overscan better in realtime

this could be something feasible / and supports these sort of FX better than master even.
