### ISSUE TITLE
"Save as game runtime" doesn't work - fix

### ISSUE THREAD

**Issue by example-sk** [UPBGE/upbge#1490]
Hi, I had problem exporting a game as runtime, so after a little debugging, here is the fix for file 3.0/scripts/addons/game_engine_save_as_runtime_eevee.py:106 (+ the comment before this line):

`
    string = bpy.app.version_string.split()[0]
    version_string = ".".join(string.split('.')[:2])
`

The problem is that all previous version strings until 3.0 had 4 characters. So the variable version_string had value of "2.93", but now it has (without my fix) "3.0."

**Comment by lordloki** [comment]
Fixed in master. Thanks for the fix. Closing
