### ISSUE TITLE
UPBGE 0.3 Viewport issues

### ISSUE THREAD

**Issue by LP-ita** [UPBGE/upbge#1493]
Hi, when I add a second camera with an overlay collection, it causes that when I activate the physics visualization "check under Framerate and profile", it returns a wrong projection in the main camera, and if I go to activate "use viewport render" and press p, the viewport starts to flashing... Last build. Win 64.

**Comment by youle31** [comment]
Overlay collections are not supported in "viewport render" mode.

More infos about not supported features in "viewport render" mode here: https://github.com/UPBGE/upbge/wiki/Release-notes-version-0.3.0#features-not-yet-supported-in-viewport-render-mode
