### ISSUE TITLE
UPBGE 0.3 - Issue with Action actuator when using Property playback type

### ISSUE THREAD

**Issue by arch-sketch** [UPBGE/upbge#1495]
How to reproduce - apply an animation on the focal length of the camera (in this case with 20 frames), add the logic birck tree shown on the image, set a value for the property to be used (in this case 10).

When playing, the camera will be going back and forth every tick, from the 1st frame and the frame set on the property value, instead of displaying only the frame defined as it should.

![a01](https://user-images.githubusercontent.com/81666035/120214197-88789f00-c20a-11eb-988d-cd0079b891a7.jpg)

![a02](https://user-images.githubusercontent.com/81666035/120214262-9c240580-c20a-11eb-81cf-6e36ea8524a1.jpg)

PS: If you play the same camera action from frame 1 to 20, and then play it from 20 to 1, frame 1 will be displayed for a single tick before going from 20 to 1.

![a03](https://user-images.githubusercontent.com/81666035/120214322-b1009900-c20a-11eb-8be1-a143705526df.jpg)

**Comment by youle31** [comment]
I can't reproduce the issue in this file:

[len_anim.zip](https://github.com/UPBGE/upbge/files/6572875/len_anim.zip)

**Comment by arch-sketch** [comment]
I can confirm that it indeed works. Its definitely something to do with my camera. Its using a script (from Mike Pan), for the mouselook smoothing it has. Its a shame, I was planning on using that... Sorry for the false alarm. Thanks for taking a look.

**Comment by youle31** [comment]
Alright, I close the report as it doesn't seem to be a bug but more a conflict caused by something in your camera setup.
