### ISSUE TITLE
UPBGE 0.2x - KX_BlenderMaterial / BL_Texture API Not Functioning Properly

### ISSUE THREAD

**Issue by AC-Panda** [UPBGE/upbge#1501]
None of the material/texture API for KX_Mesh seem to be working in UPBGE 0.2x, possibly due to the removal of multi-texture mode.

**Comment by youle31** [comment]
[specIntensity.zip](https://github.com/UPBGE/upbge/files/6603749/specIntensity.zip)

It's working for me in this file

**Comment by AC-Panda** [comment]
Forgot to deactivate `constant` values on my materials. My bad, thanks for the help!
