### ISSUE TITLE
0.3 Maybe we need give the physical grid an option to refresh with the lod

### ISSUE THREAD

**Issue by 2655251820** [UPBGE/upbge#1504]
https://user-images.githubusercontent.com/38093850/121156489-51923100-c87b-11eb-85eb-288fea5f7c66.mp4

This problem has actually appeared long ago. I found that neither 0.25 nor 0.3 has been resolved. On the ground of a large scene, when I leave the spawn point too far, the physical mesh in 0.3 does not refresh, and 0.25 will directly load the complete physical mesh grid. 0.3 Not refreshing the physical grid will cause me to go to some places and fall directly. Since I watched the new 0.25 a few days ago, I don’t know if this problem still exists. But I think at least the user should be given the option to open the new physical grid.

**Comment by 2655251820** [comment]
Mr. Youle responded to me. Thank you. Although I don’t know if I have caused any trouble, I hope to recommend upbge to some of my friends who are interested in game development. I make tutorials for them, but this problem seems to be impossible to bypass. Because there will be a problem that the subsequent game map does not have a physical grid, it is really uncomfortable for games with slightly larger scenes.

**Comment by 2655251820** [comment]
Mr. Youle responded to me, thank you. Although I don’t know if I have caused any trouble (code), I hope to recommend upbge to some of my friends who are interested in game development. I make tutorials for them, but this problem seems impossible. Bypass. Because there will be a problem that the subsequent game map does not have a physical grid, it is really uncomfortable for games with slightly larger scenes.

**Comment by lordloki** [comment]
Do you have a test file to check?

**Comment by youle31** [comment]
I added an option in last commits (3 commits because i did mistakes)...

My test file was this: 
[lod_physics_test.zip](https://github.com/UPBGE/upbge/files/6616198/lod_physics_test.zip)

But indeed, i'd be curious to see @2655251820 file

**Comment by 2655251820** [comment]
https://drive.google.com/file/d/1HFcqVI0hbRJCsb_8bYFgVsColwMP_5RP/view?usp=sharing

Since I don't know how to use github to transfer zip files, I used Google Cloud Disk. There are two in total. One is the regular lod, and the other is the lod of the geometry node. This is the case for both methods.

**Comment by youle31** [comment]
This request is normally solved in master. I tried to access the file on google drive but permission was denied.
I close this for now and you can give a feedback when you will test the new feature in next builds
