### ISSUE TITLE
Only one AOV per material possible

### ISSUE THREAD

**Issue by begbarros** [UPBGE/upbge#1505]
At the moment, only one AOV output per material is possible. It would be better to have more than that to mimic 0.2.5's render attachments feature

**Comment by BluePrintRandom** [comment]
do you have a test file?

I believe I was using multiple AOV in the past....

>

**Comment by begbarros** [comment]
![aov](https://user-images.githubusercontent.com/11696444/122603059-2f05d200-d04a-11eb-81e7-0974caa6a53e.png)
Actually the additional AOV nodes you add to material looks like they are disabled. But now I checked it's seem to be working fine (despite of the gray color)

**Comment by BluePrintRandom** [comment]
Cool, want to close this?

and happy blendering !!!
