### ISSUE TITLE
Lights jittering on turbulence rotation with volumetric fog

### ISSUE THREAD

**Issue by begbarros** [UPBGE/upbge#1507]
When there is any kind of light, volume scatter on world shader and a turbulence field in a scene, the lights flick when turbulence is rotating (at least here on my computer- GTX1070).  Just press p to check it on attached file
[turbulence_grass_light_fog.zip](https://github.com/UPBGE/upbge/files/6683926/turbulence_grass_light_fog.zip)

**Comment by lordloki** [comment]
To avoid the light jittering with Volumetrics you have to select the option Volumetrics Blending
![image](https://user-images.githubusercontent.com/1015605/122707014-70200100-d259-11eb-94d7-b40c93b933a5.png)

**Comment by begbarros** [comment]
> To avoid the light jittering with Volumetrics you have to select the option Volumetrics Blending
> ![image](https://user-images.githubusercontent.com/1015605/122707014-70200100-d259-11eb-94d7-b40c93b933a5.png)

It works..thank you!
