### ISSUE TITLE
MacOs 2D filter issue blenderplayer

### ISSUE THREAD

**Issue by youle31** [UPBGE/upbge#1508]
Reported on discord by DominusLex

![Capture](https://user-images.githubusercontent.com/10052509/122956091-fc791380-d380-11eb-994e-09013f3cac49.PNG)

File: 
[Filter2d_Broken.zip](https://github.com/UPBGE/upbge/files/6695668/Filter2d_Broken.zip)

It works fine for me on windows. The expected result is just the black screen and wired white suzanne.

Potentially similar as : https://github.com/UPBGE/upbge/commit/95f1555c544ba45267304e7c72205fa411f0bd17

**Comment by youle31** [comment]
I added this:

![Capture](https://user-images.githubusercontent.com/10052509/122966729-f176b100-d389-11eb-865d-44eea53093f8.PNG)

But idk if it could change something, and i can't build on mac

**Comment by lordloki** [comment]
I just uploaded a build with the patch, https://mega.nz/file/sk9UnBLD#x6OqXlJiy5frav8cq4j-wneLPIZ4ThIouf-8ACkstL0

**Comment by TriVoxel** [comment]
To add to this issue, it isn't just in BlenderPlayer, it is also in the editor (pressing P). The filters work* but don't display correctly at all. The actual game uses the upper 8th of the screen and the rest of the upper quarter is just the pixels on the edge of the screen being stretched out.

Video: https://youtu.be/n-Ve519gH-E

**Comment by youle31** [comment]
I pushed this: https://github.com/UPBGE/upbge/commit/bba0469867687925477e0d412a2e3e4817ba071d

I'm waiting for Trivoxel feedback. Thanks

**Comment by youle31** [comment]
The branch seems to fix the issue on mac. I'll rework it a bit later then commit in master. Thanks very much @TriVoxel  for remote session!

**Comment by youle31** [comment]
It should be ok in last master: https://github.com/UPBGE/upbge/commit/f543ac1aa982286169e8a97cb711d39ba5572142

Thanks!
