### ISSUE TITLE
Error when trying to activate actuator from component.

### ISSUE THREAD

**Issue by begbarros** [UPBGE/upbge#1510]
Although controller.state == 1 (meaning it's active), when trying to activate an actuator from a controller through component, that raises this error:
`SystemError: Cannot activate an actuator from a non-active controller`
[activate_actuator_from_component.zip](https://github.com/UPBGE/upbge/files/6705668/activate_actuator_from_component.zip)

**Comment by Feral3d** [comment]
You can make it work by adding and connecting an "AND" controller to the the actuator. For whatever reason this makes the actuator "active" and then you can activate or deactivate it with script though another object running a module or component. 
Basically do this to the actuator you want to control.
![image](https://user-images.githubusercontent.com/67176876/123487101-4eb57100-d5db-11eb-87c2-0ff12b9d8516.png)

**Comment by begbarros** [comment]
> You can make it work by adding and connecting an "AND" controller to the the actuator. For whatever reason this makes the actuator "active" and then you can activate or deactivate it with script though another object running a module or component.
> Basically do this to the actuator you want to control.
> ![image](https://user-images.githubusercontent.com/67176876/123487101-4eb57100-d5db-11eb-87c2-0ff12b9d8516.png)

That solved the issue..thanks
