### ISSUE TITLE
bge.render.setGLSLMaterialSetting() constantly forces environment lighting to be enabled

### ISSUE THREAD

**Issue by AC-Panda** [UPBGE/upbge#1511]
<kbd>Environment Lighting</kbd> shading setting switches to <kbd>enabled</kbd> at embedded player exit by constant default.

Bug happens even if scene world's environment lighting is disabled.

_Tested with startup blend / empty scene._

Bug emerged after commit: https://github.com/UPBGE/upbge/commit/fdae06d12db255c6664ac705596192d7f5c13576

**Comment by youle31** [comment]
Fixed
