### ISSUE TITLE
Crash when attempting to get vertex by none material

### ISSUE THREAD

**Issue by AC-Panda** [UPBGE/upbge#1514]
**Release Version:** UPBGE: 0.25b

**Crash Log:**
```
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF7B3DC574D
Module  : D:\Blender\Model_Templates\BA\Misc\(1) Builds\UPBGE 0.25b\blender.exe
```

**Test File:**
[UPBGE_0.2x_Crash_Invalid_Vertex_Material.zip](https://github.com/UPBGE/upbge/files/6794564/UPBGE_0.2x_Crash_Invalid_Vertex_Material.zip)

**Comment by youle31** [comment]
Fixed in mentionned commit
