### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by zeronobody0** [UPBGE/upbge#1521]
I can't build the software on Arch Linux using the AUR package.
https://pastebin.com/hiSNV4cx

**Comment by mysticfall** [comment]
It looks like the build script fails to find `nvidia` module and skips applying the necessary patch to autodetect the proper CUDA version, thus forcing it to build for every version which might cause trouble in lowend hardware.

Maybe you have an NVidia card but not using the proper driver (`nvidia`) for CUDA? What does it say if you run `grep nvidia <(lsmod)` from the terminal?

**Comment by BluePrintRandom** [comment]
this is a bot :D

**Comment by mysticfall** [comment]
Forgot to close this one. The issue has been already resolved with the current version of the AUR package.

Thanks for the report!

**Comment by youle31** [comment]
Thanks!
