### ISSUE TITLE
Play animation node didn't work with restart scene

### ISSUE THREAD

**Issue by donjwan88** [UPBGE/upbge#1531]
I have another issue

Play animation node didn't work well with restart scene 

Any object have play animation node when i want make restart scene all of the object go to the meddile I don't know why ?

https://youtu.be/PqFhRmu5czo

**Comment by mhreez** [comment]
here test file 
https://www.mediafire.com/file/igevjbvhuq18gt2/test[1].rar/file

**Comment by youle31** [comment]
Hello, can you reproduce the bug in a file without logic nodes addon? It is to be sure that the issue doesn't come from the addon/is not related to the addon.

**Comment by youle31** [comment]
Ok, I did a file with logic bricks and I have the bug: I'll try to investigate:

File:

[location_anim.zip](https://github.com/UPBGE/upbge/files/7012235/location_anim.zip)

**Comment by youle31** [comment]
Normally fixed in last master. Thanks very much for report!
