### ISSUE TITLE
Init Vertex Colors In Viewport Broken

### ISSUE THREAD

**Issue by AC-Panda** [UPBGE/upbge#1537]
# Note: This bug happens in all releases; BGE, 0.2, and 0.3

Steps to reproduce **(In 0.2, but can in any default scene)**:
- Open default UPBGE 0.2 scene **(Cube color  is blue)**
![image](https://user-images.githubusercontent.com/69180012/130292292-7aae658f-2437-4416-a2ae-8e89c675db27.png)

- Turn on material setting "Vertex Color Paint" for default [blue] cube **(Cube color is now red)**
![image](https://user-images.githubusercontent.com/69180012/130292310-f7b13189-01fd-40bd-8dae-b4c9f9d34601.png)

- Switch to Vertex Paint mode **(Cube color  is now default white)**
![image](https://user-images.githubusercontent.com/69180012/130292328-89cffbaa-6945-4110-88cd-74478191183e.png)

- Switch back to Edit Mode **(Cube color stays at default white)**
![image](https://user-images.githubusercontent.com/69180012/130292342-b2cdf0f4-f21b-41bd-a927-ab54feace640.png)

**Comment by youle31** [comment]
It doesn't really looks like a bug to me, as nothing is painted... Furthermore, it doesn't really belong to our "intervention field" (we normally only deal with gameengine folder...) For these 12 reasons, I close this task.
