### ISSUE TITLE
UPBGE 0.3 - Add Overlay Collection Render Frozen

### ISSUE THREAD

**Issue by blenderaiser** [UPBGE/upbge#1539]
When using the actuator Collection with the Add Overlay Collection mode, the camera (from the overlay collection) freezes the rendering. By activating Physics Visualization, it is possible to observe the gizmos in motion but the object image frozen.

Example:
[Overlay Collection.zip](https://github.com/UPBGE/upbge/files/7035746/Overlay.Collection.zip)

Windows 10, GeForce GTX 750ti.

**Comment by youle31** [comment]
Thanks very much for report! It should be fixed here: https://github.com/UPBGE/upbge/commit/48f744a932c442d7c71c28cc1d2ce92ba55f28b1
