### ISSUE TITLE
UPBGE 0.3 - Invalid Game-Properties Don't Raise Errors

### ISSUE THREAD

**Issue by AC-Panda** [UPBGE/upbge#1542]
Code for receiving nonexistant game-properties aren't raising console errors like they should.
After attempting to get a property's value, it apparently assigns it instead, thus creating a temp property.

# Set Nonexistant:
![image](https://user-images.githubusercontent.com/69180012/131233622-591b695f-33eb-41de-be3f-66099b14d812.png)

![image](https://user-images.githubusercontent.com/69180012/131233721-152437fb-9ed0-4838-96bb-733c59559be9.png)

# Get Nonexistant:
![image](https://user-images.githubusercontent.com/69180012/131233688-81c7a3bd-df14-44e2-afd4-7bbeec1e4ca6.png)

![image](https://user-images.githubusercontent.com/69180012/131233689-d760f885-ad3e-440e-bce3-d95d2c741b83.png)

# Test File:
https://github.com/UPBGE/upbge/files/7071664/UPBGE_03_Invalid_Game_Property_Not_Raised.zip

**Comment by youle31** [comment]
Why is it non existant? It exists because you are creating it just before. I don't see the bug...

**Comment by AC-Panda** [comment]
The game-property wasn't created in Blender; only at runtime... Shouldn't that raise errors like it did in legacy versions?
