### ISSUE TITLE
[CRASH][UPBGEv0.2.5b-Windows1032]

### ISSUE THREAD

**Issue by systemtatics** [UPBGE/upbge#1544]
Specs:
CPU - Intel Pentium E5700
GPU - AMD Radeon HD 5450
Mainboard - G41MT-S2P
OS -Win 10 Pro 32 Bits
RAM -2 gb Ddr3

Every time I try to run the game engine by pressing "P", it returns the following error:

Using OpenGL 4.3 debug facilities
GL application marker: Successfully hooked OpenGL debug callback.
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Error   : EXCEPTION_ILLEGAL_INSTRUCTION
Address : 0x012BB950
Module  : C:\Users\Monteiro\Downloads\UPBGE-2.5\blender.exe

**Comment by systemtatics** [comment]
resolved!

**Comment by lordloki** [comment]
Hi, @systemtatics do you remember how you fixed the issue? Maybe it can help other users.
Thanks for sharing

**Comment by systemtatics** [comment]
I reported the bug to a friend, he was on a 32bit windows system, he installed a 64bit version and the problem is gone, thanks for your work at UPBGE!
