### ISSUE TITLE
Eample at top of upbge.org/api/aud.html is incorrect

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [UPBGE/upbge#1545]
"[buffer](https://upbge.org/api/aud.html?highlight=audaspace#aud.Sound.buffer)" now "_Creates a sound from a data buffer_" using "[data](https://upbge.org/api/aud.html?highlight=audaspace#aud.Sound.data)" to create a numpy array from the sound. 

What buffer used to do has now become "[cache](https://upbge.org/api/aud.html?highlight=audaspace#aud.Sound.cache)", "_Caches a sound into RAM_".

This caused me endless confusion as there seemed to be no announcement anywhere by Audaspace devs of these major name changes.

These changes are not reflected in the example given at the top of "[Audio System (aud)](https://upbge.org/api/aud.html?highlight=audaspace#module-aud)" which still uses the old "_aud.Sound.buffer(sound_)" which should be "_aud.Sound.**cache**(sound)_".

Cheers !

**Comment by lordloki** [comment]
Reported in Blender system. https://developer.blender.org/D12396
I close this report as this issue belong there. Thanks for catching the issue.
