### ISSUE TITLE
UPGE crashing when hitting "esc" after play using Embedded start (with or without "Use viewport render").

### ISSUE THREAD

**Issue by ItsCubeTime** [UPBGE/upbge#1555]
https://user-images.githubusercontent.com/20190653/133584628-0c343fd7-3c82-4f39-b290-3bad0902f1bf.mp4

![image](https://user-images.githubusercontent.com/20190653/133584692-7a71bbbc-3aac-4d66-b6b8-ec91c039420e.png)

**Comment by youle31** [comment]
Yes, it is related.

For now, upbge master is a bit unstable so better to keep a version from september beginning.

**Comment by ItsCubeTime** [comment]
> Yes, it is related.
> 
> For now, upbge master is a bit unstable so better to keep a version from september beginning.

Thanks @youle31 !

Considering this was already a known issue, it would be cool if there was some stable releases for UPGE that are "roughly" tested & known to be relatively stable

**Comment by lordloki** [comment]
I just uploaded windows and linux new builds with your proposed fix included. Thanks for the fix

**Comment by Ahmad-64bit** [comment]
i have that same bug , but with UPBGEv0.2.5b-b2.79 Windows64 , and it crashs somtimes when i run the game engine , i really like upbge but now i am stuck and cannot develop any project .... could you help me please ?

**Comment by lordloki** [comment]
It can't be the same bug as this bug is for 0.3 only (due to changes in blender 3.0 alpha).

**Comment by youle31** [comment]
It should be fixed in last upbge master then I close (not fixed in blender but we'll take their fix once they have fixed it)
