### ISSUE TITLE
Last  version UPBGE 3.0  for linux 64 crashing

### ISSUE THREAD

**Issue by fumangy** [UPBGE/upbge#1557]
Last version UPBGE for linux 64(](url)UPBGE-EEVEE-Linux64-2021-09-16) crashing with undo (ctrol +z) or push key  (P) in viewport.
[blender.crash.txt](https://github.com/UPBGE/upbge/files/7188579/blender.crash.txt)
![Crashing](https://user-images.githubusercontent.com/29063438/133857520-fb062860-f2aa-481a-a70c-b74b77cebc68.png)

**Comment by lordloki** [comment]
Do you have a test blend?. I just checked and it doesn't crash for me with basic undo or pressing P

**Comment by fumangy** [comment]
It happens when I make an append another blend file, open other blend file.


[blender.crash.txt](https://github.com/UPBGE/upbge/files/7188703/blender.crash.txt)







https://user-images.githubusercontent.com/29063438/133859861-babaa634-9a47-4d5a-bb84-4e060009e068.mp4

**Comment by fumangy** [comment]
Now I have tried it with another blend file and it has not crashed. It may be that the other files are corrupted. You have been able to perform an append test.

**Comment by fumangy** [comment]
It seems a random behavior since some files do not crash but others crash, especially when I make an append.
No file crashing.

https://user-images.githubusercontent.com/29063438/133863140-eec254dc-25c3-49a1-bace-eafd4c4926cc.mp4

**Comment by fumangy** [comment]
I share one of the files that is crashing, when making an append.

[Model_Test_1.zip](https://github.com/UPBGE/upbge/files/7188815/Model_Test_1.zip)

**Comment by youle31** [comment]
There were recent commits related to append... I'd suggest to keep a version from september beginning for now.

**Comment by fumangy** [comment]
OK ,thanks .

**Comment by lordloki** [comment]
It also occurs in last blender . When you do an append and after an undo then crash.
fumangy, can i use your file to make a bug report in Blender?

**Comment by fumangy** [comment]
@lordloki  yes, you can.

**Comment by youle31** [comment]
It should be fixed in last upbge master then I close (not fixed in blender but we'll take their fix once they have fixed it)
