### ISSUE TITLE
can we get culling occlusion on UPBGE 3.0

### ISSUE THREAD

**Issue by HelloAmElio** [UPBGE/upbge#1564]
culling occlusion is still not implemented it will be nice to have it back on UPBGE3.0

**Comment by youle31** [comment]
Spam then ban

**Comment by HelloAmElio** [comment]
this is my first time posting I was jus requesting this future for UPBGE 3.0

**Comment by lordloki** [comment]
![Screenshot_2021-09-30-20-42-21-378_com brave browser](https://user-images.githubusercontent.com/1015605/135512645-4caf9205-2f71-4d46-b773-e9c9506d8fac.jpg)
I answered you the same question yesterday.

**Comment by youle31** [comment]
I blocked this user on my side as you already answered to him yersterday lordloki

**Comment by HelloAmElio** [comment]
sorry i forgot about that post don't know why github didn't notify me when my post was replayed, sorry for any inconvenient.

**Comment by EndSSgamesStudio** [comment]
eevee render already does the occlusion culling technique?

**Comment by HelloAmElio** [comment]
> eevee render already does the occlusion culling technique?

no upbge 3.0 uses eevee as it's render core and it don't support occlusion culling
