### ISSUE TITLE
easiest setup seems not to work...

### ISSUE THREAD

**Issue by luckychris** [UPBGE/upbge#1573]
Hi devs,

on my mac i have this setup:
![image](https://user-images.githubusercontent.com/232549/137625905-585131a4-8385-4119-867e-315d051aa94b.png)

if i hit P for play and then W ...nothing happens. my cube won't move at all.

i just tried out the newest alpha version.

**Comment by luckychris** [comment]
Thank you for your quick reply. Did you check on a macbook? or the windows version?
I could verify that my own file did work on an older mac version of UPBGE and the exact same file does not work on the newest version. Same with your simple_test.blend file.
I am talking about this version, which doesn't work:
![image](https://user-images.githubusercontent.com/232549/137650646-6a090080-0da3-48b5-a1d6-87b4cf2176e8.png)

**Comment by lordloki** [comment]
I just uploaded a new build for MacOS. I tested in MacOS Catalina and it works ok. Could you test with this build?

**Comment by luckychris** [comment]
this version 

![image](https://user-images.githubusercontent.com/232549/137671448-5df313a2-3a8a-4d97-9fd9-9d7139977e60.png)

works! Thank you for this fast fix!!!
