### ISSUE TITLE
no compatible graphics card on newer versions

### ISSUE THREAD

**Issue by User202207** [UPBGE/upbge#1575]
using the UPBGE-EEVEE-Win64-2021-06-15 version i am able to select my graphics card and processor as valid rendering devices for OpenCL, but on the newer versions i have tried up to the latest alpha I am not able to select my gpu, and maybe even cpu, and in the past months i had issues with it finding my hardware on linux versions. This is a report for the alpha builds.

**Comment by lordloki** [comment]
Currently, cycles (cycles-x) droped the opencl support. OpenCL for AMD will be replaced by HIP but the patch is not committed yet. https://developer.blender.org/D12578
Closing the report. Thanks for the feedback.
