### ISSUE TITLE
0.31a Edit Object Actuator  > Add Object doesn't add anything

### ISSUE THREAD

**Issue by Ifelsethendo** [UPBGE/upbge#1581]
Recipe: 
1. make a  second object to add
2. set it's physics to dynamic
3. add sensor "Always"
4. add actuator motion >  Y -0.1
3. to first object add sensor > Mouse> Left Button
4. Add Actuator Edit Object > Add Object,
5. Set the target object to the second object
6. enter play mode
7. mash left button
8. Nothing happens

**Comment by youle31** [comment]
Add Object seems to work as expected in 0.3 for me.

You can read that: https://github.com/UPBGE/upbge/wiki/Release-notes-version-0.3.0#spawn-gameobjects
and that: https://github.com/UPBGE/upbge/wiki/Release-notes-version-0.3.0#layers-replaced-with-collections

**Comment by Ifelsethendo** [comment]
Ah okay clicking the "Hide in viewport" eye in outliner started the spawning. Not intiutive at all.

**Comment by RandomPandaStudios** [comment]
> Ah okay clicking the "Hide in viewport" eye in outliner started the spawning. Not intiutive at all.

Not really... It's in the official docs
https://github.com/UPBGE/upbge/wiki/Release-notes-version-0.3.0#spawn-gameobjects
