### ISSUE TITLE
Left Mouse Button triggers logic brick script when click is outside of objects

### ISSUE THREAD

**Issue by Ifelsethendo** [UPBGE/upbge#1583]
Recipe:
View from Top camera (7 key)
Add Mesh "Plane" 
Name the object "basic_button", name the mesh the same
duplicate it twice
name copies to "MouseOver" and "MouseDown", name the meshes as well.
Make "buttons" different colors so you can tell something is happening

Select "basic_button"
Logic Bricks Editor:
Add Sensors:
MouseOver
MouseOver Invert
Left Mouse
Left Mouse Invert

To MouseOver  wire Actuator: Edit Object; Replace Mesh > MouseOver
To MouseOver Invert wire Actuator : Edit Object: Relace Mesh > basic_button
To Left Mouse wire Actuator: Edit Object: Replace Mesh > MouseDown
To Left Mouse Invert wire Actuator: edit Object: Replace Mesh > basic_button

Okay... test in game, mouse over, click, all good?

Exit Play Mode

Duplicate "basic_button" , move it somewhere you can see it in play mode.
Enter play mode, click outside of the button, both buttons change to "MouseDown" state, and stay there.
Exit play mode
Delete the duplicate "basic_button"
Re-enter play mode
Click outside of the button, it hilights and stays lit, ie, it trigger when it shouldn't and  it doesn't trigger the mouse up state at all.

Apparently there is a ray from camera to button during mouse over, but once mousedown is sent it stops using that ray to determine whose logic brick should run or if they should run at all, it just broadcasts the message into the wild.
This bug goes back at least all the way to 2014 : https://youtu.be/7mTxrtnGxgM

I thought I could limit who gets told what with a property but that didn't work. I thought maybe different material names and collision check would limit who gets mouse click, or more specifically WHEN they get it, Because obviously nobody should get it they are not getting clicked on.  

If I wire collision sensor to the AND controller of the mousedown and test for collision with the button's material, it doesn't trigger the mouse down state at all, which is completely illogical.

I tried a ray sensor, set its max distance to 99999, tested for the "name" property on the object, and the material, and it disabled the Left Click as well. That doesn't make any sense either. Well it would make sense outside the button.  I'm used to a ray from the camera to mouse location and colliding with the object under the mouse., maybe thigns are different here.

This method of building UI elements by swapping messhes is a bit convoluted. There should be a way to change material values from the logic bricks to do quick and dirty mouse-over/mousedown/mouse-up effects we were doing in Photoshop 20 years ago.

Ultimately this mass broadcast of mousedown  to objects not under the mouse is just buggy..

**Comment by youle31** [comment]
It is really too hard to understand reading the text, and the procedure described is also too complex... We can eventually discuss that on discord. The best would be to find a really simple way to reproduce the issue with a very simple .blend test file.
I close this report and redirect you to discord channel where you can eventually find help, give a simpler explaination of the issue...
