### ISSUE TITLE
LOD Crashes Game when Using Edit Object > Add Object

### ISSUE THREAD

**Issue by TriVoxel** [UPBGE/upbge#1584]
When spawning an object that has LOD with `Edit Object` > `Add Object`, the game will immediately crash. Has been a reproducable issue from builds ranging from at least September to current Master. System is macOS ARM64 but likely can be reproduced on Linux x86_64 and probably other platforms. This is a major issue for anyone attempting to optimize projectile models/instanced entities like enemies.

To reproduce this issue, download the file, press `P` to play, and press SPACE. It should add a cube to the scene with some LOD models stored in a hidden collection. It will instantly crash. Logic is applied to the empty and the "Cube" object.

[LOD Test.zip](https://github.com/UPBGE/upbge/files/7536128/LOD.Test.zip)

**Comment by youle31** [comment]
Normally fixed here: https://github.com/UPBGE/upbge/commit/e3685af2c0b037f792b46b5d1b50fdab21dc5e2b

Thanks for report! You can close it when you will test in next builds (in some days/weeks, if you don't notice issues). Thanks

**Comment by youle31** [comment]
I close this task as it seems solved. Thanks for report.
