### ISSUE TITLE
UPBGE 0.2.5b How to make camera follow Group Instance

### ISSUE THREAD

**Issue by Luckykov** [UPBGE/upbge#1589]
Hi, I'm not sure this is the best place to ask a question or a request if you have a problem. put in the comments and remove the question, I'm doing some tests in a game, where the Player can call various types of vehicles with variable numbers of loose objects, I thought I'd use Group Instace for this, which makes the job a lot easier. however, I had a problem. the Group instance uses a system where it has an Empty and appears to virtualize the real object. the problem is that I can't make a Camera follow the Group Instance, because the Instantiated object can even move, but the Empty doesn't move, and the camera copies the Empty's position. I would like to know if there is any resource, which makes Empty Follow the object instantiated, or if it is a non-existent resource.

I will leave a test file attachment. the file name is "Instace.rar"

https://drive.google.com/drive/folders/13_7hBkq4Zs6UG2AOjTq16DehVTrRa-YG?usp=sharing

**Comment by BluePrintRandom** [comment]
added = own.scene.addObject('Group_instance_name')
own.scene.obects['Camera'].actuators['Camera'].target = added.groupMembers['SomeObjectName']

**Comment by BluePrintRandom** [comment]
we can use object.groupMembers to access all the objects spawned with the empty

**Comment by Luckykov** [comment]
this is perfect, should solve my problem and help with others. Tks BluePrintRandom.
