### ISSUE TITLE
Tx and RX Message with logical node - CATCH node?

### ISSUE THREAD

**Issue by elioaccess** [UPBGE/upbge#1593]
Hi everyone, with UPBGE 0.3 I’m starting to use logical nodes and in particular I wanted to understand how to “receive” a message. Which node should I use?
I’ve seen Catch, it looks like what I need but I can’t get it to work; it never activates.
Thanks for answers.

**Comment by lordloki** [comment]
Hi @elioaccess . These issues are to report bugs in the software. To get information about how to use you can join to discord (there is a specific channel about logic nodes where the people can help you).
Here is the link: https://discord.gg/H4GTYBvE

**Comment by lordloki** [comment]
Closing the report now. Thanks for the feedback
