### ISSUE TITLE
Animating rigged characters with normal map

### ISSUE THREAD

**Issue by andrea1994** [UPBGE/upbge#1597]
very low fps when playing an animation on an armature with a mesh whose material has a normal map node attached

the fps returns to normal when the animation stops or detaches the normal node from the material

**Comment by lordloki** [comment]
Yeah, we know that the normal map node is very slow.
There is an addon included with UPBGE that it mitigates this issue:
![image](https://user-images.githubusercontent.com/1015605/145223484-7aa70fec-13f7-487e-925e-77afcf2433c1.png)

https://user-images.githubusercontent.com/1015605/145223536-dba8d3a2-dd86-4454-a51e-1cfe22a7fc3d.mp4

Thanks for reporting. We will try to include this normal map node optimized into shader editor nodes.
Closing the report now.

**Comment by andrea1994** [comment]
thank you so much, worked like a charm
