### ISSUE TITLE
Logic Bricks > Edit Object > Add Object  Inconsistant Strange Behaviors

### ISSUE THREAD

**Issue by Ifelsethendo** [UPBGE/upbge#1600]
If I have two objects with Add Object brick, sometimes the wrong object spawns 
Like sometimes my player object spawns an enemy instead of a bullet.
Sometimes objects spawn on screen...they don't appear to have physics, they just appear and remain 

Mash move around and the space bar in this blend file for about 1 minute and you should see the weird behavior
https://github.com/Ifelsethendo/Blender-Game-Engine-Templates/blob/main/Rotation_Shooter.blend
This one as well
https://github.com/Ifelsethendo/Blender-Game-Engine-Templates/blob/main/CUBE_INVADERS.blend

For some unidentified reason the spawned objects inherit the scale of the spawner object in this blend file
https://github.com/Ifelsethendo/Blender-Game-Engine-Templates/blob/main/SideScroll_Shooter.blend

I just ran it and the objects were the correct size, then suddenly they started inheriting the spawner scale

Sometimes objects despawn without warning or reason, I'll be blasting away and then poof my player object despawns, sometimes bullet objects despawn a few units in front of my player object.

**Comment by youle31** [comment]
bug with "full duplication" option in the first 2 .blends

**Comment by youle31** [comment]
There is something wrong with objects converted during runtime.

When I apply this patch, sometimes it tells me that the newly added Object is already converted:
[p.zip](https://github.com/UPBGE/upbge/files/7698095/p.zip)

I don't understand why for now.

**Comment by youle31** [comment]
I reopen this as I didn't check all the .blend (it was closed automatically when I referenced the issue in my commit).
I'll check the other .blend later.
