### ISSUE TITLE
defult location spawn physics clash 

### ISSUE THREAD

**Issue by corryVanr** [UPBGE/upbge#1606]
good evening / morning 
im having a very odd bug on the new 0.3 release dated 4th December 2021

i was using 0.3 alpha before 
my problem : i have a set default and load coordinates script it loads my character to the starting pod ,it works 100's on the 0.3 alpha (and all previous versions ) but on the 4th Dec release i have a few odd bugs my staring coordinates are (-0.30 ,-30.89 ,49.90) and it initializes itself before all other scripts , but if i run it thru the latest release my 'Z' coordinate it spawns @ (-0.30 ,-30.89 ,**_-793.84_**) or (-0.30 ,-30.89 ,**_-909.73_**) ,
if go and lock my 'Z' _concatenate_ i load in as i should but then i obviously just over everywhere if i select true pulse and Tap it completely freaks out (i understand that it should not be activated like that but that's the only way i can load in )
I've checked the physics properties where i spawn in I've even set the objs around it to no collision ,
there is a very weird margin where i an spawn in on the Z axies nd it is (42 to 45) ,even if i move my entire scene to accommodate these coordinates the same issues will occur 
(if i force the script to start it spawns me in but i cannot move then )

<img width="404" alt="Screenshot 2021-12-12 forcing script to start logic" src="https://user-images.githubusercontent.com/61900085/145723062-14d10954-7944-4c88-a26d-4bcfc7294038.png">
<img width="523" alt="Screenshot 2021-12-12 forcing script to start" src="https://user-images.githubusercontent.com/61900085/145723063-8aeaad12-30ce-41d5-85d3-365c914fe038.png">
<img width="914" alt="Screenshot 2021-12-12 Z locked" src="https://user-images.githubusercontent.com/61900085/145723065-a0b47649-4fe3-4745-a6dc-1a67d923bb35.png">
<img width="927" alt="Screenshot 2021-12-12 Z not locked" src="https://user-images.githubusercontent.com/61900085/145723071-dd13b079-33e1-4e62-9127-27da6b556665.png">

<img width="1034" alt="Screenshot 2021-12-12 scripts" src="https://user-images.githubusercontent.com/61900085/145723211-a37d0e1a-10b3-4f3f-911f-e4bd23fb73e3.png">

**Comment by lordloki** [comment]
Could you post a blend showing the issue?
From images I can see that you are trying to put the player01Position at (-0.30, -30.89, 47) but your saying that you starting coordinates are (-0.30 ,-30.89 ,49.90).
Then I don't see if "defult" sensor really exist or maybe is a type error and the sensor is called "default".
I need more info (the blend) to evaluate if there is an issue.

**Comment by corryVanr** [comment]
i can see the confusion i apologize  
the picks i posted was me forcing it to start ,as its the only way i can get it 'running' but then my Z position would be locked (as i have to lock it at the physics tab to get it to be where it roughly should be 
you'll see the literal sensor named always i enabled 'Tap' ,as i have to click it to get a forced start ,this is in my main game and i don't have it in a separate blend file ,i will make a separate blend file for you and post it tmrw night 13 Dec ,(i will start working on it now nd see if i can make a smaller concept)
in the console it does show what it must print ie..''initialize and start'
also i only have the issue with the new variant on the older versions of upbge 0.3 alpha there is no issue
 i  also included now where it should spawn and my logic brick layout ,hope this helps in the interim ,
and thanks for the quick response as always 
<img width="635" alt="Screenshot 2021-12-12 spawn point" src="https://user-images.githubusercontent.com/61900085/145728437-7141d020-b3f9-4dad-953b-3a3d9d059473.png">
<img width="593" alt="Screenshot 2021-Code_1" src="https://user-images.githubusercontent.com/61900085/145728440-20aa2ba5-e791-46d6-a474-a5dbf9729d8e.png">
<img width="635" alt="Screenshot 2021-Code_2" src="https://user-images.githubusercontent.com/61900085/145728441-b674f1d5-0974-4a23-a926-9a6354bcb0b2.png">
<img width="779" alt="Screenshot 2021-Logic setup 1" src="https://user-images.githubusercontent.com/61900085/145728442-43f63b1e-b082-40d4-8c6c-ede0021ddc7a.png">
<img width="758" alt="Screenshot 2021-Logic setup 2" src="https://user-images.githubusercontent.com/61900085/145728444-3898198c-b12e-46d0-8458-3bc7326976a1.png">

**Comment by corryVanr** [comment]
uploading the gutted level to a shareable link will take a while about 5 hrs ,will share it on the 13th 
in this gutted variant its working as it should ,but in my main game i still have the issue as described above 
Ive gone as far as to del everything in the main area

**Comment by corryVanr** [comment]
just deleted everything in the first level nd i could load in 
i honestly have no idea what is causing this issue

**Comment by lordloki** [comment]
For me, in a simple blend. is working right:
![image](https://user-images.githubusercontent.com/1015605/145844968-77ac3f42-728f-4949-a877-7d09dfcf3187.png)
![image](https://user-images.githubusercontent.com/1015605/145845039-4df7c1b9-8d9e-40c2-bd5a-c22a5076bb43.png)

**Comment by corryVanr** [comment]
I see i had the same experience, as when i del everything in my scene the script works

I've tried setting it to first priority it doesn't make a difference,must i still share my link as it does work like you stated with a simple setup

Do you think it could be a Collison isseu or a some form of script interference as i have about 5 more scripts running at that high priority?

The obj pod where it should spawn in is a instance copy (Alt D)  of the original pod,
Do you think that might be the problem?

I knw I'm throwing allot of hypotheticalls around and i really appreciate your help

**Comment by corryVanr** [comment]
Now the engine shuts down if i start with embeded start nd if i try standalone start it kills the console sofar my game is 980mb nd it's just my start lobby and one half level
Is there a memory cap?

On the alpha 0.3 everything works 100's,

**Comment by lordloki** [comment]
I don't know. I need a blend to check the issue. Other than this I can't help you because everything is so confuse

**Comment by corryVanr** [comment]
https://drive.google.com/file/d/1Ttv6tGIREiYI8GlFljXR2zWjsjp5PdXm/view?usp=sharing

**Comment by lordloki** [comment]
There are a lot issues due to use incorrectly the python module but there is no issue related to player position:
![image](https://user-images.githubusercontent.com/1015605/145860361-87762007-c75c-4628-9324-4900115cb60d.png)

**Comment by corryVanr** [comment]
all those errors are due to me  literary just un-linking the major scripts ,there are some logic bricks and properties trying to communicate across scenes,I just gutted my main game file to get a blend file out ,
its looking for a save file nd double checking witch portals are active ,where the last checkpoint was and witch equipment was looted ,if i use my save files i don't get those errors ,i also removed all textures nd main materials

**Comment by corryVanr** [comment]
or do you mean my architecture of how it calls for the data is wrong in the module

**Comment by lordloki** [comment]
I was saying that in the console window were reporting several issues due to "no module named XXXXX". If you detached those scripts then those issues come from there.

Anyway, the player position is correct.

**Comment by lordloki** [comment]
Additionally, you have a warning about empty.006 that it won't spawn because you have put it in a hidden layer (click in the eye in the outliner ![image](https://user-images.githubusercontent.com/1015605/145864453-0bc76c15-8350-4b2a-a983-012bc72bd6b6.png) )

**Comment by corryVanr** [comment]
Ok Thank you (it's my hover menu that's not spawning haha thanks)

But atm the engine just keeps bombing out on me I'll download it again nd have a look to see if it'll work then,
I'll also del all objs in that level nd add them one by one nd see what is causing it to clip nd shoot out into space 
Like it's sutch a odd thing to accor

Do you have any final suggestions?
Or anything that can cause this isseu ?
I knw this sounds like a broken record but everything works fine on the previous versions only on the new release this happens

**Comment by lordloki** [comment]
I don't know how to help you. Maybe you can pass me all the game (in private if you want) and I will test in old upbge 0.3 alpha and new ones to see if anything related to upbge or the game

**Comment by corryVanr** [comment]
Ok lol if you are up to it... i wouldn't mind at all,not everyday a developer offers help 

You are awesome !!!!!!

**Comment by youle31** [comment]
I close this report as it was more a help request and that lordloki even offered a personal help. Thanks for comprehension.
