### ISSUE TITLE
Mouse movement with mouse look doesn't work in 3.0

### ISSUE THREAD

**Issue by rollalt** [UPBGE/upbge#1607]
When creating a cube as player adding sensor mouse movement and actuators mouse look doesn't work! I need to create a second cube and add the same. After the first cube will work. I think it has to do with .null.

**Comment by youle31** [comment]
I did not notice an issue from he given informations.

Please follow this guide: https://github.com/UPBGE/upbge/wiki/Report-a-bug-guide to report an issue.

Note that in upbge 0.3, mouse movement sensor needs to have pulse mode enabled to work properly.
