### ISSUE TITLE
Soft shadows refresh continuously in viewport, even with no interaction

### ISSUE THREAD

**Issue by issimissimo** [UPBGE/upbge#1609]
Hello, I'm totally new to UPBGE, and I've made a simple scene with a cube and a light with soft shadows.
The shadows are continuously refreshing in the viewport (render mode) even if I don't do anything, about every second.
In Blender 3.0 with the same scene this does not happen.
Is there something I have to tweak to avoid this very annoying effect?
Many thanks!

**Comment by BluePrintRandom** [comment]
In upbge you have to set the number of samples per frame to the like 4 or 8
to get realtime soft shadows,

In the viewport of you go into fly mode the shadows redraw continuously

**Comment by issimissimo** [comment]
Thank-you again BluePrintRandom,
I'm not in fly mode, or walktrough mode, just in the standard perspective view (that I suppose that should work in the same way as the Blender perspective view).
I've increased the number of "samples per frame" from 1 to 4 (or 8), but nothing change, the "issue" is still there.

Here's record of the viewport to better show the problem
[https://www.issimissimo.com/TMP/20211217-231159.mp4](url)

As you will see the shadow redraw continuosly also in perspective view

Many thanks for your help!

**Comment by lordloki** [comment]
This is the normal behaviour of Blender viewport, we can't change it. Regarding to embedded or external player you can mitigate this issue increasing the samples per frame, using volumetric blend's option and reducing samples.

Anyway, to stay that this is a known issue that we will see whether is solved with the Blender eevee rewrite and vulkan. Closing this issue as is already in our TODO.
