### ISSUE TITLE
How to create a splash screen for runtime?

### ISSUE THREAD

**Issue by issimissimo** [UPBGE/upbge#1610]
Hello, I've exported my scene as runtime for PC (file->export->Save as game runtime), and the build is quite huge (more than 1GB).
So it take a long time to load, even with SSD.
Is there a way to create a splash screen, to just let people to know that something is going during loading?
With UE I'm used to create a secondary scene very light for this purpose, and load the 2nd one in the background.
Is there something like that with UPBGE?
Many thanks!

**Comment by BluePrintRandom** [comment]
You can load everything into the main blend using bpy one object at a time
and update a progress indicator as it's going

**Comment by issimissimo** [comment]
Thank-you  BluePrintRandom,
do you mean I should use Python for this stuff?
I'm used with C# and JS, never used Python... :/
Is there maybe a visual scripting add-on (like BP on UE)?

**Comment by BluePrintRandom** [comment]
Logic nodes addon does quite a bit, but I am unsure if it wraps bpy ability to load files from disk,

Once we have a bpy object, the scene can convert it to a game object,

After I get home I can make a example file.

**Comment by issimissimo** [comment]
Thank-you so much!!!

**Comment by lordloki** [comment]
I close this issue as this issue is not a software issue but a "how to use the software" issue.
Thanks for the feedback. Closing the issue.
