### ISSUE TITLE
New navmesh not working 3.0

### ISSUE THREAD

**Issue by rollalt** [UPBGE/upbge#1616]
The navmesh issue still has not been resolved!
You know about the issue from many years ago, but is still not a priority!

**Comment by youle31** [comment]
I tested 2 days ago and all was working as expected. I did a gif on discord.
Please follow this guide before opening an issue: https://github.com/UPBGE/upbge/wiki/Report-a-bug-guide

We can't do anything with provided infos, therefore I close this issue.

**Comment by rollalt** [comment]
Hi Youle,
It was my error. Basically I was trying to generate a path using array and curve but on array join surfaces must be ticked.
