### ISSUE TITLE
One point light 10 fps drop

### ISSUE THREAD

**Issue by IcyChills** [UPBGE/upbge#1618]
Hi,

I recently downloaded the 0.3 release from the web site.
I created a basic scene which uses Irradiance, Cubemap, all the Post processing enabled and four materials.

The scene runs at 60fps until I add in one point light which drops the fps down to 50 fps.
This was tested on 8-core, 16gb and GTX 1050 Ti system.

Not sure why it gets the performance hit.

Other than that issue, UPBGE is quite impressive.

**Comment by BluePrintRandom** [comment]
We should see a larger boost in lighting performance after eevee rewrite is
merged, it has tiled render / clustered light cuts / virtual shadow
mapping.

**Comment by IcyChills** [comment]
Thanks for letting me know BluePrintRandom. I'll keep a look out for the new changes. Really would love to release a commercial title using UPBGE.

**Comment by BluePrintRandom** [comment]
https://developer.blender.org/T93220

**Comment by IcyChills** [comment]
Some nice changes on that list, will continue on assets in the meantime. Closing as this isn't an issue until the changes come.
