### ISSUE TITLE
add obj-no works

### ISSUE THREAD

**Issue by 958479612** [UPBGE/upbge#1622]
![9E2VEZ8K(UZ907 CUZIT5 K](https://user-images.githubusercontent.com/82086788/147645498-d2de5728-c5be-417b-9a85-a121c818acb3.png)
add obj-no works

**Comment by lordloki** [comment]
No blend to investigate the issue. Have you hide the object to be added?

**Comment by 958479612** [comment]
> 没有混合来调查问题。是否隐藏了要添加的对象？

Thank you for your reply, follow your prompts, the problem has been resolved and this operation is not very friendly to new users.
