### ISSUE TITLE
0.3 Rendered Viewport dead-cells

### ISSUE THREAD

**Issue by Michael-A-Potter-96** [UPBGE/upbge#1623]
I downloaded 0.3 for linux today and moved to the shading and rendering tabs to find... this.
![Screenshot_2021-12-29_10-20-06](https://user-images.githubusercontent.com/96836673/147684528-1e6cc2db-b75c-4c54-aeac-76e2b8dca837.png)
![Screenshot_2021-12-29_10-20-33](https://user-images.githubusercontent.com/96836673/147684530-917113d1-ddee-4f95-9f66-1d906d9360fd.png)
![Screenshot_2021-12-29_10-22-32](https://user-images.githubusercontent.com/96836673/147684532-43a4c8f4-9fea-4dc3-99d0-37bc4bf09fdb.png)
![Screenshot_2021-12-29_10-22-52](https://user-images.githubusercontent.com/96836673/147684533-58841937-b1a1-43fa-9927-0f212b091f91.png)

Any ideas on why the renderer is behaving like this? For more information about my device, I am running Linux Mint 20.2 XFCE, and have a 4GB GDDR5 GEFORCE GTX1050Ti.

**Comment by lordloki** [comment]
It is strange. I tested in Linux and it worked well so far. Are you using Nvidia drivers or legacy ones?

**Comment by Michael-A-Potter-96** [comment]
nvidia-driver-470 ver 470.86-0ubuntu0.20.04.2

**Comment by lordloki** [comment]
For the last 6 months I tested the builds in different linux and hardware but I can't reproduce this issue.

Have you tried to update the drivers? Maybe is a hardware issue.

**Comment by Michael-A-Potter-96** [comment]
I updated my drivers a few weeks ago and the issue seems to have resolved itself. Perhaps there was an issue with one of the previous updates that caused the issue that has been patched.
