### ISSUE TITLE
Logic Nodes Mouse look

### ISSUE THREAD

**Issue by IcyChills** [UPBGE/upbge#1625]
Not sure if I'm doing something wrong on my side with the node.

![image](https://user-images.githubusercontent.com/72191422/148045440-52a86df6-8006-4b6f-bf1b-bb94d4d79c3d.png)

The Cap causes the camera to look only forward and can't look up, looking down causing the camera to look through the body until it looks behind. The camera is facing in the Y+ direction.

**Comment by IcyChills** [comment]
Ok I tried a new setting which fixed the issue. Instead of -89 and 89, I used 1/179 degrees. 180 degrees will cause the camera to flip over.

![image](https://user-images.githubusercontent.com/72191422/148046374-1473fb97-1708-4905-88e2-8c3877c8ea17.png)

Closing this issue. Hopefully it helps someone else.

Also please name the the two Look nodes for mouse and joystick. The node search results lists them randomly. Just something I noticed.

**Comment by IzaZed** [comment]
Normally that shouldn't happen
I've had cases where the camera transformation was just weird, try parenting the camera to an empty and use that for head rotation, I feel that makes it a little clearer

I'll rename them
