### ISSUE TITLE
0.3: GPU latency profile issue/weirdness

### ISSUE THREAD

**Issue by youle31** [UPBGE/upbge#1626]
Link to discord discussion in 0.3 devtalk: https://discord.com/channels/481036814539292672/623603338197467147/928710319243661423

Should we call glFinish before swapbuffer at the end of draw loop?
TODO: Find few infos on the net and test.

**Comment by Mattline1** [comment]
We'll need to be mindful of performance implications. Quick tests for the code in the discussion result in losing ~2ms per frame in my tests.

**Comment by youle31** [comment]
Thanks for the comment. Another proposed solution (by someone on discord) was to remove GPU latency from profile, which seems the best solution

**Comment by youle31** [comment]
I read this: https://blenderartists.org/t/what-does-it-mean-when-your-gpu-latency-is-through-the-roof/633944/4
As gpu latency gives an indication, we can keep it in profile.
Idk if it is documented somewhere. I'll close this issue for now as finally it has an explaination.

**Comment by lordloki** [comment]
I will took that explanation and I will include in our manual. Thanks for the investigation.

**Comment by youle31** [comment]
Thanks very much lordloki!
