### ISSUE TITLE
Rightclicking "Embedded start" doesnt show an "Add shortcut" button.

### ISSUE THREAD

**Issue by ItsCubeTime** [UPBGE/upbge#1634]
Now this might seem silly, but it has bothered me for quite some time that I cant simply right click this button to add a hotkey to it. Strangely the option does appear for "Standalone Start" which appears perfectly functional.

What I see:
![image](https://user-images.githubusercontent.com/20190653/149189090-553a2594-1933-4802-b93c-9696764f27b3.png)

What I wish I saw:
![image](https://user-images.githubusercontent.com/20190653/149189162-563f5f67-1870-4e2d-9c49-36f4cbe139e8.png)

**Comment by RandomPandaStudios** [comment]
The default shortcut for embeded start is [P].
If you want to change the default go into your User Preferences and find the shortcut binded to [P].

![image](https://user-images.githubusercontent.com/69180012/149563756-d00e05da-75a0-4b35-992c-877c6742b438.png)
