### ISSUE TITLE
Error with _init_.py, line 19

### ISSUE THREAD

**Issue by MelvinG24** [UPBGE/upbge#1638]
Every time I play the game engine I get the following error but I do not know why?

UPBGE __init__.py", line 19, in Update_GamePropertyobj = context.objectAttributeError: 'NoneType' object has no attribute 'object'[Logic Nodes][NOTIFICATION] Building Logic Trees on Startup...

![image](https://user-images.githubusercontent.com/23342477/150281418-b3c5c3c3-d44d-4565-84dc-73bac8ad9888.png)

**Comment by RandomPandaStudios** [comment]
Just a comment, the addon needs to be updated to V2 anyhow.

**Comment by lordloki** [comment]
Yeah, I know. I will update to V2 when I have a bit free time. I move this issue to addons repository
