### ISSUE TITLE
Broken images on site

### ISSUE THREAD

**Issue by koorya** [UPBGE/upbge#1639]
https://upbge.org/#/documentation/docs/latest/manual/manual/physics/introduction.html
At that page no one image is not available. Please, fix it.
Thank you!

**Comment by lordloki** [comment]
I move this issue to docs repository. Thanks for reporting!.

**Comment by rpaladin** [comment]
The issue with missing images for that page is now resolved.
Note, images are still from UPBGE 0.2.x and not 0.3.x.

Thanks again for reporting @koorya!
