### ISSUE TITLE
Collision detection - self.object.collide missing in 0.3.0 ?

### ISSUE THREAD

**Issue by kolos26** [UPBGE/upbge#1640]
Hi,

I tried to write a simple collision detection script in UPBGE 0.3.0. I found this code which worked in older UPBGE versions correctly, in this video: https://www.youtube.com/watch?v=VECpMcbtPxc

This is my code

`import bge
from collections import OrderedDict

class Component(bge.types.KX_PythonComponent):
    args = OrderedDict([])
        
    def start(self, args):
        pass
    
    def update(self):
        scene = self.object.scene
        
        plane = scene.objects["Plane"]
        
        if self.object.collide(plane)[0]:
            self.object.endObject()`

And this is the error message:

`[ERROR] KX_PythonComponent[Component] - Failed to invoke the update callback.
Traceback (most recent call last):
  File "/home/frobert/Desktop/blender/collision.py", line 15, in update
    if self.object.collide(plane)[0]:
AttributeError: 'KX_GameObject' object has no attribute 'collide'
Blender Game Engine Finished
`
I prefer to write the game via python script using no logic bricks. How can I use collision detection in python?
Thanks for this wonderful program, this new version seems really good.

Kind regards,
Kolos26

**Comment by RandomPandaStudios** [comment]
Unfortunately `KX_GameObject.collide()` only exists currently for UPBGE 0.2x.
Perhaps @mysticfall could port it to UPBGE 0.3.

@kolos26, if you're comfortable with using Python Controllers you can use `KX_GameObject.collisionCallbacks()` to create your own custom collision checker system.

```
import bge

def check_collision(hitObj):
    
    scene = bge.logic.self.owner.scene
    plane = scene.objects["Plane"]
    
    if hitObj.name == str(plane):
        hitObj.endObject()

def main(self):
    
    bge.logic.self = self
    self.owner.collisionCallbacks.append(check_collision)
```

**Comment by youle31** [comment]
Yeah, apparently this work has not been recovered in 0.3 and is a bit tricky to recover... Better to use collision callbacks

**Comment by kolos26** [comment]
Thanks a lot for your help. I will try these callbacks.

**Comment by lordloki** [comment]
I just recovered collide method in last build. Could you test it? Thanks

**Comment by kolos26** [comment]
Hi @lordloki, Thanks a lot for getting it back :) 
Is there a nightly build somewhere that I can test? (I am not familiar with building C++ code and haven't found any pointers for building upbge from source in the dev docs.)

**Comment by lordloki** [comment]
Yes, there is "nightly" build here: https://mega.nz/folder/t9EEFSaS#JPiOPSInCZyU-SW_-rhEOQ

**Comment by youle31** [comment]
Tested here and it works, thanks!

[coolide_test.zip](https://github.com/UPBGE/upbge/files/7963470/coolide_test.zip)

(comments can still be posted even if issue is closed, i close it for now)
