### ISSUE TITLE
Strange collisions behavior (on dynamics)

### ISSUE THREAD

**Issue by LordCocoNut** [UPBGE/upbge#1642]
I wanted to try, as I formally experienced lot of collision issues with UPGE, and i still got pretty bad collisions behavior.

One issue for example is, that using segmented floor makes simple dynamic cube with force applied to it jump over floor seams. Simply when I create floor from multiple planes, every seem of the floor looks like an elevated obstacle for the cube thats traveling over it.

**Comment by BluePrintRandom** [comment]
I typically have the actors float just a bit over the floor using a ray

**Comment by youle31** [comment]
There are many settings to tweak collision/contacts behaviours (collision boxes/margin/scene bullet physics settings...). But we can't really keep this issue opened because it is too vague and it is not  a bug report. Thanks for your comprhension. For help, you can maybe have advices on discord.
