### ISSUE TITLE
Problem exporting game to EXE

### ISSUE THREAD

**Issue by MelvinG24** [UPBGE/upbge#1643]
Memoryblock free: attempt to free illegal pointer
Memoryblock free: pointer not in memlist

Recently i have gotten this error like HELL in blender. and also i get LOOTS of crashes. can work for 10 sec maybe and this happens. Someone know what it meens?

**Comment by youle31** [comment]
1) Is it crashing in viewport? And is it happening whereas you did not even launch bge?

2) Can you reproduce these crashes in last blender version from here: https://builder.blender.org/download/daily/ (3.1.0 alpha) ?

3) Can you reproduce these crashes in last upbge version from here: https://mega.nz/folder/t9EEFSaS#JPiOPSInCZyU-SW_-rhEOQ (23 january 2022) ?

**Comment by rpaladin** [comment]
Original thread: https://blenderartists.org/t/memoryblock-error-line-in-blender/486732/1

**Comment by youle31** [comment]
Thanks, unfortunatelty there are not enough informations to do something with it. We don't know the version used, no .blend file, no steps to reproduce the bug, then I'll close this report for now. Please follow this guide: https://github.com/UPBGE/upbge/wiki/Report-a-bug-guide to open a bug report.
