### ISSUE TITLE
Overlay collection problem - object visibility with the delay sensor

### ISSUE THREAD

**Issue by pplaty** [UPBGE/upbge#1646]
When using a delay sensor with a visibility actuator on an object in an overlay collection, all values under 22 in the delay sensor will alter the objects opacity, rather than toggling its visibility. A value of 22 or higher will simply not work.
![delay](https://user-images.githubusercontent.com/98545833/151407930-b148c482-fe41-42a8-8062-b475d2f27146.PNG)

**Comment by youle31** [comment]
Fixed here: https://github.com/UPBGE/upbge/commit/a26c9d3c02aeb93d54a34104a7754047f6919958

test file:
[overlay_col_visibility_bug.zip](https://github.com/UPBGE/upbge/files/7955612/overlay_col_visibility_bug.zip)

Thanks for report!
