### ISSUE TITLE
Overlay collection problem - visibility actuator won't work without a hack

### ISSUE THREAD

**Issue by pplaty** [UPBGE/upbge#1647]
When toggling visibility, the actuator requires the existence of a motion actuator with any value different than 0, for it to work.
![keyboard](https://user-images.githubusercontent.com/98545833/151408747-8db6e8e5-8fb3-4b58-8e6c-ab94a2981bca.PNG)

**Comment by lordloki** [comment]
Hi, I just tested and it works ok
![image](https://user-images.githubusercontent.com/1015605/151424583-df4e5190-afe0-454c-ac1d-9301afa7942e.png)
[visibility.zip](https://github.com/UPBGE/upbge/files/7953093/visibility.zip)

**Comment by youle31** [comment]
We,'d need test files in both reports please, thanks.

Else, I think it might be related to SetVisible:
![Capture d’écran 2022-01-27 202005](https://user-images.githubusercontent.com/10052509/151428861-7b607c02-052f-480e-bfc7-c0d9d0268d9b.png)

Where we should maybe use the system used elsewhere in the code to tag objects either during overlay collection render pass, either for main render pass.

**Comment by youle31** [comment]
Fixed here: https://github.com/UPBGE/upbge/commit/a26c9d3c02aeb93d54a34104a7754047f6919958

test file:
[overlay_col_visibility_bug.zip](https://github.com/UPBGE/upbge/files/7955612/overlay_col_visibility_bug.zip)

Thanks for report!
