### ISSUE TITLE
Crash when pressing P then escape then P then escape then P then escape.... quickly

### ISSUE THREAD

**Issue by youle31** [UPBGE/upbge#1649]
If happens with default startscene since: e9f90370ae61d9587a651461f95da8c7af88c1b1

@lordloki : it seems that there is a refcount issue since this commit

**Comment by lordloki** [comment]
Yeah, i confirm. Thanks for the investigation. I revert the commit lefting the `Py_DECREF(joylist);` part only as i checked that doesn't crash

**Comment by lordloki** [comment]
Commited in master. Thanks for reporting. Closing now.
