### ISSUE TITLE
Cameras in a Scene, when parented to an empty with "mouse_look" actuator are reset at world Origin

### ISSUE THREAD

**Issue by Feral3d** [UPBGE/upbge#1658]
If you switch to a camera, that has an empty with mouselook as the parent, when you switch to that camera, the camera will automatically snap to the worldPosition (0,0,0).
You can resolve the issue by running a script at startup where you set the parent once the game has started:

i.e. 
self.scene.objects['camera'].setParent(self.scene.objects['empty_with_mouselook'])

**Comment by Petermhen** [comment]
Which UPBGE version is this taking place on? UPBGE 0.2.5 or 0.3?

**Comment by youle31** [comment]
No answer here. And no test file. I close this report. For reference, bug reports must be formatted using this guide:

https://github.com/UPBGE/upbge/wiki/Report-a-bug-guide

and last alpha release must always be tested to know if the bug is still there in last version.
