### ISSUE TITLE
UPBGE 0.3 crashes if played in duplicated window

### ISSUE THREAD

**Issue by rpaladin** [UPBGE/upbge#1659]
Originally reported by `xXXConkerXXx#4419` in the UPBGE Discord.

## Crash log errors

```
Blender Game Engine Started
Blender Game Engine Finished
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF623D0D5CB
Module  : blender.exe
Thread  : 00002c38
```

## Steps to reproduce

1. Duplicate editor window:
<https://docs.blender.org/manual/en/latest/interface/window_system/areas.html#duplicate-area-into-new-window>
2. Push `P key` to start runtime

**Comment by rpaladin** [comment]
Thanks youle!

**Comment by youle31** [comment]
Thanks for report, sorry about the delay, I forgot about it.
