### ISSUE TITLE
FPS drop when moving the mouse

### ISSUE THREAD

**Issue by HolandonHdunto** [UPBGE/upbge#1669]
On some computers, especially notebooks and computers of certain types, there is an issue where moving the mouse causes a drop in fps, with an unexpected increase in the raster indication. The problem happens even without any objects in the scene.

**Comment by rpaladin** [comment]
One question, are you using true-pulse for your mouselook sensor?
It is now required for all UPBGE 0.2.5+ releases including UPBGE 0.3+.

![image](https://user-images.githubusercontent.com/69180012/155634891-0e3bf6d9-1db6-4b4b-97c2-0ee081d1b338.png)

**Comment by HolandonHdunto** [comment]
Well I don't think the problem is with the sensors or the actuators. Well, I ended up opening upbge and running the game completely empty, without a camera, with absolutely nothing, and even then when hovering the mouse over the window, there was a drop in fps.

Also, the mouse was not wireless.

Blender bge is the craziest thing I've ever seen as it happens that the fps drops with completely empty scenes, the fps drops when adding an object with only one vertex with no material or no other objects in the scene.

 I can only imagine someone trying to open a game with this problem. Or someone trying to create a game with this problem.

**Comment by rpaladin** [comment]
You've already mentioned yourself #1670 that computers without dedicated graphic-cards' cannot function optimally.

<img src="https://cdn.discordapp.com/attachments/403655757091962910/942934792608047204/unknown.png">

By the way, have you attempted to benchmark your computer with Unreal, Unity, & Godot to compare framerate on an empty scene?

**Comment by HolandonHdunto** [comment]
Well unfortunately I don't have either Unreal or Unity, but I have Godot and it worked normally, in fact one of the main reasons to use Godot as well as Upbge is because they are light and take up little space.

Well, it's not logical to add a single vertex object to the scene and still the game crashes. Much less move the mouse over a window with an empty scene and even with the empty scene it still crashes.

If the file is empty, logically it should work correctly without crashing. Otherwise all these upbge 0.2.x or 0.3 performance improvement techniques would be useless.

**Comment by lordloki** [comment]
Could you post the blend file that crash upbge?

**Comment by HolandonHdunto** [comment]
I don't have the .blend file, but I do have the video. https://m.youtube.com/watch?v=_tPeXkjodDU, the project is just a movable sphere, with sphere invocation, the problem continues even in the current version of upbge 0.3.

The computer configuration is:

- Windows 7 Ultimate
- Intel i3 6100 4.30 GHz
-RAM 8G, two 4gb ddr3
- Geforce GT 1030 2GB

    The computer is weak but I think it meets the minimum specifications of upbge 0.3. But the problem must be for those who are going to download a game made on upbge, since they usually don't have a very good computer.

   I think in this case the problem is specifically in eevee, as in the viewport using workBench mode it worked without problems. But this mode despite being extremely limited cannot be exported, as upbge 0.3 exports as eevee.
  Maybe the problem could be a mix of eevee with really bad HD too.

   The case of upbge 0.2.5, with the increase in fps when moving mouse, computer and notebook:

X543UA-GQ3430T
- Intel Core i3 7020U
- 4GB of RAM
- Windows 10

  In this case, I used an external mouse and keyboard.

**Comment by rpaladin** [comment]
>     * Windows 7 Ultimate

> The computer is weak but I think it meets the minimum specifications of upbge 0.3. But the problem must be for those who are going to download a game made on upbge, since they usually don't have a very good computer.

Barely.
Blender 2.93+ is not no longer built on Windows 7 "officially".
UPBGE 0.3+ merely has it available for its users' as a community curtsy.

![image](https://user-images.githubusercontent.com/69180012/155775487-77f036f9-178a-4b8f-9dc1-170ee9429a9b.png)

https://www.blender.org/download/requirements/

Side note, all of these GPUs specs that you have mentioned are respectfully incredibly outdated or not even a dedicated graphics-card (only integrated).
I would strongly suggest upgrading to a more modern computer if possible.

For now, I am closing this issue as it does not appear to be a bug but rather performance complications on the user's end.
Feel free to continue commenting in this thread after it is closed though.
