### ISSUE TITLE
What about FMOD integration?

### ISSUE THREAD

**Issue by jferdelyi** [UPBGE/upbge#1671]
If you don't know, FMOD is a solution for adaptive audio and it is free for non-commercial use.
FMOD Studio is a desktop application for creating adaptive audio content (macOS, Windows, and Linux). It can be exported to many targets such as macOS, Windows, Linux, iOS, Android, Playstation...

I think it would be a good idea to integrate it with UPBGE, but I haven't found anything so far and I don't know if there is any work (planned or in progress) in that direction.

Some useful links:
- Official website: https://www.fmod.com
- Wikipedia: https://en.wikipedia.org/wiki/FMOD
- Very old post on Blender Artist: https://blenderartists.org/t/tutorial-fmod-support-without-re-compiling/372232
- Godot integration: https://github.com/utopia-rise/fmod-gdnative

**Comment by lordloki** [comment]
Hi, 
the FMOD license is incompatible with the UPBGE license (GPL). 
There is some basic features to do adaptive audio (occlusion, room/spaces transitions, etc) using logic nodes.

Thanks for the feedback. Closing the issue.
