### ISSUE TITLE
Last build UPBGE 3.0 crashed when there is  a script in to project

### ISSUE THREAD

**Issue by fumangy** [UPBGE/upbge#1677]
Last build UPBGE 3.0 Alpha 2022-03-12  crashed when there is a scriopt python in to project , this  not happend in the version the UPBGE 3.0 Alpha 2022-03-08 , this worked right. Thanks.

![upbge 3 0 alpha 2022-03-12 ](https://user-images.githubusercontent.com/29063438/158026037-13e1fa1c-7818-40e0-aaec-7200d8bf3e24.png)

https://user-images.githubusercontent.com/29063438/158026021-4ac3403b-ee09-4799-8b0c-45e32c148f5c.mp4

**Comment by lordloki** [comment]
I just committed a fix in master. Could you test it?

**Comment by fumangy** [comment]
Perfect this works, thanks.

**Comment by lordloki** [comment]
Thanks for the feedback. Closing the issue.
