### ISSUE TITLE
upbge crashes if having soft body

### ISSUE THREAD

**Issue by mushroomeo** [UPBGE/upbge#1681]
if i start game with having soft body then whiole upbge crashes.
even with fresh scene and 1 soft body object

upbge version :
![upbge version](https://user-images.githubusercontent.com/9019563/158473784-1deca8a5-d2dc-4f76-8d16-ae8685cb100e.png)

**Comment by lordloki** [comment]
Fixed in master. Thanks for reporting. Closing the report.
