### ISSUE TITLE
(0.3) GLSL shaders don't work

### ISSUE THREAD

**Issue by StickEEEEE** [UPBGE/upbge#1690]
i've been trying to add a GLSL filter to my game for some time, but it turns out GLSL shader filters don't work in UPBGE 0.3 at the moment.
how do i know this? i went to [this blenderartists forum page](https://blenderartists.org/t/rp-resource-post-process-vhs-effect/1322292) and downloaded the blend file so i can see if the shader works or not, and it works in 0.2.5b, but not 0.3.

**Comment by BluePrintRandom** [comment]
Upbge 0.3.0+  uses newer openGL syntax
