### ISSUE TITLE
bge.render.makeScreenshot("filename") saves all white images

### ISSUE THREAD

**Issue by ivanferrier** [UPBGE/upbge#1691]
I have tried to save images from the current camera on two different windows machines, but in both cases the images that were saved were either all white or all black. At fist I thought that this was an error on my part, but I tried running the same code on bge from blender 2.8 and found that the screenshots were saving exactly as expected on both machines.

**Comment by sevi78** [comment]
i still have the same problem on my macbook (10.13.6), so i think it is not fixed. i tried all the renderers, eevee ect... same result. 
i tried with python and Actuators, but only got some "crashed" images, noting to see on them. Could it be that my System is too old?
