### ISSUE TITLE
Beta 3.2 latest versions alpha channel not working properly

### ISSUE THREAD

**Issue by Frankjore** [UPBGE/upbge#1697]
it was not a reflection error, it seems that the alpha channel does not work correctly, see the example of the leaves of the trees as they did before and how they are seen in the new. 

![ERROR alpha](https://user-images.githubusercontent.com/40981362/166191223-ff02efd7-eeed-48dc-b357-6e0ecee175ab.jpg)
 it does not allow me to send the blend file

**Comment by youle31** [comment]
The render code is done by blender developers. upbge uses directly eevee. This kindof bugs can happen when Blender is in alpha or beta as it is the case currently. The bug might already has been reported in blender tracker and is potentially already fixed in last blender versions.

**Comment by youle31** [comment]
There was a bug fixed today related to alpha clip rendered as alpha hashed, maybe it was related to your issue. I'll do the merge but idk when a new version of upbge will be build to see.
