### ISSUE TITLE
Override Logic Transfrom Priority disables playing actions for objects, but not for amatures.

### ISSUE THREAD

**Issue by Feral3d** [UPBGE/upbge#1698]
I am in the process of porting my open world game over to version .3.0, and there is an issue with objects using "Override Logic Transform Priority"- 

Objects with "Override Logic Transform Priority" cannot be animated. (*Note object color still animates)
![not_working](https://user-images.githubusercontent.com/67176876/168424264-f3c37b70-0b8b-472d-ba24-74b939acf52e.gif)

However Armatures using "Override Logic Transform Priority" can be animated.
![working](https://user-images.githubusercontent.com/67176876/168424325-3cb3f140-579a-4540-b277-da5b77e76caf.gif)

would it be possible to fix this so objects using '"Override Logic Transform Priority" can be animated? I have found that this is the only way to correct the "delay" in movement when parenting an object to a bone "in" game.

Please see this demo Blender File showing the error:
[https://www.dropbox.com/s/u985czeuw9wssf0/Override%20Logic%20Transfrom%20Priority%20Example.blend?dl=0](url)

Best,
T

**Comment by Feral3d** [comment]
Update: if you set an object to be the parent of an armature, and then use a python script to update the transforms for the armature bone you are attempting to track to, it effectively solves the problem.

**Comment by youle31** [comment]
Hi, the bone parent problem should have been fixed in last master. Your file sounds to work as expected for me in last master, then I close this task. Sorry for the problem, it came from an old mistake i did about SceneGraph not being updated (sync child and parent transform with Object transform keys) when playing action.
