### ISSUE TITLE
Instances for objects that are loaded with convertBlenderObject cannot be converted at runtime.

### ISSUE THREAD

**Issue by Feral3d** [UPBGE/upbge#1701]
Whileloading objects from another *.Blend file & converting the objects with "convertBlenderObject",  I cannot use instancing with any of the collections that are loaded.
 It returns the error:
"Warning: Groupobj conversion is not supported during runtime"

Any instanced objects loaded from an external file are visually present, however they seem to spawn a duplicate collection on top of themselves, and they have no physics enabled.

**Comment by youle31** [comment]
Fixed here: https://github.com/UPBGE/upbge/commit/40fffb47d90d3c595919eaa61102ec04d55203eb

It sometimes needs some tweaks with python to have it working properly
