### ISSUE TITLE
Units for Logic Bricks always set to Metric even though blender scene is set to imperial/inches

### ISSUE THREAD

**Issue by bheiland** [UPBGE/upbge#1704]
I constructed a blender scene in imperial/inches.

When I add logic brick for moving objects, the logic bricks only work in metric units (meters)

Am I missing something , is this a software bug or feature.

**Comment by lordloki** [comment]
The gravity and collision bounds margin are adjusted automatically to imperial. Could you pass a example to can test it properly?

**Comment by lordloki** [comment]
Closing the issue as no example was provided. I will open the issue again whether a example is supplied. Thanks for the feedback
