### ISSUE TITLE
Soft body weigth

### ISSUE THREAD

**Issue by e2002e** [UPBGE/upbge#1708]
Hi, is it possible to get the soft bodies pinned to certain vertexes in the game engine ?
I read the doc which states it's a TODO:  bpy.ops.curve.spline_weight_set(weight=1.0).
Is it about implementing the original blender feature to the game engine or does it have to be written from scratch ?
If first options then I could assign to the task given some instructions.

**Comment by youle31** [comment]
It is possible with Rigid body joints or bge.constraints python module.
There are old tutorials on the net which are still working.
