### ISSUE TITLE
Can't start blender

### ISSUE THREAD

**Issue by e2002e** [UPBGE/upbge#1711]
```
Color management: using fallback mode for management
Color management: Error could not find role data role.
BLT_lang_init: 'locale' data path for translations not found, continuing
Color management: scene view "Filmic" not found, setting default "Standard".
blf_load_font_default: 'fonts' data path not found for 'droidsans.ttf', will not be able to display text
blf_load_font_default: 'fonts' data path not found for 'bmonofont-i18n.ttf', will not be able to display text
blf_load_font_default: 'fonts' data path not found for 'bmonofont-i18n.ttf', will not be able to display text
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '/home/yvain/Documents/UPBGE-0.30-linux-x86_64/blender'
  isolated = 0
  environment = 1
  user site = 0
  import site = 1
  sys._base_executable = '/usr/bin/python'
  sys.base_prefix = '/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/python'
  sys.base_exec_prefix = '/usr'
  sys.platlibdir = 'lib'
  sys.executable = '/usr/bin/python'
  sys.prefix = '/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/python'
  sys.exec_prefix = '/usr'
  sys.path = [
    '/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/python/lib/python39.zip',
    '/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/python/lib/python3.9',
    '/usr/lib/python3.9/lib-dynload',
  ]
Internal error initializing Python!
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'
```

**Comment by lordloki** [comment]
are you building you own upbge version? or are you executing upbge 0.3 linux build? we need more information (linux OS, etc)

**Comment by e2002e** [comment]
I'm under Zorin linux and have downloaded the version from the website's "download" button.

**Comment by lordloki** [comment]
Could you make a 'ls -la' in the folder where you have the blender executable?

**Comment by e2002e** [comment]
total 362212
drwxrwxr-x  5 yvain yvain      4096 juin  26 11:36 .
drwxr-xr-x 12 yvain yvain      4096 juin  26 14:46 ..
drwxrwxr-x  3 yvain yvain      4096 juin  26 11:36 3.0
-rwxrwxr-x  1 yvain yvain 368661176 déc.   3  2021 blender
-rwxr-xr-x  1 yvain yvain       713 févr. 18  2020 blender-softwaregl
-rwxrwxr-x  1 yvain yvain   2170336 déc.   3  2021 blender-thumbnailer
-rwxr-xr-x  1 yvain yvain      5340 févr. 18  2020 blender-thumbnailer.py
-rw-r--r--  1 yvain yvain      4765 févr. 18  2020 copyright.txt
drwxr-xr-x  2 yvain yvain      4096 juin  26 11:36 lib
drwxr-xr-x  2 yvain yvain      4096 juin  26 11:36 license
-rw-r--r--  1 yvain yvain      5639 juin  27  2021 upbge.desktop
-rw-r--r--  1 yvain yvain      7452 nov.   7  2021 upbge.svg
-rw-r--r--  1 yvain yvain      7843 mars   7  2020 upbge-symbolic.svg

Thanks for you thyme

**Comment by lordloki** [comment]
I just installed Zorin 16.1 and it works well

https://user-images.githubusercontent.com/1015605/175823240-d07ab1cd-e0b3-4424-a37b-af147e39fcae.mp4

From the error that you pasted it seems that your 3.0 directory is corrupted. Could you download the file and try again?

**Comment by e2002e** [comment]
Ok, it works, turns out that the first downloaded file was bigger than this one. 
Thank you a lot.
