### ISSUE TITLE
UPBGE 0.33 6/28/2022 : Force close upbge when I play game after using boolean modifier 

### ISSUE THREAD

**Issue by BlackEagle1983** [UPBGE/upbge#1713]
Hello . When I play game after using  boolean modifier with Exact solver and difference operation UPBGE software force close . 

windows 10 pro 64bit build 19044.1766
Procesor : Intel core i5 4690
Ram : 12 gig ddr3
Graphic : GTX 950 2 gig

**Comment by youle31** [comment]
[boolean_exact_solver.zip](https://github.com/UPBGE/upbge/files/9018721/boolean_exact_solver.zip)

I confirm, thanks

**Comment by youle31** [comment]
It was working in the first build and not working in the second:
![Capture d’écran 2022-06-30 235201](https://user-images.githubusercontent.com/10052509/176785180-3368695c-eb98-42f2-96ee-b137508ca19e.png)

Builds done by lordloki and uploaded on mega (accessible from upbge website). Thanks @ lordloki!

I'll have a look later

**Comment by youle31** [comment]
Mentionned commit in previous post EDIT is causing the issue

**Comment by youle31** [comment]
![Capture d’écran 2022-07-01 013232](https://user-images.githubusercontent.com/10052509/176795332-29d3aced-a3c7-403f-9a26-b6a9374b494c.png)

This avoids the crash

**Comment by youle31** [comment]
Normally fixed here: https://github.com/UPBGE/upbge/commit/8285a1496baffeab421e94bf18b6ed52b0f1c923

Thanks for report

**Comment by youle31** [comment]
With new file provided by report author, we can see that the crash happens even after we applied the boolean modifier.

Then we need to always check material indices in case meshes have been created with boolean modifiers.

Test file:
[test.zip](https://github.com/UPBGE/upbge/files/9052319/test.zip)

**Comment by youle31** [comment]
The bug you were erporting was fixed in a better way by a blender developer here:

https://developer.blender.org/rB5723bf926dcb387224dd0de2a4c562bc316e8edc

Unfortunately, files created+saved after may 2022 and today will still be crashing (No versioning code for this short period)

**Comment by youle31** [comment]
I informed Hans Goudey about potential corrupted material indices issue here: https://developer.blender.org/rB5723bf926dcb387224dd0de2a4c562bc316e8edc if he wants to add versioning
