### ISSUE TITLE
upbge 6/28/2022: menu bar does not appear correctly . 

### ISSUE THREAD

**Issue by BlackEagle1983** [UPBGE/upbge#1714]
Hello . when I run upbge menu bar does not appear correctly and I must disable **show menus** and enable it again to solve this problem please solve this issue .
![menubar](https://user-images.githubusercontent.com/72033451/176980095-979903ac-6c6e-4768-bb07-6ac1a8db07f9.png)

**Comment by youle31** [comment]
![Capture d’écran 2022-07-02 083930](https://user-images.githubusercontent.com/10052509/176989787-c63c3deb-8c02-41f9-8f30-31117b2b14ab.png)
Here is a screenshot comparing last upbge master and last blender master at opening for me. I do not notice something wrong. Am I missing something?

**Comment by BlackEagle1983** [comment]
I do not know . But I have this issue . I do not know why the reason is .

**Comment by youle31** [comment]
you can try to load default startup.blend/reset factory settings

**Comment by BlackEagle1983** [comment]
How can I do this ?

**Comment by youle31** [comment]
![Sans titre](https://user-images.githubusercontent.com/10052509/176992051-50682008-7072-4ddf-9b93-cd8306ad2d4f.jpg)

**Comment by BlackEagle1983** [comment]
I can not access to some menu bar items .

**Comment by BlackEagle1983** [comment]
![Untitled](https://user-images.githubusercontent.com/72033451/176992180-eee37cfd-ea70-4554-94e9-d328afb2e29a.png)

**Comment by BlackEagle1983** [comment]
I do your instruction but my problem still exists
![Untitled](https://user-images.githubusercontent.com/72033451/176992423-39a2fa42-c4cb-469f-b8c5-00a359b40149.png)
 .
