### ISSUE TITLE
ModuleNotFoundError: No module named 'uplogic'

### ISSUE THREAD

**Issue by b-rad-c** [UPBGE/upbge#1717]
I'm new at UPBGE and am trying to learn logic nodes based on the [official example found here](https://upbge.org/#/documentation/docs/latest/manual/manual/tutorials/introducing_logic_nodes/a_first_example.html). I'm trying to print the hello world message to console but I am seeing the following in my terminal:

```
brad@Brads-MacBook-Pro ~ % /Applications/UPBGE.app/Contents/MacOS/Blender
Read prefs: /Users/brad/Library/Application Support/UPBGE/3.0/config/userpref.blend
register_class(...):
Warning: 'NODE_MT_category_Vector Math' doesn't have an alpha-numeric suffix
register_class(...):
Warning: 'NODE_MT_category_Armature / Rig' doesn't have an alpha-numeric suffix
register_class(...):
Warning: 'NODE_MT_category_Bone Constraints' doesn't have an alpha-numeric suffix
register_class(...):
Warning: 'NODE_MT_category_Ray Casts' doesn't have an alpha-numeric suffix
Read blend: /Users/brad/Documents/UPBGE/logic-nodes-hello-world.blend
sh: color: command not found
[Logic Nodes][NOTIFICATION] Building Logic Trees on Startup...
sh: color: command not found
[Logic Nodes][NOTIFICATION] Generating code for tree NodeTree
<bpy_struct, Text("nl_nodetree.py") at 0x600002977108>
Debug: 3172, 1978
rcti: : xmin 0, xmax 3171, ymin 211, ymax 2188 (3171x1977)

Blender Game Engine Started
[ERROR] KX_PythonComponent[NodeTree] - Failed to invoke the start callback.
Traceback (most recent call last):
  File "/Users/brad/Documents/UPBGE/logic-nodes-hello-world.blend/nl_nodetree.py", line 53, in start
  File "/Users/brad/Documents/UPBGE/logic-nodes-hello-world.blend/nl_nodetree.py", line 11, in __init__
ModuleNotFoundError: No module named 'uplogic'
Blender Game Engine Finished
Saved session recovery to '/var/folders/y_/rcvstzws4853y122kgr2tpkw0000gn/T/quit.blend'
sh: color: command not found
[Logic Nodes][DEBUG] Removing Game Start Compile handler...

Blender quit
```

[blend file is available here](https://drive.google.com/file/d/1NhrRx7shsuTQw-S_2N-axqCIUwn6rS9u/view?usp=sharing).

OSX 12.3.1
Python 3.10.4
UPBGE 3.0.0 (3.0.0 2021-12-12)

Steps to reproduce
1. Open UPBGE via command line
2. Open blend file (attached above)
3. Press P to run game
4. Terminal will show the above errors beginning with "sh: color: command not found"
5. Press space bar (to trigger hello world message)
6. Nothing is printed to console.

For troubleshooting I tried installing uplogic with pip to my system python and downloading the code as a zipfile and manually installing as an add-on (and restarting upbge) but neither changed anything. If it helps, I also had to manually install the logic nodes add on but the documentation says it should be installed by default.

**Comment by IzaZed** [comment]
If you have version 2+ of the logic nodes installed, you need to install the uplogic module since the code used by the nodes is in there
There should be a button in the addon preferences (you might need to restart UPBGE after)

**Comment by b-rad-c** [comment]
I tried downloading the code ([from this repo](https://github.com/UPBGE/uplogic)) as a zip and then using the install button in add-on prefs. It looked like it installed correctly, I restarted it but I still get the error. I can't see the uplogic add-on in the prefs when i filter for 'uplogic'... 

Not sure if there's a different installation procedure, am I supposed to download the repo as a .zip or is there a different package that I need to get?

**Comment by b-rad-c** [comment]
OK, I got it now! I couldn't find the button you were talking about... For anyone running into the same problem, to find the install button you need to be in your add-on preferences and then filter for "Game Engine: Logic Nodes" and then click the caret on the entry to expand its options and then you'll see a button that says "Install or Update Uplogic Module" ... click that and you're good to go.

As an FYI, it would be nice to see a visual confirmation in the UI that the install completed, I can see it if I opened UPBGE using my console though.

Thanks @IzaZed
