### ISSUE TITLE
Skip some steps in cycles rendering for viewport mode

### ISSUE THREAD

**Issue by e2002e** [UPBGE/upbge#1725]
When rendering with cycles, there are unwanted procedure going on.
The status says:
Building Scene BVH
Building Meshes
Building Shaders

When in viewport (no in the game), these are not done unless coming from another shading mode.
An initialization step is done in a loop somewhere.
It doesn't happend in vm_draw_update() or the functions calling it, it comes from gamelogic when moving the camera for instance.

**Comment by youle31** [comment]
I didn't manage to reproduce starting from cycles rendered mode with cpu rendering

**Comment by e2002e** [comment]
I had to compile UPBGE with the CMakeFile including path for OptiX to run this on GPU,
The issue is not an issue ; device_update() which does all these steps was called because the player's cube was renderer and the mouse look does rotate this cube on X axis. I unticked 'render' in the outliner and now I can move around and look with only the image sampling being done
