### ISSUE TITLE
exporting game

### ISSUE THREAD

**Issue by e2002e** [UPBGE/upbge#1726]
I have compiled the program from source and cannot export the game as an elf.
Do you know which library is needed for the addon to be included ?

**Comment by lordloki** [comment]
I don't understand your issue. Could you paste errors that you get during the export process? Thanks

**Comment by e2002e** [comment]
I have found the addon in the repo, and installed it.
Yet:
`Traceback (most recent call last):
  File "/home/i20/.config/upbge/3.4/scripts/addons/game_engine_save_as_runtime_eevee.py", line 339, in execute
    WriteRuntime(self.player_path,
  File "/home/i20/.config/upbge/3.4/scripts/addons/game_engine_save_as_runtime_eevee.py", line 174, in WriteRuntime
    CopyPythonLibs(dst, overwrite_lib, report)
  File "/home/i20/.config/upbge/3.4/scripts/addons/game_engine_save_as_runtime_eevee.py", line 62, in CopyPythonLibs
    shutil.copytree(src, dst, ignore=lambda dir, contents: [i for i in contents if i == '__pycache__'])
  File "/home/i20/Documents/build_linux/bin/3.4/python/lib/python3.10/shutil.py", line 556, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/home/i20/Documents/build_linux/bin/3.4/python/lib/python3.10/shutil.py", line 512, in _copytree
    raise Error(errors)
shutil.Error: [('/home/i20/Documents/build_linux/bin/3.4/python/lib/python3.10/config-3.10-x86_64-linux-gnu/libpython3.10.so', '/home/i20/Documents/3.4/python/lib/python3.10/config-3.10-x86_64-linux-gnu/libpython3.10.so', "[Errno 2] No such file or directory: '/home/i20/Documents/build_linux/bin/3.4/python/lib/python3.10/config-3.10-x86_64-linux-gnu/libpython3.10.so'")]
`

**Comment by e2002e** [comment]
I linked the library from my system and it's working, question is why doesn't it come with the other build files ?

**Comment by lordloki** [comment]
This addon is already in the addons repository. During the build process, did you get the addons? here is the code that you should launch
![image](https://user-images.githubusercontent.com/1015605/183287170-f582ae1d-ed60-4dba-8ba7-779a4f508796.png)

It seems that you didn't use the compiled linux libs.

**Comment by e2002e** [comment]
> It seems that you didn't use the compiled linux libs.
What do you mean ? This library wasn't compiled with the rest.
I am testing optix for cycles rendering and have been able to render 2 samples per frame at 24 fps.
