### ISSUE TITLE
Mouse over sensor doesn't work in overlay.

### ISSUE THREAD

**Issue by ZhekaHauska** [UPBGE/upbge#1728]
Hi! In the [file](https://github.com/UPBGE/upbge/files/9311082/overlay.zip) I want to have a basic interactive overlay, but in **UPBGE 0.30.0** mouse over sensor doesn't work in overlay. 
```
$ cat /etc/lsb-release                                                                                                                                                                                                     
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.3.6
DISTRIB_CODENAME=Ruah
DISTRIB_DESCRIPTION="Manjaro Linux"
```

```
$ sudo lspci | grep VGA                                                                                                                                                                                                    
05:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] (rev c2)
```
The same problem on **Ubuntu 22.04** with **GTX 1060**.

**Comment by youle31** [comment]
This issue has been fixed after 0.3.0 release checking "overlay mouse control option".
New builds are available on upbge website > download > development...

**Comment by BluePrintRandom** [comment]
perhaps we should do a camera brick to turn it on / off for logic users to be able to swap what camera they are picking from?

**Comment by youle31** [comment]
this option can normally be toggled with python

**Comment by BluePrintRandom** [comment]
There are options in the camera to choose who is active I think
