### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by e2002e** [UPBGE/upbge#1734]
```
/home/i20/Documents/upbge/intern/cycles/graph/../util/xml.h:18:45: error: ‘OpenImageIO_v2_1::pugi’ has not been declared
   18 | #  define PUGIXML_NAMESPACE OIIO_NAMESPACE::pugi
 
```
installed libpugixml-dev and libopenimageio-dev, I am trying the openimage version 2.4 but not sure whether the cmake arguments are correct for setting lib and headers dir because this makes no changes.
System is ZorinOS (linux) and branch is 'master'.

**Comment by lordloki** [comment]
For linux is much easier to use precompiled libs. Please, follow the indications https://github.com/UPBGE/upbge/wiki/Build-UPBGE-on-Linux

**Comment by e2002e** [comment]
OK i'm got the files, I just respected the folder's name 'lib' created on same level than upbge, and it magically finds all of them when running make.

Now It's stuck here:
```
CMake Error at build_files/cmake/platform/platform_unix.cmake:483 (if):
  if given arguments:

    "WITH_OPENCOLLADA" "AND" "(" "VERSION_LESS" "4.0.0" ")"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:1120 (include)
```

**Comment by lordloki** [comment]
Maybe there is somethig modified in your side because that line says:
```
if(WITH_OPENCOLLADA AND (${LLVM_VERSION} VERSION_LESS "4.0.0"))
```

**Comment by e2002e** [comment]
It's precisely what it reads on the file line 483, I commented it out and now am having issues with the prebuild opensubdiv

**Comment by lordloki** [comment]
https://user-images.githubusercontent.com/1015605/185770725-379ad93c-b1d3-4eea-a505-172725525bb5.mp4

**Comment by e2002e** [comment]
Nice to show me the cmake gui, that seems handy.
My issue is when linking blener, related to opensubdiv. I'm trying again today.

**Comment by e2002e** [comment]
Used Kubuntu 22 and followed the steps in the link.
That builds with no errors.
