### ISSUE TITLE
No compatible GPUs found for Cycles

### ISSUE THREAD

**Issue by alexmro** [UPBGE/upbge#1738]
I have built UPBGE from source code but when I go to _Preferences > System_ and try to enable CUDA, I get this error

> No compatible GPUs found for Cycles. Requires NVIDIA GPU with compute capability 3.0

I don't get this error if I start Blender 3.2.2 or UPGE 0.3.0 and my graphics card does have compute capability 7.5. Is this feature somehow disabled in UPBGE 0.34.0 or is it a bug?

**Comment by lordloki** [comment]
Do you have compiled with CUDA binaries? Do you have the CUDA SDK installed?
Could you test the alpha build here? https://mega.nz/folder/t9EEFSaS#JPiOPSInCZyU-SW_-rhEOQ

**Comment by alexmro** [comment]
I am recompiling right now. I see `CUDA_TOOLKIT_ROOT_DIR` is set now (I just installed the toolkit) but `CUDA_SDK_ROOT_DIR` is still `CUDA_SDK_ROOT_DIR-NOTFOUND`. I don't know which one is needed, I will see if this rebuild will fix the issue

**Comment by lordloki** [comment]
You have to set up the toolkit root dir with cmake
