### ISSUE TITLE
0.3+: TODO: Test if softbodies are still working

### ISSUE THREAD

**Issue by youle31** [UPBGE/upbge#1742]
After this commit: 05952aa94d33eeb504fa63618ba35c2bcc8bd19b

as I didn't know what to do in DM_to_mesh which was using BKE_mesh_update_customdata_pointers, I commented this function.

TODO: Check if softbodies are still working.

**Comment by youle31** [comment]
Basic test works, i leave it open few days or weeks until more tests

**Comment by lordloki** [comment]
I did several tests with flags and several gummy monkeys, they worked as before.

**Comment by youle31** [comment]
Thanks very much for tests! I close this report then and we'll still have it in closed bugs with commit reference just in case. Thanks!
