### ISSUE TITLE
Some questions about the "set rigid body" node in the logical node

### ISSUE THREAD

**Issue by HHCF8** [UPBGE/upbge#1743]
I want to achieve an effect, when I press a key, the object is picked up by the character and turn off the physical collision effect, and when I press another key, the object is put down to turn on the physical effect, in upbge, I try to use "set "rigid body", use the above logic to operate on and off, but in actual operation, it does not work, so I want to know why
![屏幕截图 2022-09-07 145352](https://user-images.githubusercontent.com/112532035/188811023-8ee8da64-fa79-42a3-839f-1d56d1d28498.png)

If I don't turn off the rigid body collision of the picked object it will look like this in the video

https://user-images.githubusercontent.com/112532035/188816263-b037f51c-4e9b-468c-9be9-7365022f1d67.mp4

**Comment by IzaZed** [comment]
For some reason the "Ghost" option on the Set Dynamics node was disabled, I enabled it again and will upload it now
you'll need to reinstall the logic node addon though

**Comment by IzaZed** [comment]
This should contain the fix:
https://github.com/UPBGE/UPBGE-logicnodes/releases/tag/v2.1.4

**Comment by HHCF8** [comment]
> 由于某种原因，Set Dynamics节点上的“Ghost”选项被禁用，我再次启用它，现在将上传它，您需要重新安装逻辑节点插件

alright, thank you very much

**Comment by HHCF8** [comment]
> 这应该包含修复：https://github.com/UPBGE/UPBGE-logicnodes/releases/tag/v2.1.4

I tried it and found that it still doesn't work, do I need to unzip the zip file?

**Comment by IzaZed** [comment]
no, you need to manually remove the "bge_netlogic" folder in ".../Release/3.x/scripts/addons/" and then install the archive via the preferences menu

**Comment by HHCF8** [comment]
> no, you need to manually remove the "bge_netlogic" folder in ".../Release/3.x/scripts/addons/" and then install the archive via the preferences menu

I installed it, but now the game crashes as soon as I run it, and the n-panel of the logical node has changed?

**Comment by IzaZed** [comment]
Changed how? Would you be willing to share the file so I can take a look at it?

**Comment by HHCF8** [comment]
> 改了怎么改？你愿意分享文件，让我看看吗？

![image](https://user-images.githubusercontent.com/112532035/198585240-bb14a020-165d-449c-86db-84a733d23650.png)
Sorry for the delay, but as you can see there seems to be a change

**Comment by HHCF8** [comment]
> 改了怎么改？你愿意分享文件，让我看看吗？
The zip file is too big

**Comment by youle31** [comment]
I close this as it is stale and we can't do anything without test file, as it shouldn't be in upbge github issues but in logic nodes github, and as it is stale.
