### ISSUE TITLE
Some issues about packing resourses.

### ISSUE THREAD

**Issue by kitsdream** [UPBGE/upbge#1756]
It can't be packed resourses when I used logic node which play sound,but using logic brick can works.

**Comment by youle31** [comment]
File > external data > pack resources/pack linked things doesn't help?

**Comment by kitsdream** [comment]
> 

Thanks for your help.I found that new alpha version could work.Expecting for the final release.

**Comment by kitsdream** [comment]
> File > external data > pack resources/pack linked things doesn't help?

Thanks for your help.I found that new alpha version could work.Expecting for the final release.

**Comment by IzaZed** [comment]
Sorry for the delay
which version is this happening with? I tried 0.34.0, I can pack resources loaded with logic nodes there

**Comment by kitsdream** [comment]
> Sorry for the delay
> which version is this happening with? I tried 0.34.0, I can pack resources loaded with logic nodes there

I found that the problem in packing resources was in the early 0.34.0 alpha version.But new 0.35.0 alpha has fixed it.

**Comment by IzaZed** [comment]
Ah alright
If this isn't a problem anymore, may I ask you to close the issue please?

**Comment by youle31** [comment]
Thanks!
