### ISSUE TITLE
Crash upbge 0.2.5

### ISSUE THREAD

**Issue by JohVerse** [UPBGE/upbge#1757]
The errors above appear while I'm navigating in the viewport or I press play, the error at the end is when the upbge Crasha when I click with the mouse button...
Detail, when any object is in edit mode, the crash does not happen, only when the click happens in Object mode

![Captura de tela de 2022-10-04 05-04-20](https://user-images.githubusercontent.com/114673851/193769646-9def2db9-37fb-4cf9-8611-8b12fed3a7e1.png)

**Comment by JohVerse** [comment]
[blender.crash.txt](https://github.com/UPBGE/upbge/files/9735899/blender.crash.txt)

Can anyone help me, this is an error file generated by my upbge 0.2.5B that crashes whenever I right click on the mouse
My system is Linux, Pop Os, this didn't happen in distros like Debian and Manjaro, or even windows which makes me believe that something is missing from my current system

**Comment by lordloki** [comment]
It seems the graphics driver

**Comment by JohVerse** [comment]
> It seems the graphics driver

But it doesn't make sense for some operating systems to run without crash and others not, windows runs, debian and manjaro run, the only thing these distros have in relation to Pop Os My current system is an older Kernel, if I'm not mistaken 5.10. .

**Comment by lordloki** [comment]
do you have AMD graphics card?

**Comment by JohVerse** [comment]
After many changes of different linux distros, I arrived at Debian 11 with Gnome and Kernel 5.10... here the crashes no longer occur, I don't know if this problem is caused by my hardware or the operating system itself, in this case distros with older kernels upbge seems to work better but i don't know why, what matters is i can work in peace now.
