### ISSUE TITLE
quixels bridge cannot connect for import

### ISSUE THREAD

**Issue by e2002e** [UPBGE/upbge#1759]
Hello, the application quixels bridge cannot connect to import models to the software, their latest plugin supports blender up to version 3.1, so I though it would work with the version I downloaded from your website, but I got the same error than when being in 3.3, the plugin is not supported.

**Comment by e2002e** [comment]
Nevermind, it works after copying the scripts into startup script folder.

**Comment by youle31** [comment]
Ok, then i close the issue
