### ISSUE TITLE
Have a problem after installing: atributeError: ops has no atribute nladdpropertyoperator upbge

### ISSUE THREAD

**Issue by dimkauzh** [UPBGE/upbge#1760]
When my upbge opened, I was going to preferences, then to add-ons and then i tryed to click on the add-on: game-engine, and it failed
<img width="1283" alt="Screenshot 2022-10-17 at 16 28 39" src="https://user-images.githubusercontent.com/106883655/196203879-4d168cef-961a-4d45-ae54-765e5d5acd2b.png">

**Comment by lordloki** [comment]
Bricky nodes for UPBGE 0.3 didn't work. You have to download a new version from its github (https://github.com/IzaZed/bricky-nodes) or to use last UPBGE 0.34 Alpha (https://mega.nz/fm/ZtcDzYYA)

**Comment by youle31** [comment]
I close this one as lordloki answered, thanks!
