### ISSUE TITLE
"Save as runtime" add-on and Game Start Actuator issues

### ISSUE THREAD

**Issue by ICHIL** [UPBGE/upbge#1767]
I've seen someone posting about a Mac problem when starting a game in an executable file from the Game Start Actuator. This resulting with the next blend file not getting loaded and crashing the program.

This problem extends to Windows devices from my testings. In the last UPBGE 0.35 commit of 11/20/2022 the memory seems to not get freed correctly neither when the newly created executable crashes as the computer thinks the program is still running though it isn't. Thus, stopping the user from deleting the executable and a majority of its dependencies. But that's not all.

Materials color channels are entirely inverted when loading a blend file from the Game Start Actuator. The black turns into white for example. Textures are not concerned and work perfectly fine however. 

Apparently, not every files are concerned with that problem. A file that dosen't make any use of logic instructions seems to load correctly. But I have no idea why this behavior exists nonetheless.

My computer is a laptop that uses an AMD Ryzen 5 5600H CPU and an NVIDIA GTX 1650 graphic card if that can help catching up the source of these problems.

Disabling any antivirus software dosen't help at fixing these issues neither.

Hoping that this report will be helpful for UPBGE's development.

With all my respects to the dev team.

**Comment by ICHIL** [comment]
> I've seen someone posting about a Mac problem when starting a game in an executable file from the Game Start Actuator. This resulting with the next blend file not getting loaded and crashing the program.
> 
> This problem extends to Windows devices from my testings. In the last UPBGE 0.35 commit of 11/20/2022 the memory seems to not get freed correctly neither when the newly created executable crashes as the computer thinks the program is still running though it isn't. Thus, stopping the user from deleting the executable and a majority of its dependencies. But that's not all.
> 
> Materials color channels are entirely inverted when loading a blend file from the Game Start Actuator. The black turns into white for example. Textures are not concerned and work perfectly fine however.
> 
> Apparently, not every files are concerned with that problem. A file that dosen't make any use of logic instructions seems to load correctly. But I have no idea why this behavior exists nonetheless.
> 
> My computer is a laptop that uses an AMD Ryzen 5 5600H CPU and an NVIDIA GTX 1650 graphic card if that can help catching up the source of these problems.
> 
> Disabling any antivirus software dosen't help at fixing these issues neither.
> 
> Hoping that this report will be helpful for UPBGE's development.
> 
> With all my respects to the dev team.

**Comment by lordloki** [comment]
I think the issue has 2 parts:
- The crash: I think it comes the loaded blend through game start actuator isn't at the correct relative level respecting the executable. Remember that the executable "is" the main blend.
- the inverted colors. I have an issue that it is similar to your description. For this issue:
commit 8adb16e 13/07/22 works:

https://user-images.githubusercontent.com/1015605/203667743-81adbb26-9482-404b-bf5f-cd537e5ee804.mp4

commit  63c5a91 16/07/22 doesn't work:

https://user-images.githubusercontent.com/1015605/203667787-62ad9b0e-4f95-4809-ae7f-c80056ccd016.mp4

**Comment by lordloki** [comment]
the guilty commit is 1cf465bbc3312ae8eac3e1ae573b716e0fad92cf

**Comment by youle31** [comment]
Ah, thanks! I think we'd need to investigate in wm_window.c, which calls a function named wm_window_ghostwindow_blenderplayer_ensure and inside this there is GPU_exit and directly after GPU_init

**Comment by ICHIL** [comment]
Ah thank you very much for all your answers. 

I'll then try to put my blend file in the same directory of my main blend ASAP and will get back here to tell you what I get.

**Comment by ICHIL** [comment]
Edit : Indeed it was just the relative path that simply wasn't respecting the executable. So it was simply not finding. Then forced the program to crash. My fault on that one.

And thank you for all your help !

**Comment by lordloki** [comment]
I uploaded a new build with the proposed fix. Could you check it?

**Comment by ICHIL** [comment]
Just noticed your post sir. My apologies for not looking at GitHub more frequently.... Looking at it right now.

**Comment by ICHIL** [comment]
> I uploaded a new build with the proposed fix. Could you check it?

Working like a charm ! Thank you very much for your time !
