### ISSUE TITLE
Cannot Enable Bricky Nodes or Logic Nodes

### ISSUE THREAD

**Issue by Chandilere0Zer** [UPBGE/upbge#1769]
Using: Mac OS Catalina, Intel Core i7, NVIDIA GeForce GT 750M 1 GB, UPBGE version 0.30.0

https://preview.redd.it/3swkwo8w203a1.png?width=640&format=png&auto=webp&s=b2030140f187c7145f48b26b6d139ffbc2212250

error pops up whenever enabling bricky nodes and logic nodes in preferences. Tried enabling auto run python scripts in preferences, downloading Logic Nodes +, re-downloading UPBGE. No results.

**Comment by youle31** [comment]
is it working in last versions? https://mega.nz/folder/t9EEFSaS#JPiOPSInCZyU-SW_-rhEOQ

**Comment by smttkin** [comment]
Hi have a good day.

**I think this could be helpful in fixing your issue:**
- Can you try to install Logic Nodes add-on manually from here https://github.com/UPBGE/UPBGE-logicnodes/releases ( install that "bge\_netlogic" one   ) ?
- And create "bge_netlogic" named folder (Location: Your_UPBGE_Folder/3.0/scripts/addons) then paste the files in the zip into the folder and try to enable the add-on again after restarting UPBGE.

**Additionally, you can also install any other add-on in another way**

> you should install add-ons that you trust to its author in both either ways.


_Step 1_ ( Edit>Preferences>Add-ons *Install button):
![install-addon](https://user-images.githubusercontent.com/73013524/208225597-b353d43f-4582-4884-b3af-c65ec99cc863.png)

_Step 2_ ( Go to location that you extract add-on files and select "\_\_init\_\_.py" file in it and *Install Add-on button):
![blender-file-view](https://user-images.githubusercontent.com/73013524/208227380-dab848fd-86da-4b0a-a59c-fe36f21f00d8.png)


__Final Step__
I can use the add-on after I got this message  
![i-got-this-message-in-blender-info-log](https://user-images.githubusercontent.com/73013524/208225904-8d8ddd41-65a7-4a3c-bba8-3e503befbb31.png)

I am waiting your feedbacks, thx for attention

**Comment by IzaZed** [comment]
This is an issue with the 0.3 release from December 2021
try downloading the most recent versions of both addons and try to install those via the .zip files

**Comment by youle31** [comment]
No answere here, I close this, Thanks for comprehension.
