### ISSUE TITLE
 UPBGE crashes when pressing P (Ubuntu 20.04 / prebuilt binaris)

### ISSUE THREAD

**Issue by wetoo-cando** [UPBGE/upbge#1770]
Hello,

Thanks for the great work with UPBGE.

I downloaded UPBGE from https://upbge.org/#/download for Linux-x64. 
I am on Ubuntu 20.04 myself. 

When I start the application with the default scene and press play ("P" button), it crashes. Here is the log:

```
XXX@YYY:~/blender/UPBGE-0.30-linux-x86_64$ ./blender -d
Switching to fully guarded memory allocator.
Blender 3.0.0
Build: 2021-12-03 21:29:37 Linux Release
argv[0] = ./blender
argv[1] = -d
Debug: 1189, 687
rcti: : xmin 0, xmax 1188, ymin 79, ymax 765 (1188x686)
Writing: /tmp/.crash.txt
Segmentation fault (core dumped)

XXX@YYY:~/blender/UPBGE-0.30-linux-x86_64$ cat /tmp/.crash.txt
# Blender 3.0.0, Commit date: 2021-12-03 17:17, Hash 2df036b52494

# backtrace
./blender(BLI_system_backtrace+0x20) [0xb47fa30]
./blender() [0x11e8e4b]
/lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7f7e82a34090]

# Python backtrace
```

Any ideas how I could proceed?
 
Thanks!

**Comment by lordloki** [comment]
Could you check if the last 0.35 alpha build works for you? https://mega.nz/folder/t9EEFSaS#JPiOPSInCZyU-SW_-rhEOQ

**Comment by wetoo-cando** [comment]
Thanks @lordloki the alpha 0.35 does not crash on play!

**Comment by youle31** [comment]
Ok, thanks! I close this report then as it works in last master.
