### ISSUE TITLE
Some issues in Logic Brick Node View.

### ISSUE THREAD

**Issue by kitsdream** [UPBGE/upbge#1772]
Some issues in Logic Brick Node View.
When I copied the brick node,it would sync all the values from the orginal like the shot below.
I think if there could be a chooce between 'Copy it' or 'Copy  it and Sync it',which would be nice.
![屏幕截图_20221221_180036](https://user-images.githubusercontent.com/79633060/208879946-9e19e7ba-2011-41c5-a801-ee1bfd31d8f9.png)

**Comment by IzaZed** [comment]
Due to the way these nodes work (they just reference an actual logic brick), pressing Shift-D will copy the node as well as the reference to the same brick
There's a "Duplicate" button in the header though, next to the checkbox and the name of the brick

**Comment by kitsdream** [comment]
> Due to the way these nodes work (they just reference an actual logic brick), pressing Shift-D will copy the node as well as the reference to the same brick There's a "Duplicate" button in the header though, next to the checkbox and the name of the brick

I saw the "Duplicate" botton,the "Duplicate linked" botton and the "Copy" botton.But they still sync the value when I tried to duplicate the brick nodes which I set up before,I couldn't change any single value,because it would sync all the values in the original nodes.
I wonder how to do,if I don't want the nodes I copied sync the value from original?

**Comment by IzaZed** [comment]
I'm talking about this button here, pressing this should duplicate the referenced brick and assign the new one to the node
![image](https://user-images.githubusercontent.com/32898133/210187259-03d748e8-56ae-4494-8dd7-6b59c6784f6e.png)

**Comment by kitsdream** [comment]
> I'm talking about this button here, pressing this should duplicate the referenced brick and assign the new one to the node ![image](https://user-images.githubusercontent.com/32898133/210187259-03d748e8-56ae-4494-8dd7-6b59c6784f6e.png)

Thanks for your advise.But when I tried to press the "Duplicate" botton,there was an error tag appeared below. How to fix it?
![屏幕截图_20230102_211954](https://user-images.githubusercontent.com/79633060/210237546-1d8a1297-792e-48e2-a257-d6e42c518ea0.png)
