### ISSUE TITLE
ModuleNotFoundError: No module named 'bge'

### ISSUE THREAD

**Issue by wetoo-cando** [UPBGE/upbge#1773]
Hello,

When I try to import bge from the python console in UPBGE, I get the ModuleNotFoundError:

```
>>> import bge
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
ModuleNotFoundError: No module named 'bge'
```
Does anyone know why this is happening?

In general, I am trying to use the uplogic add-on https://github.com/UPBGE/uplogic/, and it contains a number of bge imports.

Thanks!

**Comment by BluePrintRandom** [comment]
to use bge python you have to call it in game using a script node or a py component

**Comment by wetoo-cando** [comment]
Thanks @BluePrintRandom , the python component works.
Sorry, I am new to blender. What do you mean by "script node"? A node in the uplogic-sense?

**Comment by IzaZed** [comment]
there's a "python code" node in the logic nodes addon, either that or the logic brick python controller

**Comment by wetoo-cando** [comment]
Ok, thanks @IzaZed

**Comment by youle31** [comment]
bge is a python module which is only initialized AFTER bge start then it is not available before you launch the game engine.
Scripts using bge can be used from a python controller logic brick, a python component, or python node if you are using logic nodes addon.

**Comment by wetoo-cando** [comment]
@youle31 Thank you for the explanation.
