### ISSUE TITLE
Standalone player crash runing geonodes instances

### ISSUE THREAD

**Issue by ThiagoMoraesGD** [UPBGE/upbge#1775]
Version 0.3.5

[test-geonodes.zip](https://github.com/UPBGE/upbge/files/10365297/test-geonodes.zip)

**Comment by youle31** [comment]
Hi, it doesn't crash for me in last master. Can you check again in a few days please when a new build will be done?

**Comment by ThiagoMoraesGD** [comment]
Solved in latest build
