### ISSUE TITLE
object's collide() method is crashing if the physics type is Sensor

### ISSUE THREAD

**Issue by UnidayStudio** [UPBGE/upbge#1777]
I've zipped and included a minimal reproducible file.

But it is straight forward: create an object with the Physics type "Sensor" and try using the object's collide() method. UPBGE 0.2.5.

[upbge-collide-crash-report.zip](https://github.com/UPBGE/upbge/files/10368501/upbge-collide-crash-report.zip)

**Comment by youle31** [comment]
Fixed here: https://github.com/UPBGE/upbge/commit/5a7e32fb93d6d8a484d4e94de10beb18d3b5f2f5 thanks for report
