### ISSUE TITLE
Video Texture examples in official docs don't work

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [UPBGE/upbge#1799]
Hi,

This is here: [https://upbge.org/docs/latest/api/bge.texture.html](https://upbge.org/docs/latest/api/bge.texture.html)

Confirmed by this [forum post @ BlenderArtists.](https://blenderartists.org/t/should-this-video-texture-blend-work/1451744/4)

Cheers.

**Comment by youle31** [comment]
I don't confirm this bug. I had a look at the solution proposed by rpaladin and it looks good using bpy.path module. However, bge.logic.expandPath works as expected too. Then the problem doesn't come from the software neither from the doc, but from a misuse/mistanderstanding on user side.

**Comment by Michael-Z-Freeman** [comment]
> I don't confirm this bug. I had a look at the solution proposed by rpaladin and it looks good using bpy.path module. However, bge.logic.expandPath works as expected too. Then the problem doesn't come from the software neither from the doc, but from a misuse/mistanderstanding on user side.

If you're saying the examples work on the UPBGE docs page then I'll have to look at that and test again.
