### ISSUE TITLE
Blender Game Engine - "Record Animation" Missing

### ISSUE THREAD

**Issue by danielah05** [UPBGE/upbge#1803]
in the 2.79 blender game engine, there is a neat feature that lets you record your movement into keyframes
![image](https://user-images.githubusercontent.com/35849198/228928140-410fe73d-218b-48d2-89f8-d4052a4741fc.png)

while in UPBGE this "use_animation_record" setting still exists and can be toggled to true using the blender console, no keyframes get recorded
![blender_KVBQcGip4H](https://user-images.githubusercontent.com/35849198/228929135-d081a6dd-2304-4182-916e-2969f7b2749d.png)

would be neat to have this as a working option

**Comment by danielah05** [comment]
another thing i would like to mention that this IS also part of the UPBGE documentation page, which is why i am honestly kinda surprised it does not actually work in the first place https://upbge.org/#/documentation/docs/latest/manual/manual/physics/introduction.html#recording-to-keyframes
![image](https://user-images.githubusercontent.com/35849198/228930467-1a7348f5-8aae-49ac-a00b-2040ed173ce7.png)

**Comment by BluePrintRandom** [comment]
[record.zip](https://github.com/UPBGE/upbge/files/12753143/record.zip)
this .blend is setup to not only record objects who have the property 'track_me' but also armture animation for objects who have the property 'armature_actor' (so it does more than the old one) 

we can also use simulation nodes to make games now that are cached by default.
