### ISSUE TITLE
0.3+ crash loading a file versioning 2.80

### ISSUE THREAD

**Issue by youle31** [UPBGE/upbge#1810]
File:

[filter2d.zip](https://github.com/UPBGE/upbge/files/11607445/filter2d.zip)

![Capture](https://github.com/UPBGE/upbge/assets/10052509/18dc336e-6c1f-41b3-b021-136656713f6d)

probably caused by 30a25a42e64daf697d82e94174dd9311aee46ad4

Something looks wrong here: 
![Capture](https://github.com/UPBGE/upbge/assets/10052509/ccca1ffa-8f1f-42cc-baa6-8645ca3a9d72)

**Comment by illua1** [comment]
Hi, i can't reproduce this bug (did i have to get a blender crash?).

> Something looks wrong here:
Also, not sure, that is that?

**Comment by youle31** [comment]
Hello, the file I shared is crashing at opening for me both in blender and upbge (it's a file saved with upbge but I don't think the issue is related).

It's weird that you can't reproduce the issue on your end.

I'm on windows 10, with blender "main" branch built from sources with Visual Studio 2022 (17.5 (as Ray Molenkamp told to not update to 17.6)).

this:

https://user-images.githubusercontent.com/10052509/242131704-ccca1ffa-8f1f-42cc-baa6-8645ca3a9d72.PNG

sounds weird to me because I guess LISTBASE_FOREACH macro already contains the nsc_next = nsc->next.
Then i guess it is called twice which explains why the nsc becomes nullptr.
