### ISSUE TITLE
Upbge game logic nodes not showing up at all and can not be installed via addons on Mac

### ISSUE THREAD

**Issue by Shinxj90** [UPBGE/upbge#1815]
I have no idea what happened I tried to reinstall upbge 3.0 the game logic nodes just will not appear   no matter how many times I reinstall.   it used to work once upon a time (had to do some fanangling due to gatekeeper). I've tried deleting everything on the computer blender related even made sure I went to library and private folders. I have no idea what's going on. 

even navigated to the adding folder to replace the  folders no luck.

**Comment by luckychris** [comment]
what version of game logic node did u try to install?

**Comment by youle31** [comment]
I've no Mac computer to test on my side

**Comment by lordloki** [comment]
It works perfectly in upbge 0.36. Please, test in 0.36. I close the issue. if in 0.36 occurs the same, open the issue again. Thanks for reporting
