### ISSUE TITLE
exported .app file does not react to keyboard inputs

### ISSUE THREAD

**Issue by luckychris** [UPBGE/upbge#1816]
I followed a DefaultCube tutorial and just used the simple keyboard template, pressing P i could move the cube via ASDW-keys.
But...if i exported it, the app didn't react to keyboard inputs.

<img width="638" alt="image" src="https://github.com/UPBGE/upbge/assets/232549/0586c0df-ae44-4a1c-bb13-354579f7188c">

this is the add-on i enabled to export

this is my upbge version:

<img width="665" alt="image" src="https://github.com/UPBGE/upbge/assets/232549/3993ae51-4e66-4ac3-b133-8d37caff2d6f">

i am working on a m1 macbook.

by this i exported/created my app:

<img width="597" alt="image" src="https://github.com/UPBGE/upbge/assets/232549/76c06b26-b9d9-4714-9cf3-d2199b27b085">

what am i missing?

**Comment by youle31** [comment]
I've no Mac computer to test on my side

**Comment by lordloki** [comment]
In current upbge 0.36 it works perfectly. I just test it. Closing the issue.
If you find the same problem in 0.36, please open the issue again. Thanks for reporting.
