### ISSUE TITLE
error when compiling from source upbge

### ISSUE THREAD

**Issue by eliecer696** [UPBGE/upbge#1817]
am traying to build armory from GitHub source but i keep getting this error 

c1xx : fatal  error C1083: Cannot open source file: 'C:\build_windows_x64_vc17_Release\source\blender\makesrna\intern\r
na_controller_gen.cc': No such file or directory [C:\build_windows_x64_vc17_Release\source\blender\makesrna\intern\bf_r
na.vcxproj]

**Comment by youle31** [comment]
i did a potential fix related to that 2 hours earlier. Can you test with updated code? (git pull --rebase)

**Comment by eliecer696** [comment]
> i did a potential fix related to that 2 hours earlier. Can you test with updated code? (git pull --rebase)

now it complies no problem although i notice there are some upbge elements missing from the property panel like game physics

**Comment by youle31** [comment]
> now it complies no problem although i notice there are some upbge elements missing from the property panel like game physics

I have not this problem on my end, game physics properties are displayed.

You can eventually try to load factory settings and see if it changes something OR backup userpref.blend in c:/users/appdata(hidden)/roaming/UPBGE/Blender/4.0/config, remove it, then restart upbge (it will recreate a new userpref.blend)

**Comment by eliecer696** [comment]
it only happens when the eevee next is enabled

**Comment by youle31** [comment]
Okay, i added that to eevee-next, workbench-next... here https://github.com/UPBGE/upbge/commit/17c83705fb4339329cdd42ac8d13b53f74b2a4ee
