### ISSUE TITLE
Realtime Composite Crashes Engine

### ISSUE THREAD

**Issue by tbacon29** [UPBGE/upbge#1818]
If you have a overlay collection and are using the realtime compositor if you add an object it will crash the entire engine. So far I've only found that the logic bricks crash and haven't tested logic nodes and/or python

**Comment by tbacon29** [comment]
This is in the 0.36 version

**Comment by youle31** [comment]
[compo_addobj.zip](https://github.com/UPBGE/upbge/files/12000268/compo_addobj.zip)

I add this test file and will investigate later. Thanks for report.

**Comment by youle31** [comment]
I didn't understand the whole mechanism but did a tmp fix for that issue in mentionned commits, then i close this for now, until other bugs potentially arise...
