### ISSUE TITLE
Loading modules fails to work unless the script is "embedded" in the Blend file.

### ISSUE THREAD

**Issue by Feral3d** [UPBGE/upbge#1819]
Modules that are linked/embedded to a *.blend file work, however scripts that are in the game directory fail to load, it returns this error:

ModuleNotFoundError: No module named 'test'

You can test the error in this example file:
[module_test.zip](https://github.com/UPBGE/upbge/files/11986445/module_test.zip)

**Comment by youle31** [comment]
Thanks very much for report. It came from merge mistakes I did here: d5e14bca4bb668ae09eaf667fc14900b71227adf

I'll fix it right now. Thanks very much!

**Comment by Feral3d** [comment]
Thank you!!!
