### ISSUE TITLE
libusd_ms.so

### ISSUE THREAD

**Issue by akulamartin** [UPBGE/upbge#1821]
error while loading shared libraries: libusd_ms.so: cannot open shared object file: No such file or directory

Where can I find this library?

**Comment by youle31** [comment]
Hi, could you provide more infos about how we can reproduce this issue?

For reference we have this guide to report a bug: https://github.com/UPBGE/upbge/wiki/Report-a-bug-guide

You can tell us which build you were using, on which OS, precisions on your hardware, exact steps to reproduce the bug, eventually a test file.

**Comment by akulamartin** [comment]
My bad.I solved it by copying the libraries that came with the build to my /usr/lib folder.In addition how do you reduce the build size,mines 300mb.

**Comment by lordloki** [comment]
You shouldn't need to copy the libs to /usr/lib. What distro do you have?

To reduce the build size it is necessary to compile yourself the build removing the options that won't be used by you.

**Comment by akulamartin** [comment]
My system details :
  Kernel: 5.15.0-76-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Cinnamon 5.6.8
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy

Kindly give an example of how to build.

**Comment by lordloki** [comment]
I just tested in Ubuntu 21.10 and it works perfectly. I checked the library linked by the executable and the executable can find the libusd_ms.so in the lib folder:
![image](https://github.com/UPBGE/upbge/assets/1015605/91e83d92-1165-408e-931b-37e974fd27f7)

For compiling upbge for Linux you can check this guide: https://github.com/UPBGE/upbge/wiki/Build-UPBGE-on-Linux

**Comment by akulamartin** [comment]
Just a minute. I think I made a mistake. I meant the executable from the game runtime is large. I used the default scene for testing. My apologies.

![Large exe](https://github.com/UPBGE/upbge/assets/28145289/89db4aa3-b12e-4556-92e8-9d4c9b0d294e)

**Comment by lordloki** [comment]
The size of the game runtime is composed of: blender runtime + .blend
As blender has a size of around 300MB, the minimum size for the game runtime will be 300MB.

BTW, from your scrrenshoot i can see that the lib folder wasn't copied when the game was exported. I have to fix the "save as runtime" addon. Maybe it was the reason of the issue.

**Comment by lordloki** [comment]
Fixed here (https://github.com/UPBGE/blender-addons/commit/ac8a116d1088728c609ebda86ae58f719420ffdd).
We will release a 0.36.1 this month with important bugfixes. I will include this one. Thanks for reporting. I close the report
