### ISSUE TITLE
Doesn't compile since dc5370d

### ISSUE THREAD

**Issue by e2002e** [UPBGE/upbge#1822]
Lattest commit introduces a bug on compilation:

```
~/Documents/blender_git/upbge/source/blender/editors/screen/screen_edit.cc: In function ‘void ED_screen_refresh_blenderplayer(wmWindow*)’:
~/Documents/blender_git/upbge/source/blender/editors/screen/screen_edit.cc:1977:21: error: invalid conversion from ‘int (*)(const bContext*, const char*, bContextDataResult*)’ to ‘void*’ [-fpermissive]
 1977 |   screen->context = ed_screen_context;
      |                     ^~~~~~~~~~~~~~~~~
      |                     |
      |                     int (*)(const bContext*, const char*, bContextDataResult*)
```

I tried adding -fpermissive to be to CMAKE_C_FLAGS in the screen/CMakeLists.txt but it doesn't help.

After looking at the file I found the same declaration than line 1977 with a cast, copying it in stead of the faulty line solves the error: reinterpret_cast<void *>(ed_screen_context);

**Comment by youle31** [comment]
hi, thanks for the report. Yes i did as you suggested here: https://github.com/UPBGE/upbge/commit/0bb0edf849d354b989489a0c16ee0a203cb05bb0

it happened only on linux. i had other issues in debug builds but idk if i did something wrong or not. But release builds were compiling.

**Comment by youle31** [comment]
ok, troubles to build in debug mode were related to bad RAM management with compiler + current chipset drivers.... Then i close this report. Thanks.

**Comment by e2002e** [comment]
There were a lot of errors that actually don't come from the code indeed.
i.e runing make again would solve them.
I guess this is the compiler issue you'r refering to.
Np. bye.
