### ISSUE TITLE
Upbge 0.36 windows 7 build doesn't work

### ISSUE THREAD

**Issue by lordloki** [UPBGE/upbge#1823]
Reported in discord. I will investigate it and upload a new build

**Comment by HauptmannTod** [comment]
Hello,, thank you very much for your efforts!
It returns error - The Procedure entry point CreateFile2 could not be located in the dynamic link library KERNEL32.dll.
I tried to start blender.exe

**Comment by lordloki** [comment]
Thanks for test. I already detect where is the error. When i upload the release fix it works ok.

**Comment by lordloki** [comment]
The new build will be around 16th august. Now, I close the issue as it is fixed currently. Thanks for testing,
