### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by e2002e** [UPBGE/upbge#1824]
[ 43%] Building CXX object intern/cycles/device/CMakeFiles/cycles_device.dir/device.cpp.o
/bin/sh: 1: Syntax error: Unterminated quoted string
make[3]: *** [intern/cycles/device/CMakeFiles/cycles_device.dir/build.make:76 : intern/cycles/device/CMakeFiles/cycles_device.dir/device.cpp.o] Erreur 2
make[2]: *** [CMakeFiles/Makefile2:4194 : intern/cycles/device/CMakeFiles/cycles_device.dir/all] Erreur 2

**Comment by youle31** [comment]
I can't reproduce this issue compiling with:

make update
make clean
make -j16

on linux mint 21.something
gcc --version: 11.3.0

**Comment by e2002e** [comment]
I had modified CMakeLists.txt in cycles folder because -allow-unsupported-compiler was needed.
Stashed it, did a git pull and it's compiling.
Just a question: Does eevee next support reflections / refractions already (on 4.0) ? I can use it but I don't get these effects ; also framerate drops really low.
