### ISSUE TITLE
UPBGE 0.36 Standalone Start "maximize" >  without blurring/losing resolution/sharpness

### ISSUE THREAD

**Issue by Dart3D** [UPBGE/upbge#1827]
In version 0.36, using "Standalone Start" no Fullscreen > image is blurred/little sharpness > when maximizing the program/maximize the "Standalone Start" window. 
# System Debian 12 > x11 > Nvidia > GTX 10 Series
# In version 0.30 it works perfectly "increase/maximize"  without blurring/losing resolution/sharpness
# Depth Of Field "is not used"
# video showing "no sharpness" on the edges of the cube, when maximizing > https://www.4shared.com/s/f2R93ApHVge
# download the video to watch with higher resolution

**Comment by lordloki** [comment]
Nvidia propietary driver?

**Comment by Dart3D** [comment]
# 2 testing machines > different processors "i5 760" and "Q9550"
# Nvidia GTX 970 and GTX 1050
# Done the tests on proprietary "i5 760" and non-proprietary "Q9550";
# Wayland doesn't work perfectly, so preferable to use x11
# New problem > export game does not work

**Comment by lordloki** [comment]
Thanks for the info. Export problem has been already fixed. The fix will be included in the next release 0.36.1. Meanwhile you can copy the lib folder from Upbge root folder to your game folder where the executable ia

**Comment by youle31** [comment]
The commit mentionned seem to fix this issue even if it sounds weird/dangerous
