### ISSUE TITLE
upbge-0.36-windows-x86_64 crashes on logic node search

### ISSUE THREAD

**Issue by Snowdaw** [UPBGE/upbge#1828]
UPBGE gives an EXCEPTION_ACCESS_VIOLATION when searching for logic nodes when multiple logic node trees are present

Crash file [blender.crash.txt](https://github.com/UPBGE/upbge/files/12131510/blender.crash.txt)

Reproduction:

1. Start UPBGE
2. Go to the Logic Node Editor
3. Create a new node tree
4. Create another node tree
5. press ctrl + a and s to search for logic nodes
6. Observe the crash

On a side note, I don't think the logic node search is working correctly when it is working as it does not give the same results as found in the drop down menu. This may be the same problem.

**Comment by youle31** [comment]
Fixed by @IzaZed here: https://github.com/UPBGE/UPBGE-logicnodes/commit/85d14df3fc461771348afad6e73c6bf77484e57c

Thanks for the report and Thanks for the fix!
