### ISSUE TITLE
UPBGE 0.3+ Every version of engine closes when i start playing

### ISSUE THREAD

**Issue by amcamteyzem** [UPBGE/upbge#1829]
Hello. I wanted to upgrade to UPBGE Game engine versions above 0.3 and downloaded version 0.3. I designed a version of my game with only arm animations and pressed the "p" key. As soon as I pressed the application closed. I saved the project with the "Recover last session" button, but I can't start the game in any way. 0.
The same problem occurred when I upgraded to version 34. I just tried it in version 0.4 and faced the same problem again. I started it with the blender_debug_log.cmd file located inside the engine's files and it gave me a report. I have attached the report. You can have a look. I don't know about these new versions but it is really important for me to fix this issue.
Thank you in advance for your help ^^ (sorry for my english btw, im using translate)

My PC Specs :
- Windows 11 x64 architecture
- Intel Core i5 13400F
- NVidia GeForce RTX 3060 12GB
- 32GB of RAM

[blender_debug_output.txt](https://github.com/UPBGE/upbge/files/12161491/blender_debug_output.txt)
[blender_system_info.txt](https://github.com/UPBGE/upbge/files/12161492/blender_system_info.txt)

[blender_debug_output.txt](https://github.com/UPBGE/upbge/files/12161507/blender_debug_output.txt)
[blender_system_info.txt](https://github.com/UPBGE/upbge/files/12161508/blender_system_info.txt)

**Comment by amcamteyzem** [comment]
> Hi could you share the test file please? Thanks

it's 300 mb 😨😨😨

I cannot add directly 'cause the file limit. So i drop the drive link over here :
https://drive.google.com/file/d/1h-Lwc10Zd5mAt5WGsiJzoEPCw4vS8uO4/view?usp=sharing

**Comment by youle31** [comment]
Waiting for a fix on my side, you can fix the issue on you side:

The Camera you are using is a child of an Object which is considered as inactive (because the eye beside the parent is unchecked).

Having parents and children not in the same layer (active objects and inactive objects) causes troubles, then you always need to ensure parent and children are in the same layer.

**Comment by amcamteyzem** [comment]
> 

thanks for your help. It is not crashing now but works very slow. For example, in the empty scene:

- I get about 2100fps. 

when i add an armature to my scene and animate it:
- I get about 200fps and scene is Empty. Not even any cube. Just animated 2 arms.

Then i add a player collider to make fps movements etc. this value down to 70fps

but still, scene is empty. as you know we need a scene to play this game. Forest, city etc. 

Probably when i add them, my fps will drop down to 30's. Is there any way to fix that?
or i have to return upbge 0.2.x versions

**Comment by youle31** [comment]
Yes, 0.3+ based on blender, have low performances with armatures. You can use 0.2.5 or range if you prefer, or try to lower number of animated vertices/optimize in 0.3+

**Comment by amcamteyzem** [comment]
thanks for help ❤️
