### ISSUE TITLE
UPBGE 4.0.0 crashes when pressing P

### ISSUE THREAD

**Issue by arttuautio** [UPBGE/upbge#1831]
when i start UPBGE from the commandline, it says:
Debug: 1586, 870
rcti: : xmin 0, xmax 1585, ymin 95, ymax 964 (1585x869)
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF6A67350B4
Module  : blender.exe
Thread  : 000048d0
Writing: C:\Users\  . . .  \AppData\Local\Temp\.blend.crash.txt

Here is .blend.crash.txt:
# Blender 4.0.0, Commit date: 2023-07-16 19:35, Hash 7b48905a3bc5

# backtrace
Exception Record:

ExceptionCode         : EXCEPTION_ACCESS_VIOLATION
Exception Address     : 0x00007FF6A67350B4
Exception Module      : blender.exe
Exception Flags       : 0x00000000
Exception Parameters  : 0x2
	Parameters[0] : 0x0000000000000000
	Parameters[1] : 0x0000000000000000

Stack trace:
blender.exe         :0x00007FF6A672A4A0  PyInit_aud
blender.exe         :0x00007FF6A6A11350  xmlXPtrNewContext
blender.exe         :0x00007FF6A6A11350  xmlXPtrNewContext
blender.exe         :0x00007FF6A35D33C0  PyInit_mathutils_noise
blender.exe         :0x00007FF6A27B4810  xmlFileMatch
blender.exe         :0x00007FF6A27B4810  xmlFileMatch
blender.exe         :0x00007FF6A27B4810  xmlFileMatch
blender.exe         :0x00007FF6A27B4810  xmlFileMatch
blender.exe         :0x00007FF6A27B4810  xmlFileMatch
blender.exe         :0x00007FF6A27B4810  xmlFileMatch
blender.exe         :0x00007FF6A27B4810  xmlFileMatch
blender.exe         :0x00007FF6A22C7FC6  Symbols not available

Loaded Modules :
0x00007FF6A2190000 4.0.0.0              blender.exe  
0x00007FF833510000 10.0.19041.3155      ntdll.dll  
0x00007FF8326A0000 10.0.19041.3155      KERNEL32.DLL  
0x00007FF831270000 10.0.19041.3155      KERNELBASE.dll  
0x00007FF832E40000 10.0.19041.2788      USER32.dll  
0x00007FF830D50000 10.0.19041.3208      win32u.dll  
0x00007FF831E60000 10.0.19041.2913      GDI32.dll  
0x00007FF82C700000                      tbb.dll  
0x00007FF82A5E0000                      tbbmalloc.dll  
0x00007FF830E70000 10.0.19041.2913      gdi32full.dll  
0x00007FF830F90000 10.0.19041.789       msvcp_win.dll  
0x00007FF831170000 10.0.19041.789       ucrtbase.dll  
0x00007FF833060000 10.0.19041.2913      ADVAPI32.dll  
0x00007FF832AE0000 7.0.19041.546        msvcrt.dll  
0x00007FF831E90000 10.0.19041.2913      sechost.dll  
0x00007FF8329B0000 10.0.19041.3208      RPCRT4.dll  
0x00007FF8316B0000 10.0.19041.3208      SHELL32.dll  
0x00007FF82BFD0000 14.29.30139.0        VCRUNTIME140.dll  
0x00007FF819150000 14.29.30139.0        MSVCP140.dll  
0x00007FF82B9F0000 10.0.19041.546       VERSION.dll  
0x00007FF831570000 10.0.19041.2965      ole32.dll  
0x00007FF82E3A0000 14.29.30139.0        VCRUNTIME140_1.dll  
0x00007FF833110000 10.0.19041.2788      combase.dll  
0x00007FF832770000 10.0.19041.2075      SHLWAPI.dll  
0x00007FF832060000 10.0.19041.546       WS2_32.dll  
0x00007FF81FAC0000 10.0.19041.867       dbghelp.dll  
0x00007FFFFF410000                      shaderc_shared.dll  
0x00007FF832180000 10.0.19041.1865      shcore.dll  
0x00007FF80A950000 1.3.236.0            vulkan-1.dll  
0x00007FF821700000                      boost_python310-vc142-mt-x64-1_80.dll  
0x00007FF832E10000 10.0.19041.2673      IMM32.dll  
0x00007FF830E20000 10.0.19041.3155      CFGMGR32.dll  
0x00007FFFF4E60000 4.1.0.0              embree4.dll  
0x00007FFFFC300000                      OpenColorIO_2_2.dll  
0x00007FFFE9930000                      OpenImageIO.dll  
0x00007FF818F80000                      OpenImageIO_Util.dll  
0x00007FF82A5C0000 60.1.100.0           avdevice-60.dll  
0x00007FFFFA710000 60.3.100.0           avformat-60.dll  
0x00007FF832830000 10.0.19041.3208      OLEAUT32.dll  
0x00007FFFE2B30000 60.3.100.0           avcodec-60.dll  
0x00007FF803DB0000 58.2.100.0           avutil-58.dll  
0x00007FF830D80000 10.0.19041.3208      bcrypt.dll  
0x00007FF8162B0000 7.1.100.0            swscale-7.dll  
0x00007FFFF8A60000 1.1.0.0              sndfile.dll  
0x00007FFFEA220000                      usd_ms.dll  
0x00007FF809290000 1.21.1.0             OpenAL32.dll  
0x00007FFFF8900000 2.0.20.0             SDL2.dll  
0x00007FF81FE80000                      Iex.dll  
0x00007FF832230000 10.0.19041.3155      SETUPAPI.dll  
0x00007FFFF8630000                      OpenEXR.dll  
0x00007FFFE8180000 10.0.0.0             openvdb.dll  
0x00007FF81A0F0000                      Imath.dll  
0x00007FF8295E0000                      boost_thread-vc142-mt-x64-1_80.dll  
0x00007FF815130000                      boost_locale-vc142-mt-x64-1_80.dll  
0x00007FF804030000                      gmp-10.dll  
0x00007FF80FCA0000                      epoxy-0.dll  
0x00007FF82C740000                      tbbmalloc_proxy.dll  
0x00007FF829540000 10.0.19041.1         AVIFIL32.dll  
0x00007FF829F40000 6.10.19041.1110      COMCTL32.dll  
0x00007FF82E7D0000 10.0.19041.746       dwmapi.dll  
0x00007FFFF8050000 3.10.12150.1013      python310.dll  
0x00007FF80BAA0000                      fftw3.dll  
0x00007FF82C630000                      libgmpxx.dll  
0x00007FF826230000 10.0.19041.1503      dbgeng.dll  
0x00007FF80A8C0000                      OpenEXRCore.dll  
0x00007FFFF79B0000 6.1.0.0              sycl6.dll  
0x00007FF8293D0000 4.10.100.0           swresample-4.dll  
0x00007FF828EA0000 10.0.19041.546       Secur32.dll  
0x00007FF825FC0000 10.0.19041.1         AVICAP32.dll  
0x00007FF82A2A0000 10.0.19041.546       WINMM.dll  
0x00007FF806DC0000                      MaterialXRender.dll  
0x00007FF800410000 10.0.19041.2193      OPENGL32.dll  
0x00007FF818DF0000                      MaterialXGenGlsl.dll  
0x00007FF81FF40000                      MaterialXFormat.dll  
0x00007FFFFF350000                      MaterialXGenShader.dll  
0x00007FFFFA510000                      MaterialXCore.dll  
0x00007FF8293C0000                      IlmThread.dll  
0x00007FF8216D0000 10.0.19041.1         MSVFW32.dll  
0x00007FF8251C0000 10.0.19041.1         MSACM32.dll  
0x00007FF826170000 10.0.19041.1503      dbgmodel.dll  
0x00007FF82C180000 10.0.19041.546       XmlLite.dll  
0x00007FF819FB0000 10.0.19041.2193      GLU32.dll  
0x00007FF820510000 10.0.19041.1         winmmbase.dll  
0x00007FF830AD0000 10.0.19041.2130      SSPICLI.DLL  
0x00007FF82F4A0000 10.0.19041.2311      dxgi.dll  
0x00007FF82EAC0000 10.0.19041.546       kernel.appcore.dll  
0x00007FF82ECC0000 10.0.19041.3208      windows.storage.dll  
0x00007FF830630000 10.0.19041.2788      Wldp.dll  
0x00007FF82E5D0000 10.0.19041.2193      uxtheme.dll  
0x00007FF8310E0000 10.0.19041.2486      bcryptPrimitives.dll  
0x00007FF830B20000 10.0.19041.3155      profapi.dll  
0x00007FF8320D0000 2001.12.10941.16384  clbcatq.dll  
0x00007FF82B000000 10.0.19041.1503      MMDevApi.dll  
0x00007FF830980000 10.0.19041.3155      DEVOBJ.dll  
0x00007FF831F40000 10.0.19041.2673      MSCTF.dll  
0x00007FF82C750000 7.0.19041.1741       PROPSYS.dll  
0x00007FF82B750000 10.0.19041.3155      AppXDeploymentClient.dll  
0x00007FFFD2FE0000 31.0.15.3179         nvoglv64.dll  
0x00007FF82C8B0000 10.0.19041.546       WTSAPI32.dll  
0x00007FF8307C0000 10.0.19041.2251      msasn1.dll  
0x00007FF82A8C0000 10.0.19041.906       cryptnet.dll  
0x00007FF830BF0000 10.0.19041.3208      CRYPT32.dll  
0x00007FF82A650000 10.0.19041.2546      drvstore.dll  
0x00007FF830580000 10.0.19041.546       cryptbase.dll  
0x00007FF830DB0000 10.0.19041.2913      WINTRUST.dll  
0x00007FF82FD60000 10.0.19041.546       ntmarta.dll  
0x00007FF8279D0000 10.0.19041.546       dxcore.dll  
0x00007FF8301A0000 10.0.19041.546       powrprof.dll  
0x00007FF830010000                      UMPDC.dll  
0x00007FF82F8E0000 10.0.19041.3155      WINSTA.dll  
0x00007FF820480000 10.0.19041.1387      dataexchange.dll  
0x00007FF82C8D0000 10.0.19041.2913      d3d11.dll  
0x00007FF82D810000 10.0.19041.2913      dcomp.dll  
0x00007FF82ADD0000 10.0.19041.3031      twinapi.appcore.dll  
0x00007FF826070000 10.0.19041.3086      textinputframework.dll  
0x00007FF82E0F0000 10.0.19041.2193      CoreMessaging.dll  
0x00007FF82DD80000 10.0.19041.546       CoreUIComponents.dll  
0x00007FF82D6B0000 10.0.19041.2788      wintypes.dll  
0x00007FF819F30000 7.2.19041.746        Oleacc.dll  
0x00007FFFF3C40000 1.0.5.10             Wintab32.dll  
0x00007FF814190000 10.0.19041.1806      MPR.dll  
0x00007FF808FF0000 6.4.2.3              Wacom_Tablet.dll  
0x00007FF80CC50000 10.0.19041.1949      explorerframe.dll  
0x00007FF8214C0000 10.0.19041.1566      directmanipulation.dll  
0x00007FF82C600000 10.0.19041.546       drprov.dll  
0x00007FF8188F0000 10.0.19041.2604      ntlanman.dll  
0x00007FF8188D0000 10.0.19041.546       davclnt.dll  
0x00007FF82A1E0000 10.0.19041.546       DAVHLPR.dll  
0x00007FF82FDA0000 10.0.19041.3155      wkscli.dll  
0x00007FF812B10000 10.0.19041.546       cscapi.dll  
0x00007FF830070000 10.0.19041.546       netutils.dll  
0x00007FF830590000 10.0.19041.546       CRYPTSP.dll  
0x00007FF82FC40000 10.0.19041.1052      rsaenh.dll  
0x00007FF82F460000 10.0.19041.546       hid.dll  
0x00007FF8197B0000 10.0.19041.1         dinput8.dll  
0x00007FF8237C0000 10.0.19041.1741      inputhost.dll  
0x00007FF8290C0000 10.0.19041.3031      Windows.Gaming.Input.dll  
0x00007FF827EF0000 10.0.19041.3031      OneCoreUAPCommonProxyStub.dll  
0x00007FF821AE0000 10.0.19041.844       XInput1_4.dll  
0x000001F089330000 3.10.12150.1013      python3.DLL  
0x00007FFFE7ED0000                      _multiarray_umath.cp310-win_amd64.pyd  
0x00007FF821620000                      _multiarray_tests.cp310-win_amd64.pyd  
0x00007FF8215D0000 3.10.12150.1013      _socket.pyd  
0x00007FF830030000 10.0.19041.2788      IPHLPAPI.DLL  
0x00007FF81FE70000 3.10.12150.1013      select.pyd  
0x00007FF819120000 3.10.12150.1013      _ctypes.pyd  
0x00007FF81FCB0000                      libffi-7.dll  
0x00007FFFF77A0000                      _umath_linalg.cp310-win_amd64.pyd  
0x00007FF81F660000                      _pocketfft_internal.cp310-win_amd64.pyd  
0x00007FFFFDAF0000                      mtrand.cp310-win_amd64.pyd  
0x00007FF8186B0000                      bit_generator.cp310-win_amd64.pyd  
0x00007FF8171C0000                      _common.cp310-win_amd64.pyd  
0x00007FF81F970000 3.10.12150.1013      _hashlib.pyd  
0x00007FFFE7990000 3.0.9.0              libcrypto-3.dll  
0x00007FF8163B0000                      _bounded_integers.cp310-win_amd64.pyd  
0x00007FF819B90000                      _mt19937.cp310-win_amd64.pyd  
0x00007FF819100000                      _philox.cp310-win_amd64.pyd  
0x00007FF818910000                      _pcg64.cp310-win_amd64.pyd  
0x00007FF81A0E0000                      _sfc64.cp310-win_amd64.pyd  
0x00007FFFFBFF0000                      _generator.cp310-win_amd64.pyd  
0x00007FF819FA0000 3.10.12150.1013      _queue.pyd  

# Python backtrace

**Comment by youle31** [comment]
Is it crashing in this build from today (2023/08/01): https://ufile.io/u2od6s9k

If yes, can you share a test file and give us details about exact steps to reproduce the crash? Thanks

**Comment by youle31** [comment]
oh, it is possible that it comes from audio. In user preferences, you can choose openAL instead of WASAPI for audio and test again

**Comment by youle31** [comment]
We can't do something from provided informations, then I close this report until more informations are given.

**Comment by arttuautio** [comment]
Hi, i must say that i am pretty newbie on what comes to bugreporting

Exact steps: i just start Upbge and press P, no special file

I am student at media lab and now i tried another computer and upbge is working fine there.
Only difference that i noticed is that the other computer has Intel Core i7-3770K processor. And this computer (that i am trying to fix) has AMD Ryzen 5 1600 Six-Core processor.

I noticed also that UPBGE 3 and 3.6 wont start gamemode either

I have Live-Linux Mint on USB stick. And UPBGE 3.6 works perfectly there. So theoretically this computer should be capable of running UPBGE gamemode.

this txt is from command prompt when i start blender with arguments: --factory-startup --debug-all :

wmEvent type:112/P, val:1/PRESS, prev_type:1/LEFTMOUSE, prev_val:2/RELEASE, modifier={}, keymodifier:0, flag:{}, mouse:(1027,228), utf8:'p', pointer:0000014E065B3320
UI_menutype_draw: opening menu "VIEW3D_MT_editor_menus"
Debug: 1586, 870
rcti: : xmin 0, xmax 1585, ymin 95, ymax 964 (1585x869)
graph_id_tag_update: id=GRScene Collection flags=GEOMETRY, ID_RECALC_HIERARCHY source=USER_EDIT
graph_id_tag_update: id=GRScene Collection flags=GEOMETRY, ID_RECALC_HIERARCHY source=USER_EDIT
DEG_relations_tag_update: Tagging relations for update.
[SCScene :: ViewLayer]: DEG_graph_tag_relations_update: Tagging relations for update.
graph_id_tag_update: id=SCScene flags=COPY_ON_WRITE source=RELATIONS
[SCScene :: ViewLayer]: Removed 9 relations to no-op nodes
graph_id_tag_update: id=OBgame_default_cam flags=TRANSFORM, GEOMETRY, COPY_ON_WRITE source=RELATIONS
graph_id_tag_update: id=CACamera.001 flags=COPY_ON_WRITE source=RELATIONS
graph_id_tag_update: id=GRScene Collection flags=GEOMETRY, ID_RECALC_HIERARCHY source=RELATIONS
Depsgraph built in 0.003196 seconds.
graph_id_tag_update: id=OBgame_default_cam flags=TRANSFORM, GEOMETRY, COPY_ON_WRITE source=VISIBILITY
graph_id_tag_update: id=CACamera.001 flags=COPY_ON_WRITE source=VISIBILITY
[SCScene :: ViewLayer]: Operation is entry point for update: TRANSFORM_INIT()
[SCScene :: ViewLayer]: Operation is entry point for update: COPY_ON_WRITE()
[SCScene :: ViewLayer]: Operation is entry point for update: VIEW_LAYER_EVAL()
[SCScene :: ViewLayer]: Operation is entry point for update: TRANSFORM_LOCAL()
[SCScene :: ViewLayer]: Operation is entry point for update: COPY_ON_WRITE()
[SCScene :: ViewLayer]: Operation is entry point for update: SCENE_EVAL()
[SCScene :: ViewLayer]: Operation is entry point for update: COPY_ON_WRITE()
[SCScene :: ViewLayer]: Operation is entry point for update: VISIBILITY()
[SCScene :: ViewLayer]: Operation is entry point for update: HIERARCHY()
[SCScene :: ViewLayer]: Operation is entry point for update: PARAMETERS_EXIT()
[SCScene :: ViewLayer]: Operation is entry point for update: AUDIO_VOLUME()
[SCScene :: ViewLayer]: Operation is entry point for update: TRANSFORM_EVAL()
[SCScene :: ViewLayer]: Operation is entry point for update: PARAMETERS_EVAL()
[SCScene :: ViewLayer]: Operation is entry point for update: SOUND_EVAL()
[SCScene :: ViewLayer]: Operation is entry point for update: TRANSFORM_FINAL()
[SCScene :: ViewLayer]: Operation is entry point for update: HIERARCHY()
[SCScene :: ViewLayer]: Operation is entry point for update: PARAMETERS_ENTRY()
[SCScene :: ViewLayer]: Operation is entry point for update: COPY_ON_WRITE()
[SCScene :: ViewLayer]: Operation is entry point for update: TRANSFORM_SIMULATION_INIT()
[SCScene :: ViewLayer]: Operation is entry point for update: AUDIO_ENTRY()
[SCScene :: ViewLayer]: Operation is entry point for update: SEQUENCES_EVAL()
[SCScene :: ViewLayer]: Operation is entry point for update: GEOMETRY_EVAL_DONE()
[SCScene :: ViewLayer]: Accumulated recalc bits for SCScene: 8192
[SCScene :: ViewLayer]: Accumulated recalc bits for OBCube: 128
[SCScene :: ViewLayer]: Accumulated recalc bits for OBLight: 128
[SCScene :: ViewLayer]: Accumulated recalc bits for OBCamera: 128
[SCScene :: ViewLayer]: Accumulated recalc bits for OBgame_default_cam: 8323
[SCScene :: ViewLayer]: Accumulated recalc bits for CACamera.001: 8192
[SCScene :: ViewLayer]: Accumulated recalc bits for GRScene Collection: 67117058
[SCScene :: ViewLayer]: Accumulated recalc bits for GRCollection: 0
[SCScene :: ViewLayer]: deg_evaluate_copy_on_write on GRScene Collection (0000014E022B5B78)
[SCScene :: ViewLayer]: deg_evaluate_copy_on_write on SCScene (0000014E7A3EA078)
[SCScene :: ViewLayer]: deg_evaluate_copy_on_write on CACamera.001 (0000014E06130138)
[SCScene :: ViewLayer]: deg_evaluate_copy_on_write on OBgame_default_cam (0000014E0611C138)
[SCScene :: ViewLayer]: layer_eval_view_layer on ViewLayer (0000014E0661DEF8)
[SCScene :: ViewLayer]: BKE_object_eval_light_linking on OBgame_default_cam (0000014E0611C138)
[SCScene :: ViewLayer]: BKE_object_eval_light_linking on OBCube (0000014E021E8138)
[SCScene :: ViewLayer]: BKE_object_eval_light_linking on OBLight (0000014E0221A0B8)
[SCScene :: ViewLayer]: BKE_object_eval_light_linking on OBCamera (0000014E02218138)
[SCScene :: ViewLayer]: BKE_object_eval_local_transform on OBgame_default_cam (0000014E0611C138)
[SCScene :: ViewLayer]: SEQ_eval_sequences on SCScene (0000014E7A3EA078)
[SCScene :: ViewLayer]: BKE_object_eval_eval_base_flags on OBgame_default_cam (0000014E0611C138)
[SCScene :: ViewLayer]: BKE_object_eval_eval_base_flags on OBCamera (0000014E02218138)
[SCScene :: ViewLayer]: BKE_object_eval_eval_base_flags on OBCube (0000014E021E8138)
[SCScene :: ViewLayer]: BKE_object_eval_eval_base_flags on OBLight (0000014E0221A0B8)
[SCScene :: ViewLayer]: BKE_object_eval_transform_final on OBgame_default_cam (0000014E0611C138)
[SCScene :: ViewLayer]: deg_evaluate_object_node_visibility on OBgame_default_cam (0000014E0611C138)
[SCScene :: ViewLayer]: deg_evaluate_object_node_visibility on OBCamera (0000014E02218138)
[SCScene :: ViewLayer]: deg_evaluate_object_node_visibility on OBCube (0000014E021E8138)
[SCScene :: ViewLayer]: deg_evaluate_object_node_visibility on OBLight (0000014E0221A0B8)
Depsgraph updated in 0.015018 seconds.
Depsgraph evaluation FPS: 0.179171
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF7A74141B2
Module  : blender.exe
Thread  : 00003350


I updated Nvidia drivers and AMD drivers.

How to check that this computer have all the necessary drivers and stuff in place

**Comment by youle31** [comment]
I can't tell what's wrong... None of my computers are crashing with default startup scene when pressing P and I can't tell what's wrong from stacktrace...

Idk, if it is working from an usb key but not on hard disk drive, maybe you can check for errors on your hard drive, update hard drive firmware... See if it is the same on different OS on the same drive... Try updating the BIOS (if you managed to reproduce the crash on usb stick with 0.30)... See if it is still crashing with only 1 RAM stick...

idk, i can't tell without the ability to reproduce the crash.

You can also test last 0.4 alpha which has a little change in the code which makes upbge more stable on 1 of my PC with an AMD CPU...
