### ISSUE TITLE
Upbge Crashes when i try to make a Fps game

### ISSUE THREAD

**Issue by MigrelNB** [UPBGE/upbge#1835]
So, i'm new to GitHub and i don't know if it's here that i report errors about upbge. But i was trying to make a fps game but when i tried to parent an object to the camera, upbge crashed. But that was in 0.3.0, now on 0.3.6, i just make a basic fps controller, the camera becomes very laggy, only the camera, everything else runs smoothly, like if i pressed w to move fowards, it would move foward normally but when i move the mouse to control the camera it becomes laggy, and it still crashes if i parent an object to the camera.

**Comment by youle31** [comment]
About the lag, it can come from true pulse not enabled on movement sensor.

About the crash, could you share a test file? Thanks

**Comment by MigrelNB** [comment]
ok so, i tried enabled true pulse on the movement sensor, and not only did that fix the laggy movement, but somehow it doesn't crash anymore, thanks for the help.

**Comment by youle31** [comment]
ok, I close this report for now then, and if you have a crash and a file to test file and reliable steps to reproduce the crash, i'll reopen

**Comment by MigrelNB** [comment]
no wait, i'm very confused now, i tried to parent it to the camera and it didn't crash, but then i added an animation to the object i parented, and it crashed, so here's the file 
[Cartoon game.zip](https://github.com/UPBGE/upbge/files/12313482/Cartoon.game.zip)

**Comment by MigrelNB** [comment]
now it works, thanks.
