### ISSUE TITLE
UPBGE version 0.36.1 crashed in start

### ISSUE THREAD

**Issue by Villi89S** [UPBGE/upbge#1839]
I started UPBGE version 0.36.1 for windows 7 and get alarm crash
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x0000000069AE2BB4
Module  : atio6axx.dll
Thread  : 00000ab0
Switching to fully guarded memory allocator.
Blender 3.6.2
Build: 2023-08-19 21:19:04 Windows 
argv[0] = C:\Users\Виктор\Desktop\upbge-0.36.1-windows7-x86_64\upbge-0.36.1-windows7-x86_64\\blender
argv[1] = --debug
argv[2] = --debug-cycles
argv[3] = --python-expr
argv[4] = import bpy; bpy.ops.wm.sysinfo(filepath=r'C:\Users\51FB~1\AppData\Local\Temp\blender\debug_logs\blender_system_info.txt')
Writing: C:\Users\51FB~1\AppData\Local\Temp\blender.crash.txt
its debug output text info

**Comment by Villi89S** [comment]
Problem solution - im download video drivers for ATI video card - a replace dll driver file in folder system32 and drop drive file to folder from UPBGE and start and all working, not crash, this link to video drivers https://ru.dll-files.com/atio6axx.dll.html, Thank for developers UPBGE for windows 7, im dream use this GE from 2018 today may dreams make is real

**Comment by youle31** [comment]
ok, I close this as problem solved.
