### ISSUE TITLE
Cannot change theme of Logic Bricks Editor

### ISSUE THREAD

**Issue by Ikxi1** [UPBGE/upbge#1859]
UPBGE version: 0.36.1

I'm bad at explaining, so I attached a video:

https://github.com/UPBGE/upbge/assets/69396495/f8311fc8-06d8-40fe-8c3f-748fac71536f

Edit:
OS: Windows 11 Version	10.0.22631 Build 22631
GPU: NVidia 2080Ti

**Comment by youle31** [comment]
it's fixed in upbge based on blender 4.1alpha
