### ISSUE TITLE
UPBGE 0.36.1 consistently crashes immediately after Blender Game Engine starts.

### ISSUE THREAD

**Issue by TheAstralSnowstorm** [UPBGE/upbge#1897]
This issue came about yesterday as I was trying to diagnose a problem with the uplogic module not being detected, but due to this crash bug, the Blender Game Engine component is rendered completely useless and the prior problem cannot be diagnosed any further until this one gets resolved first.

The specific error code this emits was **EXCEPTION_ACCESS_VIOLATION** and is only triggered immediately after the Game Engine component starts, so there hopefully shouldn't be too difficult to track down the bug (assuming it's software related, that is.)

I've tried the following to resolve this issue (of which nothing worked):
Re-downloading UPBGE 0.36.1.
Removing anything related to UPBGE 0.36.1 in the file system and then launching UPBGE again.
Re-installing Windows (This usually solves any sudden crash bug, but somehow it didn't here.)

Specific version: upbge-0.36.1-windows7-x86_64

Crash logs created:
[blender_debug_output(Debug Log).txt](https://github.com/user-attachments/files/15523769/blender_debug_output.Debug.Log.txt)
[blender_debug_output(Debug GPU).txt](https://github.com/user-attachments/files/15523770/blender_debug_output.Debug.GPU.txt)

**Comment by TheAstralSnowstorm** [comment]
Apparently this is a bug when running on Windows 7, I ran the exact same build on Windows 8.1 and UPBGE's game engine loads perfectly fine instead of immediately crashing somehow. I tried running in compatibility mode just in case, but saw no difference.

So it seems to me that the Windows 7 build was not patched properly, and I couldn't test if it was isolated to the hardware I was using since the only other hardware that I had that could run Windows 7 was so hopelessly under-powered to the point where UPBGE itself couldn't even finish loading and crashed with with the error code **EXCEPTION_STACK_OVERFLOW**

**Comment by youle31** [comment]
We need test file and steps to reproduce the bug
