### ISSUE TITLE
Clarify license issue

### ISSUE THREAD

**Issue by ShalokShalom** [UPBGE/upbge#1899]
As far as I understand, does the UPBGE ship the GPL licensed Blender engine - that means, I am supposed to relicense my game under the GPL 2 as well. 

And I also figured, that the blend files - so my game assets, logic nodes/bricks and so on, are allowed to be under any license, but the Python scripts need to be GPL as well. 

Is that all correct that way?
I recommend documenting that, so that people are informed about the status quo.

**Comment by lordloki** [comment]
It is indicated in the UPBGE manual
https://upbge.org/docs/latest/manual/manual/deployment/licensing.html

**Comment by ShalokShalom** [comment]
Thanks a lot. I did not find this issue, and think there could be a mention around here:

![Screenshot_20240614_211146](https://github.com/UPBGE/upbge/assets/6344099/82c8601e-f14c-4bf2-ae40-3e3955e822e3)

There is no search, so simply typing in "license" would not yield results. 

It is currently listed in the "Contribute" section. 
As a game engine user, I am not necessarily interested into contributing. 

I am interested, how the license effects me as an user.

**Comment by youle31** [comment]
I close this report since there is already a documentation about license
