### ISSUE TITLE
Sprite Animation node issue

### ISSUE THREAD

**Issue by PancheteG3D** [UPBGE/upbge#1901]
[SpriteAnimationIssue.zip](https://github.com/user-attachments/files/16046456/SpriteAnimationIssue.zip)

Hello, I've found a bug in the sprite animation node. The issue is self-explanatory in the MP4 file I've attached here. I've also attached the .blend, so you can test it by yourself.
The issue is basically that in a 225 frames in a sprite sheet (15x15 frames), when the frame is 90, the rendered frame jumps to 105. When the frame is 105 it jumps to 120. When the frame is 120, it jumps to 135... (Curiously, these are the last frames of the 6th, 7th 8th, 11th, 12th and 13th files). 
Thanks for the time taken on it.
https://github.com/UPBGE/upbge/assets/66872192/12747bf9-8063-44df-8544-025a3ec5f8aa

**Comment by youle31** [comment]
it should be fixed in last master, thanks for report
