### ISSUE TITLE
Regarding node creation buttons, the python script is called through the button to dynamically add stl files.

### ISSUE THREAD

**Issue by BruceLvSwag** [UPBGE/upbge#1902]
As a new player of UPBGE, I tried to use python script to load STL files. During this process, by running the script through the script running interface of UPBGE, the STL file can be successfully added and the STL model can be imported, as shown in the figure below.
![image](https://github.com/UPBGE/upbge/assets/156870102/7e244014-17f0-4363-89e4-2831f063bf40)

However, using the same script file and dynamically importing the STL file through buttons in the node logic will also load the model, but the model object will not be created in OutLiner, as shown in the figure below.
![image](https://github.com/UPBGE/upbge/assets/156870102/99de24c4-fcd2-4adf-9bc9-f306c417da8a)

Please tell me how should I solve the above problems?

**Comment by BluePrintRandom** [comment]
you mean during runtime or after the engine quits?

you can uncheck 'undo at exit' and have your changes persist.
