### ISSUE TITLE
Eevee 2.0 integration

### ISSUE THREAD

**Issue by Dj-Polyester** [UPBGE/upbge#1903]
Hi. I am not fully knowledeable, just an end user but I am just curious if there are plans for integration. Eevee is closing the gap with cycles and is much faster (Idk about the realtime performance though). It started to use ray tracing. Ig it is a hybrid approach like unreal's engine.

**Comment by BluePrintRandom** [comment]
This already is working in 4.2 builds I believe and beyond, and is working in experimental mode in older builds.
