### ISSUE TITLE
Asset browser UPBGE 0.43

### ISSUE THREAD

**Issue by christian66-gif** [UPBGE/upbge#1906]
Hello... when I try to open the asset browser it is the files browser that opens

I am on Ubuntu 24.4 LTS and I test the latest version of UPBGE 0.43 ... the paths for my assets are clearly indicated in the `file paths`
with blender 4.3.0 it works correctly 
[asset.webm](https://github.com/user-attachments/assets/999b15ba-1e81-4f9b-a6e3-b2da7cd7506f)

in edit it tells me that assets is open 
![asset](https://github.com/user-attachments/assets/9f11f60d-30a7-45eb-adac-00876c71a1f7)

**Comment by LP-ita** [comment]
Yes I confirm that in version 0.43 the asset browser does not work. Windows 11. Hopefully some developers...
For the logic nodes, I suggest you download the latest version and reinstall it from blender preferences/install from disk.

**Comment by christian66-gif** [comment]
Hello ... thank you ... the latest version of the Add-on `Logic Node Editor` ... it is indeed V3.2.1 that I find here ... https://github.com/UPBGE/UPBGE-logicnodes

**Comment by youle31** [comment]
The part of code related to assets browser depends on blender code, not upbge specific code. this kindof issues can be reported to Blender developers following their rules to report a bug and after testing last available Blender alpha version
