### ISSUE TITLE
UPGBE 4.3 crashes when trying to replace a mesh

### ISSUE THREAD

**Issue by Erebe-bugue** [UPBGE/upbge#1907]
When trying to replace the mesh in game (here it's just pressiong E that should change toe cube into the sphere at it's side) upbge closes whithout warning. I am using the actuator "edit object", and "replace mesh".  I've tried different stuff to solve the problem (changing the object physics type, parent, collection, etc...) but nothing worked. However this exact file is working perfectly fine on upbge 4.2 and 3.6. I also tried reinstalling upbge, but it still crashes. 

File linked bellow

[replace_mesh.zip](https://github.com/user-attachments/files/16502490/replace_mesh.zip)

**Comment by Erebe-bugue** [comment]
Sorry for my bad english btw, it's not my natal language

**Comment by youle31** [comment]
should be fixed in last master
