### ISSUE TITLE
Render to texture script fails in 4.3

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/upbge#1909]
render to texture script working in 4.2 - fails in 4.3

[03_render_to_texture.zip](https://github.com/user-attachments/files/16826129/03_render_to_texture.zip)
![image](https://github.com/user-attachments/assets/e7a54359-b354-4314-9942-91f1d1571228)

**Comment by MGameBox** [comment]
您的邮件，已经收到，如未能及时阅读还请见谅

**Comment by BluePrintRandom** [comment]
(deleted weird spam message)

**Comment by BluePrintRandom** [comment]
apparently currently video texture module is not working in eevee next*
