### ISSUE TITLE
UPBGE 0.36.1 Crashes upon switching to a particular scene.

### ISSUE THREAD

**Issue by Shadestuff** [UPBGE/upbge#1913]
I have a 0.36.1 .blend file for a game that uses scenes as stages, and I've discovered that swapping to one particular scene I could access before, now immediately crashes UPBGE. I've intermittently been on and off of work on the file, and haven't made changes to or opened the problematic scene in quite a while. Problem is repeatable. 

Debug_Output for the crash included. (I'm not terribly literate in this backend stuff, just hoping it's some niche little incompatibility instead of something wonky in the inaccessible scene.)

[blender_debug_output.txt](https://github.com/user-attachments/files/17179951/blender_debug_output.txt)

**Comment by youle31** [comment]
We can't do anything from provided infos. We need a test file, and steps to reproduce the issue
