### ISSUE TITLE
UPBGE crashing because of the "Text" property on text objects when using UTF-8 multi-byte characters

### ISSUE THREAD

**Issue by xistoness** [UPBGE/upbge#1915]
Request: fix the "Text" string property to support special characters encoded in UTF-8
Issue: After a lot of testing and debugging, I found out that the "Text" string property which is used to change a text object's text during runtime has an issue with special characters. If you try to change this property via python using a string with special characters, you will notice that the text is displayed improperly, and that the last 3 or 4 characters are usually substituted by random data that the property is trying to access in your computer. Probably the way this property is managing the memory allocation for the string is incorrect, as it is allocating a single byte for each character, which is inconsistent with  characters like "ç" or "ã", that are multi-byte characters, encoded in UTF-8, differently from ASCII characters that are single-byte characters.
Possible Solution: the property should be fixed to allocate memory properly according to the character that is being passed to it, allocating more than a single byte if the character needs it.
Relevance: this fix should be relevant for the Engine if it aims to be used internationally, since many languages around the world use special characters to represent their words, and ASCII characters without diacritics characters is mostly appropriated for English only. Fixing this would be important for anyone trying to display text that is not in English using text objects. The fact that this also causes crashes in the Engine and that it can potentially harm the user's computer by trying to access memory that it shouldn't be accessing is also considerable and relevant.

**Comment by youle31** [comment]
it should be fixed in last master, thanks for report
