### ISSUE TITLE
Component: ArmatureChannel.joint_rotation crashing Engine as Get. Setting it is only working in Start()

### ISSUE THREAD

**Issue by DecisiveAudience** [UPBGE/upbge#1918]
Hello! 

Please forgive me for any Mistakes or Inconveniences, this is my first Bug Report.

I am currently working with Upbge 0.36.1 trying to get a small Simulation going, using the Component feature.
As far as I can tell, ive set up the foundation for moving Armature Channels by Rotation using Armature.Channels[0].joint_rotation = ...

My Issue is: 
The Former Attribute, seems to always crash the Engine when used to get its Value.
print(bone1.joint_rotation) is enough, no matter when its used.

Setting joint_rotation does not Crash, but only gets applied if used in start(), in my case atleast, even though i use Armature.update() at the end of Update()

Honestly I dont know if this applies to anyone but me.
I suppose, atleast making this issue heard might be a good idea.

Thanks for making my Project even possible.

**Comment by youle31** [comment]
Hi, BL_Armature* are deprecated. I think you can use bpy API.

**Comment by DecisiveAudience** [comment]
Thanks, i will look into it!
