### ISSUE TITLE
LibNew Materials?

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/upbge#395]
is it possible to libNew a copy of a material unique to a mesh?

what about replace a texture on just one instance of a object / material? 

thanks.

**Comment by sdfgeoff** [comment]
Yes please. I currently have to do a (somewhat limited) [workaround](https://blenderartists.org/forum/showthread.php?330806-Unique-Libload) that is causing several seconds of loading time.

**Comment by lordloki** [comment]
This method will not available for upbge 0.3. I will think if we can replaced.
Closing for now but I add a label to find it later
Thanks for reporting
