### ISSUE TITLE
Suggestion to Refactor SSS

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/upbge#472]
Current SSS implementation disobeys one important physics law - energy conservation. This means that it reflects/refracts/diffracts as much(or less if it is partially converted to heat) light as it receives. When enabling SSS in UPBGE, however, the light amount doubles(the diffuse scattering, which is basically approximation of light going only slightly into object surface before reflecting, remains, but the SSS(which is the same as diffuse, just goes deeper) gets added up). Increasing scale(which is supposed to spread the SSS at wider angles) increases the brightness even more. To obtain realistic results, the diffuse light and SSS must be combined at certain ratio. So it must be like so: `light = diffuse * ratio + sss * (1.0 - ratio)`. For the scale - it must be refactored to make the SSS light get spread around instead of adding the SSS color at wider angles. Suggestably, the scale should affect the direct SSS pass(somehow make it spread wider and loose it's brightness). Also the color must be applied directly.

Lastly, the current SSS doesn't see shadows. However, it should be possible to detect whether the pixel is shadowed or not.

I hope that those suggestions help you to improve the SSS feature of UPBGE.

Sincerelly,
Adrian the Penguin! :penguin:

**Comment by lordloki** [comment]
Now the SSS is controlled through eevee directly in UPBGE 0.3.
We will relief in Blender to update it when necessary.

Thanks for reporting. Closing now
