### ISSUE TITLE
Bge.scene.findPath(kdtreeOfNodes, goal_position, Agent_position) 

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/upbge#481]
Currently The pathfinding solution relies on a static navigation mesh, that cannot be extended in runtime. I would like to place path finding waypoints by hand and build a kdtree of all nodes currently loaded, and then get the nodes in radius of a actor and pass this data to them to use to navigate. 

Agent['localTree'] = kdtreeOfnodesCloseToAgent

(so no single agent is ever trying to navigate across the whole world) 

This will allow open world navigation I believe, however the A* itself would most likely benefit from being a compiled fast native command.

**Comment by DCubix** [comment]
Can you not manually place empties in the scene and treat them as nodes?

**Comment by BluePrintRandom** [comment]
Yes, but I am loading and unloading these nodes in game, per tile.

I could use a list, but for each actor, to run iteration on each node in py
is not fast.
The kdtree can get the closest nodes in a radius, and also returns a
distance from actor vector per point to each actor.

**Comment by BluePrintRandom** [comment]
Use big kdtree, to get local nodes to agent, navigate using local nodes to
agent target goal.

On May 2, 2017 2:34 PM, "Jacob Merrill" <blueprintrandom1@gmail.com> wrote:

Yes, but I am loading and unloading these nodes in game, per tile.

I could use a list, but for each actor, to run iteration on each node in py
is not fast.
The kdtree can get the closest nodes in a radius, and also returns a
distance from actor vector per point to each actor.

**Comment by lordloki** [comment]
Closing as new tracker rules but open and feature for later tags added.
