### ISSUE TITLE
Code prefix convention.

### ISSUE THREAD

**Issue by panzergame** [UPBGE/upbge#502]
I propose to clarify the prefixes used for the classes and files names.

BL : clases duplicating or writing to blender data.
KX : Ketsji classes defining a python api for top level objects.
SCA : logic bricks classes
RAS: rasterizer classes (no necessary with OpenGL calls)
PHY: physics classes.

So following this KX_BlenderMaterial should be renamed BL_Material (no redundant BL = Blender), BL_Shader to KX_Shader and BL_BlenderShader to BL_Shader.
For the two last i prefer: BL_MaterialShader and KX_MaterialShader to avoid confusions.

@youle31, @lordloki, @DCubix : It's a very short proposal, what do you think or want to modify ?

**Comment by youle31** [comment]
I don't really know for the distinction BL/KX according according to "use blender data or not" and "use proxy or not" because we have several files that use both blenderdata and proxy like KX_WorldInfo...

I'd keep BL prefix for files which are in converter folder and KX for all files in Ketsji.

**Comment by solhrdulik69** [comment]
only +

**Comment by panzergame** [comment]
Indeed KX_WorldInfo should be BL_WorldInfo (following what i said).

About the name modification the compatibility is not  very important as the user mostly never subclass these classes in python (only KX_GameObject is heavily subclassed).

For the moment i'm not certain.

**Comment by DCubix** [comment]
I propose a change from RAS to REN (Rendering), or GFX (short for Graphics)...
Because:
> Rasterisation (or rasterization) is the task of taking an image described in a vector graphics format (shapes) and converting it into a raster image (pixels or dots) for output on a video display or printer, or for storage in a bitmap file format.
According to Wikipedia.

So we are not taking triangles and drawing each pixel...

**Comment by panzergame** [comment]
I have a higher priority request, currently classes defined in Expressions/ are using only C prefix or nothing, i would like to unify to EXP_ prefix.

@youle31, @DCubix, @lordloki : What do you think about it ?

**Comment by youle31** [comment]
Panzergame: if you think it is better i have nothing against

**Comment by lordloki** [comment]
@panzergame : go for it. It was not changed at beginning but I think is the right convention

**Comment by panzergame** [comment]
I would include in this proposal the usage of namespace named the same as the prefix, so that all code in ketsji will not use a KX prefix for other ketsji classes and usage of other part will be explicit by the usage of a prefix.

**Comment by lordloki** [comment]
Closing
