### ISSUE TITLE
Frame drop from a file.

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/upbge#505]
The file from the forum thread gives a regression;
link: https://blenderartists.org/forum/showthread.php?428160-Grass-swaying-experiment
Image: http://pasteall.org/pic/index.php?id=116257
I followed from where does the frame drop starts. As you see from the image, it starts from 002-003

**Comment by panzergame** [comment]
@Akira1San : This is still the case with recent master ?

**Comment by Akira1San** [comment]
Yes i get 26fps. The issue starts from 002-003 as in the image. I dont know if thats the old scenegraph fix.

**Comment by panzergame** [comment]
@Akira1San : Do you make sure that only VBO is used in 0.0.1/3 ? Display list was removed in 0.1.1.

**Comment by Akira1San** [comment]
Yes just tested again. Only vbo is used + glsl. the result is the same. In 003 the fps drop from 43 to 27. As the image on top shows, the scenegraphs give more ms: 001 - 0.58ms, 003 - 2.99ms

**Comment by lordloki** [comment]
Now the render in 0.3 is using eevee and all the system changed. Thanks for reporting
