### ISSUE TITLE
[Request] Debugging Physics: Draw acting fores/torque  

### ISSUE THREAD

**Issue by AeroLynx** [UPBGE/upbge#510]
Hello UPBGE Team,

since I am working a lot with Bullet and Physics lately, I'd like to suggest some Ideas which would make iterations and debugging easier - for me and hopefully for others.

Sometimes I find it hard to know which forces are acting on (a bunch of connected) rigid bodies. I suggest to draw the acting forces on the objects pivot in xRay Linestyle and text of the numbers with physical units, so that these can be seen through meshes.

I could think of some UI elements for this:
In the objects physics panel:
- Force debug: Draw Lines [checkbox], Draw Text [checkbox] 
- Torque debug: Draw Lines [checkbox], Draw Text [checkbox]

In the Game -> show Debug section:
- A seperate checkbox for global ON/OFF

Thank you for your time and efforts!

**Comment by adriansnetlis** [comment]
Yep, this is something that a lot of us would actually love to see in UPBGE source, otherwise people are often doing drawLine way which adds pointless development time for creating debug tools.
So I am totally agreeing with AeroLynx :+1:

**Comment by lordloki** [comment]
Closing as new tracker rules but open and feature for later tags added.
