### ISSUE TITLE
[Request] Rigid body joints

### ISSUE THREAD

**Issue by AeroLynx** [UPBGE/upbge#511]
Similar to my request of drawing lines and text for debugging forces and torque, I'd like to suggest a number of things related to rigid body joints:

- Drawing the the pivot points or hinges of rigid body constraints when Physics Visualization is active. I don't think it is necessary to add checkboxes for these per joint, one global switch would be enough.

- More of the parameters for Rigid Body joints exposed in the UI (Object -> Add Object Constraints -> Rigid Body Joint). E.g. the breaking Impulse threshold from the Python API
- One "Remove rigid body joint"(s) actuator in the logic Bricks, to make objects easily fall apart without Python.  

Kind regards, keep up the good work! Hopefully your efforts will be in BFs BGE one day.

**Comment by sdfgeoff** [comment]
> Drawing the the pivot points or hinges of rigid body constraints when Physics Visualization is active. I don't think it is necessary to add checkboxes for these per joint, one global switch would be enough.

If I remember correctly, the pivot point appears a black wireframe sphere and there are two small axis indicating each side's current transformation.

**Comment by AeroLynx** [comment]
You are right - I must have missed this somehow in my model. The pivot point axis are definitely drawn as three lines for x,y and z axis. Visible in the BFs Demo File for rigid body joints:
[https://wiki.blender.org/index.php/Media:BGE-Physics-RigidBodyJoints.blend](url) 
So please - ignore this one :]

**Comment by panzergame** [comment]
Could you test the branch ge_breaking_threshold ? The documentation is in the python documentation descriptor in the commit.

**Comment by AeroLynx** [comment]
Since there is no ge_breaking_threshold in the "branch" dropdown - Did you mean the ge_constraint_breaking branch? In case you do - it looks like I would have to build from source. Which I do not do usually - and that means I'd have to set up the Blender build environment just for that. Are there any prebuilt binaries I missed?

**Comment by Akira1San** [comment]
If you are on windows, i can build?

**Comment by AeroLynx** [comment]
Yes I am on windows 10, 64 bit. Today I started to set up the Build environment by following the official instructions here: https://wiki.blender.org/index.php/Dev:Doc/Building_Blender/Windows , since the link in the UPBGE Wiki seems to be dead. Now I have Git, SlikSVN, TortoiseSVN, CMake and Visual Studio Community 2013 running and in the PATH. However, it seems getting all the external libs from SVN will take a serious amount of time. 

If it's no problem for you, I would be glad to take your offer. Nevertheless, I will continue to set up the build toolchain myself for learning purposes.

**Comment by Akira1San** [comment]
Win64 vs2015 build: https://drive.google.com/open?id=0B6yNvVGWiWyseE03bmUya0I3RXc

**Comment by AeroLynx** [comment]
Thank you panzergame for considering my proposal and Akira1San for providing the build. Since the second and third bullet point of my proposal was connected to options exposed in the user interface (Constraints->Rigid Body Joints) and an "Remove Rigid Body joints" actuator, i was expecting changes in these panels in Blenders interface. They did not change, so I took a look at the both commits and tried to guess what you want me to test. 

The changes on 31st of July (commented with "add doc" & "temp") seem to be related to the rigid body constraints, but in some Python Wrapper code (!?). Please note - I am quite used to the BGE with some knowledge in C/C++, but no expert in Blenders code. Therefore (@panzergame): Could you please specify a little bit more precise what you actually want me to test?

**Comment by Akira1San** [comment]
hi
This is the joint breakage. The way i see it. :)
In the doc you have 2 variable:
"breakingThreshold" - type float and "enabled" - type bool. You have to use python to test it.

**Comment by AeroLynx** [comment]
Okay, I set up a little example using both of the values based on a stackexchange answer by sdfgeoff. A constraint is created between two Cubes and can be disabled by pressing SPACE or when a third cube hits one of them and the threshold is exceeded.
Is it something like this you were aiming for? However, I still would prefer the same solution without using python. 

[UPBGE_constraint_fail_n_break.zip](https://github.com/UPBGE/blender/files/1195351/UPBGE_constraint_fail_n_break.zip)

**Comment by AeroLynx** [comment]
I just stumbled upon the 0.1.9 release notes and read in the doc, that you added the breaking threshold to the UI now. Thank you very much!!! 

I was curious to try it, but the 0.1.9. builds don't seem to be on your main website yet. Since my build environment is working now, I made a recent build and took a look. Here my observations:

Adding a constraint which breaks from the UI is a matter of seconds now. But I struggled while trying to manually disable a UI-created constraint between two objects by pressing space. I got stuck when trying to access it in Python. Is it even possible to disable a constraint which was created in the UI? If yes - Do you have a minimal example?

Related:
https://doc.upbge.org/releases.php?id=0.1.9
https://pythonapi.upbge.org/bge.constraints.html
https://pythonapi.upbge.org/bge.types.KX_ConstraintWrapper.html?highlight=kx_constraintwrapper

**Comment by lordloki** [comment]
Closing as new tracker rules but open and feature for later tags added.
