### ISSUE TITLE
Downsampling filter image, processing at lower resolution, then upscaling

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/upbge#517]
Is it currently possible to do the following in UPBGE?

- Render scene to offscreen
- Downscale this offscreen before processing in shader (mipmap generation)
- Process the downscaled offscreen image in shader(in it's pixel scale, as if the screen size was scaled down, instead of screenspace)
- Use the obtained image in 2D filter(and have OpenGL, just as with any other textures, sample it up automatically).

Why would I/we need this?
- Allows to make very fast, but decent looking wide radius blur
- Allows to sample blurry and undetailed filter elements at lower resolution(thus reducing need for processing)

So far, when I tried to do something like this, I had low framerates and (when blurring) "ghost layering" because I had to sample those mipmap sized textures in my screen resolution. This is extremely slow (my frames were dropping below 60 on simple scene) and has case specific artifacts.

**Comment by youle31** [comment]
Why not capture offscreen to the size you need directly? Use ImageRender offscreens.
source = bge.texture.ImageRender(scene, camera, width, height, samples, hdr)
source.render()
bindcode = source.colorBindCode iirc
then use it in your shader

**Comment by adriansnetlis** [comment]
1) What are the "samples"?
2) Will this behave properly in shaders(as described by me before)?
3) THANKS already! :)

**Comment by adriansnetlis** [comment]
When I thought about your suggestion, I noticed that it invokes a problem anyways, so it's not the best way. You render scene multiple times at multiple resolutions, which costs computation time. It's unnecesarry when you can use mipmaps of bgl_RenderedTexture which look exactly the same. The problem of mine is that I have no idea if(and how) it is possible to process them in their pixel space.
Let's take this rendered frame as an example(p.s. sorry for the window border on the top, too lazy to remove :stuck_out_tongue_closed_eyes: ).
![frame](https://user-images.githubusercontent.com/6423934/27510208-7bde089c-5914-11e7-9baf-e2836cc8ef9a.png)
Now a lower resolution image(or mipmap equaliently) **in the screen(also 2D filter) space** looks like this (in this example it's the 2nd mipmap(or an image at 1/4 resolution of the original):
![frame4](https://user-images.githubusercontent.com/6423934/27510229-0f083714-5915-11e7-8b73-52e63a8f8cfd.png)
It's a bit of blur, but it's ugly, especially at later mipmaps, so manual blur is required. However, when applying a 5x5 kernel blur on this specific example, we get a bit of an issue:
![framekernel](https://user-images.githubusercontent.com/6423934/27510286-15d8a064-5916-11e7-964e-ebd4ef89dba8.png)
It's because of the method used(sampling image at different coordinates). Probably what I am looking for is image processing outside of a filter. I need it to not apply linear filtering to the image when doing kernel blur and also output a lower-resolution off screen image.

**Comment by lordloki** [comment]
Closing as new tracker rules but open and feature for later tags added.
