### ISSUE TITLE
Feature request: asynchronous loading of mesh objects

### ISSUE THREAD

**Issue by aksyom** [UPBGE/upbge#533]
In an Open World type of a game one would want a mechanism to load big chunks of geometry data asynchronously on background thread. This would enable one to remove unused terrain LOD layers from RAM, as there is a guarantee one can load them from file once again when they are needed. What I mean by LOD layers here are weight-decimated low-poly versions of a full-detail geometry, each version decimated from a specific focal point on the XY-axis. This is a very basic technique, but it is actually VERY efficient because it doesn't waste CPU or GPU time on dynamic LOD generation. Extremely good for machines with slow CPU and GPU.

Currently both BGE and UPBGE only support asynchronous loading (in a background thread) for Scenes. If a scenes are async loaded from a blend, all their objects are merged into the current scene, but they do not work as they should; they only use the lighting from the original scenes they were loaded from. This is a weird quirk that needs work-arounds that probably won't work very well.

The only way to instantiate objects is scene.addObject() method, put it can only instantiate objects from an inactive layer within the current scene. If you put a very large terrain geometry (in chunks or LOD layers) in an inactive scene, the engine has to load ALL of that geometry into RAM so that it can be later instantiated. And in my case, having around 64 LOD layers of terrain with 1M faces each in an inactive layer makes UPBGE load the scene very slow and uses up so much RAM it is ridiculous.

Yes, of course you can do a huge amount of work to split a LOD layer into itty bitty pieces on the XY-axis and then bge.logic.LibLoad() them over multiple update() cycles, but this technique is not only complex, but also probably has higher overhead than a decent background loader for geometry, even on a single core system. And on a multi-core system the backgroad loading of meshes is going to be faster anyway (and more concise, correct and simpler).

And the most important thing is that a large geometry split into 10K or 100K parts will eventually incur a massive viewport culling overhead, which makes the game grind down to a halt. I have not tested how many objects UPBGE can handle within one scene, but common sense would say not going over a few thousand!

I made a prototype of the layered terrain LOD technique with Panda3D. It was very simple, and I could render HUGE sized terrains with absolutely low specced hardware (one laptop with i3 CPU and Intel HD3000) so that the terrain still looked damn good. And the whole thing used at maximum the RAM that was required to hold in memory 9 layers of LOD at once, which was tolerable (around 130 Megabytes with a each LOD layer having 1M faces or so).

Thus I am only requesting a few things:
1. Make bge.logic.LibLoad() able to asynchronously load meshes from blends, just like it can do with entire object hierarchies with Scenes. This one improvement would open up great new possibilities for different kinds of games, not only Open World.
2. Make the objects in async loaded scene use the lighting in the current active scene (instead of using the lighting in the scene they were loaded from)

If either of my suggestions are implemented, UPBGE would be a lot better for large scale projects.

Thanks ...

EDIT: fixed some misunderstandings, LibLoad()ing a scene does load objects in inactive layers, their references are not in scene.objects but instead inactive objects are in scene.objectsInactive

**Comment by lostscience** [comment]
I would like this feature to.This would be great in digging similar to minecraft.It would be great for it work over many scenes.I am have low end hewlet packard.

**Comment by aksyom** [comment]
Actually nevermind! I just found something interesting in regards to asynchronous loading which was NOT specified in the documentation

When I do bge.logic.LibLoad("%s/untitled_next.blend" % bge.logic.expandPath('//'), "Scene", load_actions=False, verbose=False, load_scripts=True, async=True)

then UPBGE actually loads ALL of the objects in the blend file on the background, and then merges the objects onto the current active scene!

So the current asynchronous loading can be used to pull an entire scene's objects into current scene on the background.

I misunderstood the documentation and the spefication thereof. I will now close this comment.

**Comment by aksyom** [comment]
For those who are wondering about this trick do like this:
1) Create a blend file with the specfic object or objects you want to pull
2) In your acttive blend file with scene where you want to merge the objects from the other blend file, do like this:
bge.logic.LibLoad("%s/untitled_next.blend" % bge.logic.expandPath('//'), "Scene", async=True)
3) Wait, and the objects should pop into the scene in their original places in due time

To use this system in an Open World game it means you will probably have to create multiple blends with each of them storing only a specific part of the world. But that's what I was doing anyways.

**Comment by aksyom** [comment]
Actually, the problem with LibLoading a scene is that the scene is loaded as "overlay". That means that the stuff in the scene gets overlayed over the current scene, but you cannot touch that stuff.

I thought I solved the issue of loading a scene asynchronously and then using the objects within it in the current scene, and closed the ticket for a short time. But then I realized it only loaded the scene as overlay which is no good so I reopened the ticket.

So yes, we just need a mechanism to merge stuff from other blend files into the active scene on the background. And the proposal to allow async loading of meshes from blends is still the best option.

**Comment by lostscience** [comment]
the sooner the better we get this into the upbge.

**Comment by BluePrintRandom** [comment]
If the bpplayer bidirectional streaming patch is comleted, this should be
faster.
(load preconverted game data)

**Comment by aksyom** [comment]
Okay, but how does that solve the issue of loading a HUGE blob of data at once while the logic cycle waits for the loading to complete (freezing the frame updates)?

At the minimum the data blobs I will be loading are between 10~16 MB. Even if this data is pre-converted on the disk, it still does not remove from the fact that a synchronous loading code needs to load at minimum 10 MB (and with BGE probably even more) data from disk within 1 frame. If you have a very fast SSD you might just do this under 16 ms (which is frame interval on 60 FPS), but on most standard magnetic hard disks (esp. on laptop hard disks) that's just not gonna happen with the seek delay and all that.

On the other hand, if you have a working asynchronous loading for objects, the logic code does NOT need to wait for a loading operation to complete. The loading will be handled on the background, and there will no impact on frame rate whatsoever.

Honestly, I don't care even if the data is stored in a format which is slow to convert into runtime. That does not even matter, because if you have a working asynchronous backround loading for objects, you can split the scene into reasonably sized pieces and then background load them in a calculated priority order. I have proven this to work!

My only logical conclusion is that only a truly asynchronous background loading of data actually supports really massive Open World data sets. I can't really stress this enough.

**Comment by BluePrintRandom** [comment]
https://www.youtube.com/watch?v=tZOW8msMWk0 :D

**Comment by aksyom** [comment]
Unless this loading of geometry is done in a separate thread on a separate core then it has nothing to do with what I am asking for.

**Comment by sdfgeoff** [comment]
The only thing that libload async does synchronously is merging the scenes. This is something that cannot be avoided or multithreaded. So far as I know, everything else (loading, decompressing) is done in another thread. But I'm no expert in the behind the scenes for LibLoad.

---------------------------------------------------------
**Request 2**

> they only use the lighting from the original scenes they were loaded from

If you libload some lights and then load some models, the models are lit by the lights that came before. However, they are not (except for the scenes original objects) lit by lights that came after. Hence: load a bunch of lights and then position them around. Yes, this is likely a bug. If you've got a loading screen and don't mind adding extra time at startup (doesn't apply here), you can recompile the shaders by toggling one of the GLSL options to ensure all the objects show all the lights. Eg:
```
        bge.render.setGLSLMaterialSetting("nodes", 0)
        bge.render.setGLSLMaterialSetting("nodes", 1)
```

> Also, since the objects in inactive layers are not loaded at all, one cannot use scene.addObject() to dynamically add/remove objects.
Uhm, I do this all the time. Objects on inactive layers are definitely loaded in my blend files!

--------------------------------------
For things like terrain, investigate other options than loading in world chunks. Consider separating your level format from the .blend format, and instead representing it as a bunch of textures (eg heighmaps/vectormaps) and transformation matrices for entities. Then you can load all the entities at game start, generate terrain geometry on the fly (eg inside vertex shader for graphical. Probably one big physics mesh re-instanced at game start) and so on - no need to stream things in and out.
Yes, it doesn't work if things are massive enough, or if you want utter and complete control over every vertex of every object in every part of the world.
---------------------------------------

**Comment by aksyom** [comment]
> If you libload some lights and then load some models, the models are lit by the lights that came before. However, they are not (except for the scenes original objects) lit by lights that came after. Hence: load a bunch of lights and then position them around. Yes, this is likely a bug.

So this is a bug. Can this be fixed?

> Uhm, I do this all the time. Objects on inactive layers are definitely loaded in my blend files!

Yeah I realized that the inactive objects also get loaded with async scene loading. I fixed my original writings hopefully to signify this understanding.

> For things like terrain, investigate other options than loading in world chunks. Consider separating your level format from the .blend format, and instead representing it as a bunch of textures (eg heighmaps/vectormaps) and transformation matrices for entities. Then you can load all the entities at game start, generate terrain geometry on the fly (eg inside vertex shader for graphical. Probably one big physics mesh re-instanced at game start) and so on - no need to stream things in and out.
Yes, it doesn't work if things are massive enough, or if you want utter and complete control over every vertex of every object in every part of the world.

The GLSL facing interface in UPBGE lacks reference documentation upon which to build. In order for me to generate a shader I would need a shader API which provides engine specific helper functions for adding/mixing lighting, shadow mapping, environmental cube mapping and whatnot. This is because if I would make a terrain shader now, lacking API specs, I could probably only implement a Phong-shaded surface with no shadows or anything else. Thus I am simply doing what I can, and that involves regionally pre-decimated terrain meshes.

As for storing transformation matrices in separate file, I think you can just fill your world with Empty -objects and parent spawned objects on them.  And if too many empties cause overhead, I can just partition the world into regions and merge each region's empties from a different blend file when needed. The advantage with this is that I can temporarily link the empties from an external blend if I need to see them in viewport in order to get a bigger picture. You can't do that with matrices stored in a text file, well, unless you write a plugin to blender which reads these text files and places empties on the scene based on whatever ... but that's outside the scope of my project for now. I am not going to create a level editor for now, Blender shall do and thus I'll use whatever is already available.

**Comment by aksyom** [comment]
Okay, I have now tested LibLoad() on Scenes, and in my experience it does not work at all. I will provide you with a set of 3 blend files, where the libload_test.blend is the main file:
https://drive.google.com/open?id=0B3u1MJ_t35aQelJJWUFYUmROb0U

When I run the libload_test.blend, it has an empty scene and a component script on an Empty which is supposed to do 2 things:
1) load scenes from a set of blends synchronously, and after that
2) load scenes from another set of blends asynchronously

In this case the libload_test.blend has been set (via component arguments) to first load libload_test_lights.blend sync, and after that load libload_test_sphere.blend async.

If @sdfgeoff explained correctly, then all the objects from libload_test_sphere.blend should be lighted by the lights loaded previously from libload_test_lights.blend. But this is not the case.

When libload_test.blend runs, it loads the lights scene and then the sphere scene. However, the light only affects the plane -object that is part of the lights scene. The light does not affect the sphere from the sphere scene, which is clearly loaded after the lights scene.

So, I would humbly plead somebody to fix this bug, and make lights affect the objects LibLoaded() from an external file's scenes. It would greatly and immersely lighten my workload, considering the scale of my research project.

**Comment by lordloki** [comment]
Closing as new tracker rules but open and feature for later tags added.
