### ISSUE TITLE
Broken/incomplete navmesh generation

### ISSUE THREAD

**Issue by organicpencil** [UPBGE/upbge#542]
This has been a problem for as long as I can remember. Group instances are not taken into consideration when generating a navmesh. And even with normal objects it will give a totally wrong result when more than 1 are selected. It's much easier to model a navmesh by hand rather than re-joining all objects whenever there's a change. The only time nav generation works is when your level and all obstacles are contained within a single mesh.

**Comment by lordloki** [comment]
Closing as new tracker rules but open and feature for later tags added.
