### ISSUE TITLE
Bug with trilinerar filter/mipmap

### ISSUE THREAD

**Issue by UJIbU4** [UPBGE/upbge#553]
Hi,

App crashes when turning on filter/mipmap (worked in 0.1.6):
Windows app crash log:

Problem signature:
  Name of event issue:	APPCRASH
  Application name:	testapp.exe
  Application version:	2.7.8.0
  Application time mark:	5986cb35
  Module name with error:	atio6axx.dll
  Module version with error:	22.19.171.1024
  Module with error time mark:	595c11d4
  Exception code:	c0000005
  Exception shift:	0000000002023399
  OS Version:	6.1.7601.2.1.0.768.3
  Language code:	1049
  Additional information 1:	102f
  Additional information 2:	102f53b5b93e094544c6caf81f00646b
  Additional information 3:	9315
  Additional information 4:	9315d10f38681bfad61813fae7f978f6

Hardware specs:
Radeon Software Version - 17.7.1
Radeon Software Edition - Crimson ReLive
Graphics Chipset - AMD Radeon HD 7700 Series
Memory Size - 1024 MB
Memory Type - GDDR5
Core Clock - 1050 MHz
Windows Version - Windows 7 (Service Pack 1) (64 bit)

**Comment by panzergame** [comment]
Please provide a example file.

**Comment by UJIbU4** [comment]
[atibug_suko.zip](https://github.com/UPBGE/blender/files/1205694/atibug_suko.zip)

**Comment by panzergame** [comment]
The file is working fine on nvidia and intel GPU, @UJIbU4 : Could you provide OpenGL info as version and extensions list ?

**Comment by UJIbU4** [comment]
OpenGL® Version
6.14.10.13476
OpenCL™ Version
22.19.171.1024

How to get OpenGL extensions list?

**Comment by panzergame** [comment]
I have issue with HD 6770 on linux with function `textureLod` and `texelFetch` which are implemented in GLSL 1.30, but the GPU and driver are supporting the version 1.30 but the driver doesn't support the extension GL_EXT_gpu_shader4 contrary to what exposes the vendor.

**Comment by Akira1San** [comment]
I still would like to ask, what if you bump the version to 150 - OGL 3.2. Would that solve the error?

**Comment by panzergame** [comment]
I fixed my issue with texelFetch.

**Comment by Akira1San** [comment]
Crash too in master build.

**Comment by Akira1San** [comment]
image from debug:
http://pasteall.org/pic/show.php?id=118629

**Comment by panzergame** [comment]
@Akira1San: Could you try to replace:
```
	/* TODO: simplify when we transition to GL >= 3 */
	if (GLEW_VERSION_3_0 || GLEW_ARB_framebuffer_object)
		glGenerateMipmap(target);
	else if (GLEW_EXT_framebuffer_object)
		glGenerateMipmapEXT(target);
```
by
```
	glGenerateMipmapEXT(target);
```

and test please ?

**Comment by Akira1San** [comment]
Nope, got an exit blender.

**Comment by youle31** [comment]
I was wondering if this:
`/* TODO: simplify when we transition to GL >= 3 */
	if (GLEW_VERSION_3_0 || GLEW_ARB_framebuffer_object) {
		if (is_ati && !GLEW_VERSION_3_1) {
			glTexParameteri(GL_TEXTURE_2D, GL_GENERATE_MIPMAP, GL_TRUE);
		}
		else {
			glGenerateMipmap(target);
		}
	}
	else if (GLEW_EXT_framebuffer_object)
		glGenerateMipmapEXT(target);

	if (is_ati && !target_enabled)
		glDisable(target);`
would solve the bug... If you have some time to test Akira_san, thanks

**Comment by Akira1San** [comment]
Still crash

**Comment by lordloki** [comment]
I think last commit fix some problems that we have with ATI/AMD cards. Could you test with this build https://mega.nz/file/thsiHIKC#VgLYdg2yaJWSr1JAi70asKAOzrrE8AeU6q8yDtuDw0A ?

**Comment by UJIbU4** [comment]
Tested, worked.

**Comment by youle31** [comment]
Thanks. I close this reoprt then.

**Comment by BluePrintRandom** [comment]
👍
