### ISSUE TITLE
[Request] - Text HitBox mode-

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/upbge#566]
Currently the text hitbox origin is not center justified so the hitbox of a text object, when using 'box mode' is not centered on the text,

I purpose that the collider origin be placed offset from the text origin or by default the text is center justified.

**Comment by panzergame** [comment]
by `hitbox`you mean the AABB/OBB of the text object ?

**Comment by BluePrintRandom** [comment]
yes, the origin of the hitbox is offset from the text, by half height of the text, and half the width currently.

**Comment by lordloki** [comment]
This works in 0.3. 
![image](https://user-images.githubusercontent.com/1015605/145673895-0ea50cf9-1385-499c-a7af-08f28bca0979.png)

Closing the issue. Thanks for reporting.
