### ISSUE TITLE
References for the Game Engine paradigm.

### ISSUE THREAD

**Issue by chicortiz** [UPBGE/upbge#572]
Hello Dear UPBGE team.

I'm writing at first to congratulate your work. 
As a Game Engine user for about ten years now I'm really happy to see some developers take the initiative and step inside this project and give the attention and care that this engine deserves, it's really refreshing.

Along the years I saw many developers trying to improve the engine with good intentions but with a lack of a more deep understanding about some concepts that make the Blender Game Engine pretty unique.
I would like to warn you to take my advice with a grain of salt because I have some deficiencies in algebra since the infancy that today reflect as a strong difficulty to learn how to code well.

First and foremost I would recommend taking a step back with people that would like to make the game engine more "Unity" "Unreal" "Godot" "Whatever engine that is trending right now". I believe, by experience and by hitting my head against the asphalt (http://primotico.blogspot.com.br/search?updated-max=2001-04-01T14:54:00-07:00&max-results=5&start=30&by-date=false), that this kind of approach can be very unproductive for the long run.

I would recommend you (if you already didn't) to read this post with some care when you have some time:

https://blenderartists.org/forum/showthread.php?379536-quot-Invite-the-GE-team-to-rethink-game-logic-editing-to-use-viewport-and-new-physics-quot

In this post you will find some very clever community members there, and a hot discussion (in my opinion).

Monster, BluePrintRamdom, Smoking Mirror, Raiderium.

Others that, in my opinion, are able to understand the game engine pretty well and are not in this post: Campbell Barton (ideasman), Dalai Felinto, Blengine, Social, blendenzo, cthames, Doc Holiday, HG1, iconjunky, Oto, JD-multi, jesterKing, jplur, LetterRip, Makin Bacon, martinsh, mataii, NOR.J, numaQ, Saluk, snailrose, SolarLune, spacestrudel, Sutabi, VenomSeven, Oto and z3r0d.

Saluk is a big hero. He made a petition (that was in the 2.3 series of Blender) and gave it personally to Ton a long time ago at the Blender conference 2004 if I remember right. Without that, I believe that this beloved shit would be out of Blender a long time ago.

All the best and kudos for the UPGE team. (The thing with Uchronia is hillarious BTW).

Greetings from someone who melted his brain with that shit,

Ortiz

**Comment by chicortiz** [comment]
Another thing I would like to add:

The integration of the Game Engine with Blender. "Just press P" has its limitations, but is unbeatable for prototyping something fast. Also the ability to work with everything in one environment helps to get things done when team resources are scarce.

**Comment by lordloki** [comment]
Thanks for all recommendations and complinments.
Following the new tracker rules (only left visible the bugs) i close this 'issue'.
Thanks for your time
