### ISSUE TITLE
Decals on UPBGE/BGE

### ISSUE THREAD

**Issue by Hdhunk** [UPBGE/upbge#585]
Here I've found this issue a couple of days ago about making decals work on upbge. So I've came across with a few tutorials on how to do it, and some of them make use of the image mapping section (to change from repeat to clip for example) and the projection setting under the mapping section.
here's the thread on BA with screenshots about it:

https://blenderartists.org/forum/showthread.php?437063-Decals-and-Alpha-textures-in-BGE&p=3233620#post3233620

Also there's was another way of doing it like on this video: https://www.youtube.com/watch?v=d7eOvvMV-7c

But to make the clamp under in the properties panel to update in glsl, it is needed to change the shading mode (like from glsl to multitexture and then return to glsl) and so the image would not tile anymore. But in upbge it's not possible to change the shading mode and also another thing I've noticed with this method is that the image stop being tiled, but if you scale the uv bigger then the image, it gets some sort of distortion.

On the thread on BA the best method until now was the plane decals method. Also I've tried to do it with nodes in the node editor, but can be a little hard to tweak the diffuse color without modifying it.
And also to create multiple uv maps on both upbge and bge it appears that it has some kind of hierarchy like : 1 face >>> All faces or Normal UV Unwrap >>> Smart UV Projection. Because if you unwrap all the faces before the face you want the decal, the decal will apear  not only in the face you want but also on the other faces.

I hope with this I can add to something to help get this issue fixed, and even on the implementation of decals on the game engine (https://github.com/UPBGE/blender/issues/5).

:)

**Comment by justinbarrett** [comment]
firs, sorry If my post is just noise...
but I have also noticed this missing in the mapping panel....is this intentional, and or is there a reason we do not have it?...or...is there just another way to accomplish the clamping for example.

**Comment by lordloki** [comment]
Now in upbge 0.3 is possible to use decals as it is use eevee renderer.
Thanks for you report. Closing
