### ISSUE TITLE
[Feature Request] - Logic bricks layers.

### ISSUE THREAD

**Issue by JhonLoveJoy** [UPBGE/upbge#608]
_I propose the creation of specific layers for organization purposes._

**Comment by youle31** [comment]
hello, there are already layers for logic bricks: http://pasteall.org/pic/show.php?id=119276

I don't know if you are looking for something different.

**Comment by JhonLoveJoy** [comment]
No. That's not it.

I referred to customized layers, created according to the user's need. Example: 


![layers](https://user-images.githubusercontent.com/31490343/31336300-9ecc127a-accc-11e7-94ab-a4c86396f4aa.png)

**Comment by vlad1777d** [comment]
Maybe this won't be needed after Logic Nodes will be implemented.

**Comment by rpaladin** [comment]
We now have the `Bricky Nodes` addon for visualization & organization of logic-bricks.
Additionally as already mentioned, Logic Nodes now have organization groups.
