### ISSUE TITLE
HDR Realtime Reflections not Working in Standalone

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/upbge#643]
When using real time rendered HDR cubemaps (with floating point precision enabled), they work fine when game is run in viewport, but don't work in standalone.

Tested UPBGE Version(s): 0.2.1, 0.2.2
Operating System: Linux Ubuntu 16.04.3 LTS
Graphics Card/Driver: NVIDIA GeForce GTX 960M / 384.90

Here are screenshots for comparsion:
run in viewport:
![hdr](https://user-images.githubusercontent.com/6423934/33402475-585cdec0-d565-11e7-9246-3b006eafdf83.png)
standalone:
![nohdr](https://user-images.githubusercontent.com/6423934/33402507-7034bd56-d565-11e7-8928-ef8e52776361.png)

The difference is more than obvious. As you can see, when running in viewport with 'P' keys, the rendered reflections do render the wide color range provided by HDR environment map, while the standalone player seems to render LDR reflections.

**Comment by panzergame** [comment]
Could you provide an example file please ?

**Comment by adriansnetlis** [comment]
http://pasteall.org/blend/index.php?id=48446

Here is a test file.

By the way - I just tried on Windows (@ school computers) and it seems to actually render HDR reflections in standalone. It's, however, even more weird case - the color seems different, less saturated, as if the color management was different.

**Comment by lordloki** [comment]
Working in 0.3
Thanks for reporting
