### ISSUE TITLE
[Request] Real time mesh changes

### ISSUE THREAD

**Issue by UnidayStudio** [UPBGE/upbge#653]
I don't know if the "issues" tab is the best place to post suggestions/requests, but here we go:
IMHO, the main thing that BGE needs to have to give full control to the developers is the habilit to modify meshes in real time. At me moment, the only way that I found to do this (eficciently) is using OpenGL (with custom vertex and geometry shaders), but this is not the ideal on every case, once that we lost the default game engine shaders.
So my suggetion is to add some kind of functions to add and remove vertex (maybe passing the vertex coord, normals, uv and color) from a mesh and connect/disconnect edges and faces. 

Thanks for the attention. :D

**Comment by panzergame** [comment]
Current project ge_mesh_builder. This branch is to give the ability to create meshes in python.

**Comment by UnidayStudio** [comment]
Oh, great! It will take too much time until release this branch? I can't wait to see them working! :D Anyway, is there a place to post my suggestions about new features? I've a lot of cool ideas (and I'm also a C++ programmer, so I'll not give anything hard to implement. Actually, I want to join the dev team, but I've no idea how to talk to you directly about this :/). The IRC chat don't work here (tested on google chrome, mozilla, everything that i get is a blank page). 
Thank you guys for the awesome work! :D

**Comment by panzergame** [comment]
@UnidayStudio: This branch will certainly be release in the next release. About suggestions you could post here on the issues section if the requests are reasonable, as you already coded in C++ I think they are reasonable and that you could even look at the current code to evaluate the complexity.
For IRC make sure that you go on chat.freenode.net, channel #upbgecoders 
Don't hesitate to ask information about the code structure :).

**Comment by BluePrintRandom** [comment]
any chance that meshProxy.recalcNormals / ge_normals branch could merge?

**Comment by panzergame** [comment]
@BluePrintRandom: Indeed I found the recalsNormal function much more appropriate in a mesh builder, I notice it.

**Comment by BluePrintRandom** [comment]
can we check to see if this works well with the updated version of the source
(2.79c or whatever) and maybe pull it to master?

it was panzer games last pull request I believe.

**Comment by lordloki** [comment]
In UPBGE 0.3 Alpha is possible to perform real-time mesh changes using bpy library. Closing now. Thanks for the feedback.
