### ISSUE TITLE
All Lamp Loop Node

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/upbge#656]
As many of you may know, currently this is how you get lamp data in nodes:
![](http://www.blender.org/wp-content/uploads/2013/12/Manual-Nodes-Lamp-Data.png?x60906)
However, this is very limiting if you want to add custom per-lamp material effects. You often have to copy huge node groups for every lamp, making a big mess in your noodle cup. What I think would be awesome is if you had a "Loop All" checkbox in this node, which would turn the Lamp selection box grey(unactive) and pass the lamp data for each lamp. This would mean that anything that's attached to this lamp data node would run for as many times as there are lamps. Ideally this loop should only be applied to the nodes/groups that use this lamp data as input or a node that uses the lamp data as an input. This would open freedom for making custom shading in nodes that works straight out of box without need to adjust node material for every scene with different lights used.

**Comment by BluePrintRandom** [comment]
we can use 'texture cord object' and drivers to pass data about any light into the shader graph in blender 2.8+ upbge3.0
we can also use custom object attributes per object
object.blenderObject['Attribute_name'] = value
these attributes can be accessed via the attribute node.
(so not every object needs to be given the same light etc)
