### ISSUE TITLE
Wrong position with armature modifier

### ISSUE THREAD

**Issue by vlad0337187** [UPBGE/upbge#677]
Hello.

All is in .blend file: https://vk.com/wall-100864153_54
There are:
- armature
    - body
    - glasses noseframe (parent)
        - ... other glasses parts as children of parent object

I create armature modifier for main glasses part (glasses parent) and other subparts of glasses - they begin displayed normally near eyes.
I start animation - it's playing well.

But when I start game engine - only the main glasses part is followed by armature, it's children - not.
Probably this is a bug.

Best regards,
Vladislav

**Comment by panzergame** [comment]
Confirmed.

**Comment by lordloki** [comment]
With apply rotation & scale over some of glasses subparts it works in upbge 0.3.
Closing. Thanks for reporting
