### ISSUE TITLE
Realtime Environment Cube Map not working

### ISSUE THREAD

**Issue by alessiodeltrecco** [UPBGE/upbge#681]
Hi

first, i want to thank you for your great work on UPBGE, it's amazing!

Long story short: i've downloaded the v0.2.3b2 of UPBGE, i've followed the video tutorial hundred times :) but if i add a Realtime Environment Map it's working only if i set Mapping to Plane (in the Environment Map panel) but not if i set mapping to Cube.

What can be the problem?

I'll send you in attachment the screen shot of the problem and my blender system info

Thank you

![upbge](https://user-images.githubusercontent.com/11901319/37215292-d6083ae0-23b7-11e8-8921-11c5ac94c4ec.png)
In the image the UV Sphere has an Environment Map with Mapping: Cube and the plane has an Environment Map with Mapping: Plane

[system-info.txt](https://github.com/UPBGE/blender/files/1797408/system-info.txt)

**Comment by panzergame** [comment]
When you select "Cube Map" did you check that the dimension are correct ? (you can click on Resize too).

Anyway it will be better for us to have a example file via http://pasteall.org/blend/

**Comment by alessiodeltrecco** [comment]
Yes i've checked hundred times...

This is the blend: http://pasteall.org/blend/index.php?id=49784

**Comment by panzergame** [comment]
I got a working result if i select `Cube` :
http://pasteall.org/pic/show.php?id=59c9be1e3a12fd21cd97ddb5aea8c27f

Could you check if you don't have any error in console, also what is your OS and OpenGL version description ?

**Comment by alessiodeltrecco** [comment]
Here's my console log:

morg4n@debian-asus:~/UPBGEv0.2.3b2.79Linux64$ ./blender
Color management: using fallback mode for management
Read prefs: /home/morg4n/.config/blender/2.79/config/userpref.blend
found bundled python: /home/morg4n/UPBGEv0.2.3b2.79Linux64/2.79/python
Traceback (most recent call last):
  File "/home/morg4n/UPBGEv0.2.3b2.79Linux64/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'io_scene_dae'
Traceback (most recent call last):
  File "/home/morg4n/UPBGEv0.2.3b2.79Linux64/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'godot_export_manager'
serving at port 6687
Read blend: /home/morg4n/Temp/upbge_test.blend

Blender Game Engine Started
Blender Game Engine Finished
OpenCL error: CL_PLATFORM_NOT_FOUND_KHR in device_opencl_get_num_platforms_safe(&num_platforms) (/home/tristan/source/blender_master_v0.2.3/intern/cycles/device/device_opencl.cpp:144)

Blender quit

And my sys info is in the attached file

[system-info.txt](https://github.com/UPBGE/blender/files/2251404/system-info.txt)

**Comment by lordloki** [comment]
This is working in current UPBGE 0.2.5. Closing now. Thanks for reporting.
