### ISSUE TITLE
Crash when selecting weight paint

### ISSUE THREAD

**Issue by DarthMoulByte** [UPBGE/upbge#692]
when selecting weight paint on texture paint, any of these options closes suddenly blender
the only ones that do not do this are, edit mode, object mode!!!
How do I repair it or why does it happen?

![Crash GIF](https://user-images.githubusercontent.com/24207840/39685187-5ba0ed40-5186-11e8-88f2-f94ea3a0b45b.gif)

**Comment by BluePrintRandom** [comment]
I had this issue when I had a motion sensor logic brick, swapped to bf
blender and swaped back to upbge.

deleting the motion brick and putting it back fixed it.
(in my case*)

**Comment by DarthMoulByte** [comment]
good is from a guy who did not know where to put this question and show him where and how, although I think he just started using blender and had no idea about github.

but I asked him about this logical brick, and he told me that he still does not start to create programming with logical bricks, that he was following a tutorial and the next step was weight paint or vertex pain and sometimes Texture Paint, I lend him his blend file, and it is in good condition, I opened it in blender 2.78c and can use weight paint and vertex pain without problems, but I wanted to open it in UPBG 2.3 (2.79) and I had the same problem.
![blender_2018-05-07_21-04-35](https://user-images.githubusercontent.com/24207840/39733891-69544afe-523a-11e8-9482-38c1882602ab.png)

**Comment by DarthMoulByte** [comment]
good is from a guy who did not know where to put this question and show him where and how, although I think he just started using blender and had no idea about github.

but I asked him about this logical brick, and he told me that he still does not start to create programming with logical bricks, that he was following a tutorial and the next step was weight paint or vertex pain and sometimes Texture Paint, I lend him his blend file, and it is in good condition, I opened it in blender 2.78c and can use weight paint and vertex pain without problems, but I wanted to open it in UPBG 2.3 (2.79) and I had the same problem.
![blender_2018-05-07_21-04-35](https://user-images.githubusercontent.com/24207840/39733950-b3276b3e-523a-11e8-9edd-653aa455aa0c.png)

**Comment by DarthMoulByte** [comment]
![2018-05-07_21-00-06](https://user-images.githubusercontent.com/24207840/39733971-cced57cc-523a-11e8-9f05-b94cc81f3df0.gif)

**Comment by BluePrintRandom** [comment]
you can't go back and forth between bf blender and bge blender too many times or you bork the data.

typically appending it all back into a new blend fixes this though.

**Comment by DarthMoulByte** [comment]
maybe not !
mmmm could be a possibility
but it has never happened to me, today try doing several things in a blend in 4 different blender forks
-. UPBGE
-. Bforartist
-. blender 2.78c
-. Microvellum

**curious fact :**  _everyone claims that blender is free
**lie ... big lie**, in this you have to pay a license to use it completely or otherwise you can not design freely_

making changes of all kinds and did not lose any data, which makes me think that maybe something is damaged in the temporary folder in C: \ Users \ user \ AppData \ Roaming \ Blender Foundation \ Blender \ 2.79

**Comment by justinbarrett** [comment]
blender is free.

**Comment by DarthMoulByte** [comment]
hahaha you are joking right!
what a nice joke
if I want I can sell blender, that's what your license says, and also says that to whom I sell it I have to deliver the source code

Do you know or recognize Microvellum?https://youtu.be/xb43RpJTWWg
As you can see from here, the blender 2.8 interface was born
There was a blender version as you can see that it is not available anymore, in which you had to pay to release the libraries to work, now tell me that blender is free!

**Comment by DarthMoulByte** [comment]
jajajaja @justinbarrett you are joking right!
what a nice joke
if I want I can sell blender, that's what your license says, and also says that to whom I sell it I have to deliver the source code

Do you know or recognize Microvellum?https://youtu.be/xb43RpJTWWg
As you can see from here, the blender 2.8 interface was born
There was a blender version as you can see that it is not available anymore, in which you had to pay to release the libraries to work, now tell me that blender is free!

no more for blender https://www.microvellum.com/blender-2/

![2018-05-31_12-12-58](https://user-images.githubusercontent.com/24207840/40797031-753ac484-64cc-11e8-9a25-8e5249f1ad41.png)

**Comment by lordloki** [comment]
It is not recommended to go back and forward between BF-Blender and UPBGE because the data can corrupt in any way. We try to avoid this when we load blends from Blender-BF but loading UPBGE blends from BF-Blender is more problematic.
The other forks don't corupt their data as they don't modify the DNA code.
Closing the issue now. Than ks for reporting
