### ISSUE TITLE
Manage animation for materials and world.

### ISSUE THREAD

**Issue by panzergame** [UPBGE/upbge#697]
I saw in the code that SG_Controller (the classe used for updating value from animation) was also used for Material and World resource but from KX_GameObject in it's SG_Node during the spatial data update…

I think that it will be better to have material and world resource managing themselves animations.

To do so i'm thinking about implementing a common class for animable objects/ressources KX_Animated. This class contains a BL_ActionManager and a complete python API for animations add/remove.
KX_GameObject, KX_BlenderMaterial, KX_WorldInfo inherit from it and each time an instance is created, it is registered into the scene for animation update.

@lordloki : What do you think about this ?

**Comment by lordloki** [comment]
For upbge 0.3 is already possible to animate material and world nodes. Closing the report. Thanks for the feedback.
