### ISSUE TITLE
Armature animations.

### ISSUE THREAD

**Issue by panzergame** [UPBGE/upbge#698]
To avoid weird dependence to blender, I'm looking for replacing the current armature animation system by the ozz-animation library (https://github.com/guillaumeblanc/ozz-animation).

This library is designed for armature for data stored from FBX files or dynamically created.

**Comment by lordloki** [comment]
I have taking a look at the ozz library and it seems really good. Additionally, its performance seems very good.

**Comment by DCubix** [comment]
It would be good to not include any FBX related stuff. FBX is really old and closed-source.

**Comment by panzergame** [comment]
@DCubix : I will generate data for ozz directly from blender data.

**Comment by shuvit-game** [comment]
we are talking 100% backwards compatibility here right?! :-o

**Comment by BluePrintRandom** [comment]
I am looking here, and this does not appear to support IK for chains longer
than 2 bones*

**Comment by lordloki** [comment]
For 0.3 we use blender animation system directly therefore i close this.
Thanks for the efforts.
