### ISSUE TITLE
Multiple Render Targets for scene objects 

### ISSUE THREAD

**Issue by sergio5528** [UPBGE/upbge#705]
![image](https://user-images.githubusercontent.com/39790280/40766050-0a55171c-64ce-11e8-8ce5-d6559f0b81b4.png)

we can render multiple color attachment in filters ......anyone knows if we can render full scene objects to multiple color attachment? like right now we can get only bgl_RenderedTexture as input which is scene texture...if there is already function to send diff color attachments to filter then it will help to make g-buffer and many things.

![image](https://user-images.githubusercontent.com/39790280/40767558-91d77e7e-64d2-11e8-8701-93fcd97357bf.png)

![image](https://user-images.githubusercontent.com/39790280/40767760-2b61e3ea-64d3-11e8-993c-7c4660d534c6.png)

so,here is only single texture which is bgl_RendredTexture passes to filters as scene texture ...if we can pass multiple color attachment to filters as scenetexture0 scenetexture1 inplace of bgl_RendredTexture or any custom name

**Comment by panzergame** [comment]
The current blender shaders are currently writting to `gl_FragColor` so in your case it have to be defaulted to `gl_FragData[0]` other than that it could be possible.

How do you see the setup from python ?

**Comment by sergio5528** [comment]
well,right blender shaders are written in gl_FragColor .... but those who wants to make multiple render targets they have to make custom shader for every object in the scene which contains gl_FragData as output .... but while rendering scene to fbo we also should able to set slots for color attachment ,so that we can get different outputs from object which is send by gl_FragData in object shader ....yeah if gl_FragData[0] can be default it will be more easier to render simple objects so that people don't need to  use custom shader :)

**Comment by panzergame** [comment]
I think that the definition of secondary color attachment should be done in python, how do you see the API for it ?

**Comment by sergio5528** [comment]
i don't know if we can define other color attachment in python? In source code it's only sending color attachment 0 which is bgl_RenderedTexture.

**Comment by panzergame** [comment]
@sergio5528 : #774 could be interesting for you.

**Comment by lordloki** [comment]
This feature was implemented and available in current upbge 0.2.5. Then I close this. Thanks for the feedback.
