### ISSUE TITLE
can we get a split RGBA node? (for vertex color / object color etc)

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/upbge#707]
split - RGBA - if no A is present defaults to zero

this could drive splat map setups

**Comment by adriansnetlis** [comment]
This should be a thing in Blender in general.

**Comment by adriansnetlis** [comment]
Just as side note, currently you can do this:
![image](https://user-images.githubusercontent.com/6423934/42907923-01b3bc04-8ae8-11e8-864f-588bba3d97c5.png)

**Comment by BluePrintRandom** [comment]
Will that work from vertex color or from object color?

**Comment by adriansnetlis** [comment]
No. Those don't have alpha as of yet in them.

**Comment by UnidayStudio** [comment]
Just a point: No alpha means no transparency. So the default output value of the A color should be 1.

**Comment by lordloki** [comment]
This already exists in UPBGE 0.3 Alpha.
![image](https://user-images.githubusercontent.com/1015605/102760394-bad9c280-4375-11eb-94d8-17a913a8c2bc.png)
![image](https://user-images.githubusercontent.com/1015605/102760414-c0370d00-4375-11eb-8483-d0002ac92d1e.png)
Closing now. Thanks for the feedback
