### ISSUE TITLE
add support for batches of raycasts [long term]

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/upbge#719]
https://github.com/bulletphysics/bullet3/pull/1760

in this recent bullet commit they batch raycasts.

we could have users do this for things like graphics or physics,
for particle systems etc.

[ thank you again for all your work ]

**Comment by panzergame** [comment]
Apparently the Bullet 2 API is not supporting batched ray cast. I have to look if it's reasonable to switch to the Bullet 3 API.

**Comment by lordloki** [comment]
I close this. We will review it again if we change to bullet 3 at any time. I add it open & feature for later tags
Thanks for the feedback
