### ISSUE TITLE
Makes it so you can change a materials shader without using the BGE module.

### ISSUE THREAD

**Issue by Anarchokawaii** [UPBGE/upbge#720]
It's kinda annoying that you have to change a material's shader by using .getShader(). their should be a way to change the material's shader by using the Material panel or the Material Nodes panel or the Outliner.

**Comment by Jesusemora** [comment]
how is it annoying exactly? my guess is you have a project where you need multiple custom materials on multiple objects, and nodes is not enough so you need to execute scripts on all the objects?

> their should be a way to change the material's shader by using the Material panel or the Material Nodes panel or the Outliner.

you mean like, a visual way of setting a custom shader? a box where you select a text file to use for the material? maybe a new "custom shader" node if that's even posible?

**Comment by panzergame** [comment]
@Anarchokawaii : Are you meaning a way to define the vertex shader and fragment shader in UI and to give some values to uniforms ?

**Comment by adriansnetlis** [comment]
Oh yes, that'd bring more people to shader creation!

**Comment by Anarchokawaii** [comment]
> you mean like, a visual way of setting a custom shader? a box where you select a text file to use for the material? maybe a new "custom shader" node if that's even posible?

yeah pretty much. the last sentence sounds like the best possible option

**Comment by RomStef** [comment]
not bad idea at all !

**Comment by panzergame** [comment]
The drawback of custom shader nodes is that blender doesn't support settings for vertex shader from node side.
Also i don't think the user will use the fragment shader in only one node but more try to have a library GLSL and create a node per function.

**Comment by adriansnetlis** [comment]
Custom GLSL function nodes is perfect idea. I am 100% about it!

**Comment by RandomPandaStudios** [comment]
UPBGE 0.3 allows dynamic changing of Material Shader types at runtime with BPY code.

```
import bpy

def main(self):
    
    # Original material's name
    mat = bpy.data.materials["My_Material"]
    
    # Output node of the material
    material_output = mat.node_tree.nodes.get('Material Output')
    
    # The new shader type : In this case "Emission" type
    type = mat.node_tree.nodes.new('ShaderNodeEmission')
    
    # Set new attributes
    mat.node_tree.links.new(material_output.inputs[0], type.outputs[0])
```

As for a custom shader - you can design and create them with the provided real-time EEVEE Material Shaders: which will also work at runtime.
