### ISSUE TITLE
Implement render ordering material priority.

### ISSUE THREAD

**Issue by panzergame** [UPBGE/upbge#725]
To force the order of transparency objects, an UI option (integer) introducing a priority could be interesting.

**Comment by youle31** [comment]
Hi! Yes this could lead to interesting effects. But I don't know how to handle materials shared by several objects (But if it's optionnal, maybe it is not so important)

**Comment by panzergame** [comment]
Using an order per material and not per object could be more easier to manage for the user, for example having sprite effect material with an higher order priority.

For code details:
The sort is proceeded into `RAS_BucketManager::RenderSortedBuckets`using `RAS_BucketManager::SortedMeshSlot::SortedMeshSlot`, this last class associate the mesh slot (kind of object) with its distance to the screen. This class will request to store the material priority and use it in `RAS_BucketManager::backtofront::operator()`.

Note: for UI integration : https://github.com/UPBGE/blender/wiki/UI-property

**Comment by youle31** [comment]
hi, ok, thanks for your answer

**Comment by Jesusemora** [comment]
there is Material.offset_z wich is supposed to do something similar, but i have never tested if it actually works. getting rid of Z-fighting is important to create decals and complex objects.

**Comment by panzergame** [comment]
@Jesusemora : offset_z is used to shift the polygons depth by an offset or a by multiplying the depth by a factor.
This issue is related to using a option to force partially the ordering of transparent objects.

**Comment by lordloki** [comment]
Closing as 0.3 uses eevee render.
