### ISSUE TITLE
To move BGE bugs to our system

### ISSUE THREAD

**Issue by lordloki** [UPBGE/upbge#731]
I want to make you a proposal.
As the BGE is going to be removed, what do you think about to move bugs of developer.blender.org to our system?

Of course, We will have to check against current upbge code if the bugs are affecting to upbge...

**BF-Bugs Table tracking (177 bugs in total)**

Bug Number | Bug Name | Working in UPBGE lastest master
:---: | :---: | :---:
T50806 | Parent/child transformation is incorrect   when the parent's scaling is changed | Yes
T49329 | BGE standalone player   crash when loading another file more than 32 times | Yes
T48458 | bge solidify materials | Yes
T48099 | Adress boundary error given bad input | Yes
T47909 | Significant animation overhead remains after stopping animation playback | No
T47908 | Loop End action does not complete (behaves as Loop Stop) | No
T47125 | Standalone player segfaults, but embedded player works fine | Yes
T46650 | Animations don't update until looking at them | Yes
T46527 | Transformation of child objects appears broken | Yes
T46394 | bgelauncher embedded and standalone | No
T46122 | Action Actuator - Flipper Mode Frame Glitches | Yes
T45957 | light.type appears to not do anything when set in engine | ????
T45742 | Drivers in Game Engine don't work for Spawned objects | No
T45576 | SoftBody demostration file makes strange deformation. | No
T44557 | BGE leaves references in memory after quitting | Yes
T38916 | Bug Game Engine Runtime | Obsolete
T24948 | Modifiers make materials disappear in BGE | Yes
T42020 | BGE crashes when LibLoading multiple files asynchronously | Yes
T53563 | BGE X any Y doesn't work right | No 
T53457 | in bge crash from triggering addObject script | ????
T53454 | Deleting the active camera stops scene callbacks | No
T53272 | navMesh.replaceMesh('mesh',1,1) + navMesh.rebuild() does not use new meshProxy | No

**Comment by panzergame** [comment]
I agree with but I don't have enough time to do it...

**Comment by lordloki** [comment]
No problem. I take the task

**Comment by lordloki** [comment]
Ok, this is assigned to me. I will use it as TODO issue but i close it following the rules
