### ISSUE TITLE
Implement 3D texture.

### ISSUE THREAD

**Issue by panzergame** [UPBGE/upbge#732]
This feature should allow the user to provide a tiled image and create a 3D texture from it.

From basic material definition, the mesh surface is used to sample the texture, but the interest is more for node material which will allow to sample anywhere.

**Comment by ethicalfive** [comment]
Is this the same as tri planar texture mapping or something different?

**Comment by panzergame** [comment]
This is not the same.

**Comment by ethicalfive** [comment]
Ohh cool, so its like this https://youtu.be/9AS4xV-CK14

**Comment by lordloki** [comment]
Closing. UPBGE 0.3 alpha already allows volumetrics
