### ISSUE TITLE
Proposal: New Website Home

### ISSUE THREAD

**Issue by UnidayStudio** [UPBGE/upbge#741]
Hi guys! 

Our homepage is the first impression that every new user will get. So I believe thast we could do a better work on it. So, since everything is open source, I decided to try my version! :smile: 

- Just to remember, here is the original page:
https://upbge.org/

- And here is my proposal:
http://unidaystudio.esy.es/

**IMPORTANT**: Open the site on a PC. I didn't make it adjust for mobile yet. 
**Note**: Stored on my test website. Some of the images that I used are just for testing.

What do you think? Suggestions?

**Edit:** O forgot to create the News Tab and de Credits/Contact. But this is not a huge problem. I can create this in seconds.

**Comment by adriansnetlis** [comment]
That design really does look better, I'm about the change. Not keen on the fonts, tho, something cleaner looking would be a better choice (current ones seem a bit aliased).

**Comment by UnidayStudio** [comment]
Thanks for the suggestion, guys! 
@adriansnetlis would you suggest some other fonts? Thanks for the feedback!
@panzergame Amazing!
@justinbarrett I loved this idea. We need to showcase the best games on the website! 

I'm thinking about making a background video, such as UE4 does:
https://www.unrealengine.com/en-US/what-is-unreal-engine-4

By the way, what more can I add to the homepage?

**Comment by panzergame** [comment]
@UnidayStudio : Hello, we are going to use this site as a base for a new version but we would like to know what is the licence of the images and the source of the page.

**Comment by adriansnetlis** [comment]
`Some of the images that I used are just for testing.` (quote)
The images are from The Division, another game and the last one is from Armory 3D demos. All of those would preferably be replaced by UPBGE-rendered artworks.

**Comment by panzergame** [comment]
@adriansnetlis : Thanks for the image, maybe even a splash screen candidate :)
@UnidayStudio : Anyway, the most important now is to know what is the licence of your page.

**Comment by panzergame** [comment]
@UnidayStudio : Thank you a lot, see you tomorrow.

**Comment by UnidayStudio** [comment]
@panzergame The website is now on github:
https://unidaystudio.github.io/UPBGE-Website/

Source:
https://github.com/UnidayStudio/UPBGE-Website

# Important:
I made this using adobe Muse. So the generated sources may not be very legible. Because of this, I added a "source" folder that contains the .muse project. I still have to replace the two screenshots picked from google/armory website (first and last ones).

**Comment by supermoaaa** [comment]
hi I think you must rehash the section of website to be more user friendly 

in my opinion overview or blog in first position , documation , dev and download
   with a specific web page for each section

**Comment by panzergame** [comment]
@UnidayStudio : Do you have in your icons library images that can be used to create python icon for the python API link ?

**Comment by EndSSgamesStudio** [comment]
Perfect!
I really liked the model, it was impressive compared to what it is now!
but I think you should remove the last image, it's **Armory 3D**

**Comment by UnidayStudio** [comment]
@panzergame I think so.

**Comment by lordloki** [comment]
Since some time ago we have a new upbge.org webpage. I will update the images and the features in the next days.

Thanks for the opinions and the mock-ups.
Closing the report now.
