### ISSUE TITLE
Add python components in python templates.

### ISSUE THREAD

**Issue by panzergame** [UPBGE/upbge#744]
The script editor allow to load templates but for the moment there's no templates for python components.

I propose to first reorganize the template in categories (to avoid mixing blender and bge scripts) and add templates from https://github.com/UnidayStudio/UPBGE-TopDownTemplate or other collection.

**Comment by UnidayStudio** [comment]
Amazing! What kind of templates should we code?
I made an Issue in one of my Templates Git to ask the community as well:
https://github.com/UnidayStudio/UPBGE-UtilsTemplate/issues/1

**Comment by youle31** [comment]
Hi, it's ok for me.

**Comment by lordloki** [comment]
Yes, it would be great!!!

**Comment by lordloki** [comment]
This was already implemented for UPBGE 0.3 Alpha. Closing now. Thanks for the feedback
