### ISSUE TITLE
Support alpha channel in `mathutils.Color`

### ISSUE THREAD

**Issue by panzergame** [UPBGE/upbge#748]
Currently this class handle only 3 channels and is most of the time not used in game because of its lack of alpha channel.
Also for support color property in python component we have to use a different class than vector which a full support of alpha channel.

Basically the API will be changed by adding a `a` attribute and allow constructing a color with 4 elements.

**Comment by BluePrintRandom** [comment]
do you think after you get this committed we could add a split RGBA node?
this will open up many possibilities ( more splat channels or more FX
driver per color channel)

**Comment by panzergame** [comment]
We could replace the 4 channels colors in the API by a real `Color` object but it will loose some compatibility. For example the fields `x/y/z/w` are not present and could be added, but it's more complicated to port all the combination of these fields: `xy`, `xz`…

Do you think the fields `x/y/z/w` are enough for compatibility of  attributes like `KX_GameObject.color`?

**Comment by BluePrintRandom** [comment]
I have never used .xy or xz etc with color

typically I use split RGB node and use a single color channel to drive a
effect or multiple  color channels to drive splat mapping

I can't really think of a reason to use the other configs than r/g/b/a

**Comment by lordloki** [comment]
Incorporated to next 0.2.5a. Thanks for the feedback.
