### ISSUE TITLE
Use `final` keyword for virtual functions.

### ISSUE THREAD

**Issue by panzergame** [UPBGE/upbge#771]
Using the `final` keword is helping a lot the compiler to remove virtual resolution by detecting that the instance is at the final level and that the function can be called directly.
This optimization is `fdevirtualize` but it also happens in MSVC.

From this example:
```cpp
class I
{
public:
    virtual int get() = 0;
};

class A : public I
{
public:
    virtual __attribute__ ((noinline)) int get()
    {
        return 42;
    }

    int __attribute__ ((noinline)) dbl()
    {
        return get() * 2;
    }
};

int func(A *a)
{
    return a->dbl();
}
```

If A::get is not specified final, A::dbl will do an indirect call:
```
A::get():
  mov eax, 42
  ret
A::dbl():
  sub rsp, 8
  mov rax, QWORD PTR [rdi]
  mov rax, QWORD PTR [rax]
  cmp rax, OFFSET FLAT:A::get()
  jne .L4
  call A::get()
  add rsp, 8
  add eax, eax
  ret
.L4:
  call rax
  add rsp, 8
  add eax, eax
  ret
func(A*):
  jmp A::dbl()
```

Otherwise if A::get is final `virtual __attribute__ ((noinline)) int get() final`:
```
A::get():
  mov eax, 42
  ret
A::dbl():
  sub rsp, 8
  call A::get()
  add rsp, 8
  add eax, eax
  ret
func(A*):
  jmp A::dbl()
```

**Comment by lordloki** [comment]
I close it now but i put a tag for check later. I have to investigate more on 'final' word use
