### ISSUE TITLE
Batching group

### ISSUE THREAD

**Issue by panzergame** [UPBGE/upbge#775]
I recently looked at water demo file and the major issue was the trees around and especially the foliages…

It should be interesting to have a way to batch every objects in a group or a hierarchy. To do so we can add an option in group UI. 
Or allow an automatic batching of materials / objects based on distance, but the user have to be aware that these objects MUST not move.

**Comment by UnidayStudio** [comment]
Unreal Engine does a very interesting thing IIRC: All the objects is marked as "Static Object". I assume that this is for optimizations.

**Comment by UnidayStudio** [comment]
Update: I was thinking about this issue... and I figured out that we already have the solution: On the physics panel, there is a checkbox called "Actor" that works in a similar way that a "Static Object flag" works. So if we want to move an object, we just have to activate the actor. A simple change needs to me done to allow the Actor if the object have no physics.

**Comment by panzergame** [comment]
What about object not using physics ? Exposing also for non collision objects ? Also is physics a coherent context for batching ?

**Comment by lordloki** [comment]
I close this as for 0.3 the batching is done in eevee. Thanks

**Comment by BluePrintRandom** [comment]
Also is physics a coherent context for batching ?
if we use masks we can have static objects ignore each other 

and physics culling should work for a type of 'physics LOD'
