### ISSUE TITLE
web and mobile export

### ISSUE THREAD

**Issue by baptx** [UPBGE/upbge#788]
With the removal of BGE from Blender 2.8 and the recent open source release of Armory 3D game engine for Blender, it would be nice if a future UPBGE version can also export a game to web browsers (WebGL) and mobile devices (OpenGL ES).
This would make UPBGE compare better to other cross-platform open source game engines like Armory3D, Godot and Urho3D.
Do you have any plan for this feature?

**Comment by baptx** [comment]
@panzergame I also guess it would not be easy for WebGL, using Emscripten would not be enough?

**Comment by joelgomes1994** [comment]
Somewhat related to #674 ?
Outdated source to Android export seems to exist.

**Comment by lordloki** [comment]
I'm investigating the use of regal library for opengl->opengl es wrapper

**Comment by hartsantler** [comment]
any progress on the Android port? I think eevee integration makes this easier to do, since it drops support for the old style OpenGL.

**Comment by BluePrintRandom** [comment]
I think that the 2.8 branch / build that youle is using restored some of
the old drawing code - to draw the logic brick editor.

A blender player for 2.8 projects is possible I think, however the editor
itself (logic bricks) needs to be redone to use the node editor - to remove
the last of the dependencies on old code I think.
also there is logic etc that would need to be implemented.

**Comment by lordloki** [comment]
This can be started when blender has vulkan support. Until then i close it but i can put a tag to check later

**Comment by baptx** [comment]
@lordloki isn't it possible to dot it with OpenGL? And WebGL is based on OpenGL instead of Vulkan.

**Comment by lordloki** [comment]
At this moment it is not possible and we dont have enough workforce to do this. We will waitto vulkan support in blender (planned for this year/beginning next year)

**Comment by alexkowel** [comment]
Verge3D addon should be compatible with UPBGE. One can use it to produce web-based interactives or games.
