### ISSUE TITLE
Improvements on audio engine and support to realtime SFX

### ISSUE THREAD

**Issue by joelgomes1994** [UPBGE/upbge#792]
Hello! I will expose both a feature request and a suggestion on where to research to achieve it (i hope).

Modern games frequently support realtime sound effects, such as hi pass, low pass, reverb, delay, distortion, etc. The uses are many:
- Hi pass: can be used when character is hit by a flashbang grenade.
- Low pass: can be used when character is underwater.
- Reverb / delay: both can be used to simulate closed space ambience (such as large halls, caves, etc).
- Distortion: can be used to simulate radio speech.

Currently, Audaspace supports some effects such as hi pass and low pass, but these effects aren't in real time, they are just a pre buffered version of the original Factory. The best approach would be a Device which supports these and more sound effects, allowing to apply sound effects in a 'global' way and in realtime (including allowing to change the effects parameters in realtime).

This, for sure, would lead to a lot of work to rework the way that Device works, develop the effects and so on, so I bring something that may help in this case: [libaudioverse](https://github.com/libaudioverse/libaudioverse) library.

The [libaudioverse](https://github.com/libaudioverse/libaudioverse) library is, among other things, a realtime environmental audio library, and open source, just like Blender's Audaspace. However, libaudioverse supports realtime audio effects, such as reverb, delay and much more, and its intent is exactly to be used on games and interactive apps. Its development is halted, but the library is somewhat useable on its current state (i even tested it in UPBGE through Python), and its source code is available to be improved or used as reference. My suggestion is to implement it on UPBGE along with Audaspace, or use libaudioverse source code as reference to improve Audaspace.

In any case, the recently removed Audio panel on Scene tab could return, now with the global effects options and, in case of libaudioverse is implemented, an audio engine selector (just like the physics engine selector).

**Comment by panzergame** [comment]
@lordloki : Is ge_eax covering some of this issue ?

**Comment by lordloki** [comment]
Yes, it will cover the effects and filters that @joelgomes1994 asked for and a few more.

**Comment by lordloki** [comment]
I close it but i will check later as i want to finish and commit the ge_eax branch
