### ISSUE TITLE
Feature request: MakeScreenShot without lag (Rocky Madio demand)

### ISSUE THREAD

**Issue by youle31** [UPBGE/upbge#800]
Hi, a feature request from discord, try to find a way to capture the screen without generating lag.

Demand from Rocky Madio on Discord. @panzergame had ideas about

**Comment by panzergame** [comment]
It is possible to use a PBO (https://www.khronos.org/opengl/wiki/Pixel_Buffer_Object) to copy from the GPU the framebuffer and after get buffer from glMapBuffer.

**Comment by BluePrintRandom** [comment]
also what about a delay that only takes 1 shot per X frames instead of as long as you hold the button??

else I think it's copying into the buffer like 10 or 15 times in a little tap of print screen right?

**Comment by panzergame** [comment]
>>> also what about a delay that only takes 1 shot per X frames instead of as long as you hold the button??

I think it should be a user behaviour.

**Comment by panzergame** [comment]
Experimental branch ge_screenshot.

**Comment by lordloki** [comment]
0.2.5 was released without this. Closing but noted to check later.
Thanks
