### ISSUE TITLE
Triplanar texturing

### ISSUE THREAD

**Issue by RomStef** [UPBGE/upbge#812]
it would be interesting to implement a triplanar texturing feature. I came across this article that talks about the topic and how to implement it via shader. this functionality is present in substance painter and greatly facilitates the texturing phase.

https://therobotseven.com/devlog/triplanar-texturing-derivative-maps/

**Comment by panzergame** [comment]
Could you describe the UI that user can use to setup the 3 textures ?

**Comment by RomStef** [comment]
i think the correct place is in the texture tab under the Mapping coordinates. in the dropdown combo we can  adda triplanar option to manage the texture mapping

**Comment by panzergame** [comment]
It is hard to define the three textures in one material textures, as blender, VideoTexture, and BL_Texture expect one texture in a material texture.

Reference for later: https://medium.com/@bgolus/normal-mapping-for-a-triplanar-shader-10bf39dca05a

**Comment by RomStef** [comment]
yes , i know it's not a priority at this moment.

**Comment by panzergame** [comment]
A material node could be really easy to implement as there's no material texture in this area.

I target the issue as good first issue.

**Comment by ethicalfive** [comment]
Turns out that the node already exists in cycles material nodes under Textures->image texture->projection box.
And it works with UPBGE/internal nodes, just change to cycles and then add the node.

https://i.imgur.com/LGZpWMB.png

**Comment by lordloki** [comment]
Now in 0.3 is possible to do triplanar with node:
![image](https://user-images.githubusercontent.com/1015605/145674180-ed1b2ce5-af49-4db8-8cdd-f7fe5d684aa0.png)

Closing the issue, thanks for reporting.
