### ISSUE TITLE
Internal debug option with vertex\faces\edges index visualization

### ISSUE THREAD

**Issue by RomStef** [UPBGE/upbge#828]
it's just a stupid thing but , is it possible to include a "bpy.app.debug" trigger inside the "game \ show debug" menu ? maybe including the show index flag enabled ? this option allow the visualization of the progressive index assigned by blender to vertex\face\edge created 
type in the python console "bpy.app.debug = True" and , in the edit mode appear the flag as show in image below
![debug_indices](https://user-images.githubusercontent.com/20901566/45263107-da0de980-b423-11e8-862c-01435cf06a4a.PNG)

**Comment by lordloki** [comment]
But why to put under game engine part if we can to put easily exposing the check through the .py ui file?

**Comment by RomStef** [comment]
I'm agree

**Comment by panzergame** [comment]
@lordloki : I thought you wanted this option in game too.

**Comment by lordloki** [comment]
@panzergame it could be interesting although it is a more modelling-focused feature

**Comment by RomStef** [comment]
@lordloki , i think this would be interesting for testing vertex shader. Maybe if we could select the geometry to debug

**Comment by lordloki** [comment]
I close this as this feature doesn't exist in eevee now. I will tag it with "open" & "feature request for later" to recover it when upbge0.3 is more stable. Thanks for the feedback.
