### ISSUE TITLE
Addons Catalog takes you to expired link for blender 2.6 in the blender wiki

### ISSUE THREAD

**Issue by ethicalfive** [UPBGE/upbge#836]
under user preferences->addons->online resources->addons catalog, opens a browser to the page https://wiki.blender.org/wiki/Extensions:2.6/Py/Scripts

**Comment by panzergame** [comment]
This is happening in vanilla blender, did you report the bug to them ?

**Comment by ethicalfive** [comment]
I'm not exactly a fan of BF's branches these days with the removal of the BGE and being stigmatized by their userbase for wanting to support and use the BGE.

**Comment by panzergame** [comment]
I think it's this link https://en.blender.org/index.php/Extensions:2.6/Py/Scripts right ?

**Comment by panzergame** [comment]
@youle31, @lordloki ?

**Comment by lordloki** [comment]
Yes, is that link

**Comment by lordloki** [comment]
Closing. Upbge 0.3 has link fixed
