### ISSUE TITLE
proposal to compile UPBGE once a week

### ISSUE THREAD

**Issue by EndSSgamesStudio** [UPBGE/upbge#845]
I finally realized that there are still beginners with problems compiling UPBGE and these people want to see the improved UPBGE before the release.

![screenshot_20180924220400](https://user-images.githubusercontent.com/35436445/45987082-03df2700-c046-11e8-8c8e-ca0c72afd2ee.png)

as you can realize the blender has compiled every day that are compiled by bots

As you do not, I found it interesting.
as they know how compiling is tedious and time consuming ...

we would like to create such compilations and post to all people
we have computers to spare to do this ...
and will have 1 compilation per week

and it's a volunteer job, I will not ask for anything

I just need a page here to post the links
what do you think?

**Comment by lordloki** [comment]
Thank you for the offer. 
I think that @panzergame was preparing a dayly build machine.
I am configuring several virtual images to compile with ubuntu, windows and mac os.
I think between the 3 of us we can supply with fresh builds to UPBGE community.
I will contact you with details when we have the page ready.

Thanks

**Comment by EndSSgamesStudio** [comment]
ok! thank you!
can I compile from Windows 32 and 64 bits
I'll be preparing two machines for compilation!
I'm waiting ^ ^

**Comment by panzergame** [comment]
I already have the buildbot with scripts for linux compilation and windows VM with equivalent scripts.
This machine also include test checking for render difference of multiple files.

If someone have some idea on the GLIBC issue he is really welcome. The buildbot is a gentoo system with a relatively recent glibc compared to ubuntu based distribution.

**Comment by panzergame** [comment]
I found a potential fix for GLIBC, you can test https://download.upbge.org/download/release/linux64/UPBGE_master_v0.2.3b2.79d30092018he2fde22Linux64.tar.xz

**Comment by BluePrintRandom** [comment]
https://developerinsider.co/compile-c-program-with-gcc-compiler-on-bash-on-ubuntu-on-windows-10/

**Comment by lordloki** [comment]
I'm doing regular releases:
Each 1-2 days for Windows and Linux
Each 15 days for MacOS

Closing the report. Thanks for the proposal.
