### ISSUE TITLE
Expose depth texture in custom shader for material using depth transparency.

### ISSUE THREAD

**Issue by panzergame** [UPBGE/upbge#874]
The proposal is about providing a `bgl_DepthTexture` for custom shaders when they are attached to a material using depth transparency.

In this case the user can do it's own depth transparency or other effects.

**Comment by lordloki** [comment]
I close this as I'm going to add only several bugfixes and a feature tested in next 0.2.5b release. After this, I will go with 0.3 only.
Thanks for the proposal.
