### ISSUE TITLE
Display management

### ISSUE THREAD

**Issue by marechal-p** [UPBGE/upbge#875]
https://pythonapi.upbge.org/bge.render.html#bge.render.getDisplayDimensions

This function is useful when you have one display, but as soon as you have two it becomes a pain: What should we do if the screens have different resolutions? Also how to set the window size solely based onto the dimensions of one the monitors?

Proposition:
- Having one more method, `getDisplayCount()` to get the amount of monitors.
- Make a function such as `getDisplayDimensions(displayIndex)`, that would return the dimensions for the given monitor.
- Make a function such as `setFullscreen(displayIndex)` to set the fullscreen on one specific monitor.
- Make a function `getFullscreen()` returning the index of the screen on which the fullscreen is set, or `None` if not set.
- Make a function `disableFullscreen()`

**Comment by lordloki** [comment]
I close this as I moved to new https://github.com/UPBGE/upbge/discussions/1358
Thanks
