### ISSUE TITLE
Binary math mode for vector math node

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/upbge#882]
if top vector is equal to bottom vector in math node vector output is 1,1,1 and value is 1,
else output is 0,0,0 for vector and 0 for value

this will greatly help with mixing textures to allow 1 node group to represent 100's of materials for batching/atlas usage.

**Comment by adriansnetlis** [comment]
I agree this could be useful. Currently you can, however, already do this by making your own group.
![image](https://user-images.githubusercontent.com/6423934/47498313-89344200-d865-11e8-8a48-b90938a1326d.png)

**Comment by lordloki** [comment]
Following new rules i put an open tag to check later and i close it.
