### ISSUE TITLE
1 new uniform for objects -  SpawnedTime

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/upbge#901]
SpawnedTime = how long a object has lived since spawned

edit : removed rotation issue

geometry[world]Out----transform node can do this

**Comment by adriansnetlis** [comment]
I thought one could access rotation matrix (part of transformation matrix) through shaders for that purpose (and rotation matrix makes way more sense than euler rotation, if you really need those euler vectors you can convert from the matrix).
Regarding the spawned time, you can pass custom uniform for that when creating object. I don't see any reason why would we need to hard code that uniform.

**Comment by BluePrintRandom** [comment]
To access it in the glsl node graph

**Comment by rpaladin** [comment]
Closing thanks to similar solution at: #802
