### ISSUE TITLE
Feature request: Make Cycles texture node tab accessable in UPBGE material nodes tab

### ISSUE THREAD

**Issue by ethicalfive** [UPBGE/upbge#903]
Blueprint and I have been experimenting with material texture nodes from cycles and they seem to function pretty bug free in UPBGE so we request they be made available in UPBGE material nodes directly.

They open up stuff like making generative textures and normal maps (through bump) as well as triplanar texturing is basically already available in the Image texture node(cube selection and blending).

**Comment by ethicalfive** [comment]
I made a patch that adds the cycles textures to old material nodes:
https://drive.google.com/open?id=1jnSRn24FtYX1NvJsiXODrKXOCfoyja-G

**Comment by lordloki** [comment]
Thanks for the patch. I will take a look about it when we enter in the 0.2.5 development.

**Comment by lordloki** [comment]
In 0.3 we have nodes shared. Thanks for reporting
