### ISSUE TITLE
Inverse Square Cutoff Ignores Energy

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/upbge#909]
![image](https://user-images.githubusercontent.com/6423934/47619994-8186ce80-daed-11e8-94e6-1b80a1f399a2.png)
On the left it's radius 0.1, energy 10, on the right it's radius 0.1 energy 100. Cutoff 0.00001 on both. As you can see, the right one looks way off because the cutoff is the same as for the one on the left, while it actually illuminates at noticeable rates way further. I think the cutoff equation requires energy taken in account.

**Comment by panzergame** [comment]
@lordloki : What do you think ?

**Comment by lordloki** [comment]
Although the cutoff follows the algorithm correctly i see the @adriansnetlis point. I will see how i can modify the code to put the cutoff distance based on energy.

**Comment by lordloki** [comment]
In 0.3 is fixed. Thanks for reporting
