### ISSUE TITLE
Allow Python controllers run in asynchronous mode

### ISSUE THREAD

**Issue by vlad0337187** [UPBGE/upbge#910]
Tags: [question], [discussion]

Hello.

### Subject:

Wanted to ask / discuss about launching complex Python logic from controllers.
(thought that's better to do this in IRC, but several days all channel is in silence)

Sometimes it's needed to process complex logic using script.
For example, calculate some points for some mesh (water simulation, etc), steer NPCs, request some info from server, or something like this.
I think that many tasks, near 30% doesn't require to be finished before next logic tick.
 
And you don't need to run this from first to second logic tic.

### Questions:

`Question 1`: As I understand, if to launch one time blocking task, for example, for 200ms, there would be a freeze from 1 to 2-nd logic tick, all other ticks will work well, and FPS counter can still show 60 FPS, while user feels freeze; Right ?

As I understand, I could spawn separate Python process and ask it to do all required waiting tasks, but it would require large overhead for making / debugging passing objects through pipe system, inconvenience with impossibility to run UPBGE API's functions directly.

`Question 2`: Is it possible at all (and is it difficult if possible) to add `async` mode (with checkbox to activete) to Python controller ?

### Usage:

I see such use cases:
- controller is activated every 70 ticks, and launches Python function. Frames are rendered and after function finished (returned something or None), it can be launched another time.
- controller is actevated only one time on startup. It has while loop, and sleep() calls. It wakes when needed, calls some API, performs some work, and suspends to sleep.

Why did i asked question 2, because I don't know how to implement it using threading from C code.
I can look only from Python's side, so if I would need to implement this using only Python, I would do so:
- Add wrapper, which calls our target function, after it returned result or nothing - sets value of variable `asyncFunct023435finished`  to true.
- Check in main thread if variable `asyncFunct023435finished` has true value, than async task is finished and can be called another time.

### Behavior:

Current behavior when creating a thread that just prints some text in while loop then sleeps 1ms, using delay sensor:
- Thread is created, but prints text only after any other sensor activated.
- After game engine finished, it begins printing text to console as it should do during game
- it won't be stopped until you'll quit blender itself

Expected behavior:
- thread created and works separately from other threads, it's not bounded to logic cycles of game engine
- to receive some data from bge module, it should use some wrapper (like `bge.async_wrapper.get_result(method=Cube.rayCastTo, arguments=(...,...)), which will add method calling to queue and will call it and return result when it would be possible
- thread is suspended after game engine stopped

Thanks for attention, sorry for spamming questions to issue tracker =)

**Comment by panzergame** [comment]
> Question 1: As I understand, if to launch one time blocking task, for example, for 200ms, there would be a freeze from 1 to 2-nd logic tick, all other ticks will work well, and FPS counter can still show 60 FPS, while user feels freeze; Right ?

The FPS counter is an average of the last 25 frames (else it's totally unreadable). This can create the impression to have fixed framerate where it's not the case. I noted an idea about exposing maximum and minimum framerate during these 25 or more frames.

> As I understand, I could spawn separate Python process and ask it to do all required waiting tasks, but it would require large overhead for making / debugging passing objects through pipe system, inconvenience with impossibility to run UPBGE API's functions directly.
> Question 2: Is it possible at all (and is it difficult if possible) to add async mode (with checkbox to activete) to Python controller ?

The major issue is the modification of objects while they are read for rendering, physics etc…

**Comment by lordloki** [comment]
Closing the report to keep clean the tracker for bugs.
I will add a label to find it later when we check for new features
Thanks for reporting
