### ISSUE TITLE
Activate / Deactivate any actuators from any controller.

### ISSUE THREAD

**Issue by vlad0337187** [UPBGE/upbge#911]
Hello.

Now we have such lines:
https://github.com/UPBGE/blender/blob/master/source/gameengine/GameLogic/SCA_PythonController.cpp#L440
https://github.com/UPBGE/blender/blob/master/source/gameengine/GameLogic/SCA_PythonController.cpp#L456

, which block activating actuators from Python code, if that Python code is called from controller, to which that actuator was not connected.

Can't imagine reason, for what they were written, but I don't think it's needed.
Neither for security reasons (don't see such), nor for any other.
If Python code obtained some actuator (even not connected to it) and tries to activate it, in most cases it was done intentionally.

I think, it would be better just to remove them to be able calling any actuator from any Python controller.
So we could pre-create objects with set of not-connected actuators and activate them from any place.

**Comment by youle31** [comment]
I think this is not really in the "logic" of logic bricks. The python controller itself is activated only if it gets a signal from its own sensors list and can only activate its own actuators list. Then try to "force activation" of a "controller+actuator" if this controller has a spacebar sensor to trigger it, AND without having to press spacebar seems very weird to me and could lead to confusion and weird behaviours. It's too risky imo then I close this request.
