### ISSUE TITLE
Feature Request: Screen Space Reflections

### ISSUE THREAD

**Issue by 0by1** [UPBGE/upbge#914]
Faking Realistic Scenes would be SO much easier, and optimized if UPBGE featured Screen Space Reflections (SSR)
eg.
https://www.youtube.com/watch?v=x7LeX-EDhww
https://blenderartists.org/t/ssr-screen-space-reflections-shader-v0-4/685927

If this can be implemented into a simple material node, with an RGB channel to control the Roughness/intensity- It would open a lot of doors to making visually interesting scenes/levels.

How I as an artist suggest this should be implemented:
-----a Material Node with the following options:

*Roughness RGB input.
*Background RGB Input (for the spaces the SSR cant reach) OR a Cubemap to fill in gaps.

-----Material pannel+texture pannel with the following options:

*Roughness RGB Slot under textures
*Cubemap support for empty gaps.

Thenks :3

**Comment by vlad1777d** [comment]
Yeah, SSR is faster than current cubemap and planar reflections, as I know.

**Comment by BluePrintRandom** [comment]
SSR is good for some stuff, parallax corrected cube-maps is better for
others

The ideal solution uses a light-field to gather static reflection, and RTX
for the raytracing or something like that - but it's bleeding edge

SSR is nice but still needs to fallback to cubemaps.

taking the parralax corrected cubemap and falling back to it if SSR hits
something outside the camera futurism is what most engines do.

I think we need to remove BGL support in favor of many cubemaps rendering
during the logic step and getting a parralax correction during the draw
step.

**Comment by vlad1777d** [comment]
@BluePrintRandom , didn't got it, how is BGL binded to this =)

Anyway, I saw your video with open world on youtube, wanted to ask you some questions about it.
How can I contact you ?
Do you have Telegram messenger, or something like this.

Also wanted to ask you about possibility of chaining fragment / vertex shaders.

**Comment by BluePrintRandom** [comment]
BGL is called during the logic step to perform drawing operations, and
makes things quite flexible, however during the logic step we could be
doing other things on the GPU like particle simulations, or cube map
rendering or ???

basically the cpu is busy during logic step and the GPU is idle,

and as far as talking about BGE stuff - https://discord.gg/vQmGnm here is
the bge discord and here is the blender discord - <@&438645847778000897>
Blender Talk - Invite > https://discord.gg/blender <

**Comment by vlad1777d** [comment]
@BluePrintRandom , seems, BGE invite is outdated =)
(just wanted to join it)

**Comment by BluePrintRandom** [comment]
https://discord.gg/Mnw67yB - this will never expire

**Comment by lordloki** [comment]
SSR is already included in 0.3. I close this. Thanks for the feedback
