### ISSUE TITLE
Creating an AUR package

### ISSUE THREAD

**Issue by katp32** [UPBGE/upbge#915]
I'd like to create an AUR package (and realistically this is pretty easy since I can just use the existing PKGBUILD for `blender-git`, however the issue is that the binaries, desktop file, etc all still use the name `blender`, which causes the package to conflict with regular Blender. Does anybody know how feasible it would be to fix this...?

Edit: My current hacky fix is to just mark the package as providing & conflicting with `blender`, although unless this repo is kept up-to-date with the official blender repo that's not really a permanent solution

**Comment by atoms118** [comment]
Note that after a couple hours of tinkering I now have a working PKGBUILD. Of course, I applied the hacky fix I mentioned before so it isn't great, but it works for now.

**Comment by panzergame** [comment]
Hello, is it possible in the package to rename `blender` and `blenderplayer` to `upbge`and `upbgeplayer`.

@lordloki, @youle31 : Iirc a github issue is targeting it, would you like to apply these changes ?

**Comment by atoms118** [comment]
Does UPBGE have any additional dependencies that Blender does not? Additionally, does UPBGE depend on Cycles, as cycles pulls in a bunch of optional dependencies which would not be needed otherwise

**Comment by atoms118** [comment]
So a hacky solution I found is if you take the download from the website, you can just `ln -s` the binary into `/usr/bin` or wherever, and give it whatever name you want. I'll apply this to the AUR package in the next couple days. It's not a perfect solution, but so far it seems to be working just fine

**Comment by lordloki** [comment]
I close this and translate the rename to issue #858
