### ISSUE TITLE
Bug: Crash while using GameObject.collide method inside component

### ISSUE THREAD

**Issue by MrVentz** [UPBGE/upbge#916]
Hello,

When I attempt to use KX_GameObject.collide method inside component it causes the engine to crash after a few seconds (in case of Win64 versions) or crashes instantly (in case of Win32 versions).
I've tested it with both 0.2.4 and 0.2.3 - they both crash.

[collide_bug.zip](https://github.com/UPBGE/blender/files/2542646/collide_bug.zip)

I've tried it on 2 omputers:
    OS: Windows 7 x64
    CPU: Intel Core i7 6700K
    GPU: Nvidia GeForce GTX 1050 Ti
    RAM: 16 GB

and:
    OS: Windows 7 x64
    CPU: Intel Core i5 3300
    GPU: AMD Radeon RX 460
    RAM: 8 GB

I hope it'll help.

**Comment by MrVentz** [comment]
I didn't have tested it on Linux (and unfortunally I don't have the possibility to install it yet). Should I post more precise information about how to reproduce this bug or do something else?

**Comment by lordloki** [comment]
I confirm the crash on Windows
Here is the log
![image](https://user-images.githubusercontent.com/1015605/47958338-d92fa900-dfc9-11e8-9294-c58d2718f1da.png)

**Comment by youle31** [comment]
I have no crash in last master. Else, in the file, both objects (Cube and Suzanne) are static and there are no collisions between static objects. @MrVentz and @lordloki : Can you test when you have time in last master to see if the bug is still there? Thanks!

**Comment by lordloki** [comment]
There is no crash in current 0.2.5 (win32 & win64) and 0.3 builds.
Closing the issue. Thanks for reporting.
