### ISSUE TITLE
`Save Startup File` overrides current file path to `Untitled.blend`

### ISSUE THREAD

**Issue by marechal-p** [UPBGE/upbge#921]
1. Make something in a blend
2. `Save As` somewhere on your disk, in a non-default location. At this point the window title should be display the path where you saved the file.
3. `Save Startup File`.
4. `Ctrl + S` to save the file again. If you look at the window title, the path should have changed to something else (`USER/Documents/Untitled.blend` in my case).

UPBGE 0.2.4
Window 10

**Comment by lordloki** [comment]
The bug exists in 0.2.5 and 0.3 but it is clearly a bug from Blender-BF as it is occurs in Blender 2.82
I propose close it

**Comment by youle31** [comment]
I agree to close because the bug is too small, because it's blender code, and because it seems we don't want to work on it :p
