### ISSUE TITLE
Object brush

### ISSUE THREAD

**Issue by EndSSgamesStudio** [UPBGE/upbge#930]
was watching "Speed Runs" from Unreal Engine
and I looked at some features that would really be interesting if the upbge had!

_like a "Paintbrush" to add objects!_

![1](https://user-images.githubusercontent.com/35436445/48293835-14b5f180-e468-11e8-83db-615690bca33b.gif)

_or an object that touches the mesh of another object, paste a texture in it!_
but I think this is going to be very complicated!

![2](https://user-images.githubusercontent.com/35436445/48294126-91959b00-e469-11e8-800d-cdde34535620.gif)
But there are two ways to do this.
would be: the cube creates a mesh with the texture

and the other (easier) would be: in applying the changes he created a new texture in the "Material" and made a uv projection from his perspective

What did you think?

**Comment by BluePrintRandom** [comment]
I have these types of tools in game :D

they are very handy.

we can make new copies of meshes using replace mesh and mesh.copy() very
quickly
I use vertex color so far and normals but have not messed to much with
adding new material indexes / faces

but Mesh1+=mesh2 (a plane that is a decal) may work pretty well.

(so we use the mesh editing api for this stuff)

another issue is to be able to save constructed meshes to disk and libLoad
them later.

**Comment by BluePrintRandom** [comment]
https://github.com/KhronosGroup/glTF-Blender-IO

just opened a issue for the exporter so we can save in game edited meshes
to disk :D

**Comment by lordloki** [comment]
Interesting idea. I have added the feature request for later and open tags. I will check it after 0.3 release. Thanks for the feedback.

**Comment by BluePrintRandom** [comment]
bpy can do this stuff now 😄 

I will try and post an example
