### ISSUE TITLE
animations time displayed in rasterizer 

### ISSUE THREAD

**Issue by vlad0337187** [UPBGE/upbge#931]
Hello. 

If you render scene in one .blend file, than you see in debug info it's animation and rasterizer time spent values.
But if you'll link model from one scene in one file to another scene in other .blend file, than that model's time taken to render animations will be written to "rasterizer" property.

Video:  https://www.youtube.com/watch?v=n0wnaRGfaPc

**Comment by panzergame** [comment]
Can you provide an example file please ? Also are you using any VideoTexture in it or planar / cubemap ?

**Comment by vlad1777d** [comment]
@panzergame , sure, I'll make it.

**Comment by youle31** [comment]
As there's no example file and as it seems a minor issue, I close this report.
