### ISSUE TITLE
glTF-Blender-IO

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/upbge#932]
https://github.com/KhronosGroup/glTF-Blender-IO

the creator of this patch says it's split into 3 parts, and we should be able to gut it and use it for KX_MeshProxy() -> to disk -> blender can then load -> save as a blend for libloading later or we can support loading them from disk.

"in game mesh export pipeline"

**Comment by lordloki** [comment]
It is possible to import gltf files in game for upbge0.3.
Thanks for reporting. Closing now.
