### ISSUE TITLE
If set slow parent - child object moves slow

### ISSUE THREAD

**Issue by vlad0337187** [UPBGE/upbge#934]
If to set to child object "slow parent" to one object, and "offset" to 0 - it moves very slow anyway.
Seems, that "offset" doesn't matter at all.

Example video:  https://www.youtube.com/watch?v=qJGQ46FlCdc
There is a base physics object, armature object with "no collision" is parented to it with "slow parent".
Other objects, like body, clothes - just parented to armature.

So when "slow parent" on armature is turned on - then you see that it moves too slowly up and down not regarding to "offset".
But when moving is not going by z axis - all is well.

I think, that's not related to physics, because I when I turned on visualization, physics object moves as needed.

**Comment by vlad1777d** [comment]
If you'll point me where to search for reasons of this error - would be very grateful.
It's important to me, without it character became very tremble due to it's physics object =)
(wrote logic to avoid it on mouse rotation, but impressions from it's moving are very "tremble")

**Comment by ethicalfive** [comment]
Could you open a default scene and distill the issue down to something simple and upload the .blend? That might help explain and pinpoint the issue much more clearly.

**Comment by lordloki** [comment]
I just tested and this works ok in current UPBGE 0.2.5. Here is a test file: 
[slow_parent.zip](https://github.com/UPBGE/upbge/files/5726861/slow_parent.zip)

Closing the report. Thanks for reporting.
