### ISSUE TITLE
Manjaro Linux xfce GPU not detected

### ISSUE THREAD

**Issue by Mainman002** [UPBGE/upbge#936]
I noticed that when running upbge in Manjaro Linux xfce upbge wasn't detecting my gpu but the newest builds of 2.79 and 2.8 were both detecting my cpu and gpu

![screenshot_2018-11-12_17-32-51](https://user-images.githubusercontent.com/11281480/48382458-dc502680-e6a6-11e8-95e9-6ddc1aec1ad2.png)
![screenshot_2018-11-12_17-37-50](https://user-images.githubusercontent.com/11281480/48382459-dc502680-e6a6-11e8-9c5c-f1ae057ad484.png)
![screenshot_2018-11-12_18-04-39](https://user-images.githubusercontent.com/11281480/48382474-e96d1580-e6a6-11e8-9c5d-95406ba721fa.png)
![screenshot_2018-11-12_18-04-54](https://user-images.githubusercontent.com/11281480/48382475-e96d1580-e6a6-11e8-8137-69b03736cb40.png)

**Comment by lordloki** [comment]
Surely it is build without CUDA support.
@panzergame ?

**Comment by panzergame** [comment]
@lordloki Yes it is build without CUDA support…

**Comment by lordloki** [comment]
Current 0.2.5 is not compiled with CUDA support due to conflict with CUDA toolkit. Sorry.
UPBGE 0.3 supports CUDA and GPU is shown.

Closing the report. Thanks for your feedback.
