### ISSUE TITLE
Python Components don't know how to navigate Python packages

### ISSUE THREAD

**Issue by marechal-p** [UPBGE/upbge#942]
[python-components-package-issue.zip](https://github.com/UPBGE/blender/files/2592954/python-components-package-issue.zip)

In this example, we can clearly see that Python Components are using a weird scheme of importation.

File layout is the following:

![image](https://user-images.githubusercontent.com/14182238/48675147-70951000-eb23-11e8-951e-3cb544cb262c.png)

The issue happens when we try to import the `KX_PythonComponent` named `NotWorking` in `package/components/notworking.py`.

When using sub-packages, UPBGE Components get lost, when Python Module Controllers know how to import such an object.

The script `python_knows.py` shows that Python knows how to access the class (when you execute it), and that it is UPBGE that is failing here.

**Comment by youle31** [comment]
Fixed by @mysticfall  here: 8f89bfe13ba7b30f88e07d . Thanks!
