### ISSUE TITLE
Version 2.4 Windows32 is closing when I press "P"

### ISSUE THREAD

**Issue by MarllonxD3** [UPBGE/upbge#945]
Version 2.4 is closing when I start my game.
My setup:
Window 7 Home Premium
System: 32 bits
RAM: 2,00
processor: AMD C-50 Processor 1.00 GHz
Graphics: AMD Radeon HD 6250 Graphics
(All drivers updated)

**Comment by lordloki** [comment]
When you downloaded the 0.2.4 version?

**Comment by MarllonxD3** [comment]
> When you downloaded the 0.2.4 version?

Today.
I downloaded the latest version.
I also tested the previous versions and none of them worked.

**Comment by MarllonxD3** [comment]
I am using the default cube.
I already tried to delete all the objects in the scene and it still does not work.

**Comment by joelgomes1994** [comment]
@MarllonxD3 has been testing the 32 bit version for a while, I provided the latest master build twice for the chat we participate, only him have crashes regarding this build, it worked for everyone else in the group.

**Comment by MarllonxD3** [comment]
> @MarllonxD3 Try this.
> 
> 1. Open Notepad
> 2. paste the following...
>    `cmd /k blender.exe -con`
> 3. save the file in the same directory as the blender executable and name it debug.bat
> 4. double click on debug.bat
> 5. press "P" in the the blender window that appears
> 6. paste what you see in the terminal in this thread

![debug](https://user-images.githubusercontent.com/45244378/48872076-b88b8f80-edce-11e8-89de-b691a4547c3a.png)

**Comment by MarllonxD3** [comment]
@joelgomes1994 
and I don't know why :/

**Comment by totterfree** [comment]
@MarllonxD3 Do you have Windows Service Pack 1 installed?  That solution seems to have helped other users with this problem (It's not UPBGE specific).

**Comment by MarllonxD3** [comment]
@totterfree 
![debug](https://user-images.githubusercontent.com/45244378/48872730-99423180-edd1-11e8-8539-e9d8e396aff5.png)

**Comment by EndSSgamesStudio** [comment]
@MarllonxD3 

could check if there is a folder called "UPBGE" in
C:\Users\ You-User\ AppData\Roaming

and then make a copy of "Startup.blend"
C:\Users\You-User\AppData\Roaming\UPBGE\Blender\2.79\config\startup.blend
and upload...
send here: http://pasteall.org/blend/ is fast...

**Comment by diegoultimate** [comment]
I also use version 0.2.4 32bits that joel compiled, with me it closes when I used it using the edit object> add object actuator, but when I renamed the actuator it started working again
Note: I'm Brazilian and I do not know how to speak English! I'm sorry

**Comment by EndSSgamesStudio** [comment]
@diegoultimate 
Me too...
If you're not using google translator, you're doing well ...
IIIII'm not saying that I use it ... 😄

**Comment by lordloki** [comment]
I can not make it crash either with the add actuator. Very strange.

**Comment by lordloki** [comment]
Current 0.2.5 for win32 works OK. Closing now.
Thanks for reporting
