### ISSUE TITLE
Access violations up the wazoo -- apparent memory issue

### ISSUE THREAD

**Issue by Liebranca** [UPBGE/upbge#946]
Hey folks,

First off I'm not native to english and this is a somewhat complex problem that I might not be explaining correctly, so please bear with me.

Essentially, unless I have it find certain references on every frame, Blender tends to fall into a recursive loop and crash whenever trying to lookup a list of linked data-blocks that have more than a single user across blendfiles -- when I try to link the same material, mesh, world data or even simpler types across packages through code (even a module containing nothing but strings and lists will do), the program apparently has to find it once for each user. It's absolutely ridonkolous: being the exact same data, these multiple lookups are completely redundant and I'm guessing only contribute to instability; I've seen this sort of unpredictable behaviour before with way too many pointers to a single address.

My reasoning here is long-winded. I could be way-off and don't intend to waste your time, so to spill it out quick and clean, I'd wager it's the OS shutting down Blender because of what it _perceives_ to be a potential issue of insufficient memory. I'm not sure that this is solely a problem unique to the engine, it might as well be Blender's quirks getting in the way. I'm looking into it myself, however if someone who understands the source better can share some insight that'd be quite useful. What I need here, more specifically, is some directions on where to look for how data-block linking is handled. And if this is related to libLoad (I have a gut-feeling it is) it might as well be useful in fixing it once and for all. So any help is appreciated.

Cheers.

**Comment by panzergame** [comment]
Hello, if the bug is happening when the game engine is not running, there's a lot of chance to not be related with. Right, you can report the same issue to BF bug tracker, but I advice you to provide an example file and a procedure reproducing the violation.

**Comment by Liebranca** [comment]
Outside of the game engine, Blender has a strong tendency towards creating duplicates of existing libraries on each attempt to find a linked data-block -- for reasons unkown to me, linked object data steers towards needless waste of memory, when it should be the other way around. I'll try and tell BF about this, it might be helpful, but right now I just can't bring myself to put too much trust in them (why I'm sorry internet please don't judge me, eh)

I've experienced this issue on both the standardard engine as well as uchronia, it just so happens to be the case that this one has a higher proclivity towards it -- the immediate crashes only happen when the engine is running. I have a few projects suffering heavily from this but they are intense on content. I'll try to scrounge up an example file to better illustrate the point whenever I get the time.

**Comment by youle31** [comment]
Idk if this issue is still there in last upbge 0.2.5a. There was a big work done by panzergame and lordloki on libload before 0.2.4. If we had a test file as simple as possible to reproduce the crash, we could maybe try to do something, but as upbge based on blender 2.7 is more or less stale, as 0.3 doesn't use libload anymore (bpy.ops.wm.append or other operators + convertBlenderObject/convertBlenderCollection instead), and as we have no example files, I close this report for now.
