### ISSUE TITLE
Allow UPBGE Users to Enable Bullet's Continuous Collision Detection (CCD)

### ISSUE THREAD

**Issue by totterfree** [UPBGE/upbge#951]
Currently, Bullet supports Continuous Collision Detection, or CCD for short. I would like to request that a checkbox be added in the physics menu to to allow a user to enable CCD for their game objects. Some other aspects of CCD could also be exposed to UPBGE users as well such as sweep sphere size, and motion threshold once box is checked. 

I request this feature because my player object is too small relative to its speed. It must detect collisions between static, paper thin, objects. For context, I'm trying to make an [FPV drone racing simulator](https://www.youtube.com/watch?v=81ct-Vk8QMM), so there's not a lot of wiggle room for the dimensions of the obstacles, or player model/speed.  Because the game is designed to be competitive and multiplayer in nature, this feature would be extremely helpful!

The use case for this common problem is more generally described [in this article](https://www.panda3d.org/manual/index.php/Bullet_Continuous_Collision_Detection).
A demo for CCD exists in the Bullet repo [here](https://github.com/blackberry/Bullet/blob/master/Demos/CcdPhysicsDemo/CcdPhysicsDemo.cpp).

I'm not well versed in C (hoping to change that someday), otherwise I'd submit the code myself for review. However I am willing to buy a beer for anyone that can help me out 😄 🍻

**Comment by BluePrintRandom** [comment]
With something like a drone we can raycast forward based on linV and the
time step from each corner of the bound, we can use speed, and delta time
to make the ray cast to where the drone will be next frame

**Comment by totterfree** [comment]
@BluePrintRandom That sounds like it would solve my problem for the most part. What occurs when the ray is tripped though? I was under the impression that CCD handles the temporary increase in substeps for us. Are you suggesting we implement that part of it ourselves?

**Comment by BluePrintRandom** [comment]
Vector.reflect and apply impulse work well,
I typically set position of the object, apply impulse

Enabling ccd would be great for later, this is just a temp work around.

**Comment by totterfree** [comment]
@BluePrintRandom ahh gotcha. Are you suggesting I do this via python though? Because I worry the logic and the physics won't always stay in sync.

**Comment by totterfree** [comment]
As for CCD, I think I may have figured out how to add it... Someone please correct me if I'm missing something

add...
```
void RB_body_set_ccd(rbRigidBody *object, bool active, float threshold, float radius)
{
	btRigidBody *body = object->body;
  if (active) {
		body->setCcdMotionThreshold(threshold);
		body->setCcdSweptSphereRadius(radius);
	}
}

void RB_body_set_ccd_motion_threshold(rbRigidBody *object, float value)
{
	btRigidBody *body = object->body;
	body->setCcdMotionThreshold(value);
}

void RB_body_set_ccd_swept_sphere_radius(rbRigidBody *object, float value)
{
	btRigidBody *body = object->body;
	body->setCcdSweptSphereRadius(value);
}
```
to [blender/intern/rigidbody/rb_bullet_api.cpp](https://github.com/UPBGE/blender/blob/7cf667d9b602fcbdcdba657598c469e67ad07402/intern/rigidbody/rb_bullet_api.cpp#L419)

add...
```
RB_body_set_ccd_motion_threshold(rbo->physics_object, rbo->cdd_motion_threshold);
RB_body_set_ccd_swept_sphere_radius(rbo->physics_object, rbo->cdd_swept_sphere_radius);
```
to [blender/source/blender/blenkernel/intern/rigidbody.c](https://github.com/UPBGE/blender/blob/7cf667d9b602fcbdcdba657598c469e67ad07402/source/blender/blenkernel/intern/rigidbody.c#L675)

add...
```
float cdd_motion_threshold;		/* The threshold after which the motion (in one step) triggers continuous collision */
float cdd_swept_sphere_radius;		/* The swept sphere radius for continuous collision (0.0 by default) */
```
to [blender/source/blender/makesdna/DNA_rigidbody_types.h](https://github.com/UPBGE/blender/blob/7cf667d9b602fcbdcdba657598c469e67ad07402/source/blender/makesdna/DNA_rigidbody_types.h#L114)

add...
```
static void rna_RigidBodyOb_cdd_motion_threshold_set(PointerRNA *ptr, float value)
{
	RigidBodyOb *rbo = (RigidBodyOb *)ptr->data;

	rbo->cdd_motion_threshold = value;
#ifdef WITH_BULLET
	if (rbo->physics_object) {
		RB_body_set_ccd_motion_threshold(rbo->physics_object, value);
	}
#endif
}
static void rna_RigidBodyOb_cdd_swept_sphere_radius_set(PointerRNA *ptr, float value)
{
	RigidBodyOb *rbo = (RigidBodyOb *)ptr->data;

	rbo->cdd_swept_sphere_radius = value;
#ifdef WITH_BULLET
	if (rbo->physics_object) {
		RB_body_set_ccd_swept_sphere_radius(rbo->physics_object, value);
	}
#endif
}
```
to [blender/source/blender/makesrna/intern/rna_rigidbody.c](https://github.com/UPBGE/blender/blob/7cf667d9b602fcbdcdba657598c469e67ad07402/source/blender/makesrna/intern/rna_rigidbody.c#L257)

add...
```
/* Continuous Collision Parameters - CDD */
  prop = RNA_def_property(srna, "cdd_motion_threshold", PROP_FLOAT, PROP_UNIT_LENGTH);
	RNA_def_property_float_sdna(prop, NULL, "cdd motion threshold");
	RNA_def_property_range(prop, 0.0f, 100.0f);
	RNA_def_property_ui_range(prop, 0.0f, 100.0f, 0.01, 3);
	RNA_def_property_float_default(prop, 0.0f);
	RNA_def_property_float_funcs(prop, NULL, "rna_RigidBodyOb_cdd_motion_threshold_set", NULL);
	RNA_def_property_ui_text(prop, "CCD Motion Threshold",
	                         "The distance threshold (in one step) after which the objects motion triggers continuous collision"
	                         "(used to prevent small, fast moving object from tunneling through static meshes)");
	RNA_def_property_update(prop, NC_OBJECT | ND_POINTCACHE, "rna_RigidBodyOb_shape_reset");

  prop = RNA_def_property(srna, "cdd_swept_sphere_radius", PROP_FLOAT, PROP_UNIT_LENGTH);
	RNA_def_property_float_sdna(prop, NULL, "cdd swept sphere radius");
	RNA_def_property_range(prop, 0.0f, 100.0f);
	RNA_def_property_ui_range(prop, 0.0f, 100.0f, 0.01, 3);
	RNA_def_property_float_default(prop, 0.0f);
	RNA_def_property_float_funcs(prop, NULL, "rna_RigidBodyOb_cdd_swept_sphere_radius_set", NULL);
	RNA_def_property_ui_text(prop, "CCD swept sphere radius",
	                         "The radius of the continuous collision swept sphere"
	                         "(higher value may be needed for large, extremely fast moving objects)");
	RNA_def_property_update(prop, NC_OBJECT | ND_POINTCACHE, "rna_RigidBodyOb_shape_reset");
```
to [blender/source/blender/makesrna/intern/rna_rigidbody.c](https://github.com/UPBGE/blender/blob/7cf667d9b602fcbdcdba657598c469e67ad07402/source/blender/makesrna/intern/rna_rigidbody.c#L1001)

**Comment by lordloki** [comment]
The code that you modified in the bullet wrapper for Blender-BF. UPBGE uses bullet but it uses another wrapper (is in source/gameengine/Physics).
I close the report but I add a label to can review later and see if i can implement it in UPBGE 0.3.
Thanks for reporting and for the code.
Closing
