### ISSUE TITLE
Segmentation fault on KX_GameObject.collide

### ISSUE THREAD

**Issue by vlad0337187** [UPBGE/upbge#952]
I have another crash.
Sorry me for this =)

Creating "little" test .blend files, probably, is not the best idea.
Often can't reproduce, as in case with https://github.com/UPBGE/blender/issues/950
I had code with 100% probability to reproduce, but loosed it.
Also I think now, maybe this issue was causing crash I described in  https://github.com/UPBGE/blender/issues/950...

So in this branch I created bookmark with 100% crash:
https://bitbucket.org/new_novel/oasis/src/default/

Steps to reproduce:
- pull repository: `hg clone https://vlad1777d@bitbucket.org/new_novel/oasis`
- move to bookmark with crash: `hg update -r bug/upbge/KX_GameObject.colide`
    (or checkout to that commit: "dac3134aa664")
- open scene in upbge: `upbge ./scenes/dream_tower/dream_tower.blend`
- press P and see a crash

It's caused by adding next line to code: `player_is_on_block	= obj.collide (player) [0]`
("./scripts/scene_dream_tower/scene_helpers.py", line 137)

When you stay on some other cubes rather than 3-rd - all is OK (no collision).
If you jump on that cube - there is collision with it.
When you jump from that cube - collision disappears and UPBGE crashes.

Video with bug:  https://www.youtube.com/watch?v=UP1wFJugDKM

OS: LInux Mint 19 Cinnamon
Kernel: 4.15.0-39-generic
UPBGE: 0.2.4
GPU: Nvidia Geforce GT 840m

**Comment by BluePrintRandom** [comment]
If you are using collision sensor the correct format is
```
if collision.positive:
    player_on_platform = collision.hitObject
```
if you are using callback for this I am not sure why but I think that is
causing your crash.

**Comment by vlad1777d** [comment]
@BluePrintRandom , thanks, but I'm using Always sensor =)
It moves my block a little bit, and it should check collision with player. If it's present - than move also player a little bit.

**Comment by RomStef** [comment]
then use the bvhTrees. they also detect the collision between geometries.
Your player must have a collision box and you can check the intersection between the obstacle and the collision box testing the bvh every logic tic

**Comment by BluePrintRandom** [comment]
Or use a ray and if it hits yourplatform state grab a local,
Local = platform.worldOrientation.inverted()*(player.worldPosition -
platform.worldPosition)

And next frame use stored local to set player position

Player.worldPosition = platform.worldTranform*local

Player key presses on platform manipulate local

**Comment by vlad1777d** [comment]
@BluePrintRandom , thanks, I thought about rays too, but hadn't time to make it.

@RomStef , Thank you very much. I was searching a way detecting collisions without physics engine using only their geometries for a long time.
Hope, I could somehow detect intersections of two objects when one will have no physics at all =)

**Comment by MrVentz** [comment]
I think that this issue may be somewhat related to #916 (though I'm not 100% sure, it sounds very simillar).

**Comment by lordloki** [comment]
It works OK in current 0.2.5. Thanks for reporting.
Closing now
