### ISSUE TITLE
AA Samples

### ISSUE THREAD

**Issue by EndSSgamesStudio** [UPBGE/upbge#954]
Anti-aliasing has a problem of interfering with other 2D filters
I think Anti-aliasing should work on layers of texture as well.

http://pasteall.org/blend/index.php?id=50787

**Comment by EndSSgamesStudio** [comment]
I noticed that AA samples also hinder "Depth Transparency"

![aa](https://user-images.githubusercontent.com/35436445/49355468-e4e8bb00-f6ae-11e8-8f65-3350ce395581.gif)

**Comment by lordloki** [comment]
0.2.5 is working for with your example. Closing the report. Thanks for reporting
