### ISSUE TITLE
Python Components not working in Group Instances

### ISSUE THREAD

**Issue by UnidayStudio** [UPBGE/upbge#957]
When you add a Python Component to an object, add this object to a group and spawn some group instances, the component will not run on the instances.

Test file (.blend):
http://pasteall.org/blend/index.php?id=50817

This issue is dangerous, since group are one of the best ways to organize a project and with this problem, there is no way to use components with them.

**Comment by EndSSgamesStudio** [comment]
I confirm the problem.
it is not possible to use the component in instances.

**Comment by UnidayStudio** [comment]
Just a small follow up: The issue is fixed in 0.2.5, but now the same problem happens in 0.3 with the new Blender Collections.

So it's a 0.3 issue only now.

**Comment by UnidayStudio** [comment]
Another update, this time for 0.3:

It's working, but you need to activate this option in the collection object (not the instance):
![Screenshot_19](https://user-images.githubusercontent.com/19742284/93240301-572e7080-f75a-11ea-9143-88721f8eaa0b.png)

**Comment by youle31** [comment]
As lordloki made "instance spawn" the default behaviour in 0.3 (https://github.com/UPBGE/upbge/commit/674e8ee7684c31e2dd6498831b712ea23d1f17fc), and as it is fixed in 0.2.5, I close this issue. Thanks!
