### ISSUE TITLE
[ Question ] Ambient Occlusion

### ISSUE THREAD

**Issue by RomStef** [UPBGE/upbge#958]
I'm Just curious.
Is It Expected to implement any sort of ambient occlusion like ssao or dfao ?
Thanks

**Comment by joelgomes1994** [comment]
Making some of the filters present in [this addon](https://github.com/thatimster/bge-post-processing) builtin would be very cool, along with the current builtin filters at `2D Filter` actuator.

In the meantime, SSAO custom filter [here](https://raw.githubusercontent.com/thatimster/bge-post-processing/master/filters/SSAO.txt), from the same repo.

**Comment by youle31** [comment]
in the shader there are 2 undefined vars: lt and gt. Apparently it means less than and greater than, then you can replace with < and >

**Comment by RomStef** [comment]
Thanks a lot !  The scene without ao is so flat.

**Comment by lordloki** [comment]
UPBGE 0.3 has AO included by default. Thanks for reporting
Closing the report
