### ISSUE TITLE
[Linux Bug] Can't Open UPBGE in Lubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by ditokp** [UPBGE/upbge#959]
Today I download the UPBGE v0.2.4 from the UPBGE website. After I extract the content, I can't open the app. Before I'm use UPBGE v0.2.4 in Lubuntu, I try in Ubuntu 18.04.1 LTS and works fine. I try opening the app with the terminal and I have this error message:

`./blender: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory`

Edit:
I can run Blender 2.80 Beta in Lubuntu, so I don't know why I can't run UPBGE 0.2.4.

Edit 2:
I can run UPBGE 0.2.3 in Lubuntu.

My System Specs:
Lubuntu 18.04.1 LTS 64-bit

**Comment by lordloki** [comment]
Hi, you need to install tbb library

**Comment by ditokp** [comment]
@lordloki Hi, I'm really sorry, I can't understand English very well. What is tbb?

I search in the internet but it has many meaning, I'm confused.

**Comment by lordloki** [comment]
I was referring to this library:
https://launchpad.net/ubuntu/+source/tbb

**Comment by ditokp** [comment]
sorry for late reply. I have finish install tbb library from Lubuntu Synaptic Package Manager, but I still can't open UPBGE 0.2.4. The file type of UPBGE 0.2.3 and 0.2.4 is also different. This is the screenshot, left is UPBGE 0.2.3 and right is UPBGE 0.2.4:

![2018-12-19-163254_1366x768_scrot](https://user-images.githubusercontent.com/27815899/50212109-c96af900-03ac-11e9-99ac-cf2416e2dde5.png)

**Comment by ditokp** [comment]
Okay, and thank you very much for helping me :-)

**Comment by Jah-On** [comment]
Hello,
Upon doing some testing on Linux Mint, UPBGE is missing the shared library "libomp.so.5". Running 
`sudo apt-get install libomp-dev`
will fix the issue for 2.81. 
Hope that helps!

**Comment by lordloki** [comment]
Now libomp and tbb are compiled as static at UPBGE 0.3 alpha.
Closing the issue now. Thanks for reporting.
