### ISSUE TITLE
UPBGE 0.2.5 - Disable "use framerate" doesn't work

### ISSUE THREAD

**Issue by lordloki** [UPBGE/upbge#975]
After commit 23183936242afafaecd8a00a116668fa68e8381c (implement render extra attachment) we are always locked to 60fps

![image](https://user-images.githubusercontent.com/1015605/50369519-6db09380-0597-11e9-88f0-b67b3a54cd5b.png)

Addittionally I have a win error in consoled (no crash). Tested with win64.
![image](https://user-images.githubusercontent.com/1015605/50369531-9769ba80-0597-11e9-9d85-913ec131de11.png)

**Comment by youle31** [comment]
When we disable use framerate, but if vsync is enabled, isn't it normal that the framerate is still 60fps?

![sans titre](https://user-images.githubusercontent.com/10052509/50755110-4f65bb80-1258-11e9-882d-73f3652b9a1b.jpg)

For me, when I disable use framerate and vsync, I can have more than 60 fps.

About win32 error, I can reproduce the bug, but I don't know where it comes from for now

**Comment by lordloki** [comment]
Closing as this issue doesn't affect to 0.3

**Comment by BluePrintRandom** [comment]
now that 2.5 is released I am getting asked about this*

**Comment by lordloki** [comment]
I don't know how to fix it yet.

**Comment by lordloki** [comment]
Fixed in 9ec291e9ebf3d419bb0e9cb5d90cfe1b349f3f7a . Thanks to youle

Closing report. Thanks for reporting.
