### ISSUE TITLE
Missing `Python.h`

### ISSUE THREAD

**Issue by marechal-p** [UPBGE/upbge#980]
I am having troubles, trying to install the following package for my project: https://pypi.org/project/dependency-injector/

So far, I have a few dependencies, such as:
- https://pypi.org/project/uvloop/
- https://pypi.org/project/promise/
- https://pypi.org/project/pylint/ (dev-dep)

But only `dependency-injector` is having issues being installed.

Steps to reproduce:

```sh
virtualenv -p /path/to/upbge/2.79/python/bin/python3.6m .tmpenv
source .tmpenv/bin/activate
pip install dependency-injector
```

On my workstation, I was missing `x86_64-pc-linux-gnu-gcc` although I had `x86_64-linux-gnu-gcc`, so I just made a symlink under `.tmpenv/bin` in my virtualenv, worked.

Then the issue is that it was missing `Python.h`.

Problem doesn't occur when I use my system Python (3.5), and I am able to run the package installation/build without any issue.

**Comment by marechal-p** [comment]
While I think I can make it work on my machine by pulling the correct `Python.h` for UPBGE's Python version, I feel like it will be a pain for anybody wanting to install the dependency on their side too.

My guess is that UPBGE should bundle this file with its Python executable, wdyt?

**Comment by atoms118** [comment]
I'm not an expert on how any of this works, but let me take a stab at it: Is there a reason why the build system is using `x86_64-pc-linux-gnu-gcc` instead of just `gcc` (which should be a symlink to the correct executable)?

**Comment by lordloki** [comment]
UPBGE 0.3 has pip included and you can install packages correctly. Closing the report.
Thanks for reporting
