### ISSUE TITLE
How to disable obstacle simulation in python?

### ISSUE THREAD

**Issue by MarllonxD3** [UPBGE/upbge#983]
I search for it in api, but i don't find an option to disable the obstacle simulation of an object.
It seems python not have an option for this

**Comment by youle31** [comment]
We can't do this in reatime, and for now we won't add new features, but only fix some bugs (Unless the other devs want to add a new API), but the development might only focus on bugs fixes I think. @lordloki  : Can we close this feature request to clean up the tracker?

**Comment by lordloki** [comment]
I add the tag enhancement to can find it later but I close the issue to keep clean the tracker.
Thanks for reporting
