### ISSUE TITLE
At the time of execution, some parts of the objects become invisible

### ISSUE THREAD

**Issue by Frankjore** [UPBGE/upbge#985]
at the time of execution, some parts of the objects become invisible. This happens when using light with shadows, it does not happen if we activate the button of fixed shadows.
![bug1](https://user-images.githubusercontent.com/40981362/51020618-615c9c80-157f-11e9-83a3-511d4abb1206.jpg)
![bug2](https://user-images.githubusercontent.com/40981362/51020619-615c9c80-157f-11e9-81de-20692f1361db.jpg)

**Comment by RomStef** [comment]
uncheck backface culling and set the alpha blend as "Alpha Sort" in the material tab 

![cattura](https://user-images.githubusercontent.com/20901566/51024328-86eea380-1589-11e9-9b15-b864c893fa14.PNG)

**Comment by Frankjore** [comment]
In this example, palm trees do not have an alpha channel, although parts disappear. This also happens in the left channel in SBS stereo, however they appear correctly in the right.
![bug1](https://user-images.githubusercontent.com/40981362/51037271-0d1de080-15b0-11e9-8236-e308f8de7ea0.jpg)
![bug2](https://user-images.githubusercontent.com/40981362/51037273-0d1de080-15b0-11e9-96e1-ac023db31a30.jpg)
![bug3](https://user-images.githubusercontent.com/40981362/51037274-0d1de080-15b0-11e9-8b91-45c63a2ca3af.jpg)

**Comment by Frankjore** [comment]
Yes, it's off. The strange thing is that in the stereo view it appears well on the right side and bad on the left

**Comment by marechal-p** [comment]
I think you either need to tick "double sided" somewhere.

Basically by default, you will only see the faces which normals are kind of towards you, and if you happen to see the face from the back, you won't see it.

Either make it double-sided, or duplicate the faces and invert the normals on the duplicates.

This might not be an engine issue.

**Comment by Frankjore** [comment]
Not so, the texture appears on both sides if it is not activated Backface Culling.

**Comment by marechal-p** [comment]
![upbge-backface](https://user-images.githubusercontent.com/14182238/51063414-e7e99c00-15c8-11e9-8ac6-42b35408c0bc.gif)

In the editor the texture will appear to be on both sides, while it is not the case.

Once again, this is because a texture is only rendered on the side of the face where the normal is pointing outward from.

**Comment by marechal-p** [comment]
By the way, the "double sided" option has no effect on my end (UPBGE 0.2.4)

**Comment by Frankjore** [comment]
Resolved: the problem was in a bad update to a new version of UPBGE, some module had not been updated
