### ISSUE TITLE
Navmesh system is slightly broken

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/upbge#991]
![image](https://user-images.githubusercontent.com/7190873/51278701-28159980-1990-11e9-984c-c110313ffb6b.png)

behavior in BGE

behavior in recent master 
![image](https://user-images.githubusercontent.com/7190873/51278730-3b286980-1990-11e9-9bf5-97516d38d699.png)

Did the navmesh libs change ?

**Comment by BluePrintRandom** [comment]
[NavMesh.zip](https://github.com/UPBGE/blender/files/2766066/NavMesh.zip)
example file

**Comment by EndSSgamesStudio** [comment]
navmesh really is very out of the ordinary!

![navpoopmesh](https://user-images.githubusercontent.com/35436445/51467292-5e1d9980-1d53-11e9-9b4d-b7f1b0171944.png)

**Comment by UglinessInTheUI** [comment]
Read blend: C:\Users\Lindows\Downloads\NavMesh.blend
Error: building NavMeshObject, can't find vertex in polygon


Blender Game Engine Started
Blender Game Engine Finished

**Comment by UglinessInTheUI** [comment]
There is definitely an error in python or C++ code. On my system it says: 

Error: building NavMeshObject, can't find vertex in polygon

**Comment by youle31** [comment]
note for me: seems to come from this commit: 574bb22eed28f0a429f75fcf5a0b787fc0626f83

**Comment by youle31** [comment]
there's also an issue with the base mesh both in bge and upbge... What I can do better is to revert the commit i mentionned. This is fixing part of the problem but some issues remain

**Comment by BluePrintRandom** [comment]
is this fixed @youle31  ?

**Comment by youle31** [comment]
the commit which caused the issue was reverted in ge_23a branches

**Comment by lordloki** [comment]
Fix included in 0.2.5. Closing the issue
