### ISSUE TITLE
Depth Transparency Render Issue

### ISSUE THREAD

**Issue by IzaZed** [UPBGE/upbge#997]
I'm seeing this artifact when working with Depth Transparency, though strangely it seems to be only my computer that does this:

![image](https://user-images.githubusercontent.com/32898133/51686496-c4731800-1ff0-11e9-809f-aa1658fd6e69.png)

On the other hand, I didn't get to test it on any other machine with an AMD R9 Fury graphics card, which is what i have installed. I thought it must have been a driver issue first, but i've had it for multiple driver versions now, since UPBGE 0.1.9 (where I started using it)

Specs would be 
![specs](https://user-images.githubusercontent.com/32898133/51686704-2764af00-1ff1-11e9-9bb3-9a0fd3b318d1.PNG)

Graphics Card Driver Version: 25.20.15003.5010

Would be glad to know what causes this , using DT again would be a blast

**Comment by EndSSgamesStudio** [comment]
Hi
Do you have a test file?

**Comment by UglinessInTheUI** [comment]
Where is that tricky blend file ?

**Comment by IzaZed** [comment]
sorry, got caught up in university, totally forgot about it

only visible in play mode, it happens when i look around

![bug](https://user-images.githubusercontent.com/32898133/53802135-53a11300-3f41-11e9-9533-3c99ef3aef0a.PNG)

https://drive.google.com/open?id=1YKEbCFM8lQimd6ljSuLPyaVQbOG8fxpP

**Comment by lordloki** [comment]
It seems to work in 0.2.5 as I don't see any artifacts. Closing the issue
Thanks for reporting
